## Acknowledgements {-}

So many people have helped me become the historian and community member that led to this book. I think of my high school history teacher, Pete Lynch from Granby Memorial High School, college professors Jim Miller, Kim Steele, and Joan Hedrick from Trinity College. Graduate school professors Mari Jo Buhle and Joan Scott each helped me find my voice.

As a teacher, my department supervisors at Conard encouraged and supported me in teaching a Local History course, and did so for over 20 years. My students taught me much about what mattered and what stories had staying power. Thanks too, to the Town of West Hartford, and Mayor Jonathan Harris for naming me Town Historian in 2004.

[West Hartford Life](http://www.turleyct.com/west-hartford-life.html) provided a motivation and venue for my work. Thanks to Mark Jahne and others who encouraged me. And thanks to TurleyCT Community Publications for permission to publish the over 140 articles that first appeared in their magazine.

I especially want to thank Prof. Jack Dougherty, who, when I was at a very low point, came to me asking if I would be interested in making the articles into an online book. Jack made things happen. His intern and my former Trinity student Vianna Iorio did much of the legwork to help me get the articles in order and provide searchable words, a short synopsis and a means to organize them. What a treat to have them both help me through a difficult time and keep me motivated. Thanks for their friendship and professional help, especially when I needed it most.

Thank you to the Noah Webster House and West Hartford Historical Society, especially Jenn DiCola Matos and Sheila Daley. Sheila had the knowledge and the skills to help me find the primary sources which appear throughout the book. And she helped me find the illustrations and embedded them in the text, no small task.
Thanks to the West Hartford Public Library, and especially to Martha Church who always encouraged me in my study of Local History. Her knowledge of the town is vast and she has documents at her fingertips. Their Local History Room keeps the power of local history alive.

Thanks on a personal level to Liz Devine. We taught together for 37 years at opposite ends of town, for most of it, and then we retired together. We continue to talk history and teaching as we write curriculum and train young teachers. She is as good a friend as you’d ever find!

And finally, my family - Peter, Adam, Brittany, Caroline and Billie - who delight in my love of history and find ways to keep me guessing. And, to Beth, who is the best partner a person could ever have and my best editor. She is supportive, fun, and curious, and she knows what I love.

*-- Tracey Wilson, June 2018*
