## King Philip: Why Did We Name a School After Him? {-}

*Originally appeared in West Hartford Life, August 2002*

According to Harvard historian Jill Lepore, in her book *The Name of War: King Philip's War and the Origins of American Identity* (1998), the war was "always brutal and everywhere fierce" and it "proved to be not only the most fatal war in all of American history, but also one of the most merciless."

Why, then, did our town, in 1955, name a school after the Wampanoag Indian King Philip? The war devastated both Native and English settlers from 1675 to 1676, with casualties greater than any other war in American history in proportion to population.

The simple answer, according to a Board of Education action in 1955, was to change the name of the King Philip Drive school to the King Philip school. It was named after the street on which it was located.

But why would a real estate developer choose King Philip, also known as Metacomet, as someone to honor in the 1950s? Why a Wampanoag Country Club? Why Mohegan, Seminole, Pontiac and Tecumseh Drives?

This fascination with Indians and what they represent begs some historical investigation.

Between 1620 and 1661, Phillip’s father and Wampanoag sachem Massasoit maintained a stable relationship with the English, but those peaceful relations deteriorated quickly after his death. As more and more English settlements became permanent, the Wampanoags were being pushed off their land and they realized their way of life was endangered.

During Phillip’s 14 years as Wampanoag sachem, from 1661 to 1675, the Plymouth colonists with whom he remained uncomfortably allied, mistreated him and his people. Philip was concerned that Massasoit had given up so much land to the English.

He noted that land was taken unfairly, through written documents, and if the English did not get enough land, they let their cattle roam Indian land, or they negotiated with Indians after supplying them with liquor.

Philip also disliked John Eliot’s praying Indians, those who had been converted to Christianity. There were 14 praying towns in Massachusetts. Philip believed this religious conversion was a dangerous thing and knew that the Christianized Indians were subject to the English king and not their own. They also were under the aegis of the English courts.

King Philip's War began in June 1675 in southeastern Massachusetts after the English settlers hanged three Wampanoag men by the neck not far from Plymouth Rock. These three men, loyal to Philip, the sachem or chief of the Wampanoag, were accused of killing John Sassamon, a fellow Wampanoag.

According to Metacomet’s men, Sassamon betrayed the Wampanoag plan to wage war on the English settlers. A jury of 12 Englishmen and six Christian Indians convicted these Wampanoag men of murder.

By the end of June, Philip and his men began attacking English towns to try to reassert their control in New England. They attacked three towns in Connecticut, the closest to us being Simsbury, burned to the ground in 1676. Legend has it that King Philip hid in a cave on Talcott Mountain just below where people hang glide off the cliff today.

The Nipmucks, Pocumtucks, Narragansetts and Abenakis joined the Wampanoags at various times, depending upon local disputes and Native alliances which had a long history.

From June 1675 to August 1676, Philip and his men devastated 25 English towns, more than half of all colonial settlements in New England. In 18 months, 2,500 English soldiers and civilians were killed, about 5% of the colonial population.

The Wampanoags slaughtered more than 8,000 cattle. The Wampanoags were fierce in their determination to get back the land the English settlers had taken from them over the previous 55 years.

At the same time, the war proved to be disastrous for the Wampanoags. The settlers killed both soldiers and civilians in their attempts to take land from the Wampanoags and their Pequot and Mohegan allies. Five thousand Native peoples, as much as 40% of the estimated population, were killed.

Thousands more died of disease or starvation or were shipped out of the colonies and enslaved in the Caribbean. Even those who attempted to assimilate by converting to Christianity were removed from their towns and kept on barren islands, where many died.

From the accounts written by English settlers in the 1670s, right after the war, there seems little reason to name the school after King Philip. These first historians portrayed him as a brutal and irrational man.

The colonial militia beheaded him at the end of the war, and quartered his body so it could be displayed in four places. His head was kept at Plymouth on a pole for 20 years. English settlers certainly saw Philip as a vicious, threatening foe.

In 1836, William Apess, a Pequot who was the first to write about Philip in a positive light, claimed that Philip was opposed to attacking the English. He wrote that his young warriors were out of his control. He quoted Philip saying "brothers, these people from the unknown world will cut down our groves, spoil our hunting and planting grounds, and drive us and our children from the graves of our fathers, and our council fires, and enslave our women and children."

Philip was a man who stood up for his culture, according to Apess, and believed that assimilation was destroying his people. There were values in his culture, he believed, worth dying for. Philip fought to defend the rights of his people.

Apess also said "we find Philip as active as the wind, as dexterous as a giant, firm as the pillows of heaven, and fierce as a lion, a powerful foe to contend with indeed, and as swift as an eagle gathering together his forces to prepare them for the battle."

Philip was kind to his prisoners, including captive Mary Rowlandson who wrote a captivity narrative. Apess portrays Philip as a man who understood the English’s devastation to Indians from despoiling the forest and hunting grounds, digging up their dead, taking away the Indian’s leadership, their enslavement, and all their rights taken away.

Philip’s was the voice that said this oppression and destruction was wrong.

Apess, who wrote around the time of the Trail of Tears, encouraged Native Peoples in the 1830s to "seize the mantle of liberty... We want trumpets that sound like thunder, and men to act as though they were going at war with those corrupt and degrading principles that robs one of all rights merely because he is ignorant and a little different color. Let us have principles that will give everyone his due; and then shall wars cease, and the weary find rest."

Apess called Philip “the greatest man that was ever in America." So, from Apess’ point of view, King Philip represented values that many of us accept today as American values: to stand up against wrongs, to support liberty, and to believe that all people deserve respect. It is not clear that the real estate developers or the Board of Education had these ideals in mind when they named the school.

Naming a school after King Philip can make us think about our fascination with war and war heroes. Which side in war deserves our compassion? How do we reconcile our idealistic disdain for war and yet our continued willingness to fight? Extreme conditions often make us think of the essence of the human condition and what it is that makes us human.

The words of Apess can give us a sense of why King Philip was a hero and see why his qualities could be emulated. King Philip’s actions in war can also make us question why the Board of Education chose this name.
