## The Sarah Whitman Hooker House {-}

*Originally appeared in West Hartford Life, January 2005*

A house can tell a story. Take the Sarah Whitman Hooker house on the south side of New Britain Avenue east of Main Street. With its beginnings in 1720, it survives today as the oldest structure in the town. The house is owned by the town, but limited access to the house has not allowed its story to be heard by very many people.

The structure was built about 50 years after lots were first divided in the West Division. Split in the late 17th century, people started to move here after the fear of the Indians died away with the end of King Philip’s War (1676). By the 1680s, Stephen Hosmer built a mill on Trout Brook where it crosses North Main and owned 310 acres of land. In 1710 and then again in 1711, citizens of the West Division, 27 families and 164 people, petitioned and got their own church which became the Fourth Church of Hartford.

![The Sarah Whitman Hooker House, 1237 New Britain Avenue, was built pre-1740 around a tavern room, probably the oldest section of a building in West Hartford. The home has been used as a tavern, a one family home, a prison during the Revolution, a boarding house, a restaurant and inn, and since 1976, a museum owned by the Town of West Hartford. Source: Noah Webster House & West Hartford Historical Society. Date: 1882](images/01-WhitmanHookerHouse-web.jpg)

Ten years later, John Seymour purchased the land on which the house stands from Stephen Steel. In Seymour’s 1747 will, he mentions his “mansion house on Four Mile Hill in the West Division.” In colonial days this location was called Four Mile Hill --- four miles west of the Old State House on the South Road to Farmington.

The structure began as one room with a chamber above and was probably first used as a tavern. Soon after, Seymour added onto it, making it a seven room house by 1747, at the time of Seymour’s will. Seymour’s son Timothy held a license for a tavern in 1733. Next to the meeting houses, the taverns were the most important centers of village life in colonial America.

In the mid-1770s, Sarah and Thomas Hooker moved into the house on the South Road. Sarah Whitman Hooker was the daughter of John Whitman, a prominent town merchant and political leader in the 18th century. The extensive list of household furnishings and goods which her father gave her on her marriage are enumerated in his account book and thus provide a glimpse into the material nature of her life. This account book can be found at the Connecticut Historical Society.

Thomas Hart Hooker went off to war in May 1775, right after the first battle at Lexington and Concord, leaving his wife and two children ages three and five. He died of pneumonia six months later during the siege of Boston.

Bristow, a man enslaved by the Hookers, bought his freedom before his master left to fight. It seems that Hooker also owned a slave named Amboy; according to an 1882 photograph, the house was home to a slave named Amboy who planted an Elm tree on the property in 1769 (cthistoryonline.org). I question the date recorded on the photograph, because it wasn’t until 1777 with the first American victory over the British at Saratoga, that there was a systematic planting of elms in the center of Elmwood by Capt. Ebeneezer Faxon.

During the American Revolution, after she was widowed, Sarah Whitman Hooker was asked to “keep” Philip and his son Andrew Skene, Tories who were taken as prisoners. Hartford had a “Committee Appointed to Take Care of Prisoners” that received their orders from Governor Jonathan Trumbull. Hooker was charged to “confine him on his parole of Honor not to go out of the bounds of Hartford... And provide...[him] with suitable lodgings and entertainment in some remote part of the town of Hartford.” Philip Skene was the Loyalist Governor of both Forts Ticonderoga and Crown Point in upstate New York. The Skenes were native born, not English soldiers. A report in January of 1776 claimed that over 20 people gathered outside the Hooker homestead to harm the prisoners. Purportedly, Hooker calmed them down and they dispersed.

In 1779, Sarah married West Division resident Seth Collins. In the early 1800s, she added on to the house and had the central chimney removed and in turn built twin chimneys on the east and west sides of the house. It is a typical five bay center hall Georgian style home, with clapboard siding and 12 over 12 double hung windows. One chimney has been rebuilt after it was destroyed by fire in the 20th century.

A man named Jedediah Mills lived there in 1807 while Hooker owned the house. He had a taverner’s license for several years in the early 1800s. Still, again in the mid-19th century it became a tavern under the name the Sheaf of Wheat.

In the 19th century, West Hartford remained a farming town. By the mid-19th century, farming became more specialized, particularly in dairy. Just to the north of the house, Charles Beach built his Vine Hill Farm and by 1900, the farm was famous for “baby’s milk.” The Hooker house, then owned by the Beach dairy farm, was used as a boarding house for workers from the Vine Hill Farm.

By the early 20th century, West Hartford transformed into a suburb and the Beach family sold its farm in the 1920s. They donated a good portion of their land to the town in the form of Beachland Park in the early 1930s. Once the farm stopped producing, the Hooker house changed from the boarding house, to a restaurant and inn and that was known as the Sarah Whitman Hooker House.

By 1976, the town of West Hartford owned the house and leased it to the West Hartford Bicentennial Trust to be open to the public as a museum. It was renovated through the efforts of the Fran Fransson family. Her recent death has left the house in the same trust under the behest of her children. The house is on the National Historical Register.

To interpret an historical home, usually the trust decides on a time period, and certainly this house has rich ties to the Revolutionary War period. At the same time, the changes in its structure and use tell much about the history of the town in the 19th and 20th centuries as well. If the house was open more, the citizens who own it could learn more of the richness of the story in three dimensions.
