## Old Lights and New Lights {-}

*Originally appeared in West Hartford Life, October 2003*

In 1977, local historian Elizabeth Hathaway wrote a “Chronology of some of the events that might have been discussed by West Division families during Noah Webster’s youth.” In this four page chronology of the years 1757 to 1774, she notes two particular events about choosing a new minister and buying and settling land in the Susquehanna which tie the reader to colonial and international affairs, illustrating how learning the history of our town, then the West Division, can teach about national and international issues.

Choosing a new minister was part of a web of larger events. The issues of fate, salvation, the role of the sermon, the role of emotions and good works were all part of the decision about who to choose as the next pastor. In 1759, Benjamin Colton, the first minister in the West Division, died. He served the town for 46 years and baptized Noah Webster, Jr. Colton trained to be a Congregational minister at Yale, and so was ordained by other ministers, not by bishops. Pastors from surrounding towns, including the First Church in Hartford, ordained him.

Colton held the beliefs of an Old Light minister, a man who supported the Puritan ideals of the colony’s founders. Old Lights had softened some of the strict rules of the church and the Halfway Covenant allowed more members into the church. The New Lights challenged the established Old Light clerical leadership who were trained at Yale. They emerged from the First Great Awakening in the 1740s. New Lights were considered more evangelical, and the sermon, which could move congregants emotionally, was more important than the reasoned sermons of the learned Old Light ministers. New Light ministers were not college educated, but were known for their ability to preach.

The Hartford ministry liked the revivals at first. They felt they breathed new life into their congregations. Itinerant preachers like George Whitfield – an outsider, without a Yale education - preached in the area. As the New Lights gained followers, the Old Lights condemned them. Local Puritan ministers refused to approve New Lights for ordination.

The Old Lights, like Benjamin Colton, supported the Presbyterian associations that were set up by the Saybrook Platform in 1708 which centralized the choosing of ministers to make sure that they were products of Yale and the traditional preaching of the Puritans.

New Lights wanted each church to have congregational independence. They accused Old Lights of believing that people could control their salvation contrary to the belief that their fate was established at birth. New Lights said that the Old Lights examined people's lives, not their hearts. New Lights opposed the rational, more intellectual teachings of Old Lights. These New Light evangelical ministers allowed congregants into their churches without being baptized and attacked Old Light ministers for being spiritually dead.

There must have been some discussion of these issues in the West Division upon Colton’s death in 1759. In that same year, there was an attempt to oust the Old Lights from control of the General Assembly which met in both Hartford and New Haven, but it was not successful.

In 1759, the West Division congregation elected Nathanael Hooker, another Yale graduate, thus affirming the Old Light control of their church. But the New Light presence did not disappear. Just seven years later, in 1766, a parish member invited a New Light minister into the group and it was deemed a disorderly thing to do. The influence of the First Great Awakening had West Division residents thinking, but their allegiance remained with the Old Lights.

A second issue which brought world issues to the West Division was Connecticut land claims in what had become Pennsylvania. The Connecticut Charter dating back to the 17th century claimed Connecticut’s land stretched from sea to sea. This led to overlapping claims with William Penn‘s charter, which most people agreed, superseded this charter. But, some people, especially in eastern Connecticut still believed they had jurisdiction over western Pennsylvania. The French also claimed some of this territory.

People in the Connecticut colony started a land bank where people borrowed and deposited money. The deposited money earned interest, and people put up Susquehanna land as collateral for the money they borrowed. The land bank invested in the Susquehanna land company. Speculators in eastern Connecticut had done so for years.

Noah Webster, Sr. subscribed to this land bank in 1754; he owned land there that would be bought by a settler. This land was disputed during the French and Indian War which endured from 1754 to 1761. When the war ended and the threat of the French and the Indians dissipated, settlement began in Susquehanna County, Pennsylvania.

However, the Proclamation of 1763, part of the French and Indian War peace treaty, banned settlement in the Susquehanna land. Webster’s investment seemed to have lost its value. But, in 1769, Connecticut residents, in direct opposition to both Parliament and the Pennsylvania colony, once again settled in the Susquehanna.

This settlement stirred up old tensions over Connecticut’s charter. Opponents of settlement, who tended to be Old Lights, felt settlement jeopardized Connecticut’s charter. They feared that this charter, which allowed for an elected Governor, not an appointed one by the Crown, would be in jeopardy if the settlers persisted. Connecticut was the only colony which did not have a Royal Governor, and the Old Light leaders believed Connecticut should lay low and not draw attention from Parliament in any way.

After Parliament passed the Stamp Act in 1765, New Lights took the principled stand of proclaiming the tax as evil. They questioned the Parliament’s ability to lay an internal tax and used this issue to unseat the Old Light Governor Thomas Fitch. Fitch had written a pamphlet on the issue, but he had not opposed the Stamp Act strongly enough. William Pitkin, a New Light, won the election and took control.

Webster, Sr., aligned with the New Lights, while he lived in an Old Light town. Certainly there would have been those here who would have discouraged the speculation in Pennsylvania land. We can only guess whether Webster was making a political statement along with trying to make some money. We do know from Hathaway that Webster, Sr. was elected a grand jury man in 1760, and a selectman in 1768 and 1769, and from 1772 to 1774 he was elected Treasurer of the Ecclesiastical Society when Nathan Perkins, a Princeton graduate, became minister, upon Hooker’s death.

In the 1760s, tensions abounded in the West Division. These religious, economic, and political tensions were often tied to national and international events. The beauty of local history is that it provides specific evidence, familiar to us, that helps shed light on these broader events and ideas. The local and national events can each gain deeper meaning when we can make those connections.
