## The Rev. Benjamin Colton and the Great Awakening {-}

*Originally appeared in West Hartford Life, February 2009*

The story of the Rev. Benjamin Colton, the first minister in the West Division, is a story of stability and tradition. He served the Fourth Congregational Church of Hartford here in the West Division for 46 years.

Settlers traveled to attend the First or Second Congregational Church on Main Street in Hartford when the West Division of Hartford was settled in the 1690s. By 1711, local residents wanted to have their own church.

When the settlers applied for a separate parish, there were 27 families with 164 family members here. According to their petition, seven houses had just recently been built, a sign that the area was growing. The petitioners claimed that there was enough land to support 90 families as they tried to make their case for their own church.

Connecticut’s General Court (now known as the General Assembly) granted the West Division the ability to have its own church, the Fourth Congregational Church of Hartford. On February 24, 1713, ministers in the Hartford area ordained Benjamin Colton to become the pastor of the new church.

Colton took on his ministry in the first meetinghouse. It was a plain building, built in 1712, at the site of the Veterans Memorial on the corner of North Main Street and Farmington Avenue. It was a square wooden, unheated building, with a pyramid roof, small windows, small galleries, a wooden pulpit and rough-hewn benches. This building served the church and the town for 30 years.

The new congregation had 29 members. To become a member of any Puritan Congregational church, parishioners publicly confessed their faith. There were 12 husband-wife couples that belonged to the church as well as five men, one wife without her husband and a widow. This group was Colton’s first congregation.

Benjamin Colton studied for the ministry and graduated from Yale College in 1710. He was 21 when he took the pulpit. He was from a family of 18 children and grew up in Longmeadow, Mass. His grandfather emigrated from England.

Colton started as a trial candidate in his position until in October 1713, at age 23, he was hired for a series of years. He married Ruth Taylor two months later. They had four children and in 1725 at age 32, she died. Colton was a widower for about one year. He then married Elizabeth Pitkin and they had five children. Elizabeth had her fifth child at age 47. This growing family became an integral part of the town.

In 1758, when Rev. Colton was 68, church records show the Baptism of "Chris (Negro serv't of Rev'd Colton)." In that same year, Chris was recorded as "owning the covenant," revealing he was old enough to consent to being a part of the church.

Colton’s church grew in its early years, as did the population of the town. Not much is known about his preaching, as he only published two sermons. But he was clearly an effective leader, as the congregation kept him on and the church kept growing. The First Great Awakening in the 1730s increased his attendance even more, but led to controversy because Colton was not a supporter of this Great Awakening.

Colton was a religious leader in Connecticut. In 1737, he was selected to deliver a sermon to the newly elected representatives in the new state house that was built in 1719. In his “election sermon” he urged the legislators to get back to God by cleaning up their moral lives. He felt as though there were too many sins including “uncleanness,” pre-marital sex and the enormous amount of rum consumption, particularly among legislators. If, according to Colton, legislators were more moral, they could be more successful. Colton stood up for traditional values.

Even with his colony-wide stature, an outside authority had to come to settle things down at Colton’s church due to the intrusion of the Great Awakening. This religious revival tested the authority of Congregational ministers, their education and their message.

In 1734, Northampton’s Jonathan Edwards began the “awakening” revival, encouraging his parishioners to be more emotional in their faith and put their lives in the hands of God. Conversions were personal, but not public confessions.

George Whitefield’s revival tour in 1740 and 1741 caused a stir. The young English Episcopalian evangelist was emotional, enthusiastic and convincing at his first stop in Boston, where churches seemed unable to contain the crowds that came to hear him. He preached up to 16 times per week. Converts cried out, wailed and jerked their bodies and made the settled ministers uneasy. Whitefield preached in nearby Suffield, East Windsor, Hartford and Wethersfield. Colton and other settled preachers were upset with Whitefield’s invective against settled ministers who had not been taken up by the revival. He denounced their education at Yale and their lack of emotion in the pulpit.

Whitefield’s message was taken even further by the Rev. James Davenport of Southold, Long Island, who in 1742 vehemently denounced the Congregational ministry and in New London arranged for lay converts to burn the symbols of what he thought was wrong with material goods and symbols of learning, including their clothing, ornaments and books.

The Great Awakening moved many of Colton’s parishioners, and Colton and Reverend Wadsworth in Hartford were both worried. But Colton remained in the pulpit, as officials from outside parishes came and settled things down.

The fact that Colton continued his ministry until 1759 showed that there was at least some victory for what were known as the “Old Lights.” His church remained the only one in the West Division until the Episcopal Church in the 1840s. However, it seems clear that he had to change his message to adapt to the ideas of the Great Awakening, even if he didn’t like it.

Colton’s tenure of 46 years at the First Church was a testimony to the importance of his traditional role of the ministry that he learned at Yale. There is no doubt that the Great Awakening jarred him and his fellow ministers, but with their mutual assistance, they sustained the monopoly that the Congregational Church had on religion in Connecticut for at least another 70 years.
