## Mary Merrell {-}

*Originally appeared in West Hartford Life, March 2002*

When Jacob Merrell died from an accidental fall on his pitchfork in 1771, his wife Mary Merrell was left widowed. She never remarried, and lived in the West Division until her death in 1792. Surviving as a widow at that time in history was challenging, as it was seemingly impossible to live as a single person in an 18th century household. Mary stands out because she seemed to do quite well as a widow, probably through the support of her seven children.

How did Mary do more than just survive for the 21 years after her husband died?

The Merrells lived on the Farmington Road, now known as New Britain Avenue on their farm where Wolcott Park is located today. Samuel and Jonathan Skinner, Joseph Skinner, Allyn Seymour, and Charles Seymour were her neighbors. At the top of the hill, on the corner of New Britain Avenue and South Main Street stood a one-room schoolhouse for the south end of town.

Mary grew up in Wintonbury Parish (now Bloomfield), and married Jacob Merrell in the 1750s. Jacob was 41 at the time of their first child’s birth. When Jacob died at age 57, he and Mary had four girls and three boys who ranged in age from 16 to 4. Mary bore children in 1755, 1757, 1758, 1760, 1762, 1766 and 1767. Thus was the life of a farming woman.

According to Blackstone’s four-volume legal code written in 1765, married women were literally “covered” by their husband’s authority. Her “very being or legal existence,” he wrote was “consolidated into that of her husband; under whose wing, protection and cover she performs everything.” As a married woman, Mary Merrell could not own or buy property in her own name, enter a contract or write a will. Once she was widowed, she gained some of these rights back.

We can get an idea of how Mary lived by comparing the probate record of Jacob Merrell when he died in 1771 with Mary’s inventory when she died in 1792.

Upon a husband’s death, wives received one-third of their husband’s wealth, called the “dower’s share.” The most valuable “movables” Mary received were a feather bed bolster, a year old heifer, curtains, a blanket, and six silver teaspoons. Each of these items was worth more than a case with drawer (a blanket chest with one drawer). She also acquired a bed, two pillows and two blankets. For her third of the farm, she got a one-year-old heifer.

She also received one-third of the real estate of land and house. The probate records described specifically what parts of the house legally belonged to her. Along with getting the South Lower Room, she also got the “liberty to use the fire place in the North Room for washing and baking and to pass and repass thro’ the entry North Room and Kitchen to the well.” She also got the west end of the barn and the liberty to use the barn floor for carting in hay and threshing and feeding the cattle.

Her oldest son Jacob, who was 13 at the time, owned the other two-thirds of the estate. What would it have been like for a grown woman to have to depend so heavily on her 13-year-old son?

Mary’s inventory on her death 21 years later provides a window on how she survived for those years without a husband. She kept many of the movable goods she received in 1771 and she added a large number of goods showing that, though she may not have prospered, her standard of living probably did not decline noticeably.

By the time of her death, when she was in her late 50s, she had items that reflected economic production, furniture and clothing, and items that went beyond the necessities.

There was clearly economic production in her house. Mary had a churn, Dutch wheel, and two hetchels for preparing flax to spin into linen. She had a few hogsheads and two meat barrels in which to store her food. She had one pig, two cows, and one steer. She had a right to the horse house and she owned 36 acres of land in her own right. She also had two hives of bees, which aside from her animals and land, were her most valuable property. Perhaps she got these hives during the Revolutionary War when West Division families chose to stop importing British traded sugar.

She had about the same amount of furniture, and had added blankets, quilts, another bed and several sheets. She had many more kitchen tools including a porridge pot, teapot, large basin, brass kettle, large iron kettle and a washtub.

Her ownership of a clock, two “best” tablecloths, five teaspoons, five napkins, and two pictures show the growing gentility of the age. The standard of living for all New Englanders improved over these twenty years, and Mary’s ability to buy or produce these items shows that she was able to improve her standard of living.

Her children were in their 20s and 30s by time she died. Some of them must have stayed to help her or lived nearby.

Mary had enough money to pay her funeral expenses which included, in order of value, a gravestone, money for the distributors, two quarts of gin, money for the surveyor, money for the advertisements, money for “time and trouble,” one quart of rum, and a horse and wagon.

Widowed farm women had to live with others to survive, and Mary Merrell had her children. She could continue to run the household and, in Mary’s case, her honey might have given her some extra buying power. Women could choose not to remarry, but my guess is that Mary’s 21 years of widowhood would have been remarkable in small town New England.
