## African-Americans in the 18th Century West Division {-}

*Originally appeared in West Hartford Life, April 2001. The author thanks Sally Whipple, who collected these documents when she was director of the Noah Webster House.*

In 1893, Bernard Christian Steiner wrote the following in *[A History of Slavery in Connecticut](https://archive.org/details/histslaveryconn00steirich)*:

> In general, Connecticut has little to be ashamed of in her treatment of the Negroes. She treated them kindly as slaves and freed them gradually, thus avoiding any violent convulsion… Her treatment of the slaves was almost always kind and generous. A master, in true patriarchal style, regarded them as in truth a part of his family. With the coming of the revolution and the struggle of the Colonists for freedom, a feeling arose that it was not just to hold other men in bondage and as a result, importation of slaves was forbidden in 1774.

How much truth is there to Steiner’s assessment of the treatment of enslaved people in Connecticut? Were they treated kindly? Were the slave masters generous? Were enslaved people treated as part of the family and was the slave trade ended because of the ideology of freedom, which was so prevalent during the years leading up to the American Revolution? How did Steiner come to his conclusions?

The Public Records for the Colony of Connecticut, October 1774 reveal a far different reason for ending the slave trade in Connecticut than Steiner offers. “An Act for prohibiting the Importation of Indian, Negro, or Molatto Slaves” starts with the phrase, “Whereas the increase of slaves in this colony is injurious to the poor and inconvenient”… The legislators of the General Court in Connecticut were moved more by economic and political or moral reasons.

From the point of view of lawmakers, enslaved people took work away from the poor. Each town was responsible for taking care of the poor and the more enslaved Africans there were, it seemed, the more white poor there were. When legislators ended the slave trade, they acted out of their own self interest more than out of their commitment to liberty for all.

“Run-away” advertisements from the Connecticut Courant reveal that many enslaved people chose to flee rather than serve as a slave. In August 1774, Jude ran away from Stephen Sedgwick, a resident of the West Division of Hartford, now known as West Hartford. Jude was described as a "molatto servant man . . . about 21 years old, about five feet, eight inches high."

In the West Division, enslaved people were sometimes called servants. Stephen Sedgwick's probate record confirms that Jude was owned; he is listed in the record as "my Negro Boy Jude" on the line just above "all my sheep and all my swine.”

Perhaps one could argue that Sedgwick was generous to Jude. Jude ran away with a claret-colored coat, two waistcoats, three pair of trousers, a pair of leather breeches and three shirts. He traveled with a forged pass.

Whether Jude wrote the pass, we do not know. Masters describe their property carefully and knew their clothing down to the type of buttons. His wardrobe leads one to believe that Jude was not destitute, but despite Sedgwick’s generosity, Jude reacted in a way that questions whether he was being “kindly,” and “as a member of the family.” The owner offered a $20 reward.

There is some evidence of good treatment in the church. John Whiting owned Page, who was listed in the Congregational Church records as a member of the church. Page also had economic power. During the winter of 1740-41, he bought cloth, thread and stockings from merchant John Whitman as recorded in his account book. These transactions lead us to believe that Page actually earned wages and had some economic autonomy. Perhaps this is an example of the master-slave relationship Steiner was describing.

Steiner's definition of a stable system based on family loyalty was put to the test in the 1790s. With the African uprising and revolution in Haiti between 1791 and 1794, Connecticut residents grew more nervous about the possibility of a slave revolt.

A newspaper article from the Connecticut Courant on September 19, 1791 reported on the “Insurrection of Negroes" in which the Negroes "destroyed all the plantations by fire; that they massacred without distinction every white man in their power; that Negroes are in immense bodies; that they have cut off all communication with any part of the country."

The newspaper reported that the U.S. sent boats to Haiti to rescue the white women and children and to send them to Jamaica or Cuba. Seemingly the fear of slave revolt had to be stronger in the South, where in a state like South Carolina, there were counties with more than 75% African slave population. Connecticut’s slave population made up only about 3% of the total population.

However, in an alarming run-away ad in the Courant in 1794, Charles Churchill, a Wethersfield resident and owner of Jack, “a yellowith Negro who speaks French, Spanish and broken English" declared that Jack was a "cunning, wicked, blood-thirsty fellow who drawed his knife and cut a gentleman."

Churchill went on to lambaste the legislature's gradual emancipation act of 1783 because he believed freedom would only encourage freed men to cut the throats of the white people, "which would shortly be the consequence as hath been the case in the French islands, where thousands of white people have been cruelly murdered by the same act of liberality."

This reaction does not seem like the actions of a slave or slave master who had a generous paternal relationship with the slaves as Steiner argues. Joanne Pope Melish in her book, Disowning Slavery: Gradual Emancipation and Race in New England (1998), argues that before the Civil War, New England's leaders were pushed to establish an ideology in opposition to that of the South which requires them to forget about their oppression and exploitation of African-Americans.

Bernard Steiner must have used sources of slaveowners, not the enslaved to write his history; diaries of whites, not run-away ads, to establish what seemed like a beneficial relationship for both slave and slaveholder.

A look at 18th-century primary documents reveals a world of tension between owner and owned. Personal rebellion on the part of the enslaved instilled fear in the slaveholders trying to uphold this economic, political and social institution. The West Division was not immune to these tensions.

While all people understood the concept of freedom, not all experienced it.
