## Equality and Difference in Colonial West Hartford {-}

*Originally appeared in West Hartford Life, November 2000*

“All men are created equal.” This grand statement appears in the Declaration of Independence written in 1776. Since the writing of the Declaration, Americans have thought a lot about the issue of equality in political, economic and social terms.

Was there equality in the West Division of Hartford (as West Hartford was called before independence in 1854) by 1776? And, did colonial residents recognize economic and social differences?

Landholding is one place to look for differences in wealth. When the proprietors divided the West Division land into long lots in 1671, they distributed it according to how much land each man owned in Hartford. Those who had large lots in Hartford received large ones here. There was no attempt in the move west to equalize fortunes; instead this land division reinforced the economic hierarchy that existed.

At the same time, more Americans had the chance to own land than in England. Proprietors divided the abundant land among all sons in the New World, as opposed to only the first son in England.

A look at colonial homes still standing in town gives a glimpse at the range of house sizes and thus the resources of individual families. A middling farmer built the Noah Webster House at 227 South Main. Built around 1748, the house originally had four rooms built around a center chimney. The Benjamin Colton House (c. 1770) at 25 Sedgwick Road and the John Wells Jr. House (c. 1766) at 505 Mountain Road both are substantially larger than the Webster House. They have five windows in front and two on each side, while the Webster House has three windows across the front and one on each side.

![The Gillet house, at 202 South Main Street is one of 18 remaining colonial homes in town. It was built by Asa Gillet, a grandson of Joseph Gillett, one of the first proprietors of the town in 1694. Asa Gillett farmed both sides of Main Street in the late 18th century and he traded with the merchant Joseph Webb in Wethersfield. Source: Noah Webster House & West Hartford Historical Society.](images/01-Gillet.jpg)

This comparison tells us only so much, however. The houses of the poorest residents did not survive. Those who had not reached the middle-class status of the Websters might have lived in a cellar with a roof, or in a shack that did not withstand more than a few winters. Archaeologists in other New England towns have found the remains of such buildings. We have no sites or artifacts here because larger homes were built over these original, simpler structures. But we can hypothesize that the difference between rich and poor housing was greater than the examples left standing.

Inventories taken at the time of a man’s death, are another way to assess the difference in wealth among West Division residents. Designated townspeople went into the deceased person’s home and listed everything found in each room. Today these inventories can be found at the Connecticut State Library. In the 1770s , the total value of the inventories of eight different West Division families (featured in Noah Webster House educational programs) ranged from about 300 pounds to 1,300 pounds.

The types of goods owned by these farmers did not vary greatly. Most families had a Bible and perhaps one other book in their inventory. Wealthier families had more clothing, more looking glasses and more books. The biggest difference in wealth was the amount of land an individual owned.

The Rev. Nathaniel Hooker, the second minister in town (1738-1770) who died at the early age of 32, had a list of books and drugs appended to his inventory, showing his educational background as both a minister and doctor. Though his estate was worth only about 550 pounds, Reverend Hooker had the most social prestige in the town because of his education and his position as minister.

The presence of slavery in the West Division was a clear sign of inequality. At least 15 families owned people of African heritage between 1738 and 1827. We have the names of more than 40 people who were owned. Some bought their freedom, some were freed by the 1784 gradual emancipation law, and some died in slavery. Reverend Benjamin Colton owned what he named a "negro servant," and Reverend Nathanael Hooker owned a man, a woman, and a child.

Finally, the use of church records can tell something of the social structure within the town. In the late 18th century, there was but one church in town: the Fourth Congregational Church of Hartford. All townspeople had to belong to the church and paid taxes for its upkeep and the upkeep of the town. These records reside in the John P. Webster Library in the First Church (so-called after West Hartford became an independent town in 1854).

In a First Congregational Church booklet from 1913 commemorating the 200th anniversary of the church, there is a description from the 1760s about how people were seated in the church. A church committee assigned those with the highest social, political and economic standing to the pews in the front. Church leaders designated a pew for “old maids” in the back of the church. African-Americans like Page and Lew and the widow of Jude (listed as Negro) were members in full communion of the church. They also sat in the back.

People knew where they ranked by their seating in church.

In a list of “Members in Full Communion” in December of 1764 from the Fourth Church, the only church in town, there is a clear differentiation between people by sex, race, marital status and social status. Titles such as captain, lieutenant and colonel distinguished military men. Leaders of the church were denoted as deacons. That Page and Lew were considered members in full communion at the church, however, is evidence that everyone could be full members of the church.

Gender defined social status as well. Married women, like “Stephen Sedgwick’s wife” were listed as wives, not by their own names. Women considered “old maids,” such as Lydia Smith, were listed with their given name and surname, but many widows were noted as Widow Gillet, without the use of a given name. Where you sat in the pews each Sunday reminded those church goers of the social and economic hierarchy of the church members.

In the 1770s, West Divisions residents saw the difference between rich and poor all around them. But the gap, in a small town like the West Division, was nowhere near as wide as it is today, where multi-million-dollar homes exist not too far from one-bedroom apartments. Yet the abundance of land gave more people the chance to be independent farmers and the chance at a higher standard of living than they would have in England.

And, even with the distinctions between classes, there was a sense of equality of access. All residents had to attend the Fourth Church. All of them traded with John Whitman and Zaccheus Butler. While they were reminded of their social standing in church every Sunday, they all shared the right to vote on church matters, and those who owned land voted on town matters. All West Division residents had certain basic inalienable rights, but they clearly knew their place within the established hierarchy of their small New England town.
