## America Exposed as a Divided Society {-}

*Originally appeared in West Hartford Life, October 2005*

Hurricane Katrina washing away the veneer of New Orleans, bearing the economic reality of American life, led me to reflect on our own community. How clear were the class, race and gender differences in the West Division at the time of the American Revolution? How did people separate and include one another in this community?  

Economically, there was a clear difference in wealth in town by the second half of the 18th century. In 1766, Colonel John Whiting, former Treasurer of the Connecticut Colony, died at age 73. He was cited as the wealthiest man in the West Division. He lived north of Albany Avenue. In April 1768, Timothy Goodman’s house burned to the ground. The *Connecticut Courant* reported that the house “was entirely consumed, together with all his household furniture, clothes, &c. which were very rich and costly, about 200 bushels of grain, and a considerable sum of money.”  

These same men who were amassing wealth may also have had indentured servants and enslaved people and/or apprentices in town. Jude, enslaved by Stephen Sedgwick, ran away in 1774. Bristow bought his freedom from Thomas Hart and Sarah Whitman Hooker in 1775. Once the gradual emancipation act passed in 1784, a number of African Americans appeared in the church records dying in a pauper status.

A number of indentured servants and apprentices were part of the West Division community as well. In 1768, an apprentice about 19 years of age named Moses Cook ran away from Ashbel Wells. Cook “carried away a great coat, a good suit of brown cloth, yellow buttons and sundry other articles of cloathing.” By law, anyone who found him was forbidden from hiding or employing the runaway. Wells did not offer a reward for his return.

September 1784, an 18 year old named Truman Merrill ran away from Samuel Stanley. The advertisement in the *Connecticut Courant* said Merrill was about five foot ten and was well built with “short curl’d hair.” He worked Stanley’s clothier’s shop and Stanley believed Merrill would try to get work at this trade again. Stanley offered a reward of one shilling and sixpence.

![This *Connecticut Courant* runaway ad, August 9, 1774, is typical in describing what the runaway Jude was wearing and carrying. Note that Jude had a forged pass, indicating that either he was literate or he knew someone who would forge a pass. The owner, Stephen Sedgwick (1731-1792) married three times and had 10 children by his second wife, between 1762 and 1781. When Jude ran, Sedgwick was 43 years old and had 7 children. Source: The *Connecticut Courant* and *Hartford Weekly Intelligencer* (1774-1778); Hartford, Conn. 09 Aug 1774: 3.](images/01-Runaway-web.jpg)

In 1793, Charles Stedman, a lad of 18 ran away from West Division resident Francis F. Olmsted. A reward of two dollars was offered to the person who returned him. Olmsted described him wearing a London smoke coat, a stitched vest and brown trousers.

As early as 1791, there were ads in the paper about Charles Webster’s store where he had just received a fresh supply of European Indian goods, cloth and crockery ware. A customer could pay with “cash, country produce, tow cloth, linen check, clean cotton and linen rags,” all items produced in the West Division. In 1797, an ad for Webster’s store advertised that he had received goods from New York including broad cloths, plain and figured cashmere, flannels, vest shapes, chintzes, calicoes, satins, Persians, plain silk, and many other types of cloth. He also offered crockery, hardware and groceries.

The ability to trade for goods in the store is a sign that farmers could produce more than they could consume. Their production depended to a great degree on the amount of land they farmed and whether they also had a trade. Still, all 1,000 residents must have felt like they were part of the community.

The availability of land made life in America different than it was in England and spread opportunity around. Yet by the 1750s, land in the Connecticut colony was almost all being farmed. In 1754, Noah Webster, Sr. subscribed to land in Susquehannah County in the northern part of Pennsylvania. A man in Windham organized the subscribers. All the subscribers in the West Division lived near Webster on Main Street. Webster believed this land was controlled by the Connecticut colony because the charter gave the colony a right to all land westward.

The French and Indian War broke out in 1756 and fighting continued to 1761. In 1762, settlement began in the Susquehannah. In 1763, as a result of the Treaty of Paris ending the French and Indian War, the King in Council banned settlement on the Susquehannah land. There was concern among Connecticut’s political leaders about this land. Connecticut had an elected governor and by the late 18th century the citizens feared that this right would be taken away if they caused any trouble and the British in turn would appoint a royal governor like in Massachusetts. In 1769, opponents of of the Susquehannah land felt settlement there jeopardized Connecticut’s Charter which allowed for the citizens to elect their own governor.

The General Assembly replied in 1774, by extending Connecticut’s jurisdiction over the Susquehannah Company’s claim in the Wyoming Valley in Pennsylvania. Thus, those who had the means could speculate in land out west, increasing their wealth in relationship to those who could not invest.

Religion provided a sense of community in New England, but it was clearly a hierarchical community. The Congregational Church was the established church; all had to pay a tax for the support of the minister, and it was the only church in town until 1859. The first two ministers of the West Division were Benjamin Colton and Nathanael Hooker. Both men graduated from Yale College. Colton graduated just 13 years after it was founded and became a minister in the West Division in 1714. He served for 46 years until 1759 and earned his fame as a solid preacher.

Nathanael Hooker graduated from Yale in the late 1750s and was hired straight away; he was known to be a brilliant man. He died young at age 33 in 1770. A 1764 list of members in full community at the Fourth Church of Christ Congregational revealed all levels of people who belonged to the church including a colonel, a lieutenant, several captains, deacons, “negroes,” widows, wives, and single women listed by their own names. Anyone could be part of this church, though within it, people’s ranks were clear by the seating arrangement, decided upon by the deacons. Women could be members in full communion, but widows sat in the back and wives were known by their husband’s names.

The Reverend Nathanael Hooker understood that for women’s education, his community could not offer all he wanted for his daughter. For her, he felt, it was necessary to leave the community to get a good education. In his will he wrote that,

> my said Daughter Ruth have a better and more polite Education than she can possibly have in the parish of West Division where she was born, and that for this purpose, She be sent to Boston or elsewhere as her circumstances will allow and prudence dictates, and thereby empower her Uncles James and Horace Hooker and her Aunt Eunice Ellery... [to carry out this desire].

For Ruth Hooker, the mores and services of the community would not allow her to develop in a way that her father envisioned so she had to leave.

The community in which she lived did delineate between people by gender, race and class. Clearly many of those divides could be considered even deeper in the late 18th century than they are today.
