## Putting the Pieces of an African-American Life Together {-}

*Originally appeared in West Hartford Life, February 2006*

The Noah Webster House’s newest exhibit, “Bristow: Putting the Pieces of an African-American Life Together,” opens February 28. The exhibit is the culmination of a year’s worth of research, collecting artifacts and puzzling out the mysteries of Bristow.

Come visit, read, see, and feel Bristow’s experiences in the context of an 18th century home.

Noah Webster House Executive Director Chris Dobbs, explains that one of the challenges for public historians is to catch the emotions of their audience. He argues that reading about the past and seeing pictures can pique curiosity, and once the emotions are stirred, people’s memory is enhanced.

Mr. Dobbs wants this exhibit to be a visceral experience that draws visitors to the house.

You can sit on a bench and see images of a British slave ship carrying African captives. You’ll be below deck with a hatch above you. You can hold the shackles for the below-deck scene of the middle passage.

A blacksmith from Mystic Seaport reproduced the type of shackles that would have been found aboard a ship in the mid-1700s. These shackles linked the captive to the person on either side through a horseshoe and rod, and were chained to a place on board the ship with a lock holding the individuals together. Captives were riveted together and only a blacksmith could undo them. Even feeling the weight of the shackles gives some sense of the agony of the middle passage.

Some time after Bristow arrived in the West Division of Hartford, he was acquired by Thomas and Sarah Whitman Hooker. Sarah was the daughter of John Whitman, a slave holder. Might Whitman have given Bristow as a gift to the newly married couple in 1769? We don’t know the answer. We do know that at age 43, in 1775, Bristow bought his freedom for 60 pounds as Thomas Hart Hooker made his way to Massachusetts to fight in the American Revolution.

Imagine an enslaved man earning what was the equivalent of $9,500 today, working in his spare time on farms beyond that of the Hooker’s. In the exhibit, you can view a copy of Bristow’s manumission papers from the Connecticut Historical Society.

Those who visit the exhibit will be able to fill out a copy of a manumission paper to document their own freedom. Imagine the value of that paper for free African-Americans who lived in a tenuous state of semi-freedom in New England.

An interactive flip panel will help participants understand the limitations of freedom for those freed by the gradual emancipation law in 1784 or by buying their freedom.

Unlike most African-Americans in the late 18th century, Bristow had economic success. He bought three acres of land and a grist mill in 1788 in Bristol. The exhibit will display a copy of the land deed. He bought these properties for “the consideration of 140 pounds lawful money,” more than double the cost of his freedom. Bristow sold the land for 85 pounds four years later, at a substantial loss. A map in the exhibit shows where the grist mills in Bristol were in the 1790s.

While Bristow owned the land he wrote a will, something unusual for an African-Americans in the 18th century. He bequeathed his property to his former owner Sarah Whitman Hooker’s children; they were 21 and 17 at the time the will was written.

By the time Bristow died in 1814, his estate was worth $600. You can see a copy of his real will, which is held at the Connecticut State Library.

These historical documents will be set against three original pieces of art by Brian Colbath, an accomplished West Hartford artist. One painting is a collage of the major events in Bristow’s life. The painting will be in the exhibit, scanned and printed onto magnets, so that those who visit the exhibit can piece together Bristow’s life on a magnet board.

The second work is a five-by-six-foot painting of the Sarah Whitman Hooker House, which will be the backdrop for Bristow’s and the West Division’s main economic activity, farming. A real wood and iron plow from the 1790s will be displayed here. In the late 1800s, in a memoir of early West Hartford, Bristow was hailed for his agricultural expertise.

The third mural is of a liberty tree, an elm planted at the Sarah Whitman Hooker House. Elm trees were planted as liberty trees in the 1770s as a symbol of the American Revolution; the first elm named a liberty tree was in Boston, where an effigy of Massachusetts Gov. Thomas Hutchinson was hung in reaction to his enforcement of the Stamp Act.

All along the street in Elmwood, citizens planted elms which gave that section of town its name. There is evidence that either Amboy or Bristow planted the elm at Sarah Whitman Hooker’s House. Those who view the exhibit can imagine the strength and symbolism of these trees.

The exhibit is part of a series of events during February and March 2006 that will highlight the role of African-Americans during Bristow’s lifetime. On February 12, West Hartford native Jenifer Frank will discuss her book, *Complicity*. On March 9, this author will lead participants through a series of primary documents that tell the story of African-Americans in the 18th century West Division.

The exhibit will remain at the Noah Webster House for about six months and then will travel to Bristow Middle School as a permanent exhibit.

History museums are one of the prime ways that Americans learn history. Museum exhibits often provide a way into the past not offered by books or television or the big screen. Be part of the growing number of Americans who learn and feel history at museums. Check out the Noah Webster House exhibit, beginning February 28.
