## Rochambeau and the Revolutionary West Division {-}

*Originally appeared in West Hartford Life, June 2005*

The West Division was a vibrant farming community when le Comte de Rochambeau and his French army of about 5,000 men marched through in 1782. In May 2007, West Hartford commemorated his march by installing a marker at the Sarah Whitman Hooker House. This marker shows us how a war had far reaching effects on the homefront in our town.

The Revolutionary War was over when Rochambeau marched through, but the effects of the seven-year war reverberated through the town’s economic and political life.

Nathan Perkins was a young pastor in 1775 when he gave an impassioned sermon in which he delivered a scathing attack on British imperial policy as a threat to the New England way of life. He delivered his sermon in a patriot hotbed. Most locals had voted to support non-importation of British goods and once the first shots were fired at Lexington, West Division men volunteered to fight.

Out of a total of about 1,000 people in the West Division during the American Revolution, about 250 would have been adult males. Twenty-six men died, about 10% of the adult male population. These men had an average age of 33. Thomas Hart Hooker was the first West Division man to die in December 1775 after fighting in Boston. In 1778, members of the militia went to Ticonderoga and a Negro servant of John Whitman Jr., named Pent, died in the camp. The widows and families of those who died were forced to rely on each other to survive.

The first turning point in the war came in 1777 at the Battle of Saratoga. British General John Burgoyne invaded upstate New York from Canada hoping to meet up with William Howe’s troops in New York to cut New England off from the other colonies. Burgoyne captured Ticonderoga. In October, Burgoyne surrendered to American troops at Saratoga. Howe’s troops never made it north. This was a big blow to the British and proved to be more than a military victory for the Americans.

This victory led to the French making an alliance with the United States and sending about 6,000 troops to the United States to help in the war effort. Jean Baptiste Donatien de Vimeur, le Comte de Rochambeau, led this group from France in 1780. When they landed in Rhode Island in July, they were quickly put to work. Rochambeau marched to Connecticut in May 1781 where he met with Washington in Wethersfield. His last visit in 1782 was the one commemorated in May 2007.

In the West Division, citizens celebrated Burgoyne’s defeat and Ebeneezer Faxon organized the planting of elm saplings at the corner of Quaker Lane and New Britain Avenue (then South Road). The elm was a symbol of liberty in colonial New England. Patriots in Boston hung tax collectors in effigy from the elm Liberty Tree in Boston.

![Ebeneezer Faxon, a potter, celebrated the win over General Burgoyne in 1777 by planting elm trees on his front lawn and along what became New Britain Avenue. After the elms died in the 1940s and 1950s, the Elmwood community has funded the replanting of elms in Victory over Burgoyne Park, also known as Blanchfield Park. Source: Noah Webster House & West Hartford Historical Society.](images/01-FaxonHouse-web.jpg)

The town also participated in the war effort by providing land for a Revolutionary War Camp set up on Albany Avenue as early as 1776. Some of the original fireplaces remain. When soldiers stayed at the Revolutionary War Camp in 1779, townspeople benefited by supplying them with provisions. At least 50 West Hartford men supplied goods and services including coffins, medicine, milk, Indian meal, straw, wood, hay, horses to use to transport sick from Hartford to the West Division, Indian corn, turnips, mutton, vinegar, oats, horse feed, paper, and transportation.

According to West Hartford’s first Town Historian Nelson Burr, West Hartford sheep supplied wool for blankets, which the people sold to army quartermasters at the campsite on Albany Avenue up Talcott Mountain. The potter, Ebenezer Faxon, supplied tow cloth, a mixture of wool and linen. The army bought cows for food for the soldiers.

Aside from supplying the encampment, West Division families made money by supplying soldiers in the war. In 1777, 21 families provided blankets for the militia. Thirteen more families supplied beef cattle to the army between 1775 and 1777.

Moses Goodman & Co. ran a distillery one mile west of the West Hartford meeting house, probably not too far from present day Gin Still Lane. Moses was the son of Timothy Goodman who lived on Mountain Road. These distilled spirits were a boon to the men who marched through and those in camp.

Even those not directly involved in provisioning the army were affected by the war. People had to sacrifice in their businesses for the war effort. In 1779, Ebenezer Faxon asked the General Assembly to let him purchase lead in Boston for his pottery business in exchange for three barrels of flour and a hogshead of Indian corn. He declared that his occupation was necessary for the town, but the General Assembly turned him down, deeming lead for the war effort more important than for his pottery.

Governor Trumbull asked the West Division to house British and Loyalist prisoners from the battle at Fort Ticonderoga. The British prisoner of war Colonel Philip Skene was moved from Middletown to West Hartford when the African he owned, John Anderson, attempted to become Negro Governor of Connecticut. Connecticut officials believed that the British, through Skene’s slave, might encourage the Connecticut slaves to revolt against their masters, thus helping the British cause. Sarah Whitman Hooker House housed Skene on the corner of New Britain Avenue and South Main Street from July 26, 1775 until September 1776. It is probable that Hooker’s house had a tavern. Its previous owners, Timothy Seymour, held a license for a tavern starting in 1733. It is likely that Hooker’s house was a meeting place for political talk about the war as well as a place to rest, eat and drink.

Though the fighting was far from the West Division, we were about halfway between New York and Boston and many armies marched through, along the street where the liberty elms were planted. What is now New Britain Avenue, but used to be called South Road, was an important military highway, according to Burr.

Another French soldier, Marquis de Chastellux, who marched through in 1780 wrote in his journal that he noticed the “inhabitants engage in some industry in addition to their prosperous agriculture, some cloths and other woolen stuffs are manufactured here.” He went in a house in which they were weaving and dyeing cloth.

It wasn’t until October 1782, a year after the British surrender at Yorktown, that Rochambeau marched back through the West Division with his men from Yorktown to Boston. It is thought that he may have stopped at Sarah Whitman Hooker’s house. By that time, her husband Thomas Hooker had died in the war, and she had remarried Seth Collins in 1779. Her children were 13 and 11. Though Bristow had bought his freedom in 1775, Hooker still owned Amboy, listed as a negro servant.

Sarah Whitman Hooker’s life during the revolution shows probably as much dislocation as any in the town. In 1775, Bristow bought his freedom from she and her husband. Her husband went off to war and died leaving her with a 6 and 4 year old. She ran a tavern during the war and held prisoners of war there. The French army marched by her house and probably stopped for provisions. But like many Americans, she was able to adjust, take advantage of her circumstances, and endure the political and economic turmoil. She remarried in 1779 and readjusted her life. Using her as an example, it is clear that social, economic and political life in this small town changed as dramatically as it ever did in a short period of time.
