## West Hartford Center {-}

*Originally appeared in West Hartford Life, August 2009*

West Hartford Center’s vibrant mix of commercial, residential, religious, office and public buildings attracts many people each day. Even back in the 1770s, according to Elizabeth C. Hathaway, a local historian and researcher for the Noah Webster House in the 1970s, the town center from the Old Burial Ground south to Sedgwick/Park Road consisted of commercial, residential, religious, educational and public land.

John Pantry originally owned West Hartford’s Center in the late 17th century, according to Hathaway in her unpublished article ”A look at West Hartford in 1776.” In many New England villages, the proprietors made small house lots near a center meeting house but in the West Division, the land was divided in long lots from Mountain Road to Quaker Lane before there was a meetinghouse. In the late 1670s, when the land was divided, the proprietors expected that the residents would attend church in Hartford. It wasn’t until 1711 that the General Court allowed for a meetinghouse to be built in the West Division, and according to Hathaway, this is when the “center” began to take on an identity.

In the 1710s, the Ecclesiastical Society, the name by which the Congregational Church was known, bought land from John Janes north of the meetinghouse to establish a burial ground. According to the deed, Janes kept his animals there but had to maintain the fence around the land

Soon after the burial ground was established, the Brace family bought land abutting the burial ground. Probate records show that family members were paid to dig graves. The Brace family built the second mill in the West Division in the 1720s, right north of where Farmington Avenue crosses Trout Brook. If you walk in the Old Burial Ground, you can still see the lane that led from Main Street down to their mill. Sons of the first Brace mill owner, Zenas and Henry, operated the gristmill and lived on opposite sides of Main Street just south of the Old Burial Ground.

Citizens built the one room schoolhouse just south of the mill lane on the east side of Main Street.

Dr. Caleb Perkins lived across from the schoolhouse, and just north of the meetinghouse. He was a cousin of the Reverend Nathan Perkins.

By 1742, when the meeting house became too small for the increased population, Timothy Goodman granted land to the Ecclesiastical Society on which to build a larger meeting house. Goodman married a Pantry daughter and he gained ownership of the western section of land as part of her dowry. Goodman also granted land to the Ecclesiastical Society “for a place of parade forever.” Local men in the town’s militia trained at what today we call Goodman Green. Though the size and shape of the Green has changed in the last 265 years, it is still owned by the First Church of Christ Congregational and leased to the town for $1 per year.

The Ecclesiastical Society chose Reverend Nathan Perkins to be minister in 1772 after the Reverend Nathanael Hooker died at age 30. Perkins served the church for 66 years. He purchased Hooker’s house on the east side of South Main Street and it remained the parsonage and stood until the 1930s when the new library and new Town Hall were built. Perkins tutored young men who had finished at the one room schoolhouse and wanted to attend Yale.

The Butler family owned land south of Hooker’s parsonage. Descendants of Joseph Butler lived on both sides of Main Street. John Whitman’s account book records the Butler family producing barrels, pails, wheels and plows on the land probably at the location of the Crate and Barrel and Radioshack today.

South of the Butlers, probably where the Town Hall is today, was the land of Abijah Colton, the son of the first pastor. He lived in his father’s house.

John Belden lived across the road and lived in what people in 1738 perceived of as “mansion home.” Belden also owned land west of Mountain Road on land that was then part of Farmington. He owned a share of a sawmill.

The Olmstead family owned the next pieces of land on the westside of South Main Street reaching to a point just north of Sedgwick Road. They were descendants of Nicholas Olmsted, one of the original landowners in town. His son Thomas inherited the land in 1683 and was the first member of the family to settle in town. In 1776, Thomas’s sons, Stephen (age 82), and Daniel (age 75) and his grandson Timothy and great grandson Nathaniel Steel, Jr. all had homes on the original property. Stephen had been a blacksmith and Nathaniel was a shoemaker. The land stayed in the family until the 1880s.

Ebenezer Crosby, Samuel Sedgwick, and Stephen Hopkins owned the land at the intersection of Sedgwick and South Main. On the northwest corner where the SNET building is today, Ebenezer Crosby ran his blacksmith shop. On the southwest corner, Samuel Sedgwick had his farm and his tavern. In 1714, he got a license “to give public entertainment for victuals and drink to sell at his house to people who come for ordination of their minister.” By 1731 his license included the “retail of strong drink and keep a house of public entertainment of strangers.” This is probably the site of the first tavern in the West Division.

Just to the west of this site, the Sedgwicks sold a piece of their land to the heirs of Reverend Colton. They built the colonial home which still stands today on the corner of Sedgwick and Ridgebrook Roads.

On the east side of South Main at Sedgwick, Samuel Sedgwick’s great grandson lived on part of the original farm and continued the weaving shop that had been there for two generations. He built another house and a tanyard that he worked into the 1800s. A tanyard was the part of a tannery that had the tanning vats to process cowhides into leather.

West Hartford’s town center in 1776 had mixed use. The third and fourth generations of the original owners had divided and subdivided the land, many carrying on the economic use of their elders. Weaving, tanning, shoemaking, blacksmithing, preaching, tavern keeping combined with farming provided for a lively town center.

Today, with West Hartford Center’s post office building on the list to close to save the federal government money in these tough economic times, it reminds me just how fluid the ownership of land in the center has been. While residents lament a loss of convenience, and a walkable service, and sign petitions to keep the small, but handy post office, both the federal government, and some local elected officials and developers yearn to develop this prime spot of land in the town’s center.
