## Here Lies the Story of Elisha Seymour {-}

*Originally appeared in West Hartford Life, November 2011*

Elisha Seymour died at age 32 in October 20, 1776 of “the putrid fever" while serving in the West Division 's militia to fight the British in the Revolutionary War.

He left an inventory of his "reale and personal estate" which allows us a window into the world of revolutionary America. By carefully reading Seymour's inventory, one can discover what he did for a living and something about his position in the community.

Noah Webster House researchers found Seymour's inventory in the Probate Records Collection at the Connecticut State Library. They searched through the Fourth Congregational Church records to find out how big his family was to try to recreate the texture of his life.

Elisha married Rhoda Sedgwick on June 13, 1762 when he was just 18 years old. Their first son Elisha was baptized just seven months after they married, a sign that premarital sex is not new.

Just 14 months later they had their second son. Rhoda and Elisha went on to have five more children, for a total of six boys --- Elisha, Levi, Theron, Herman, Luther and Ambrose --- and the last, a girl born in 1773 named Prudence.

When their father died in the war, their children were ages 2 to 13.

Seymour's fighting in the Revolutionary War may have led to our independence, but what did it mean for Rhoda and her seven children? We don't know how soon she remarried, but it would have been most difficult for her to survive on her own.

At age 13, it would have been difficult, but possible, for son Elisha to act as head of household.

Seymour's inventory was used to appraise the total value of his estate so that his debts could be settled and his belongings could be fairly distributed to his heirs. The colonial court appointed appraisers, usually neighbors, to conduct inventories.

For Seymour, Daniel Webster (Noah Webster's uncle) and Noah Webster Sr. appraised the property. Solomon Ensign and Benjamin Gilbert appraised a few more items that were tacked on to the end of the inventory, completed almost a year after his death on October 16, 1777.

Usually, the wife received one-third of the estate and the sons got the other two-thirds. Seymour's entire estate was worth 257 pounds, 6 shillings and 10 pence.

He owned land, but probably not enough to be a farmer. He owned a house, three acres of land and a barn worth 140 pounds. This made up about 55 percent of the worth of his estate.

He also owned eight acres of woodland worth 33 pounds, about four pounds per acre. In the 1770s in New England, a middling farmer needed about 50 acres to make a go of it.

Seymour owned a yoke of oxen (10 pounds) and four cows (10 pounds) that provided him with a means for transportation and milk. He owned one draft chain and a narrow axe. He also owned a "chair carriage," which likely was pulled by his team of oxen.

He owned seven stock sheep and two swine. He had two bushels of flaxseed in his inventory as well. Flax was used to make linen cloth.

Clearly, Seymour did not have enough land to make a living as a farmer. Further down in his inventory, a set of shoemaker tools and a pair of boots is listed. He owned a shoemaker’s candlestick as well. So, he would have had a farm, but would have made a living as a shoemaker.

To process the wool and flax, Seymour owned two wool cards, a great wheel and a Dutch wheel for spinning. Cloth manufacturing was going on in his home, probably by Rhoda and the children.

In the kitchen, his household had a new corn basket and a frying pan. He had three old cider barrels and two hogsheads. He had a pepper mill, an old brass kettle, a box iron and heater, old knives and forks, a shovel and tongs, a pair of hand irons, a great trammel and a small, both installed in the fireplace.

He had two powdering tubs, three bottles, one stone jar, one coffee copper pot, a tea kettle and an iron pot. He had two great platters, five pewter plates, two pewter basins, a pewter teapot, three glasses, a china cup, a warming pan and a punch bowl.

The poor used wooden utensils, so the existence of pewter objects shows that Seymour did have the ability to show signs of gentility. Pewter cost about one-tenth of the price of silver, but still the cost of a dish equaled what a skilled craftsman could earn in a day. More than 300 pounds of pewter were shipped to the American colonies annually in the 1760s.

He also had eight earthen plates made by the local potter. He had a hand-held looking glass. There was a glass decanter and a glass cruet for vinegar. Seymour had an iron kettle and iron shovel for the fire, a pair of flat irons, which may have been manufactured in western Connecticut where an iron foundry was established in the early 1700s, despite British policy that no manufacturing could be done in the colonies.

In colonial homes, rooms had many different functions: Homeowners moved their furniture around daily. The best room where guests visited would also be the parental bedroom. Seymour owned two chairs, two feather beds and a second bedstead. a trundle bed and a bed quilt. He had three pillows and two pillowcases.

He also possessed woolen sheets. These woolen sheets could be a sign that Seymour bought locally woven woolen cloth. Cotton cloth was manufactured at this time in England, but Patriots like Seymour would have chosen not to import such materials during this time period.

He also owned linen sheets. Flax plants were grown right west of Webster 's house down the hill in what is now Rockledge Golf Course. The two bushels of flax seed in his inventory point to home manufacturing of these sheets.

Before the invention of the cotton gin in 1793, flax literally sustained people in colonial America. It was grown in every colony. It was not only used for its fiber to make cloth. Flax also was used for its linseed oil.

Seymour's ownership of a tablecloth and curtains were a sign of the increased ability to produce cloth and the sign of a growth in consumerism.

Clothing was a valuable part of anyone's estate in the late 1700s. Seymour had four coats, four vests, one pair of leather breeches and one pair of knit breeches. He had three pair of stockings, a new checked linen shirt, two plain shirts, a yard and a half of cloth, six pair of trousers, a silk handkerchief, a pair of gloves, a pair of shoes, a pair of shoe buckles and a pair of knee buckles.

He stored his clothing in a chest of drawers and a white chest. Seymour owned a gun and two powder horns. It is notable that he left a gun at home, because he probably had one with him while serving in the militia.

Seymour also owned two Bibles. He had a mariner's calendar, a book called the Young Man's Companion and an Old Mariner book. The shoemaker was both literate and religious.

Finally, he had a "note against Joseph Waters" worth 4 pounds 16 pence, 7 shillings. This note made him a lender, not a debtor.

Seymour made a living at one of the most commonly practiced trades in colonial New England. Because it was so easy to set up shop, the competition could be fierce and by the late 18th century, ready-made shoes from England were part of the competition.

With non-importation that came with the American Revolution, this could have helped him financially. Instead, he chose to go off to war.

Perhaps young Elisha had taken up the trade by that time. My guess is that family and maybe even the town had to step in to help Rhoda as she managed her household of eight without her husband.
