## Community in the West Division {-}

*Originally appeared in West Hartford Life, April 2004*

How does a town develop its sense of community? How often do citizens interact? What parts of town are exclusive and what parts are open to all? In a town of 63,000 residents, how often does the whole town come together?

The town’s sesquicentennial celebration in May and June 2004, will provide a time for members from different areas of the community to come together for a parade, a picnic, an art day, an historical scavenger hunt, a public history day and finally a fireworks celebration. Six garden clubs are planting sesquicentennial flower beds and the Faxon Library is hosting an ice cream social. None of these activities costs money for the participants and they invite all to come and enjoy.

How else is this sense of community built in our town and how has this changed over time?

Our public schools, public parks, public hearings, libraries, streets and roads are open to all. Some institutions are semi-exclusive like churches and synagogues which people join. Cornerstone Pool, the Veterans Memorial Skating Rink, the Science Museum, Boy and Girl Scouts, and sports leagues all allow anyone in, but each of us chooses our spots and pays to participate. Then there are exclusive places which have tests of money or skill for membership like private country clubs, and private and parochial schools where each of us define our community in a more specific and exclusive way that can make a large community like West Hartford feel smaller.

What common experiences did all West Division residents have 230 years ago when Noah Webster was alive? Have we built on these building blocks?

Until 1754, the West Division had a “common” area of land that stretched from Quaker Lane to Prospect Avenue. Farmers grazed their livestock and cut wood for building houses, for fences, and for firewood. By 1754, however, the land became so valuable that it was divided and doled out to individuals. Noah Webster, Sr. received three acres from “the common” in that year. This symbolized a declining sense of community and the rise of individualism. The tensions between the private good of the individual and the common good still remain today.

There was but one church in town and in 1764, the meeting house sat at the northwest corner of Main Street and Farmington Avenue. A list of “members in full communion” in that year listed 130 members (out of a population of about 1,000). Men, women and “negroes” could be church members. Church membership and attendance were open to all and, whether you attended or not, you paid tax money to the church.

A keen sense of community is built when people live where they work. In the West Division, almost everyone was a farmer and each farmer who owned land had a real stake in the community. Land records from the 1770s show a great amount of buying and selling activity to consolidate land holdings. They also reveal how much contact there was between neighbors.

Noah Webster, Sr.’s land sales show him making 26 transactions from 1740 to 1813. Most of his land was bought between 1740 and 1769. He bought the pieces of land from eight different people with three transactions from his brother Daniel Webster who lived across the street on South Main. At his peak, it is likely that Noah Webster, Sr. owned about 80 acres. Historians believe having 50 acres of land in colonial New England would make a middle class farmer.

The land transaction records show that the land that Noah Webster, Sr. bought and sold seemed to consolidate his holdings; the land was bordered by the land of 28 different households in the West Division. In the 1770s, farmers were careful about their land borders and often had to build fences to demarcate the land and keep their livestock separate from others’ crops. Watching out for their land took the cooperation of all those with whom they bordered.

While the farms were here in the West Division, one day a week in season, farmers traveled four miles east to Hartford to trade their goods. Farmers hitched their horses to wagons and made the trek to market. This became a community activity, mostly for men, but several times a year women and children joined them. Neither John Whitman nor Zaccheus Butler had stores in town in the 1770s, but they did serve as centers of trade. Their account books show the interdependence of town residents and the trading that went on here. They traded farm goods for imports such as brandy, rum, silk, and the services of both people and animals. Those who owned bulls or horses studded them. People lent their horses for trips into Hartford. Day’s labor is recorded. Each of these transactions was established at a set price and each included an interaction between those with the goods and services, the middle man, and those who wanted to buy the goods and services. Buying and selling brought the community together. No one was self-sufficient, and no transaction could be made without a conversation.

In 1774, everyday life took on a political nature as colonists protested the actions of the British toward their colonies when the Parliament imposed the Intolerable Acts on Boston. After the First Continental Congress met in 1774, the Hartford town meeting decided to support non-importation. Community members chose to sacrifice individual needs and comfort for the common good. The four taverns in town became hubs of political discourse. Women gathered for spinning bees as they joined in to make homespun cloth.

The activity surrounding Patriot protests provided leadership opportunities for more residents. Leaders coordinated activities in the West Division with those in the other colonies, particularly Boston. Hartford established a Committee of Safety. Members watched their neighbors to see if they were following the non-importation, non-consumption resolutions which the town meeting supported. The outside force, Britain, led to a stronger sense of community, but also led to tensions within the community between Patriots and Loyalists.

Because the West Division had only about 150 residences and about 1,000 residents in 1774, developing a sense of community must have been easier than in a town of 63,000 in 2004. While the difference economically was growing by 1774, there were not many divisions in daily living. There were one room school houses, one church, and a local militia which were open to all. Everyone could trade, including “negroes” and widows. It would have been difficult to live an isolated existence and though transportation was not as easy, there was a great deal of movement and interaction, making the town a community with its own identity. By the 1790s, already residents petitioned the General Assembly to be an independent town.

As West Hartford plans to celebrate itself at this spring’s Sesquicentennial, there is a chance once again to reflect on our identity as a community. There is only one other town in Connecticut, which has as high a percentage of its residents working in the town as outside of town. Just like the farmers of old, West Hartford residents have a real stake in the community. Tensions always exist around budget time over how much personal income we should justly give in taxes for town services for the common good. What type of community do these tensions help to define? Residents today are much more numerous and diverse than 230 years ago; the Sesquicentennial is an opportunity for all of us to come together to enjoy activities that make our community a place to celebrate.
