## Bring on the Elms {-}

*Originally appeared in West Hartford Life, November 2007*

On October 6, the Elmwood Business Association and the town planted a disease-resistant elm, with 12 more to follow, on the Elmwood green in the former parking lot of Talcott Junior High School. This tree planting has its seed back when the first elms were planted in 1777, giving this section of town its name.

Symbols are significant to every community. For Elmwood and West Hartford, the recent planting of the elm symbolizes a love for liberty defined during the Revolutionary War, reconciliation with opponents and it reinforces the sense of community which Elmwood has had since the original elms were planted.

First and foremost, the elm tree stands for liberty, harking back to its significant role in the Revolutionary War. The elm was a liberty tree, first getting its fame in Boston in 1765 as a symbol of resistance to tyranny. Tax collectors were hung in effigy from the Boston elm.

In Connecticut, the oak tree from the Charter Oak story served as the symbol of liberty more often than the elm. But the important piece here is that Ebeneezer Faxon had to plant the trees; as you may know, there are oak trees everywhere in West Hartford. The elm was a special tree and Faxon’s action was noticed and helped bring an identity to the community.

The specific trees planted in Elmwood hearken back to the Revolutionary War, commemorating the Patriot win at Saratoga over British Gen. John Burgoyne. This was no small battle. The British were 9,000 strong at this battle and they surrendered on October 6, exactly 230 years before the replanting. This battle secured the northern American states from further attacks out of Canada and prevented New England from being isolated from the rest of the colonies. Burgoyne’s force was made of 3,000 red-coated British, 3,900 German mercenaries and about 650 Canadians, Tories and Indians from Canada. This multinational force surrendered to a larger Patriot force under General Gates.

But the treatment of the enemy seems unusual to us today. The demand for unconditional surrender was flatly turned down by Burgoyne, but eventually a treaty of convention was accepted as the British agreed to not surrender, but be taken as prisoners of war and be marched to Boston and returned to England on condition that they would not serve again in the war.

On October 17, 1777, Burgoyne appeared before General Gates in his full ceremonial uniform and they greeted him with formal cordiality. About 6,000 men were surrendered to the Patriots. This common 18th century military practice, however, was not carried out.

The Continental Congress refused to ratify the convention and the enlisted men were held in captive camps in New England, Virginia and Pennsylvania until the end of the war. It seems that Charles I, Duke of Brunswick, did not want the soldiers back in England. He believed their presence would hurt recruitment for the duration of the war. Many of the British soldiers were housed by local patriots and ended up becoming Americans.

Burgoyne and Gates, as the story goes, had a cordial dinner party after the battle, with Burgoyne toasting George Washington and Gates replying with King George III. Frederica de Riedesel, the wife of a German mercenary and the daughter of the Prussian minister of state, was 31 when she witnessed the dinner party in the fall of 1777. She wrote a journal, published in 1801, in which she recorded the events:

> We reached Albany, where we had so often wished ourselves; but did not enter that city, as we had hoped, with a victorious army. Our reception, however, from General Schuyler, and his wife and daughters, was not like the reception of enemies, but of the most intimate friends.
>
> They loaded us with kindness and they behaved in the same manner towards General Burgoyne, though he had without any necessity ordered their splendid establishment to be burnt All their actions proved that at the sight of the misfortunes of others, they quickly forgot their own.
>
> Burgoyne was so much affected by this generous deportment, that he said to Schuyler you are too kind to me who have done you so much injury. Such is the fate of war, he replied; let us not dwell on this subject. We remained three days with that excellent family and they seemed to regret our departure.

This scene, describing the reconciling of enemies, reminds us of the importance of the results of battle. How are we to live together when the war is over if we objectify the enemy? This treatment of prisoners of war was not unusual during the Revolution.

In the West Division of Hartford, Sarah Whitman Hooker held prisoner of war Philip Skene during the war. On July 26, 1775, Ethan Allen sent Skene and the black man he owned, John Anderson, to Hartford after the capture of Fort Ticonderoga. It seems Hooker also held dinner parties in her home for the prisoner of war. Coming face to face with the opposition humanized the enemy right here, as it did in Albany.

It is thought that Hooker’s freed man Bristow planted an elm on the front lawn of their New Britain Avenue home. The Burgoyne elms helped to establish a sense of community in the southeastern section of town. They were planted in the West Division while Skene was held as prisoner of war. The elms helped to define a part of Hartford separate from the West Division, leading to the name Elmwood.

This sense of community and love of liberty remain today.

But the lesson of reconciling with our enemy takes even more strength to develop and is a more difficult lesson to practice.
