## Naming the New Middle School: Bristow or Sperry? {-}

*Originally appeared in West Hartford Life, August 2004*

As a high school history teacher, I am constantly considering what to include and what not to include in the curriculum. How much should I focus on leaders who made decisions which affected large numbers of people and changed the way people acted and thought? How much should students learn about those who left little record but were instrumental in building our nation?

It is this choice, it seems, that the Board of Education is faced with in naming the new middle school on Highland Street to open in September 2005. What the Board decides will be a symbol for the community.

A committee has narrowed the choice to two names: Bristow (1728-1811) and Roger W. Sperry (1913-1984). This is the choice of two men, the first who spent almost his entire life in West Hartford, and the second who spent his formative years here. This is the choice of an enslaved and then free African man and a white well-educated man. This is the choice between one man who had to fight for his very survival and another already well-recognized for his accomplishments. Each man is worthy of having a school named after him, but on the face of it, Sperry certainly has the credentials.

Sperry’s brain research had a great impact on further research in psychology and medicine in the 20th century. In his lifetime, Sperry published 290 scientific articles.

He discovered that the neural network that connects the sense organs and muscles to the brain is hardwired. He disproved the theory of his mentor, Paul Weiss at the University of Chicago where he got his PhD in 1941, who believed that the neural network was randomly connected. Sperry’s experiments, which included surgery on fish, salamanders, and monkeys, showed that the development of this neural network is just the opposite of what Weiss believed. In fact, each nerve cell, he found, was tagged in the embryo with its own chemical individuality and the function of the cell was fixed for life.

Sperry did not win the Nobel Prize for this discovery. He won that prize for his discovery on split brains. Sperry determined that both hemispheres of the brain are conscious and can act separately. This finding came again, from Sperry questioning the accepted theory that sectioning the corpus callosum, the large band of fibers that connects the two hemispheres of the brain, did not affect behavior. Sperry investigated first with cats and monkeys, and then later on humans whose brain hemispheres were surgically separated to control epilepsy. Sperry found that the right hemisphere was conscious, and could perceive, think, remember, reason, and emote. Further, he argued, the right and left hemispheres could be conscious, carrying on mutually conflicting mental experiences at the same time.

Sperry was born in Hartford to Francis Bushnell, a banker and Florence Kraener Sperry. His mother was born in Elmwood. Sperry’s father died when he was 11 and Roger took his mother’s surname. When his father died, the family moved to West Hartford, and his mother became the assistant to Hall’s principal for almost 20 years starting in 1924.

Sperry went to elementary school in Elmwood possibly at Charter Oak School. In his autobiography, found on his [website](https://web.archive.org/web/20041216090652if_/http://www.rogersperry.info:80/), Sperry wrote that he “collected and raised large American moths in grade school.” When he was at Talcott Junior High, he “ran trap line and collected live wild pets.”

At Hall High School, from which he graduated in 1931, Sperry was not just an academic. He was also an accomplished athlete who lettered in football, basketball, baseball, and track. At Oberlin College, Sperry was the captain of the basketball team and also lettered in football, baseball and track.

As an adult, Sperry practiced what his Hall yearbook quote proclaimed, “There’s time for work and time for play.” In 1981, at the time the Nobel Prizes were being awarded, Sperry left Caltech for a week’s fishing vacation with his wife. It was over a week before he came back and actually knew he’d won the Prize. In his spare time he was an artist in sculpting, ceramics, water colors and figure drawing. He loved American folk dancing, fishing, boating, and snorkeling. And he had a large collection of unusual fossils.

Clearly, Sperry has much to offer as an inspiration to school children and townspeople.

Bristow may, too, have been a renaissance man, but the documentation on him is not nearly as rich. Bristow is the only African American with a marked headstone in the Old Burial Ground on North Main Street in West Hartford. Bristow spent about half of his 83 years as an enslaved person. He was born in Africa and was involuntarily brought to the America when it was still a colony. He was owned by Thomas Hart and Sarah Whitman Hooker until 1775 when he bought his freedom for 60 British pounds. The fact that Bristow could raise 60 pounds shows the ability of enslaved people to make money and Bristow’s initiative to better his position in society. According to the recently published *Celebrate! West Hartford*, Bristow became an agricultural expert in his later years and farmers in town consulted with him.

Booker DeVaughan, the President of the West Hartford African American Social and Cultural Organization, was the impetus behind Bristow’s new headstone in the Old Burial Ground and in getting this headstone placed on Connecticut’s Freedom Trail. DeVaughan, in his dedication of the headstone on June 12, argued that Bristow represented many attributes that make him the quintessential American. He represents those ever-present American traditions of self-improvement, upward mobility, and reinventing ourselves.

We have only three pieces of primary evidence about him: his gravestone, his manumission papers, and his last will and testament. Much of what we make of Bristow comes from the ideas of social historians who study those who have not left a record and try to place them in the context of their times.

We don’t know if Bristow was literate, if he had a family, or if he made any important agricultural discoveries. But we can surmise, from information gathered about involuntary African immigrants, that Bristow had no formal schooling. He probably lived in the Hooker homestead at 1237 New Britain Avenue, and probably did a variety of jobs for the Hookers. Unlike slavery in the south, where those enslaved repeated the same tasks over and over, men like Bristow in the north, could learn a trade and could hire themselves out and make money.

Bristow represents the African American presence in the West Division which goes back to 1738. Sally Whipple, former Director of the Noah Webster House, researched African Americans for an exhibit the Noah Webster House in 1989. Her research through land and probate, birth, marriage, death records and account books shows how much African Americans were an integral part of the town in the 18th and 19th centuries. The first record of an enslaved African American is Jack, born in 1696 and owned by Col. Whiting.

Between the years 1738 and 1791, at least 20 white West Division men and women owned at least 37 black slaves. If there were 124 families in town in 1764, over 15% of the families owned Africans. These families were those that were wealthy and leaders of the town. Two of the first three ministers, Benjamin Colton (1713-1759) and Nathan Perkins (1772-1838) owned Africans. When Colton died in 1759, his inventory listed a “Negro” worth 33 pounds. This “negro” was probably Chris who had been baptized in 1758. By law, at Colton’s death, Chris was passed on to his son Abijah Colton.

John Whitman grew up in a house with slaves. To pay for purchases in 1740, Thomas Hosmer paid Whitman’s father “a negro named Ned a boy of nine years old w[orth] 115 [pounds]. Enslaved people were split from families, and even those who were free, lived in quasi-freedom.

In Dr. DeVaughan’s dedication of Bristow’s headstone, he said that “with all his American traits, however, he very well may not have risen to the very pinnacle of success. He was marginalized because of who he was . . . freedom for Bristol and his contemporaries was severely limited.”

Students in my Local History class leaned toward naming the school after Bristow. “We stand for diversity in this town,” one student said, and “we shouldn’t just give it lip service.” Another said that Bristow spent all his life in West Hartford and that gave him an edge.

Both these men are exemplary. The more I read about Sperry, the more I think, how could the Board not choose him? Yet there is this part of me that also wants to celebrate the common person, the ordinary citizen who rose above the circumstances to which he was tethered in slavery, the one who represents struggle, freedom and a measure of success beyond what was expected of him. But these attributes could apply to Roger Sperry whose father died when he was young and whose scientific career is characterized by his questioning established theories of giants in his field.

Is the symbol more valuable if the person has reached the pinnacle of society, or is someone who would live among us?

Contact your Board of Education members (Jack Darcy, Beth Bye, Bruce Putterman, Harry Captain, Terry Schmitt, Tom Fiorentino, or Jeanette Becker) with your opinion about the school name.
