## Researching the Revolutionary War Dead {-}

*Originally appeared in West Hartford Life, April 2005*

The voluminous work of the Veteran Memorial’s Joe Donahue, researching every veteran who died in uniform from West Hartford, compels me to try and make meaning out of the facts of their service, the tragedy of their deaths, and the sacrifice of their lives for the larger cause. The local connection makes the American Revolution come alive.

Twenty-six men from the West Division died in uniform in the Revolutionary War. Three quarters of the West Division’s men died by the end of 1776, just six months into the war. Their average age was 33. Their median age was 31. Two men died at age 50 and one man died at age 17.

Of the 26 men, there is a record of service for 21. Cornelius Flower served just five months before dying in camp of putrid fever. Epaphras Bull served for 56 months before he died of fever in Williamsburg, VA in September 1781, about 2 weeks before the British surrender at Yorktown. The average time of service was 17 months

Eleven men died “in camp.” Seven died of fever. Two of the 26 died in battle: Aaron Henery died of a wound at Fort Anne, NY, and Eli Mix died in an assault at Stony Point, New York. Three men, Jonathan Gillet, Joel Clark, and Joseph Mygat died after being released from prison ships.

As soon as news of the Battle of Lexington April 19, 1775 made it to the West Division, men answered the call. Thomas Hart Hooker enlisted into Connecticut’s Second Regiment under the leadership of Captain Samuel Wyllys of Hartford on May 10, 1775, just 25 days after the Battle at Lexington in what was known as the “first call” for troops from the state legislature. Hooker served at the siege of Boston and died of peripneumonia at the age of 30. On November 26, 1775 he became the first West Division man to die in the war. Just before he left for the war, Bristow bought his freedom from Hooker for 60 pounds. Hooker’s genealogy claimed Hooker gave Bristow his liberty before going to “fight for liberty” from the British.

West Division men fought in the next battle at Fort Ticonderoga, New York and three died there. Controlling Boston depended on an attack of this Fort about 150 miles away from Boston. The Green Mountain Boys, led by Benedict Arnold and Ethan Allen, surprised the British garrison and then hauled the fort’s heavy guns to Boston. The threat of bombardment forced the British to evacuate Boston.

The West Division men thought, like most of the Patriots, that they were involved in a skirmish, not a Revolution. The Patriot Army left a list of artillery taken from Fort Ti. They thought they would return the arms to the British as soon as things calmed down. The British remained uncertain about whether or not they were actually engaged in war. They believed they were only quieting pockets of rebellion.

West Division soldiers John Cowle, Cornelius Flowers and John Steele all died at Ticonderoga between April and October 1776. Members of their militia held onto Fort Ticonderoga to stage an assault on British Canada. Arnold threatened Quebec after a difficult winter march. The Patriots were frustrated in Canada when they could not get the Canadians to ally as a 14th state. Cowle was 50 years old when he died in the camp. He enlisted in August 1775 and died six months later. Cornelius Flowers also died at age 50 in the camp of “putrid fever.” John Steele was an army private who also died of “putrid fever” at 17, and had served 18 months. His regiment helped Gen. Schuyler reinforce the troops besieging Quebec. They retreated in April 1776 and were stationed in Ticonderoga. The men suffered severely from smallpox. The assault on British Canada was not successful, but the British evacuated Boston and many Loyalists fled to Halifax.

Nineteen of the West Division’s 26 men died in the second phase of the war in the Mid-Atlantic region. Fourteen died in 1776 and 12 of them at the outpost of Peekskill on the Hudson, north of New York City. Most of them are listed as dying “in ye camp.” Two died of “putrid fever.”

The British regrouped in the waters around New York City under Sir William Howe. He had 32,000 trained soldiers. Washington had 19,000 men who were poorly armed and poorly trained. Washington had no navy. Still, the Continentals fought and suffered one defeat after another as the British pushed them out of Manhattan, over the plains of New Jersey, across the Delaware River into Pennsylvania. Two West Division men, Lt. Col. Joel Clark and Private Joseph Mygat died on a prison ship in the waters around New York in 1776.

The British hunkered down for the winter of 1776-7, but George Washington recrossed the Delaware River on Christmas Eve. Joseph Hulbert from the West Division was with Washington when he crossed the Delaware. Hulbert died that night. He had served for 20 months in the war. Washington’s troops scattered the Hessian soldiers and claimed two minor victories at Trenton and Princeton.

In 1777, Horatio Gates defeated Burgoyne at Saratoga, New York. The citizens in the West Division were so excited that, led by Ebeneezer Faxon, they planted a living memorial in a park named Victory over Burgoyne at the northwest corner of Quaker Lane and New Britain Avenue.

At the same time, Howe headed for Philadelphia taking many of his troops with him to take the Patriot capital. In Washington’s unsuccessful attack on the British at Germantown, Pennsylvania, 17 year old Lewis Stanley was killed after serving for 2 years and one month in the militia as a Minuteman. Stanley must have been 15 when he signed the second call. He died “in captivity.” He served under Col. Jedidiah Huntington at Germantown.

When George Washington retreated to Valley Forge, February 16, 1778, William Wheeler, an army private was with him. Wheeler died with many others at Valley Forge where soldiers suffered from sickness, cold and starvation.

Jonathan Gillett died at home after being held prisoner by German troops in British service for 18 months. The Hessians confined him on a prison ship in New York Harbor. He was disarmed, and beaten. The prison ships in New York harbor were notorious for filth, disease, and cruelty. One of Gillet’s letters to his wife Elizabeth detailed his being disarmed, beaten by the Hessian soldier’s gun butts and treated unkindly. He was released after 18 months and returned to the West Division but died in December 1779 at age 41. He and his family lived in the house just north of the Noah Webster House on the east side of Main Street.

Epaphras Bull, aged 33 and a Major in the Army died of fever after serving for four and a half years in Williamsburg Virginia, just two weeks before Cornwallis’ surrender at Yorktown.

About 5,000 Patriot men died in the Revolutionary War, only a fraction of the 58,000 in the Vietnam War. Out of a total population of about 1,000 people in the West Division, 26 men died -- approximately 5 percent of the male population of the town. These men, whose average age was 33, left widows and families. Those on the home front sacrificed by not importing British goods. The dislocation of this war, in retrospect, loomed large. In the Vietnam War, 18 West Hartford men died out of a population of about 70,000, or 0.05 percent of the male population.

But both wars split the community as its citizens debated the merits of fighting for democracy and independence. Joe Donahue’s statistics of those who died in uniform bring home the heroism, tragedy, and misery of war.
