## Textiles in Early West Hartford {-}

*Originally appeared in West Hartford Life, February 2002*

Go see Lucy Young’s tablecloth and towel in the Noah Webster House’s exhibit “Textiles 2001.” The tablecloth is an “M’s and O’s” pattern made of natural linen. It is 23.5 inches wide and uses three panels of cloth. Woven sometime between 1775 and 1820, it has a hand netted fringe similar to fishnet attached on all four sides. Lucy Young signed her name to this tablecloth.

![Lucy Young demonstrates her skill weaving natural linen using the “M’s and O’s” pattern. The fringe on the tablecloth denotes a sense of gentility in a growing consumer culture. It also represents women’s role in an economy based on work by both men and women. Source: Noah Webster House & West Hartford Historical Society.](images/01-tablecloth-web.jpg)

You can also see a towel, known then as a “point twill diamond diaper” with a cotton tab on each end. This, too, was woven between 1775 and 1820 and belonged to Young. These pieces of woven cloth are beautiful, and represent so much of the change and tension of life in a small town in Connecticut at the time of the new nation.

I happened to view these two textiles, among the 30 on display in the exhibit, while I was in the middle of reading Laurel Thatcher Ulrich’s new book, *The Age of Homespun: Objects and Stories in the Creation of an American Myth* (2001). Ulrich argues that textiles, as much as farming, were the center of the economy of the new republic in New England. When you find out how linen cloth was made, you get an idea of the interdependence of men and women and a feeling of the rising sense of gentility in places where people had been living for almost 100 years.

Ulrich, a Harvard history professor, uses a linen tablecloth from New Hampshire, very similar to Lucy Young’s, as an example of household production. She argues that the edgings, tassels and fringes were a sign of “emerging neoclassicism and the spread of rural refinement.” She spends a chapter showing how this tablecloth reflects New England’s industrial beginnings, not as a radical departure from home production, but as an adaptation to what they already knew. She describes the interdependence of men and women in household production.

When we think about Lucy Young’s tablecloth within Ulrich’s interpretation, it gives us a new window on life in the West Division.

Local historians believe that flax was grown west of the Webster house, in what are now Rockledge Golf Course and the neighborhood that surrounds Duffy School.

Daniel Webster, grandfather to Noah, had a loom in his house. His inventory in 1766 listed one peck of flaxseed worth 1 shilling 3 pence, and 7 pounds of flax worth 6 pence.

Flax was planted in May by farmers who sowed the seed by broadcasting it. The seeds were light, but it was difficult to seed evenly. To plant a half an acre, farmers needed ¾ of a bushel of seed. In June, women often weeded the flax. Three or four days of harvest in late July or early August meant pulling the flax plants up by its roots, being careful not to tangle the stems. New Englanders let the plants grow long enough to produce seeds and the next step was to remove the seeds from the stem to save them for the next planting. Ulrich reports that in one Connecticut town, merchants exported more than 4,000 bushels of flaxseed in one year. West Division farmers probably produced only for local consumption. Daniel Webster’s flax seed was probably from last year’s crop.

The next step was to “ret” the flax to get the hard outer stem off the silky fibers. Interpreters at the Noah Webster house believe that this was done in the brook, which today flows through the golf course and then runs through a pipe under the Conard High School athletic fields. Ulrich believes that many New Englanders retted flax in the fall by placing the flax on the grass where it would soak up the dew, until the outer shell broke down. Whichever method was used, it smelled terrible.

If you go up to the garret in the Noah Webster house you will see the tools used for the rest of the process. A “braking” machine swings a heavy plank onto a small bundle of flax and then a small paddle was used to separate the husk that remained. The short fibers called “tow” fell to the ground. Either women or men could have done this task. The husk was saved as tinder to start a fire; processing flax was often dangerous because of its flammability.

Hetcheling was women’s work and could be dangerous. Hetchels consist of a square of wood with an array of nails through which one draws the flax to prepare it for spinning. The Noah Webster House has three different sizes.

Spinning was a big part of women’s work in the early republic. Women spun alone and they spun in groups. They spun flax and wool. And they spun day after day.

Even as people were able to buy machine-made cloth from England, and as the industrial revolution began in New England, they continued to weave and spin. The consumer society, which we so easily recognize today, had begun. People had more textiles in their homes in the form of clothing, bed and table linens. But the home production continued. When 100 years earlier, a man might have two shirts; by 1800 he could have five.

In Connecticut, certain portions of the textile making were taken out of the home. By 1800, almost every town, including the West Division, had a carding mill. One was on Trout Brook in what is now Beachland Park, just north of the pond. No longer did women need to do the time-consuming job of carding the wool. People took their wool to the carding mill and it did this work very quickly. Then women had more time to spin. This did not mean that families got rid of their cards. Some total home production continued. In the 1759 inventory of the West Division’s Thomas Olmsted, one pair of cards is listed along with 15 ½ pounds of wool.

Inventories of Jacob Merrel (1770), shows him owning a weavers’ loom, a winding wheel, three shuttles and one hetchel. Allyn Seymour (1760) had a Little Wheel, a Dutch Wheel, linen yarn and worsted yarn. Ebeneezer Mix (1766) had 32 pounds of wool, some wool colored blue, a Dutch wheel, clock reel, hetchel and 34 weight of flax in his garret.

Mehitable Bidwell’s inventory (1767) shows the cooperative nature of the world 200 years ago. The inventory shows 1/3 of a hetchel, demonstrating that Bidwell had to share. Ulrich argues that ownership and cloth making were often community affairs.

The existence of Lucy Young’s table cloth, which is homespun, also tells of a new sense of gentility and the possibility of having more than what was necessary, another sign of the growing consumer culture. It is not until the 1770s that tablecloths began to appear in inventories. By this time, people had the time and means to make what were not necessities. Allyn Seymour's inventory (1760) listed two tablecloths, Ebeneezer Mix’s (1766) two diaper tablecloths, a fringe tablecloth, a birdseye table cloth, and a plain and a diamond tablecloth. Ebeneezer Sedgwick (1760) had a diaper tablecloth, two tablecloths, six diaper napkins, and four homemade diaper napkins. In this case, the distinction was made between machine bought and homespun.

These inventories and Lucy Young’s textiles remind us that men’s and women’s economic lives were interdependent. The household remained a site of production even as the industrial revolution began to move some production outside the home. This Industrial Revolution was not a sudden dislocation, but a slow process blended into the family economy providing more consumer choice and a higher standard of living.
