## Lemuel Haynes Crossed the Color Line {-}

*Originally appeared in West Hartford Life, September 2011*

Who has crossed the color line? Many people in the United States today can lay claim to a family member, neighbor, or friend who has crossed the color line in marriage or in a lasting relationship of some type.

In the mid-1990s Gary Nash, a UCLA history professor, helped to start a movement called Mixed Race Studies in which historians, sociologists and artists focus on understanding multiracial, interracial and transracial adoption populations with a focus on social justice.

Mixed race studies scholars challenge dominant conceptions about race, emphasizing the flexibility of race and the porosity of racial boundaries. They critique how social stratification is often based on race.

West Hartford was the birthplace of Lemuel Haynes (1753 - 1833), a man of mixed race who married a white woman. Haynes' legacy has been resurrected by the PBS series, *Africans in America* (1998) and by Gary Nash's book, *Forbidden Love: The Hidden History of Mixed-Race America* (2010).

On July 18, 1753 in the West Division of Hartford, Lemuel Haynes was born to a father of "unmingled African extraction" and Scottish servant girl Alice Fitch. Lemuel took the name of Fitch's master, John Haynes of West Hartford, likely a descendant of John Haynes, the first governor of the Connecticut Colony who served eight terms and was instrumental in writing the Fundamental Orders of Connecticut.

Haynes took the name of his mother's master rather than that of his father, implying that his father was enslaved. Lee Ellenwood, former minister at the First Church of Christ, Congregational, suggested that his father may have been Bristow.

Five months after Haynes was born, his mother gave him up to Deacon David Rose of Granville, Massachusetts, who took him in as an indentured servant. Part of the agreement was that Haynes be educated.

Though not much is known of his youth, Haynes spent time helping out on the farm. He attended church and showed a passion for the Bible and books on theology. In his teens, he was exposed to Calvinist thought and conducted services at his local church.

At age 21, Haynes' indenture expired. He joined the Minutemen of Granville. Haynes marched with his militia company to Roxbury after the Revolutionary War battles of Lexington and Concord. He also volunteered in the expedition to Ticonderoga, NY in 1776 to help protect the fort.

In 1776, Haynes wrote a well-circulated pamphlet entitled “Liberty Further Extended” in which he said “That an African. . . has an undeniable right to his liberty.” Haynes condemned slavery and was one of the earliest to point out the irony of slave owners fighting for their own liberty while denying it to those of African descent.

When he returned to Granville, he was offered a scholarship to Dartmouth College but turned it down and “apprenticed” with local Congregational ministers, learning theology, Greek and Latin, and how to write and deliver sermons.

He spent 1780 in Wintonbury (Bloomfield) studying Greek with the Rev. William Bradford while teaching in the local one-room schoolhouse. He was a Calvinist who read revivalists George Whitfield and Jonathan Edwards from the first Great Awakening. He believed in the absolute sovereignty of God and that human virtue was a reflection of God’s love.

Haynes married Elizabeth Babbitt, who was white, in 1783 in Hartland and stayed married to her for 50 years. They had 10 biracial children born between 1785 and 1804. One of their sons became a physician and another a lawyer.

Haynes was licensed to preach in 1780 and in 1785 was the first African American officially ordained a minister of the Congregational Church. He was first called to be pastor of the Torrington Congregational Church from 1785-1787. He was the first black man in America to serve as a pastor to a white congregation. However, he left after to two years because of the active prejudice of the all-white congregation.

![Haynes served as a pastor from 1785 to 1833. He was popular as a preacher and as an intellectual. In his 1776 pamphlet “Liberty Further Extended," Haynes condemned slavery and was one of the first to point out, in writing, the irony of white men fighting for liberty while enslaving those of African descent. Source: Archives, First Church of Christ Congregational, West Hartford, CT, John P. Webster Library.](images/01-Haynes.jpg)

Haynes’ longest pastorate was in Rutland, Vt., where he served for 31 years from 1787-1818 until he was 64. While there, his fame as preacher and scholar spread. He earned a transatlantic reputation largely due to his 1804 published sermon against the idea of universalism.

Under Haynes, the church grew from 46 members to more than 300. In 1804 Middlebury College presented him with an honorary degree, the first of his race to win such an award.

But by 1818 he said that conflicts had grown within his congregation that at first seemed to be about politics and style, but in the end seemed to be more based on racism.

He was so popular in Vermont that he preached at a different church every Sunday after his dismissal and then served for three years in a Manchester, Vermont, church. He finally moved to Granville, NY and served his last 11 years as its pastor.

Haynes’ homestead in Granville is now part of the National Historic Register and he and his wife are buried in the cemetery in South Granville, just a mile from his house.

Since his rediscovery in the 20th century, Haynes has been criticized for not coming out strongly enough against slavery. But he needs to be seen in the context of his times. He would have been at the forefront of a moderate approach to the abolition of the slave trade.

According to Gary Nash, he never stopped preaching that “liberty is equally as precious to a black man as to a white one, and bondage equally as intolerable to the one as it is to the other."

Haynes' life exemplified the tension between the ideology of freedom in the new republic and that of slavery, as he argued for the full inclusion of African peoples in the new republic.

Haynes crossed the color line yet had to constantly be aware of his color in a country divided by race. His legacy to his birthplace can be to ask if race determines what neighborhoods people live in, if race determines school achievement and if race determines socioeconomic status.

Studying men like Lemuel Haynes can help us to see the social construction of race and help us to think more about whether race overpowers other human attributes which contribute to success. If race does, it makes us wonder even further about those willing to cross that color line.

Why are people like Haynes willing and able to buck societal norms and cross the color line? Who plays Haynes’ role today?
