## Noah Webster’s Social Life {-}

*Originally appeared in West Hartford Life, August 2007*

I found the green shoebox the other day---the one I was looking for. It holds 3 x 5 cards on which I tracked social meetings Noah Webster had with his friends and acquaintances in the 1780s. The box is a size 9 ½ wide (that’s children’s size) and it is 2/3 full of cards noting people with whom Webster met from 1783 (when he was 25) to 1786.

Let’s see, 9 ½ wide means my oldest son was about 3. Sixteen years ago seems like I might have entered these social interactions on the computer. If I did, I could manipulate them by date, by activity, by gender, and by place, but alas, I have them alphabetized by last name in this green shoebox. So, I have a chance to look back at events on paper. I have about 500 cards and to me, this is the stuff of history.

How do I make sense of them?

I remember why I put them on note cards. That summer when I read the book compiled by Webster’s granddaughter, Emily Ellsworth Fowler Ford, *Notes on the Life of Noah Webster* (1912), I was amazed by the number of times Webster socialized. Ford’s book was a compilation of seven first printings of extracts, letters, memos and diaries of his life. In 1912, the book was privately printed, and was reprinted in 1971. The Noah Webster House has a copy of the two-volume work. Was there a pattern in who Webster talked to? Was this an average number of interactions in the time period?

Webster’s life will be celebrated next year in town as we reach the 250th anniversary of his birth. Americans like anniversaries and we like to revise our history as well. As the West Hartford Historical Society and Noah Webster House gear up for this grand event, we struggle with the issue of who Webster really was. If you look at the paintings and sculpture and read some of what he wrote – there is a 500-page bibliography of his writing – he has the reputation of being ponderous, taciturn and a bit overbearing. But all these interactions make me think he was something more.

He wrote the *Blue-Back Speller* in 1783 and we know to make money from the speller he had to travel to each state to secure publication rights to his book. There were no national copyright laws and printers could buy the book and just print it and gain the reward. Webster traveled up and down the Atlantic seaboard selling his book, selling the idea of an American language, boosting public education, and pestering state legislators to pass copyright laws to protect intellectual property.

Perhaps the travel to push for copyright laws led him to believe in a stronger national government. In fact, in 1785, two years before the Constitutional Convention, Webster called for a stronger central government in his pamphlet, *Sketches of American Policy*.

His social interactions show him talking to leaders of the revolutionary generation. A quick look through my cards reveals that he took tea, dined, danced, and would “wait on them,” meaning to go to see or visit on business.

As I looked at the cards and wrote this article, I “googled” the men he visited. Today information about the revolutionary generation is right at my fingertips --- a big change from 16 years ago.

Between November 1785, and March 1786, Webster met with Mr. Moses Austin seven times, dining three times and taking tea with him four times. Moses Austin, 34 years later set out for Texas, petitioning for a land grant to settle 300 families on 200,000 acres of land. His son Stephen Austin, carried out his plan.

In May 1785, Webster took tea with Col. Aaron Burr and his wife Mrs. Theodosia Prevost Burr. Burr married Theodosia in July 1782 when he was 26 and she 36 with five children. She was the widow of a former colonel of the British Army and some questioned her loyalty to the new country. Webster knew her because he taught her children when he was a schoolmaster in Sharon, Connecticut. Just 10 months later, Webster met with the family again in Philadelphia. Burr was a member of the New York State Assembly at the time of their meeting.

On a 1786 visit to Philadelphia, Webster met with Benjamin Rush. In February and then in March Webster dined with him. Rush, like Webster, had many interests including physician, writer, educator, humanitarian, and finally a professor of medical theory and clinical practice at the University of Pennsylvania. He was an early opponent of slavery and capital punishment.

Webster heard Mr. Moyes and Dr. Rush speak on “harmony of tastes.” Moyes, who was blind, was a lecturer and professor of the philosophy of mathematics, engineering, and the history of medicine. Webster had tea with Moyes, attended his first benefit lecture on air, attended his last lecture and on two different occasions wrote that he “waited on him.”

Rush was a very good friend of John Dickinson of Wilmington, Delaware. Webster met Dickinson in February 1786, possibly through his connection with Benjamin Rush. Webster noted that Dickinson wrote *Letters from an American Farmer in Pennsylvania* (1767-8), which united the colonists against the Townshend Acts. Webster declared him a “sensible man.” Dickinson was one of the wealthiest men in America who served for four years, until 1785 as the President of Pennsylvania. Rush was the founder of Dickinson College in Pennsylvania in 1783, named after John Dickinson.

Webster met at least three times in late 1785 and early 1786 with a Mr. Samuel Curson of Baltimore. Curson was a merchant who traded corn, wheat, wines, flour, slaves, gunpowder, tobacco and rice in the U.S., the Caribbean, Africa, and England. On September 28, 1785, Webster noted that Curson was a man of “respectable character.” In October, Webster met him for tea, and three months later in January 1786, they dined together. In April 1786, Mr. Burling of New York killed Curson in a duel. The dispute seemed to be over Curson fathering a child with Burling’s sister. Burling wanted Curson to pay him money and he pursued Curson from the West Indies to London and finally to America. Burling challenged Curson to a duel and stabbed him in the groin. Curson died three days later. I wonder how much Webster knew of the allegations when he deemed Curson a “respectable character.”

This article was spun from seven out of my 500 cards. The possibilities of making sense of Webster’s social life through historical research right at my fingertips is something I could not have imagined 16 years ago. Webster, at a young age, was a man of the world and must have been pleasant company. My cards show he had numerous meetings with the same people and then they introduced him to their friends. Knowing something about his meetings helps us to open a window into the social context of a world of ideas, duels and travel that are not so familiar to us today. There’s a lot more to learn from my green shoebox!
