## Noah Webster and Amos Beman {-}

*Originally appeared in West Hartford Life, November 2005. Thank you to Robert Forbes at Yale for bringing my attention to this letter.*

In 1840, Noah Webster, age 82, wrote the following letter to Amos G. Beman, a black Congregational minister and abolitionist in New Haven.

> Mr. Beman,
>
> I have your note of thanks, with a request that I would refer you to such authors as may give you some account of the origins of the African race.
>
> In answer, I would remark that of the woolly haired Africans, who constitute the principal part of the inhabitants of Africa, there is no history. There can be none. That race has remained in barbarism from the first ages of the world; their country has never been explored very fully by civilized men, & the late efforts of travelers to penetrate to the sources of the Niger, have not been very successful.
>
> Of the nations inhabiting the northern portions of Africa, who are of a different origin, viz. the Egyptians, Carthaginians and Numidians, I suppose you will find the best accounts in some Encyclopedia, under the words Copt, Egypt, Carthage & Numidia – add also Moors.
>
> Yours respectfully,
> N Webster

A twenty-first century reader may well cringe at this correspondence. But a closer look at Webster’s times and at Amos Beman’s beliefs can illuminate the range of ideas about racial equality in the early 19th century.

For many years, scholars have argued that Connecticut’s treatment of African Americans both enslaved and free, was paternalistic and overshadowed by abolitionists. However, recent scholarly research and books for a popular audience like the newly published book *Complicity: How the North Promoted, Prolonged, and Profited from Slavery* by Anne Farrow, Joel Lang, and West Hartford’s Jenifer Frank, challenge this view. The authors describe how much whites in the north participated in the institution of slavery either by owning slaves or profiting through trade. This milieu sets a context in which Webster could make a statement which was degrading to Africans.

Webster's letter was typical of nineteenth-century "white" American opinion. Webster and his contemporaries assumed that vast, fixed, biological, and intellectual differences separated Europeans from Africans. He believed these things were fixed by nature, not constructed by human beings. These assumptions led to a tremendous cultural divide between the Africans themselves, and whites who supported emancipation but not equality and those few whites who supported emancipation and equality. A belief like Webster’s led to decades of racial discrimination before, during and after the Civil War.

As early as 1785, Webster wrote that he wanted the abolition of slavery to be part of a new constitution. In 1791, Noah Webster co-founded Hartford’s Society for the Abolition of Slavery. He believed, as many northerners did in the 19th century, that slavery should end, but he never conceived of free blacks having the same rights as whites. Lincoln, in his writings and speeches, claims to want to free the slaves, but he does not accept social, political, or economic equality, just a short time after Webster died in 1843.

Webster’s writings 50 years earlier, in the 1790s reflect interest in emancipating slaves, but not in equality. In 1793, Webster published a lecture called "Effects of Slavery on Morals and Industry," in which he argued that it was not economically profitable to favor enslaved over free labor. Webster believed he needed to convince slave owners that it was in their best economic interest to emancipate slaves. He felt slave owners would be alienated by appealing to them about the immorality or cruelty of slavery. And, there were many who perceived that slavery uplifted what Webster stated was the “race [that] has remained in barbarism.” Webster may have seen educated, Christian, free blacks in a different light than the Africans in Africa, but clearly he gives Beman very little to feel good about in this letter.

Amos G. Beman, the recipient of Webster’s letter was a black minister and abolitionist leader from the Temple Street African Congregational Church in New Haven, who later served the Talcott Street Church in Hartford. Both Amos Beman and his father Jehiel organized abolitionist and political conventions throughout Connecticut. They were leaders of Connecticut’s black abolitionist movement, and they led a successful petition drive in 1847 for black suffrage which was passed by the General Assembly. However, the right to vote was defeated in a statewide referendum soon after. Clarissa Beman, Amos’ first wife founded the Colored Female Anti-Slavery Society in 1834, the second one of its kind in the country.

Beman’s Congregational and evangelical religious beliefs moved him to be an abolitionist, in many of the same ways it moved many white Congregationalists. Beman believed that all people --- British, American and African --- suffered from sin. He believed Jesus would emancipate equally all people from the slavery of sin. This salvation would lead to a colorblind society.

Beman believed God treated all sinners equally. He believed that black people had a moral obligation to reform themselves. Beman believed that people had to try to eradicate selfishness and be kind. He preached against drinking alcohol, theater-going, and the use of tobacco. He argued that if black people could show white society that they were morally pure, they would more likely win the right to vote. Lewis Tappan and Beman helped found and later served on the executive committee of, the American and Foreign Anti-Slavery Society. Beman recommended disobedience of the Fugitive Slave Law and made his Hartford church a station on the Underground Railroad. Beman’s religious and moral beliefs matched those of many of the white religious abolitionists.

Perhaps part of Webster’s point is that education is the hallmark of civilization; Webster knew Africans in Africa were not educated as Americans were. Webster is certainly willing to correspond with the educated Beman, but Webster cannot see any history of people who had no written language or formal schools. Beman believed, like Webster did about white people, that blacks had a history. Webster could not fit that into his frame of reference.

However distasteful Webster’s words may be to us today, if we do not listen to Webster’s voice, it makes the Civil War and equal rights seem inevitable. A look at the tensions of the 1840s makes us realize that racial equality and abolition were clearly contested terrain that we still address. It is our job to try to understand the motives of men like Webster and Beman. This allows us to see the past as a contentious playing field of ideas and actions, not one ordained by nature or God.
