## Noah Webster the Federalist {-}

*Originally appeared in West Hartford Life, July 2007*

In 1800 at age 42, Noah Webster penned a pamphlet called “A Rod for the Fool’s Back,” in which he took New Haven’s Abraham Bishop to task for supporting Democratic-Republican principles. The pamphlet, published in New Haven, was part of a flurry of pamphlets stirred up by the Democratic-Republican win in the 1800 national election. Webster’s pamphlet was a searing commentary not only on Bishop’s beliefs, but also on his virtue. Webster believed that Bishop cared only about his own self interest, and that his political beliefs would hurt the common good.

Webster was a staunch Federalist who believed in a strong national government, a standing army and navy, and a unified culture based on a common language. On a national level, Democratic-Republicans like Bishop believed that we needed no foreign diplomats, no national debt, and no attention by the government to commerce. Connecticut Democratic-Republicans had so little power that the 1800 federal election win gave them some hope.

From 1800 to 1816, in five straight elections, Connecticut voters cast the majority of ballots for Federalists. In 1804 only Connecticut and Delaware gave their electoral votes to the Federalist Charles Pinckney. In 1816 when James Monroe ran against Federalist Rufus King, Connecticut once again voted for the Federalist, this time with two other states. Being a Democratic Republican in Connecticut meant being in the minority, even though nationally they were the majority. Webster’s support of the Federalists was mainstream for Connecticut.

Webster found himself embroiled in a debate about both national politics and the state Charter of 1662, which unlike most other colonial constitutions, had not been replaced in the 1780s after we separated from England. But by 1800, when Democratic-Republican Thomas Jefferson defeated Federalist John Adams for the presidency, followers of Jefferson in Connecticut were encouraged to believe they should have some say in state politics. Both sides used both national and state issues to garner support.

By 1800, Webster had been married for 11 years and had four of his eight children. In 1798, Webster moved to New Haven from New York City where he edited the Federalist *American Minerva*, New York’s first daily newspaper. From 1802 to 1807, Webster, the Federalist, represented New Haven in Connecticut’s General Assembly. He helped make the laws to carry out Connecticut’s 1662 charter.

The national fight between the Federalists and the Democratic–Republicans spilled over into state issues. The Connecticut state government “established” or supported the Congregational Church with tax money longer than any other state in the union. When all but Connecticut and Rhode Island rewrote their state constitutions in the 1780s and disestablished their Congregational churches, Connecticut did not do so until 1818, because of the power of the Federalists here. The Federalists believed that their policies furthered the common good and used the tactic that Democratic Republicans did not understand the common good -- only their own self-interest.

The Charter of 1662 required all people to attend Sunday services and pay taxes to support the local church unless they got a certificate signed by an officer of a dissenting church, like the Baptists, Quakers, or Episcopalians. A 1791 law stated that the certificate had to be signed by two civil officers, always Congregationalists, and so the dissenters were often harassed. These laws, while attempting to solidify the power of the Congregationalists, actually caused an uproar among the dissenters like Bishop, and helped them to get support from the Republicans.

Webster was a Congregationalist, but one who did not support the establishment of a particular denomination. He believed, as he said in his 1828 dictionary, that religion was the source of virtue:

> In my view, the Christian religion is the most important and one of the first things in which all children, under a free government, ought to be instructed... No truth is more evident to my mind than that the Christian religion must be the basis of any government intended to secure the rights and privileges of a free people...

However, unlike other Federalists, Webster had a more wide-ranging view of religion and did not feel that Congregationalism was better than other Christian sects. He would have been happy with the 1818 Constitution, which disestablished the Congregational Church but privileged Christianity. In Webster’s pamphlet, his religious views come out by lumping Bishop, a deist with “Atheists, Adulterers and profligate men” who will “lead the people to destruction.”

Webster characterized Bishop’s pamphlet as “mere rant, declamation and incongruous sentiments, incapable of being comprehended, much less answered.” He claimed that Bishop wanted to be part of the state government only for his own self-interest, not for the good of all. Webster argued that the state was doing very well economically, so why would anyone want change? The government’s regulation of trade and its relationships with other countries were very important to the Federalists, but not to the Democratic Republicans. Bishop believed all foreign entanglements were a waste of good taxpayer money.

Bishop believed that Alexander Hamilton’s funding scheme for Revolutionary War state debts was a “calamity” and led to “aristocracy, even more so than in France.” Democratic Republicans did not believe in having a national debt, or in funding state debts incurred during the Revolution. They believed that a citizen’s allegiance should be to his state, not to his nation. Webster countered by saying that only a small number of speculators grew rich off the funding scheme. In fact, Webster argued, independent farmers got most of the money.

When the Constitution was written, Democratic-Republicans won the election of 1817 to push for the Constitutional Convention. Once the Democratic-Republicans held power, they could change the charter. The Constitution opened up suffrage to all white men. But Webster clung to his Federalist beliefs claiming:

> The very principle of admitting everybody to the right of suffrage prostrates the wealth of individuals to the rapaciousness of a merciless gang who have nothing to lose and will delight in plundering their neighbors.

In the early 19th century, as both state and local issues became part of the political world, Webster held fast to the ideas of the Federalists long after the party had lost its national and then state power. He believed that the right people who served in government had to protect the state from those who were in government only for their only self-interest. While Webster believed he knew who those leaders were and what their vision of the US was, so did Bishop. Each believed they would serve for the common good and both believed the other was in politics for their own self-interest, a conflict which appears in politics to this day.
