## Noah Webster, 248 Years Later {-}

*Originally appeared in West Hartford Life, September 2006*

The 13 foot, 8.5 ton marble statue of Noah Webster, with one finger missing, endangered by acid rain and errant vines, is gone from its spot at 50 South Main Street. On Thursday, August 11, 2006, conservators removed Korczak Ziolkowski’s statue which had graced the lawn of the old Town Hall building for 65 years.

The statue is part of the town’s logo and Webster’s presence symbolizes the town’s dedication to learning. Naming the new development Blue Back Square is further evidence of the man’s influence in the town.

Webster’s 250th birthday will be here in just two years and already the Noah Webster House and West Hartford Historical Society is planning a bash. What form will this take? How will we remember Webster in 2008?

In 1958 for his 200th birthday, West Hartford had no ordinary celebration. The West Hartford Historical Society and the Noah Webster Bicentennial Committee held a parade, followed by a “huge community banquet” at Temple Beth Israel on Farmington Avenue. Governor Abraham Ribicoff, U.S. Senator William A. Purtell, U.S. Representatives Edwin May, Thomas Dodd and Rohe Walter attended both events.

The parade began on Memorial Drive, stopped for a ceremony at Webster’s statue on South Main Street, and then proceeded east on Farmington Avenue all the way to South Highland Street. The parade included the Governor’s Foot Guard, Governor’s Horse Guard, the Conard High Band, the West Hartford Remington Riders and a number of floats.

The celebration included a four cent Noah Webster commemorative stamp first available here and delivered to all West Hartford homes by their mailman as a souvenir. Businesses in the community sponsored the mailing.

A town wide spelling bee on October 15 was held at the Duffy School, with Ross Miller of WTIC as master of ceremonies. Governor Ribicoff presented the keynote address. Included at the head table with him were the president of the Merriam Company which owned the Webster dictionary, Mayor Harold Keith, and ministers from three faiths in West Hartford.

Along with the postage stamp, every home in town also received a pamphlet called “Your Schools” devoted to Noah Webster and produced by the School Department.

*The West Hartford News* produced a 24 page “souvenir supplement” on Webster. Henry Steele Commager (1902-1998), the head of the history department at Amherst College, wrote the cover article. At that point, Commager was “one of America’s most noted historians,” a devotee of the consensus school of American History. This same article appeared in the *Saturday Review* just two days later.

Commager was a prolific writer who believed that history should inform the public discourse. He continually transcended the divide between the academic and the public world as he lectured extensively and wrote hundreds of articles and columns for the public press. He campaigned for political candidates, railed against the anti-communism of Senator Joseph McCarthy, and publicly opposed the Vietnam War. He rallied other liberal historians like Arthur Schlesinger behind his causes.

So what did Commager say about Webster almost 50 years ago?

Commensurate with the consensus school of history, Commager argued that Webster’s *Blue Back Speller* served to draw all Americans together with a common language. Commager argued that “under its benign guidance, generations of young Americans learned the same spellings, the same pronunciations; read the same stories; absorbed the same moral lessons.” Commager claimed that Webster deserved to be considered one of the Founding Fathers and clearly he was “Father of the American language . . . and of American education.”

According to Commager he was also a Father of American political thought in his *Sketches in American Policy* (1785) and as editor of the *American Magazine*, the *Minerva*, and the *Herald* through the 1830s.

Webster was a leader in science with his two volume work the *History of Epidemics*. He was the father of the copyright, one of the first to write about American history, and American banking and finance. Webster, like Thomas Jefferson, rewrote the Bible, and wrote the first American dictionary in 1806 and then in 1828.

Yet, according to Commager, Webster did not have the mind of a Jefferson or Franklin. He claimed Webster was full of “nagging ambition, grim determination and indefatigable officiousness… and vanity.” For all his wide range of interests, Webster “did not have an open mind.” Commager argued that Webster was:

> narrow, cold, almost passionless, [and] was wholly lacking in those grace-notes his great contemporaries added to their scores with such ease. He read everything, but in order to get definitions for his dictionary; he taught music, bur revealed not the slightest interest in the musical giants of his own time; he studied history, but only to learn that man is vile. He knew the languages of 20 nations but was interested in none of these; he visited France only to deplore its licentiousness; he visited Cambridge only to remark on the inferiority of its architecture. He was devout, but curiously untouched by religious sentiment... He was zealous for education, but had little faith in the young, and thought voting should be restricted to those over forty-five.

Even so, Commager believed that Webster was much more than his personality. He should be remembered for his desire and ability to build an American culture. Commager thought that, through language, he diminished the role of class, background, or region to invent a common culture, especially with his Blue Back Speller. Commager argued that “no other secular book has ever spread so wide, penetrated so deep, lasted so long.”

And, Commager said, Webster was typical of his age. The Founding Fathers were intent on building a national character which differentiated this new country with the corruption and division of the Old World. No longer would the Monarchy, the Church, the Aristocracy, or the Military be the definers of the nation.

For Commager, Webster’s role as “teacher” was his most important role. In 1958, Commager argued that “in America the teacher should play a larger role in the creation of nationalism than almost anywhere else. . .because the United States was the first nation to inaugurate anything remotely like universal free education.”

Webster was the first to write “moral and patriotic readers.” On page one of Part III of the *Blue Back Speller*, Webster wrote, “Begin with the infant in the cradle; let the first word he lisps be Washington.” Webster believed that learning about the great men would build pride in nation.

Commager concluded that Webster’s most important contribution to American culture was building a pride in the American language and literature. Even though he was a practical and utilitarian in all he did, his key contribution was developing a belief in the United States as a unified, successful, self-sufficient whole.

Interestingly, Commager prided himself on being a teacher first and scholar and writer second. In the midst of the Cold War, an excellent education system for all seemed to distinguish us from Communist countries, as well.

In 2008, on Webster’s 250th birthday, with a national consumer culture, but a country as ethnically diverse as ever, will our interpretation of Webster’s influence on the nation change? Do we still consider a common language a binding force? Does education tell our nation’s story? Is this education accessible to all? Stay tuned!

The Noah Webster House is reviving the Noah Webster Birthday Party. Come September 30 for the celebration!
