## Noah Webster’s Sketches in American Policy {-}

*Originally appeared in West Hartford Life, September 2008*

With election season rolling around, it is fun to look back at Noah Webster’s take on the new republic in 1785. Webster yearned for a strong national government and an American culture that emerged from the American Revolution based on the power of citizens. How did Webster want to define this new government and why?

October 16, 2008 marks the 250th anniversary of Noah Webster’s birth in the West Division of Hartford and the Noah Webster House will be celebrating Webster’s legacy in a number of ways this fall. Though he was not considered a “founding father,” Webster was a man who was part of the founding generation who weighed in on many key political issues.

While Noah Webster is most famous for his 1828 dictionary, and in West Hartford for his *Blue Back Speller*, he boasted that he was the first person to call for a strong federal government two years before the Constitution was written in 1787.

In Webster’s *Sketches in American Policy* (1785), written as a four-part pamphlet, he outlined the need for a strong central government. His arguments helped him define an American character different from Europeans and from the native “savages.”

At age 26, Webster was bold enough to print his Sketches, and in fact the record shows that James Madison, author of the Constitution, read it. According to Webster’s most recent biographer Harlow Unger, Sketches had “a far wider circulation than any other published Federalist document prior to the Constitutional Convention and covered a broader range of issues.” In the fourth section of Webster’s pamphlet, he urged the public to call for a stronger central government based on the will of the people, not based on power that emanated from state governments.

Webster knew citizens feared that a strong central government could lead to tyranny, the main issue of the American Revolution. Webster believed that a strong central government, abolishing slavery, and a good educational system would all protect Americans from tyranny.

Webster argued that until the 1780s, three principles made an independent state: a standing army, a government controlled by religion, which made government less transparent, and the fear of an enemy nation. After the Revolutionary War ended, according to Webster, none of these existed in the United States.

He believed standing armies should be banished from free governments because they could easily be used as an instrument of tyranny. The Confederation Congress did establish a standing army in 1785, but it was under civilian control and Webster did not perceive it as a threat to democracy.

He argued that Christianity had been separated from the state and thus would work in a spirit of peace and harmony, not coercion as it was used in many European countries. Even though Connecticut had an established church, and citizens paid taxes to that church, Webster did not believe the Congregational faith was used to keep people in ignorance.

Webster did not feel that either Canada or Mexico were enemies that would unite us and he believed that we would stay out of Europe’s business, so Americans would not be united by a common enemy.

Webster wrote his *Sketches* with a sense that there needed to be national government that would help bind us into an American nation. States could easily opt out of any decision made by the Confederation Congress with no penalty. The most famous example was both Rhode Island’s and New York’s refusal to support taxes in the form of an import duty. The Congress needed money to pay off war debts, but the fear of a far away government raising taxes was too much for either state. Hadn’t they just fought a war about taxes and hadn’t they wanted a voice in that taxation? Now that they were represented in the government, Rhode Island and New York chose to use their prerogative to stop the import tax. Webster wrote, “So long as any individual state has power to defeat the measures of the other twelve, our pretended union is but a name, and our confederation, a cobweb” (p. 32).

Webster did not see the Congress as established by the Articles of Confederation defining an American nation. The government allowed for each individual state to stop the nation from acting as one. But, he also knew that Americans feared tyranny. How to strike the balance?

To protect against tyranny and have a unified government, Webster argued that power should be vested in the people, not in state governments. Under the Articles, representatives were elected by state legislatures, and thus were beholden to state governments, not to the people. Webster’s plan was to have equal congressional representation chosen annually by the citizens. He believed there should be a three-year limit on the length that magistrates could serve to insure that the people were heard.

In *Sketches*, Webster explained how an executive could work to enforce the laws without being tyrannical; he used Connecticut’s Governor as an example. He wrote:

> The state elects a governor or supreme magistrate and cloaths him with the power of the whole state to enforce the laws. Under him a number of subordinate magistrates such as judges of courts, justices of the peace, sheriffs, etc. are appointed to administer the laws in their respective departments. These are commissioned by the governor or supreme magistrate. Thus the whole power of the state is brought to a single point; it is united in one person (p. 33).

Webster put his faith in the citizens to elect the best people. He thought that if elections were held frequently and the freemen were treated equally, the government would be free of tyranny. In a footnote, he explained how he chose to vote for a candidate:

> People, in the choice of rulers, are too apt to be deceived by ... a specious show of popular virtues. I pretend not to lay down rules for other people; but for my own part, I will never give my vote to a man who courts my favor. I always suspect that such a man will be the first to betray me. Nor, will I give my vote to men, merely because they have been in office and it will hurt their feelings to be neglected. Such motives appear to me to discover weakness and a disregard to the true principles of government. I endeavor to give my votes to men, in whose integrity and abilities I can repose confidence; men, who will not dispense with law and rigid justice, to favor a friend or secure their own popularity. When I hear people talk of elevating a man to an office, because be comes next in course, and he will do well enough, I suspect they have forgot that they are freemen, and have lost their oaths or their consciences (p. 34).

Webster’s words ring true today as we head toward the polls in November. At an early age, Webster knew the importance of an enlightened citizenry to make the right decision about who represented them. This power in the hands of ordinary citizens, he believed, was the core of the American identity.
