## West Hartford Moves to Payson, Illinois {-}

*Originally appeared in West Hartford Life, December 2012*

> This building was erected by  
> Henry M. and Lucy W. Seymour  
> In memory of their only son  
> CHARLES  
> 1912  

Jeff Zanger, principal of the Payson Seymour Elementary School, Payson, Illinois, assures me that this bronze plaque is still in the “beautiful marble foyer of our building. It is the first thing you see when you walk through our front doors.”

West Hartford descendants of the first settlers of Payson funded this high school building in 1912 and named it after the Seymour family. One of the original Charles Seymours lived in the West Division of Hartford during the American Revolution and served in the local militia. His son, Martin Seymour moved to Payson in 1838 and his grandson Henry built the high school.

West Hartford’s connection with this town of 1,026 people dates back 180 years. According to William H. Hall in his *History of West Hartford* (1930), “in 1833, Albigence Scarborough, a prominent citizen of West Hartford, rode on horseback to the far-off state of Illinois, for the purpose of prospecting with reference to the establishment of a new settlement there.” Scarborough, like so many others, believed that life could be better out west; his new settlement in Payson is a story of the transplanted, a move which made him adapt to the geography of Illinois, and brought much from New England.

A 1919 book, the *History of Payson and Plainville, IL*, claimed that Payson had “some of the richest lands” in its location just five miles east of the Mississippi River, just south of where Missouri, Iowa and Illinois meet. In the 1830s, many farmers from Connecticut and Massachusetts moved west as land became scarce and word of the fertility of western land filtered east.

Scarborough, it seems, walked “much of the way, in order to save the strength of his mule to carry provisions” on his first trip in 1833. He must have found the location satisfactory as he returned to West Hartford in 1834, packed up his family and belongings in a wagon to return to Illinois.

Deacon Albigence Scarborough purchased the land on which Payson now stands and in the spring of 1835 laid out the village in a grid, having it mapped and recorded. Scarborough followed the pattern of New England towns by setting a commons in the center. With two other settlers, he laid out and sold lots in late summer 1836, and four acres of land were given by Deacon Scarborough upon which to build a school.

Scarborough named the town after Edward Payson (1783-1827), a Congregational minister from Portland, Maine who preached during the Second Great Awakening. Scarborough admired Payson, a man who read Jonathan Edwards and preached with “the eloquence of truth spoken in love.” Payson preached in Maine and in many pulpits around New England and Scarborough must have heard him.

Scarborough acted on his faith and helped to build a Congregational Church in 1839 but even before it was dedicated, it burned down. A second church, smaller than the first, was built right away. The Congregational Church was the second church in town, following the Baptist Church in 1834. In 1836 the Methodists formed a religious society as well.

Deacon Scarborough planted the first apple orchard in the spring of 1838. He bought the trees in St. Louis. A few years later he planted peach trees which produced some of the best peaches around. By 1835 a new migrant from New York opened the first store in Payson. By 1837, two merchants set up shop and one became the first postmaster.

Scarborough helped fund and build the first parsonage in 1845. Scarborough had the help of the Mormons in his endeavor. They were hounded out of Nauvoo, a town just 60 miles north where Mormon leader Joseph Smith was killed in 1844. Most of these refugees made their way to what became Salt Lake City by 1849, but in the meantime, some stopped in Payson and helped Deacon Scarborough.

In the late 1830s, many other West Hartford residents moved to Payson. According to Hall, Moses Spencer left his farm on Farmington Avenue just west of the center and took his wife and nine children there in 1839. In 1930, his descendant was one of the largest landowners in Payson. Charles Whitman, Cyrus and Wells Butler, and Martin Seymour with his wife and nine children all travelled to Payson. Seymour owned a 100 acre farm on the present site of the American School for the Deaf in West Hartford; in Payson he managed a limestone quarry.

Payson quickly distinguished itself as a place to get a good education. This was unusual for the frontier, but the West Hartford settlers seemed to take responsibility. When Scarborough sold the first land in Payson village, he took 20 percent of each sale price and donated that money to education in the town.

Before there were enough students for a public school, many were educated in private schools. The first was in an old log cabin with a roughly finished timber floor on the northeast corner of Edwards and Fulton streets. Miss Emily Scarborough, probably Albigence’s daughter, taught students at this school and later became the first public school teacher.

In 1916, Henry M. Seymour, a grandson of Martin Seymour, one of the founders of the town, donated one of the finest school buildings in the west. He gave the building in memory of his only son who was killed at age 16 playing baseball on the school playground and commemorated his son with the aforementioned bronze plaque.

The five West Division families that settled Payson in the 1830s brought material goods and values with them. While the geography of Payson, near the Mississippi River may have changed something of their daily lifestyles, their priorities stood the test of time. The idea of common land, and the importance of an education were key parts of 19th century New England settlements that descendants carried on in both towns.
