## Diversity in West Hartford {-}

*Originally appeared in West Hartford Life, November 2003*

According to the 2000 United States census, 22% of West Hartford residents spoke a language other than English at home. The languages spoken in these homes included Spanish (6.4%), other European (11%) and Asian (4%). Almost 15% of the town’s residents are foreign born. Of these foreign born, 46% come from Europe, 28% from Asia, 16% from Latin America, 6% from North America, and 4% from Africa.

When residents report their ancestries, the largest was Irish at almost 17%, followed by Italian (11%), English (10%), Germans (9%), Polish (6%) and Russian (6%). When residents were asked about their race, 86% indicated they were white, 6.3% Hispanic, 4.8% African American, and 4.8% Asian.

This represents a population which many consider to be much more diverse than West Hartford has ever been. In the schools, the differences are even more defined. That is, at Conard, for instance, about 12% are Hispanic, 9% African American and 9% Asian, about double that of the general population. These groups tend to be younger and have families.

A look back into the 19th and 20th centuries shows a picture of ethnic, racial, and religious diversity as well. The 1840 census (in which West Hartford was included in the Hartford figures), the population included Irish, German, French, and Swedish immigrants. Patrick McCabe, Patrick Martin, and James Riley were all petitioners in 1854 to make West Hartford a separate town. None, though, were among the first office holders in the new town.

The Irish presence in the 1840s, however, did not translate into much religious diversity at that point. In fact, it wasn’t until 1918 that the first Roman Catholic Church, St. Brigid opened in town. This church was a mission chapel of the St. Lawrence O’Toole Church just west on New Britain Avenue in Hartford. Today St. Lawrence O’Toole holds services in Vietnamese on Sundays.

A look at the birth records of the town from 1885 to 1899 reveals quite a diverse population before the turn of the twentieth century. Irish, English, Swedish, and French Canadians are the ancestries most listed. A look at the death records for the same time period reveals mostly native born and Irish.

Other anecdotal evidence appears as well. In a letter which described registering men between the ages of 18 and 46 for the war on September 12, 1918, three interpreters were present: N.C. Casciano, Italian, Bernard Caya, French, and Malcolm Swanson, Swede. In 1918, West Hartford’s population stood at about 8,000, and there was a need for interpreters in three different languages.

By 1919, Swedes bought property on Park Road near Oakwood Avenue for $1,000 to build a chapel seating 200. The structure was built mainly by men from the church. In 1921 the West Hartford Ladies were organized into an auxiliary and by 1941, they had worked long enough and hard enough to pay off the mortgage. The Swedes were active in the Boy Scouts and they built a cabin for the troop near Mountain Road in the area around Spice Bush Swamp. Very quickly the West Hartford Chapel had to be enlarged because the Sunday School grew so rapidly.

Even today, the legacy of this large group of Swedish immigrants remains in the Park Road area. You can still buy Swedish sausage and bread at Hall’s market. A.C. Petersen’s and Youngstrom’s Floor Covering are still going concerns.

But, today if you drive down Park Road, you will see a distinct Asian presence with a Vietnamese and a Chinese market, and Pho Tuong Lai, a Vietnamese restaurant.

In 1936, Congregation Beth Israel moved from Hartford to 701 Farmington Avenue. Jews began to move from Hartford’s north end to West Hartford in the mid 1920s. Abraham Feldman had been the rabbi of the congregation since 1925. When he came to Hartford, there were about 200 families at the temple. When he retired in the early 1970s, his West Hartford congregation had over 1,400 families with more than 1100 children in the religious school.

Feldman, in an oral interview in 1974, remembered West Hartford as being a closed community politically. He believed it was “the most Republican town in the United States.” Feldman related that there was “no chance for a young Jew, or a Jewish lawyer... to enter the political life of the community.” He said this was also true for Catholics.

Feldman related a story he had with a town chairman of one political party in town at the dedication of the Universalist Church in town in 1931. Feldman said the chairman asked him point blank, “What do you want?” He replied, ”There isn’t a damn thing I want from you... I have never come to ask you to appoint a Jew, to give a job to a Jew, or to do anything else for a Jew. But heaven help you if I ever get a report that you have denied a job to a man because he was a Jew.”

The Catholic population had been in town longer than the Jews, but still the Protestants controlled the town politically until the 1960s when Democrats got elected more frequently. In the 1970s and 1980s Sandy Klebanoff, Beverly Greenberg and Lonnie Brick led the Town Council and Board of Education.

How has the town reacted to these changes? It seems like the economy changes first. The various ethnic and racial groups establish businesses and through that become a part of the community. It seems as though it takes at least another generation to get political representation.

The newer migrants to West Hartford --- Asians, Hispanics, and a larger group of African Americans --- have only begun to test the political waters in town. The first Asian, Naogan Ma, who serves on the Board of Education, is a Republican. Today’s elected officials reflect the ethnic diversity of second and third generation migrants from the 1920s, 1930s, and 1940s. Present members of the Town Council and Board of Education represent the Irish, Italian, French Canadian, and Jewish migrants of two or more generations earlier.

Though the housing stock in town has changed little since 1970, those who live in those houses have changed, not so much in their economic backgrounds as in their ethnic and racial makeup. In a real democracy, the town government should reflect those changes, but using the past as a yardstick, without any direct recruiting and encouragement, it may take another generation.
