## We Are What We Have {-}

*Originally appeared in West Hartford Life, December 2002*

When I look at the possessions in my house, I know that life is different for my children than it was for me. They have more things: more toys, more sports equipment, more books, computers, electronics and even different types of food.

The material trappings of a 21st century life reflect not only what we have, but also our values. Different things surround me, and my beliefs are shaped, to a degree, by these possessions.

Historians look back in time to reveal both what we have in common with those who lived before us and what makes us different. They like to discover connections between people over time that reveal not only what they own, but also what they thought and felt.

An 1836 inventory from West Division resident Thomas Barrows gives a snapshot of his world. When Barrows died in 1836, officials from the town came to his home and enumerated all of his belongings.

When I read his inventory, a list that goes on for five and a half columns, I see evidence about how life changed in the West Division from 1770 to the 1830s, and I think about how national and world events contributed.

The first industrial revolution began in the U.S. because of an embargo of British goods caused by the war of 1812. With the embargo, Americans began to manufacture more of their own products outside the home and shops and factories. This began with the mass production of textiles in Lowell, Massachusetts, around 1815 and continued with mass production of chairs, pottery, and carpets. Manufacturers used new technology and a new organization of work to produce better goods at a cheaper price.

As farmers began to specialize and produce a surplus, they joined the market economy and had the means to buy more products. Transportation improved with the coming of the steam engine and railroads; the steamboat and canals also encouraged trade.

Thomas Barrow’s inventory does not let us down on this score. His belongings revealed the increase in the amount of goods Americans possessed.

He had more than 40 pieces of clothing including nine coats, nine pairs of pantaloons, six cotton shirts and nine vests. This is far more clothing than the three sets of clothing the average man had in the 1770s.

Cloth was cheap and without having to spin, women had more time to sew clothing. Even though he had a great wheel, it is likely it was used only for spinning thread for specialty items, not for everyday cloth. He had one pair of boots and three pair of shoes.

Some items tell us about trade. He had a silk handkerchief, silk stockings and a palm leaf hat. The China trade, which began in the 1780s, continued, and the interest in producing silk cloth in Connecticut had begun. Cheney Mills in Manchester started to produce silk cloth. It is likely the palm leaf hat came from the British -controlled islands in the Caribbean.

The Barrows inventory reflected the increased importance of individualism found in the amount of silverware. In the 1770s, some inventories list no silverware. Barrows had three sets of knives and forks, two large silver spoons, five tablespoons and twelve silver teaspoons.

He had a tin wash basin. In the 1770s, wash basins were made of pottery. The 1850 census shows that a tinner actually lived in town. Barrows also had tin funnels, a tin coffee pot and a tin two-quart measure. In the 1770s, measuring for baking was done with a pottery cup with no markings. In the 1830s, the first recipe books came out which required more exact measurements. New foods were available and cooking changed as people began to use cook stoves rather than cook over an open fireplace. No longer was a meal made as a stew in one pot.

Barrows owned a carpet, a new addition to home decorating. This was a sign that people had money beyond what it took to provide food and shelter. Carpet mills in Tariffville and Thompsonville had already started to manufacture these carpets.

Though there is no evidence in his inventory, some people put wallpaper on their walls for the first time and others added curtains. This ability to decorate was not just an activity of the rich, but served the middle class as well.

Barrows’ brass clock may have come from the fledgling clock industry in Waterbury and signified an increased interest in time, which came with industrialization's marketing of a workday in hours.

But some things continued. Reminding us of 60 years earlier, Barrows had a horse harness, leather halter, horse whip and draft chain, a plow, a wood saw, 30 harrow teeth, a hoe, an axe, an iron crowbar, an ox yoke and an iron shovel, all tools of a farmer.

Barrows had a Bible and a psalm book and these were his only books. He had horses, swine, sheep and cows. He had 4 pounds of wool rolls, 5 bushels of wheat, 4 bushels of rye, 2 and a half bushels of wheat, 100 bushels of potatoes, 17 pounds of butter, 10 tons of hay, 6 barrels of cider and 75 pounds of cheese. These items showed continuity with the past.

He had mulberry trees worth $14, the value of one of his 24 acres of land. Silkworms live in mulberry trees, and there was an idea that they could grow silkworms in New England for the silk industry. Only two years later the Cheney Silk Mills opened in Manchester.

Why would Barrows take a risk and invest in mulberry trees? As a budding capitalist, he had an idea that his investment could bring him some profit along the way. He had to have a surplus to take the risk; he had to have an idea to take the risk. He had to have the means to procure a tree, all things that took time and money. Woefully, this experiment with mulberry trees was unsuccessful, though the silk industry in Connecticut was quite profitable from the 1840s to the 1920s.

Thomas Barrows’ inventory provides a snapshot into a life during Andrew Jackson's presidency that shows both continuity and change. He was both a traditional man with his roots in farming, but also a man accepting new ideas with his carpet and his mulberry trees. Often it is our grounding in the past that allows us to try new things.
