## Remembering Romanta Seymour and 19th Century Agriculture {-}

*Originally appeared in West Hartford Life, April 2010*

In 1850, if you stood on the ridge that is South Main Street where it meets New Britain Avenue, cleared fields, pastures, and woodlots would surround you. You might see a grist mill to the east along Trout Brook and the South District one-room schoolhouse to the west.

If you traveled down the hill toward Elmwood Center, you could find Romanta Seymour's farm. In October 1850, the Hartford County Agricultural Society awarded West Hartford’s Romanta Seymour second prize in a contest for the best-cultivated farm in the county. Seymour won $15 for his farm production, which made a 19 percent profit over the 1850 growing season.

By 1815, competition with western farms began the switch for New England farmers from wheat and meat production into dairy farming and vegetable production. Transportation improved over the next 35 years, allowing local farmers to more easily sell their surplus. The Hartford-New Haven Railroad line opened through Elmwood in 1839. Agricultural societies and fairs flourished under state aid.

Farmers began to use more scientific methods to increase their yields and the agricultural societies supported these efforts. The Hartford County Agricultural Society was incorporated in October 1817. While the industrial revolution in textiles began during this period of time, agricultural production continued to drive the U.S. economy. The value of agricultural goods increased more than 100 times between 1810 and 1880. West Hartford farmers were part of this growth in production.

Romanta Seymour's house lot of 50 acres was on the south side of the old Farmington Road, now known as New Britain Avenue. The entire front of his property was lined by a white picket fence, according to the agricultural society, “giving a pleasant and comely appearance.”

In 1847, Romanta Seymour passed the farm's management to his son William, who actively worked to increase the cultivation and production of the land. According to Seymour, the field produced a large hay crop without any manure and only a light top dressing of ashes. He planted grass seed in two small patches and its yield increased so much that he thought he would do that more in the future. His fields produced between two and three tons of hay to the acre. The average farm produced between three-quarters and one ton per acre.

Seymour probably planted about one quarter of his acreage in hay. The pasture at the end of the ravine that ran through his farm had not produced much under his father's cultivation. However, William plowed the tract and the improvement raised yields by 50 percent.

He bought a section in the southeast part of his farm, which was covered with white birches and bushes so thick that even the cattle could not get into the area. In the past three years, Seymour "subdued it" to get in a crop of buckwheat.

Buckwheat, not related to wheat, grows best in a low-fertility, acidic soil. Today buckwheat is eaten as soba noodles, porridge and kasha. The grain grows quickly and is used as a second crop in the season, especially where the growing season is short. Some farmers use buckwheat as a cover crop because it grows and establishes itself quickly and keeps out weeds. Seymour's crop netted him $50 in 1850.

According to the agricultural society, this land would soon turn into "handsome meadow ground producing hay in abundance, adding more than 100 percent to its value." Seymour's intensive use of the land through his "untiring industry" was a major factor in winning the agricultural prize.

Seymour owned 12 acres of land across the street to the north of his house. On this patch, he had three acres in pasture and the rest in grass and corn. The agricultural society commented on Seymour's use of manure. He had large stalls with abundant straw. With some of last year's manure remaining in the bottom to act as yeast, he was able to accumulate a good batch of manure. His animals produced 200 loads of manure annually, all of which Seymour plowed in for crops.

Even though by 1850 many New England farms had switched to dairy, it is unclear how many cows Seymour kept, but he did raise hogs and turkeys. He started an orchard by planting young apple trees that in 1850 were growing "luxuriantly.” He grew strawberries and had beehives and grew 11 different crops. Seymour's income also included pasturing a neighbor's two cows and a calf for $21 and labor done off the farm garnered $72.

He grew crops to consume directly, but also marketed some. According to former Town Historian Nelson Burr, rye was in great demand; West Hartford had a prosperous distilling business. Elmwood's Ebenezer Faxon specialized in distilling and selling rye. The Goodman family distilled rye, corn, barley and cider. Mountain Road and Still Road had five distilleries and Gin Still Hill had three. The Connecticut River Valley also grew into a center of broom making and Seymour's broomcorn would have fed this industry. His hay and corn were most likely fed to animals.

Seymour's expenses included $160 for his own labor and $180 for hired labor. He bought ashes and plaster worth $47 and seeds for $25. His 19 percent profit for his work added up to $757 and led his farm to be recognized in Hartford County.

In 1850 West Hartford, farming dictated the rhythm of life. The fields, barnyard, garden and household ruled the lives of young and old from April to November. But farming changed with the market, just as manufacturing did. Farmers like William Seymour were moved by supply and demand, using their acreage to make the highest profit, and experimenting on plants, animals and insects to insure a good income. To be a good farmer in 1850, farm owners had to change with new technology, markets, transportation and crops. Seymour's willingness to take risks on his farm led the Hartford County Agricultural Society to honor him.

In so doing, the society encouraged others to step out of the traditional ways and experiment, not unlike those in the industrial sector.
