## The Story of Vanderbilt Hill {-}

*Originally appeared in West Hartford Life, March 2004*

In a recent class, I asked my students if they had ambition. Do you expect, I asked, to live in a house larger than that of your parents? At least three-quarters of the students answered yes. I wondered at the pressure that put on them, and when the size of houses and rooms in houses would ever level off. Then I remembered the Vanderbilt Mansion.

In the mid 1870s, Cornelius Vanderbilt decided that his son, Cornelius, Jr. should have a mansion and that its location should be West Hartford. The mansion was to be built on a 75 acre farm at the peak of Farmington Avenue, across from Whiting Lane. Vanderbilt selected and bought this site in the late 1850s after he had surveyed prospects for the New Haven Railroad and the Providence & Fishkill railroad having routes through West Hartford.

Mark Twain called Hartford the richest city in the world, and New York City was building its reputation as the center of commerce and culture in the United States. West Hartford was but a farm town. The population in 1880 stood at just over 1,800, and the town had been independent from Hartford for only 25 years. No doubt the town was beginning to change with farmers specializing in dairy, and an increase in the number of immigrants, but wealth even on the scale of the most scorned Vanderbilt son hadn’t really been seen before in the town.

Cornelius Vanderbilt (1794-1877) first made his money when he monopolized ferry service and then shipping on the Hudson River. By the mid-19th century, he invested in the luxury liner business and then by 1857 in railroads, eventually taking control of the New York and Harlem Railroad, and the New York Central. He built Grand Central Terminal in New York City and employed thousands of men during the Depression which began in 1873.

Vanderbilt had two sons, and eight daughters. Young Cornelius never lived up to his father’s expectations and was sent off to live in a modest farmhouse on what is now known as West Hill, the same hill on which his mansion was built. His father bought the 75 acres in 1857 from the Hamilton family. Cornelius, Jr. hated every minute he was away from New York City. While living in West Hartford, young Cornelius went into debt. When his father died in 1877, he thought his money problems were solved. However, Vanderbilt left his son William $95 million dollars, his eight daughters split four million dollars, and Cornelius received just $12,000 a year.

Cornelius, Jr. tried to use the money to break his father’s will. This gave him some ability to borrow money to build what he called his “dream house” on Vanderbilt Acres. He borrowed half the price of the $60,000 house, a fortune at the time, for this area, but only a small amount compared to his father’s and brother’s mansions in New York City.

Cornelius hired architect John C. Meade to design a 27 room house on Farmington Avenue. Meade designed a four story tower mansion with a view of Hartford and the valley to the west. The mansion’s cupola rose five stories high. The central hall was wide enough for a horse and buggy to turn around in. The mansion had a veranda on three sides. The brownstone wall and entrance are the only things left from the house, setting it off from Farmington Avenue

But, Cornelius had no luck breaking the will, and thus was stripped of his West Hartford house and land. Meanwhile, sympathetic friends bought it and sold it back to him for $1. However, Cornelius never lived in the house. He committed suicide in 1882. His desire to “live like a Vanderbilt” never happened.

The house was auctioned off to a real estate speculator and stood empty for six years, while a caretaker kept it up.

Ira Dimock, a rich Hartford silk manufacturer and inventor bought it in 1888 and lived there. In May 1917, his wife died in the house and he died a week later at age 90. In the midst of World War I, no one felt capable of taking care of the house, and it was torn down in 1918.

![Ira Dimock, a silk manufacturer, owned and lived in the Vanderbilt mansion from 1888 to 1917. His son Irving Dimock died in the Spanish American War of typhoid fever in a camp training to go fight. Another son, Stanley Dimock teamed up with Horace Grant to tear down the family mansion in 1918 and establish the West Hill neighborhood with 25 homes. Source: Noah Webster House & West Hartford Historical Society.](images/04-Dimock-web.jpg)

Dimock’s son Stanley Dimock and Horace Grant, a Hartford manufacturer, developed the Vanderbilt Hill area after the mansion was torn down. The houses Dimock built were smaller than the house he had grown up in. The two men made sure that the 25 homes built were all single family with garages. The developers approved each architect who designed the houses and made sure that each one cost at least $10,000. The development became the first to put electric lines underground. The first house, completed in 1920, stood on the site of the Vanderbilt Mansion.

Both Cornelius Vanderbilt, Jr. and Stanley Dimock built and lived in homes that were smaller than those of their parents. Cornelius would say that his son lacked ambition and his alcoholism sank him into depression. Dimock, on the other hand, chose to make more of the land on which he had grown up by subdividing the land and making a handsome profit. Since 1988, West Hill has been denoted an historic district, representing a new style 1920s suburban neighborhood.

The Vanderbilt Mansion was the first of several mansions in town in the 1870s and 1880s. The first wave of suburbanization was not the middle class, but it was the upper class who moved here first. The Russell Mansion, at the corner of Prospect and Cone Street, built in 1874 was four stories. It too has been demolished. The Home of Yung Wing on the corner of Prospect and Fern was demolished as well. The Judd Mansion on Highland still stands, now surrounded by the Hughes Convalescent home. It wasn’t until the 1890s, when the electric trolley came through that developers began to build middle class housing. The ambitions of the wealthy in the 1870s and 1880s could not be sustained by the next generation as witnessed by the number of these mansions that were demolished.
