## Democracy in the Mid-19th Century {-}

*Originally appeared in West Hartford Life, December 2000*

What did freedom and independence mean for the new town of West Hartford in its first decade? How did democracy take shape in this town of about 1,200 Americans in the 1850s and 1860s?

Democracy here was contentious and bipartisan. The 153 men who petitioned to the General Assembly for independence in 1854 argued that with a population of more than 1,200 and a Grand List of more than $20,000, it was as large as most of the towns in the state.

The 95 men who presented a petition to the General Assembly opposing independence argued that their business was all transacted in Hartford, the population was not large enough, and the new representatives would increase membership in the already too-large House of Representatives. They thought that their indebtedness for roads and bridges would increase taxes in an independent town.

The General Assembly accepted the petition for independence and those who were opposed were brought into the new government. By looking at the town meeting minutes from 1854 to 1863, one gets an idea that this was a highly participatory democracy.

By 1860, West Hartford had a population of about 1,200 people. Of that, about 600 were men and of the 600, at most half of them were over 21 and eligible to vote. With about 300 eligible voters, at the first Town Meeting in June 1854, the citizens voted 31 men into office. Jobs included selectmen, grand jurors, constables, treasurer, registrar, fence viewers, pound keepers, haywards, and sealer of weights and measures, indicating the agricultural basis of the town. Later on jobs including school visitors and a board of relief were added.

If 31 men out of 300 voters were elected, more than 10% of the voting male population served in elected office, making up almost 3% of the total population. The equivalent today would be 1,800 officeholders in the town for our population of 60,000. Today there are 18 elected town officials (nine on the Town Council, seven on the Board of Education, a Probate Judge, and a Town Clerk).

These first officeholders, elected in May 1854, indicate that the townspeople wanted a bipartisan government. Of the 31 men elected to office, 18 signed the petition for independence, eight signed a petition against, and five did not sign either petition.

The townspeople quickly mended fences and worked shoulder to shoulder. They met at Town Meetings twice a year, usually in March and October. Between 1854 and 1863, they voted on the candidates, the tax rate (anywhere from 5-7% of assessed value of their property), building roads, establishing a second cemetery and attempting to build a Town Hall.

And they argued about all of it. In November 1857, a resolution passed that said no person could speak on one subject more than twice or for more than 10 minutes.

In 1858 as the town tried to separate itself from the power of the Congregational Church, citizens debated who should take care of Goodman Green, property of the Church. At first the town voted to take over care of the green from the church and “a committee would be established to grade, fence in, improve the park near the meeting house.” The motion went on to ask that $20 be set aside to pay for these improvements. Then it was amended to have the town take possession of the land. Then it was amended to table the whole idea. Then it was voted to drop the issue indefinitely. The town also attempted to build a separate meeting room so that town meetings did not have to happen in the church.

The discussions about this issue began in 1858 and finally in 1863 the town purchased the Congregational Church’s vestry building to serve as a Town Hall. At every meeting during this period of time, citizens debated the roads: where to build, how much to pay workers, how much to pay the highway surveyors ($1.25 per day), where the roads would go, and making the highway district the same as the school district.

Collecting taxes must have been troublesome because there was constant mention of how to collect those that were in arrears. The highway surveyors collected the highway taxes separately and citizens were taxed separately for one of the eight school districts in the town.

Newcomers to the town were the beneficiaries of this roadbuilding. The 1850 census showed a considerable number of laborers born in Ireland living in town. Laborers were paid about one dollar per day to work on the roads. The labor of these Irish men, many of whom had families here, was much in demand as the town grew. However, there is no evidence that any of these men served in any elected town office during this period of time.

Decisions about education also led to protracted discussions. Education was an important foundation of the town and town government. Each of the eight school districts had their one-room schoolhouse. Each hired its own teacher and collected their own school tax. In 1859, the district known as “the commons” (presently the area around Charter Oak School) wanted to join together with the district to its east, in Hartford. The resolution to accomplish this was voted and re-voted over a two-year period until the cross-district school became a reality.

Citizens fought over who was in each district and whether one district got more funds than another. In 1860, the town voted to collect taxes as a town and divide them among the districts to equalize the spending. It was not until the 1890s that consolidated schools were built.

The town also closely monitored its care of the poor. When it separated from Hartford, one of the stipulations of being an independent town was taking responsibility for the poor. West Hartford chose to do this by providing for the poor citizens in their place of residence. The town provided firewood, food, medical care and clothing for those in need. But the town was also circumspect about its money. It paid medical bills of $1.25 to Dr. Wells and Dr. Brace, but then made a resolution that the town would not make another payment of that amount of money unless it was approved by the selectmen ahead of time. A resolution passed in October 1856 said that a particular woman, Sarah Cadwell, could receive no more aid until it was proven she was a pauper of the town.

It was rare for events outside town to impinge on the town meeting, but the Civil War certainly did. At the March 1861 meeting, the town voted to pay a bounty of $30 for every man who enlisted. It voted to pay five dollars in money or goods and services to any resident family whose son or husband went to war.

West Hartford’s fledgling democracy in the 1850s and 1860s deliberated and exemplified the idea of civic engagement for those landholding men eligible to participate. That these meetings were contentious and bipartisan is a tribute to its citizens and the system itself.
