## Who was Burdett Loomis? {-}

*Originally appeared in West Hartford Life, March 2008*

Farmington Avenue is once again getting a makeover, and it seems like a good time to look back at the work of Burdett Loomis who led improvements on that Avenue in the 1870s, over 130 years ago. Burdett Loomis, (1838-1919) was a businessman and entrepreneur whose vision helped transform West Hartford from a farm town to suburb.

Loomis was an inventor, patent holder, and manufacturer of gas plant machinery and a citizen who “planned ahead for Hartford and West Hartford” according to a 1912 *Hartford Courant* news article. The 1912 article was prompted during improvements-in-progress on Farmington Avenue that year. Prospect and Farmington were each a standard three rods (48 feet) across and Loomis wanted to widen them to 75 feet.

By 1873, Loomis owned the land bounded by Farmington Avenue, Prospect, Fern and Vanderbilt Hill, now West Hill. Loomis was married in 1859 at age 21 and moved to Hartford in 1871. He first lived on Wethersfield Avenue in Hartford and in 1873, built what became known as the Russell Mansion on Prospect Avenue. This house had ornamental woodwork and a stately tower. It stood on the west side of Prospect near Cone Street, close to where the Bristow Middle School is today. It has since been torn down. Loomis seems to have lost his first fortune as a result of the panic of 1873, so was forced to sell the mansion, and in 1878, he moved north to 837 Prospect Avenue just south of Elizabeth Park, on the West Hartford side to a more modest home built in 1845.

When Loomis first moved to Prospect, he believed that Farmington Avenue would be “one of the finest thoroughfares out of Hartford” into West Hartford, Farmington and further west. Loomis also believed that Prospect Avenue should be wider and when Loomis asked Hartford to share in widening the street from 48 to 75 feet, the city refused to take land from the Hartford side even though no houses had been built there. Loomis reduced the grade of the avenue for about 1/3 of a mile to one inch in every 100 feet. He cut down trees and then planted a row of trees between Farmington and Fern. He spent $1,000 of his own money to widen Farmington Avenue. As the town widened the street, the “Great Panic” –- probably of 1873 –- took over, and he lost most of his fortune.

Loomis’ businesses helped West Hartford grow through ingenuity and public utility and transportation systems. Loomis was a part owner of the trolley company. He was instrumental in getting the horse car line extended to West Hartford Center in 1889. Loomis also had a hand in the building of the water pipe system from the reservoir. It first opened in 1867 before he was here, but he worked on getting the pipes laid under the road and accessible to West Hartford citizens.

In 1881, at age 43, he organized the Steam Heating Company of Hartford. He soon found problems with the steam heat in that so much was lost in its transmission. He decided to substitute cheap natural gas to heat and invented cheaper methods to make gas, which was soon used for gas engines. From 1886 to 1889, he built the first gas plant that produced gas from coal, wood or lignite and delivered it to its domestic users through pipes laid underground over long distances. His company laid gas lines on the frontier. By 1899, Loomis headed the Loomis Gas Machinery Company in Hartford. His company laid iron pipes for gas and water, both important pieces in building the infrastructure of towns and cities.

In 1882, he organized the first Electric Lighting Company in Connecticut. By 1912 he and his son, Burdett Loomis, Jr., served as directors of the Northern Connecticut Light and Power Company. His son was also treasurer of the company.

Throughout these years as a developer, Loomis made and lost several fortunes, according to family legend. Probably Loomis’ biggest gamble, and his best fun came when he helped establish Charter Oak Race Track in 1873. Loomis promoted and developed the race track at Flatbush and Oakwood Avenues. In 1876, he planted the elms in the front of the park on New Park Avenue and had the avenue widened. The park became one of the finest trotting courses in the country. Loomis saw his first trotting race on a half mile track on Hartford’s Albany Avenue in 1861. When he relocated to the city, he believed Hartford should have one of the best courses in the country. He chose the site, organized the association, superintended the building of the track, planted the trees and gave the grounds a park-like appearance. Loomis had backing from Charles M. Pond and Governor Morgan Bulkeley. The track drew all the leading harness horses and their drivers. He was Secretary of the Charter Oak Association in 1880. Bets ranged from $100 to $20,000.

In 1882, Loomis decided he wanted a special event in Hartford, and he drafted conditions for a $10,000 purse over Labor Day Weekend, one of the largest in the nation. When Loomis proposed the large purse, people thought he would lose money, but Governor Bulkeley, the treasurer of the association guaranteed the race. It made money that year and every year after. That race continued into the 1920s, even after Loomis’s death in 1919.

Loomis was one of the seven men who “labored zealously to establish and maintain the “Grand Circuit” of harness racing. This circuit gave light harness racing the prestige that it has maintained to date. Charter Oak Park was on the Grand Circuit until 1925.

Burdett Loomis, according to Caroline Church, was one of the men who helped turn West Hartford from a small farming village to a suburb over 100 years ago. In her senior college thesis, which brought Loomis to my attention, she focuses on the role of public improvements, particularly the West Hartford Reservoir system in defining the changing nature of West Hartford from 1870 to 1910.

He was certainly a man of his times –- a businessman, an entrepreneur, and a man who wanted to give back to his community. His maxim throughout his life, still rings true today: “to do something for the world and the community, regardless of whether or not [he] was going to reap the benefits derived therefrom.” Something that distinguishes West Hartford from other towns is that there are so many in West Hartford who continue to abide by this maxim.
