## West Hartford’s First Foray with Regionalism {-}

*Originally appeared in West Hartford Life, December 2006*

An 1869 map of West Hartford shows an aqueduct running from a small reservoir #1 down Farmington Avenue into West Hartford center then on to Hartford. This first reservoir, authorized by the Hartford Water Board in 1866, flooded 32 acres of West Hartford land. But West Hartford residents could not drink the water from the sheet iron pipes coated with cement. It bypassed the town to serve the city of Hartford, which by 1860 had 30,000 inhabitants, to West Hartford’s 1,200.

The aqueduct was the beginning of a regional solution to a regional need. In 1857, the Water Board in Hartford realized the city needed to provide more water to its inhabitants. Its population had more than doubled since 1850, and there was not enough potable water in the Hog or Connecticut Rivers. A report by the Water Commission in 1860 recommended that the supply of water should come from the hills west of the city and make its way by gravity, through pipes, to Hartford. Trout Brook seemed to be the perfect source for this water. Hartford’s 1856 petition to the General Assembly to get water from West Hartford was finally granted. The Water Board acquired the pasture land and woodland on the north side of Farmington Avenue that we now know as the MDC reservoir.

There was some resistance in West Hartford to the reservoir system. Residents of the newly independent town of West Hartford (1854) did not take well to Hartford damming the brook which also brought their 1200 residents not only clean water, but a source of power for its grist and saw mills. An organized protest of West Hartford mill owners and citizens with water rights, however, was not successful. Resident William H. Seymour and 400 West Hartford citizens showed their support for the project by presenting a petition to support the reservoir project.

In 1866, Hartford’s City Engineer began construction of the 53 foot high dam which held back 145 million gallons of water, 260 feet above the Connecticut River. The first water reached Hartford in January 1867. Many West Hartford residents living along Farmington Avenue felt that they should be able to drink the reservoir water as the pipe went right by their houses. In a legal proceeding, West Hartford argued that because the water came from West Hartford territory they should get it for free. West Hartford citizens felt that the possession of the water outweighed the cost of the pipes. The courts decided that they could access the water, but had to pay the same rate as the people in Hartford.

Just eight months after the dam was completed, torrential September rains broke a portion of the dam, and the wall of water flooded across Mountain Road, on to Fern and North Main streets, carrying away three bridges. The water deposited stones and gravel on farm land and destroyed fences. The City of Hartford paid $12,000 in damages to the town for the damaged roads and bridges and over $17,000 to individual farmers and mill owners for damages. It took almost three years to rebuild the dam. They opened reservoir No. 2 in 1868, No. 3 in 1875, No. 4 in 1880, and No. 5 in 1884, and No. 6 in 1896.

As soon as the Farmington Avenue electric trolley was built past the reservoir in 1894, the reservoir became an even bigger destination for walking, picnicking and “pleasure riding.” By 1930, the reservoir area comprised 1,625 acres of land or about three square miles of West Hartford’s 22 square miles.

In 1929, the regional governing body, the Metropolitan District Commission was established with seven member towns including Hartford, Windsor, Wethersfield, Newington, Bloomfield, East Hartford, and Rocky Hill. By the 20th century, as West Hartford developed, the cleanest water was found even farther west in Barkhamsted and in New Hartford. By 1930 as is true of today, our water no longer came from the West Hartford reservoirs, but residents wanted to be sure the three square miles remained as open space for recreation in the town.

In the twentieth century this land has been used as a treatment facility for the water from Barkhamsted. West Hartford’s facility near Reservoir No. 1 and Bloomfield’s facility near Reservoir No. 6 treat an average of 55 million gallons of water daily. The facilities treat all of the drinking water provided to MDC customers. Today portions of Glastonbury, East Granby, South Windsor, Farmington and Portland use MDC water but are not members of the Commission. About 400,000 people get water from the MDC in 2006.

West Hartford did not become a voting member of the MDC until the last quarter of the 20th century. In 1981, Republican Mayor Chuck Matties encouraged the town to join the Metropolitan District Commission. With rising rates in the early 1980s, Matties felt that West Hartford should have a say on the Board. This was not necessarily a popular stance to take because people in town often worried about being involved in a regional solution. But Matties led the charge to join the other seven towns in the District. With the Town Council split 5-4, and his Republican caucus divided on the issue, he and two other Republicans joined two Democratic council members to join the Board. A follow up referendum passed overwhelmingly by the voters.

In November 2006, voters got a chance to vote on an $800 million improvement to the water system. This referendum was prompted by federal and state mandated regulations to address sewer overflows where water gets into pipes carrying sewage. Damages from the 2005 rains that caused sewer overflows in Elmwood have finally been settled.

But now the Commission has to take on this regional maze of pipes which carry both clean water and sewage and the cost is high. The 15 year project has an estimated price tag of $1.6 million, with the first phase estimated at $800,000. While many of us believe water should be free, the cost of maintaining pipes today is just as much of an issue as in the 1860s when West Hartford residents were told that water is no longer free!
