## Elmwood's Industries {-}

*Originally appeared in West Hartford Life, July 2001*

West Hartford has the reputation of being an upscale inner ring suburb. Many of its residents live here and work in Hartford. But, since the 19th century, West Hartford has had an industrial base that differentiates it from suburbs that are solely residential. Those businesses and their workers add to the stability of our town.

The first Industrial Revolution in the United States began in the 1820s with canals, textile mills, and the growth of the market economy. West Hartford’s residents bought ready-made cloth and products that came from around the world.

Until the 1850s, the main industries in the West Division were grist mills, distilleries and blacksmith shops. The individually owned mills were tied to the only source of power –- water -- until the mid-19th century.

West Hartford’s largest early industry was the Goodwin Pottery. The Goodwins began their business in 1798, before the railroad came. The West Division had excellent clay deposits and the company produced earthenware jars and containers sold throughout New England. The jugs the Goodwins produced also served the town’s local distilleries. Fires plagued the pottery works, but after the second one in 1867, the Goodwin sons bought land south of New Britain Avenue where the present Abbott Ball Company stands, just west of the railroad tracks of the New York, New Haven and Hartford Railway Station that had been built in 1839.

By the end of the 19th century, the Goodwin Brothers diversified their line of earthenware to offer terracotta objects with ornate designs for outdoor and indoor decoration. They also made fine china. The market for these goods encompassed the span of the railroads, so became nationwide.

The Goodwins developed a large market for their products and soon their industrial site took up ten acres. By the beginning of the 20th century, they employed over 75 workers. Their workers may have included some of the immigrants who had moved to town. By the 1860s, a sizable number of Irish and Germans lived here.

With the railroad, the Goodwins hired salesmen to replace their traveling peddlers. These men sold the Goodwin’s wares all over the eastern United States.

In 1908, a fire destroyed the wood frame factory. By then, H. Burdette Goodwin, who was in his 60s, decided not to rebuild the factory because of competition from other container makers.

The Providence and Fishkill Railroad (later the New York, New Haven and Hartford), whose tracks ran through the southeast section of town, changed the nature of the small farm town, by the 1850s. Industry grew up around this new transportation route and allowed for increased trade to distant points.

After the Civil War, the second Industrial Revolution based on heavy industry like steel grew in the northeast. Hartford became the machine tool capital of the country, and West Hartford’s industries were a result of this industry. With the factories came immigrants. By the late 1800s, Scandinavians and Italians moved to town.

In the 1870s, Hartford boomed economically; it was dubbed the wealthiest city in America. Industries in Hartford grew and prospered, built to a certain degree on the profits of Colt’s Manufacturing. By the turn of the century, as the insurance companies began to grow, there was little industrial land left for expansion. West Hartford had land available

In 1891, Whitlock Coil Pipe Company moved to South Street along the railroad tracks. In 1913, the New Departure Company moved to West Hartford from Bristol. The company made push-button doorbells and ball bearings for the growing automobile industry in Hartford.

![Whitlock Coil & Pipe Company moved to West Hartford in 1892 and was West Hartford’s first big factory. They built their new factory south of New Britain Avenue and just east of the railroad line. Founded by 35 West Hartford men, Whitlock made products that transferred heat through bent pipe and tubing. They specialized in a feed water heater that connected to steam boilers. President Charles Edward Beach from 1898 into the 1920s also owned Vine Hill Farm, a dairy farm, much of which is now Beachland Park. Source: Noah Webster House & West Hartford Historical Society.](images/04-WhitlockCoil.jpg)

Like many industries of its day, New Departure built something of a company town by buying a large tract of land between Woodlawn Street and Newington Road. The company divided it into 100 lots and sold them to employees at low prices. This allowed workers to live close to their jobs. These industrial workers who owned their own homes had a real stake in the town and added to the stability of the neighborhoods in the southeastern section of town.

During World War I, employment at New Departure grew from 200 to 1,200 in a matter of a year. The contracts for war materiel added workers and profits. In 1910, West Hartford’s population stood at about 4,800, and grew to 8,000 by 1920.

In 1912, Abbott Ball Company moved to the old Goodwin Pottery site from Hartford. Abbott began producing steel balls and became one of the largest producers of deep-hardened and tempered carbon steel ball bearings. Many of these ball bearings were made for the auto industry in Hartford.

In 1954, the founding family still owned Abbott Ball and employed 105 workers. They produced ball bearings for cars, conveyors, and lazy susans. In 2001, Abbott Ball employed a few more workers than 50 years before and was the 14th largest employer in West Hartford.

In 1919, Spencer Turbine moved to West Hartford. Wiremold arrived in 1929 and continues its manufacturing after being bought out by LeGrand in 2000. It continues to be one of the town’s largest taxpayers. In 1939, Pratt & Whitney Machine Tool factory moved to the site of the old Charter Oak Race Track. This was the largest industrial site in West Hartford. By the late 1950s, Chandler Evans, Colt’s, and Pratt & Whitney Machine Tool shared the site. In 1954, the three companies employed 5,000 people.

Since 1970, industrial production in West Hartford has slowed and commercial and retail sales have grown. But the blue-collar workers in Elmwood’s factories played an important role in the town’s growth. While the owners, financiers, and middle class commuters often have a high profile in town, these industrial workers also help define our suburb.
