## When Abraham Lincoln Came to Hartford {-}

*Originally appeared in West Hartford Life, December 2008. Thanks to Eugene Leach, “Glimpses of Lincoln’s Brilliance,” Hog River Journal, Fall 2005.*

March 5, 1860. I can imagine a 16-year-old William H. Hall making his way to Hartford in an open carriage.

He could have joined a “larger infusion of young men than was usually the case in antebellum political assemblies,” as the *New York Times* described the crowd, to hear Abraham Lincoln give a speech. Lincoln had not yet been nominated for president; that would come two months later on May 16 in Chicago, but he was looking for a national audience. I want to believe that Hall would have been there based on his political interests.

His town of West Hartford had been an independent town for less than six year. The population was about 1,300 people, perhaps 200 families. During the 1850s, the new Republican Party appealed to local voters emphasizing higher education, banking, railroads, industry and cities, and free homesteads to farmers.

The Republican Party started as a revolt against the Kansas-Nebraska Act of 1854, which allowed settlers to vote on whether there would be slavery in their territories. The Republican Party pledged to stop the spread of slavery.

In 1858, 136 men voted in the local election, about 85 voting Republican and about 50 voting Democrat. (See Nelson Burr’s *From Colonial Parish to Modern Suburb*, p. 46.) It is likely that the native born were Republicans and the more recent immigrants including the Irish, German, French, and Swedish listed in the 1850 census were more likely to be Democrats.

Hartford, a city of some 29,000 people, was a solidly Democratic town. This might have encouraged the interest in West Hartford’s independence movement in 1854. The first officers in the new town and delegates to the General Assembly were Republicans.

On Lincoln’s swing through the northeast, he claimed to be visiting his son Robert at Phillips Academy. But by February, Lincoln clearly had an interest in the presidency.

He made a series of speeches in New York, New Hampshire and Connecticut to make himself known nationally, as he was seen as a sectional candidate from the northwest. His most famous speeches were the one given at Cooper Union in New York City and the one given in New Haven, the day after his Hartford speech.

Still, the Hartford speech is worth noting. In it Lincoln established himself as a strong opponent of the extension of slavery and slavery itself, even as the Republicans were trying to moderate their stances to show that they were not abolitionists, but instead merely opposed to the extension of slavery.

He spoke inside a packed Hartford City Hall on that Monday in March. According to the *Hartford Courant*, he was “greeted with applause which was almost deafening.” Lincoln used the image of a snake to represent slavery, as he established the Republican focus on banning the extension of slavery. For instance, Lincoln argued:

> ...out in the street, or in the field, or on the prairie I find a rattlesnake. I take a stake and kill him. Everybody would applaud the act and say I did right. But suppose the snake was in a bed where the children were sleeping.
>
> Would I do right to strike him there? I might hurt the children or I might not kill, but only arouse and exasperate the snake, and he might bite the children.
>
> Thus, by meddling with him here, I would do more hurt than good.
>
> Slavery is like this. We dare not strike at it where it is. The manner in which our Constitution is framed constrains us from making war upon it where it already exists.
>
> The question that we now have to deal with is shall we be acting right to take this snake and carry it to a bed where there are children? The Republican party insists on keeping it out of the bed.

His statement clearly spoke to his audience on the dangers of slavery’s spread. With the focus on the extension of slavery, there are some who argue that it was hard to tell whether Lincoln was against slavery when he took office a year later.

He claimed that when the Union entered the Civil War, it was to keep the Union together, not to abolish slavery. Some say his stance was not clear that he was opposed to the institution of slavery until he issued the Emancipation Proclamation in September 1862. However, at Hartford’s City Hall on March 5, Lincoln declared:

> ...the free states carry on their government on the principle of equality of men. We think slavery is morally wrong and a direct violation of that principle. We all think it wrong. It is clearly proved, I think, by natural theology, apart from revelation.
>
> Every man, black, white, or yellow, has a mouth to be fed, and two hands with which to feed it, and bread should be allowed to go to that mouth without controversy. Slavery is wrong in its effect upon white people and free labor. It is the only thing that threatens the Union.

This clear declaration denouncing slavery on intellectual and economic grounds pushes the Republican feelings that they had to tread lightly on the topic of slavery or a Republican would not be elected president. Lincoln was clear in his declaration against slavery.

The most interesting aspect of his speech was how he tried to find common ground with southerners, highlighting how important economics were in their political decisions. Unlike William Seward, the frontrunner for the nomination, Lincoln did not demonize the southerners. In fact, he found what the two sections had in common:

> One sixth, and a little more, of the population of the United States are slaves, looked upon as property, as nothing but property.
>
> The cash value of these slaves, at a moderate estimate, is $2,000,000,000. This amount of property value has a vast influence on the minds of its owners, very naturally.
>
> The same amount of property would have an equal influence upon us if owned in the North. Human nature is the same; people at the South are the same as those at the North, barring the difference in circumstances.
>
> Public opinion is founded, to a great extent, on a property basis.
>
> What lessens the value of property is opposed, what enhances its value is favored.
>
> Public opinion at the South regards slaves as property and insists upon treating them like other property.

Lincoln’s claim that “people at the South are the same as those at the North” would have been anathema to abolitionists, and even to Seward, who claimed that those in the South were greedy and amoral, while those in the North were idealistic and righteous.

This position was one that echoed through Lincoln’s presidency, including one of his most famous lines found in his second inaugural.

> With malice towards none; with charity for all...to bind up the nation’s wounds, to care for him who shall have borne the battle and for his widow, and his orphan, to do all which may achieve and cherish a just and lasting peace among ourselves and with all nations.

Here Lincoln does not distinguish between Union and Confederate people. If William Hall did indeed hear him, he probably would have then proceeded with the crowds led by the Hartford Corner Band, which led Lincoln to the home of his host, Mayor Allyn. He also might have been interested in Lincoln’s meeting with Gideon Welles of Glastonbury at a local Hartford bookstore after his speech.

The next year, Welles was appointed Lincoln’s Secretary of the Navy.
