## Who was William A. Burr? {-}

*Originally appeared in West Hartford Life, June 2009*

W.A. Burr's name is prominent in the 1896 and 1909 insurance atlas maps of West Hartford's town center. He owned the land east of South Main Street to Trout Brook along Farmington Avenue. The land surrounding the First Church was bounded by present-day South Main, Burr Street and Raymond Road, and goes east as far as Trout Brook.

Surprisingly, Burr is not mentioned in any of the histories written about this town. Yet he clearly had a role in its development from rural town to modem suburb. He was a landowner and an entrepreneur.

Burr was born in Hartford where his father, Allen Burr and his grandfather, Thomas Burr, lived before him. Thomas ran the only general store in Hartford on North Main Street, then called Burr Street, near the head of Trumbull Street. William moved to West Hartford with his family when he was five, probably before this town was separate from Hartford.

William A. Burr was at first a farmer. In October 1873, a news article proclaimed that Burr could “boast one of the best orchards in the state. Mr. Burr’s orchard has produced 150 bushels of apples and his pear trees have been unusually prolific of choice varieties.” In the 1870s he took his produce and his animals to the Connecticut State Fair near the race track on New Park Avenue.

By 1875, Burr had established a hardware store and carriage shop. An 1875 news short claimed that "Mr. W.A. Burr of West Hartford has the agency for the sale of the Tompkins County Self-Tilting Wheel Rake said to be the best wheel rake, seeder and plaster sower combined that there is in the world.”

This "Carriage Repository and Hardware Store" stood at the present site of the Noah Webster Library. There were two buildings in his operation in 1896 and 1909. Burr's success with the sale of new farm machinery was a sign of the increasing industrialization of farming and of his role as entrepreneur.

In Burr’s role as businessman and real estate owner, he amassed wealth. He owned a summer vacation home in Branford at Short Beach and a winter home in Ormond, Fla., just north of Daytona Beach. A *Hartford Courant* article in October 1910 described William A. Burr buying land for a winter residence in Ormond, Fla. The paper claimed it was a time of “remarkable growth of resorts in Florida.”

In 1913, the pastor of the Congregational Church, the Rev. Thomas M. Hodgdon, expressed an interest in building a new church and a new parsonage for the growing church. He cited the congestion in the center and the increasing value of the present site for business purposes. Burr delivered.

In 1914, according to the *Hartford Courant*, William A. Burr, most likely a member of the church, donated a strip of land to the First Church of Christ in the center of town. The land was 19 feet on Farmington Avenue by 15 feet deep and ran on the east side of the church. This strip of land straightened the line of the church's property and allowed the church to provide easy access to the sheds in the back of the church where people stabled their horses. It also allowed them to level the rear lawn and beautify the property.

![On this 1909 insurance map, note William A. Burr’s land on the corner of Farmington Avenue and Main Street, and on Main and what became Burr Street. Burr owned the Carriage Repository & Hardware Store just south of the Congregational Church and Parish. Sandwiched between was the Masonic Hall. Another piece of his property came to the town to build William Hall High School in 1924. Burr died in 1923. Source: Atlas of the City of Hartford, and the Town of West Hartford, Connecticut: L.J. Richards & Company, Springfield, Massachusetts, 1909, Plate 23.](images/04-1909-map.png)

The article claimed that Burr was thinking about running a street along the eastern boundary of the church property from Farmington Avenue to Seyms Street (now Memorial Drive), giving the church a corner on which they could possibly build a chapel.

In that same year, the Barker-Tanner Hardware Company bought Burr's retail business. This was the same year the A.B. Judd Company was incorporated as a druggist and it purchased the building it occupied on the comer of Farmington Avenue and South Main Street.

In 1923, right after Burr died, his estate was valued at $112,681 ($1.2 million in 2009 dollars). The real estate on Farmington Avenue was more than half of the total of the estate. He had half a block of frontage on Farmington Avenue just when the Center started to become a retail center. He also owned land on Vera Street to the southeast of the center and two parcels of land on South Main Street, one worth $6,500 and one worth $7,300. He owned four parcels of land along Farmington Avenue.

In May 1924, the First Congregational Church bought a tract of land from Burr's estate south of its property for $59,000. The new tract was between South Main, Seyms Street and a proposed street running from Raymond Road to Seyms (the current Isham Road). This land helped the First Church survive during the Great Depression in the 1930s, as it was sold to the town to build the Town Hall and library. These building projects, along with other development in the Center, helped define the burgeoning suburb.

South Main Street from Farmington Avenue to Burr Street was the scene of much building activity by 1924. The population had grown to 9,000 and residents wanted to be able to take care of their needs without going in to Hartford.

The Masonic Temple was under construction on the west side of South Main Street. Hall High School was in mid-construction. The town was prepared to move two houses from the Hall High site to make way for the school. The West Hartford Trust Company site was being readied for the first bank in town.

Burr's land sale, after his death, provided an important opening for economic growth as well as the placement of public buildings in the town center. Burr Street stands as a reminder of a man who successfully navigated the change from farm town to suburb through his real estate and business acumen.
