## The Town’s Role in the Civil War {-}

*Originally appeared in West Hartford Life, August 2005*

When the Union went to war with the Confederacy in April 1861, West Hartford had been an independent town for only seven years. Its population stood at almost 1,300. Thirteen men, 1% of the population from West Hartford died in the Civil War. At war’s end, West Hartford had sent 117 men to serve, almost 10% of the population and about half of the male population of military age. The sheer number of men and the newness of the government may have led to fewer records being kept. But, the tally of West Hartford men who served and died in the Civil War (1861-5) probably tells less about West Hartford than any other war.

Incentives in the form of bounties led men to move from town to town. West Hartford’s quota of 44 men was oversubscribed by 83 recruits. Many of the 117 were not West Hartford residents. It is more difficult to verify that those who died actually lived in West Hartford.

West Hartford men who served were lured by federal, state and local bonuses. Connecticut offered each man $140 for enlisting while they received $27 from the federal government. In May 1861 just one month after the opening salvo at Fort Sumter, South Carolina, West Hartford residents voted at town meeting to borrow $3,000 for war bounties and for the families of soldiers. Male citizens voted for every inhabitant who enlisted in military service for three years to get $30 or its equivalent in equipment and clothing. Families of those who enlisted were paid a monthly amount of up to $5 and $2 for every child under age 12. At first, the town paid this money to all those who enlisted from West Hartford, but within six months, rescinded the amount to those who it was determined did not live in West Hartford.

There was much incentive for men to become “bounty jumpers.” They enlisted in one town, got the money, and then deserted. Then they showed up in a second town. Wealthy men were able to “buy” a replacement for $300. Of 20 deserters from West Hartford, it is thought that many were never residents here.

The Union’s many advantages made Union recruits believe the war would end quickly. Those who mustered first, signed up for 90 days. There were heavy casualties. The first six West Hartford men who died in 1862 averaged just four months in the army.

The Civil War was the last war in which soldiers for the same regiment were mustered from the same town. For instance, at the 1862 Battle of Antietam, the 16th Connecticut Regiment had nine West Hartford men. At this crucial battle in Maryland, the Union Army stopped General Robert E. Lee's first invasion of the North in September 1862. On the bloodiest battle day, September 17,1862, more than 23,000 men were killed, wounded, and missing. West Hartford’s Edward Deming died on that day. At Antietam, three West Hartford men were killed, four were disabled and two survived to fight another day. Charles Sternberg and Arthur Talcott died of wounds within three months of the battle. West Hartford was thought to have suffered the most of any town its size from this particular battle.

In the 1860s, the majority of West Hartford’s population consisted of white Congregationalist farm families. But the town’s population was changing. The 1850 census shows a growing presence of Irish and German immigrants and African Americans continued to live and work here. These demographic patterns were reflected in the Civil War dead and the enlistees.

Charles Sternberg, who died at Antietam, was one of four German immigrant brothers who fought in the war. Their father Charles emigrated from Germany in 1854 as a result of the 1848 Revolution. Charles established a farm at the corner of Sedgwick and Mountain Road. One brother William was imprisoned at Andersonville and survived.

The 24th Connecticut Regiment included three Irish companies one of which came from Hartford and West Hartford. West Hartford’s John McCarty, who had been a musician in the Regiment, was sent to the front lines and killed at the siege at Port Hudson, Louisiana in the second assault on June 14, 1863. Port Hudson was a pivotal battle for control of the Mississippi. The siege began on May 23, 1863 and lasted for 48 days. About 30,000 Union troops fought 6,800 Confederates. On the morning of May 27, and again on June 14, the Union army launched assaults against the earthworks protecting Port Hudson. McCarty sacrificed his life in the second assault. Finally, the Confederacy surrendered on July 9th, seven weeks later.

Once the men got to battle, there were many deserters. In light of the conditions in the Union Army, it is not surprising that desertion was so rampant. It is thought that over 200,000 deserted over the course of the war. The daily hardships of war, lack of weapons, and forced marches which sometimes made straggling a necessity for less vigorous men, caused some to desert. West Hartford’s John Hall mustered and served but died by a military execution for deserting. The military used men like Hall as examples to try to reduce the number of deserters.

West Hartford’s Thomas Wells wrote a letter to his family in 1862 claiming to march 20 miles per day, sometimes in the pouring rain, with only a cup of coffee as nourishment.^[George Wells to Mrs. Elizabeth Sisson, 2 June 1862, Butler Bassette Collection, Noah Webster House archives.] J.G. Butler wrote that the army made it hard for soldiers to keep a high morale. Butler marched 300 miles in seven days.^[J.G. Butler to Mrs. Elizabeth Sisson, 13 January 1863, Butler Bassette Collection.]

The horrors of the Civil War were made real to West Hartford residents through the first war photographs, letters, and returning men. In R. H. Morse’s letter to West Hartford’s Mrs. Elizabeth Sisson, 23 July 1863, he wrote “Only three short weeks before, our regt. left Hartford with over one thousand brave men ready to strike a blow for liberty and restore our glorious union once more... Only those who have seen it or have been engaged can tell one half the scenes of horror or carnage of the battlefield. Imagination fails to conceive the one half of it.”^[R.H. Morse to Mrs. Elizabeth Sisson, 23 July 1863, Butler Bassette Collection. Morse mustered on July 25 1862 as part of the 16th Connecticut Regiment.]

West Hartford men’s Civil War experiences show their willingness to join for a common cause and of a town to support them. Not everyone enlisted for the same reasons and their fighting situations varied greatly. Some could well articulate the purposes of war and some fought for bounties. The local history becomes more meaningful and complex when intertwined with state and federal policies and world immigration patterns.
