## West Hartford in 1896 {-}

*Originally appeared in West Hartford Life, January 2009. Thanks to Dick Kreitner for the atlas.*

This fall a friend passed along a real treasure to me in my role as the Town Historian: a 112-year-old atlas of Hartford and West Hartford. The atlas provides unique information. It opens up a world to me that newspaper articles and even photographs cannot engender. The *Atlas of the City of Hartford Connecticut, including also the Town of West Hartford* tells me much about the economic world of West Hartford over a century ago. It defines the town of West Hartford as a town that supported agriculture and industry, as it became a suburb of Hartford, on which it depended for its economic well-being.

In 1896, West Hartford had about 2,500 residents and was just starting to move from farm town to suburb. L.J. Richards & Co. of Springfield, Massachusetts published the atlas based on records from Hartford and West Hartford municipal engineers and some of the publisher’s own engineers. There are 30 Plates in the book, 26 from Hartford, and four from West Hartford. You can browse through this atlas in the Local History Room in West Hartford's Noah Webster Public Library, or their [historical maps online page](http://www.westhartfordlibrary.org/services/local_history/historical_maps.asp).

Plate 27 is a map of the entire town, showing every dwelling in town. The mapmakers delineated whether buildings were brick, wood, brick and wood, stone, iron, whether it was a barn stable or shed, or a greenhouse. The atlas includes the owners’ names for each dwelling and piece of land.

The map marks sewers under Park Street from Prospect past South Main, and on Fern, Quaker Lane, and the south end of Steele Road, a sure sign of the infrastructure built for residential neighborhoods. The street railway that traversed Farmington Avenue spanned the town from east to west. The Hartford and West Hartford Horse Railroad Company, incorporated in 1863 sent the line out to West Hartford in 1889.

![Wallace Thomson founded the W.W. Thomson Company at 146 South Main Street in 1899. Originally they grew vegetables and produce that they sold to farmer’s markets in the region. His son, W. Pomeroy Thomson, produced over 30 new varieties of carnations between 1958 and 1988 in West Hartford, Florida, and Bogota, Colombia. Source: Noah Webster House & West Hartford Historical Society.](images/05-thomson-web.jpg)

By the 1890s, West Hartford’s farmers specialized in dairy. The two creameries in town, Highland Creamery on the southwest corner of Albany Avenue and Mountain Road and the Elmwood Creamery owned by C.M. Beach, now part of Beachland Park, were important parts of this agricultural base. According to William H. Hall in his *West Hartford* (1930), the creamery was supplied by the farms that surrounded each dairy.

On Plate 27, the publishers named two farms in town: Boswell Farm on the west side of South Main where Rockledge is today, and Maplewood owned by F.A. Thomson across the street. These farms were just to the north of the Vine Hill Farm and Grist Mill which included land on three corners of New Britain Avenue and South Main Street.

Gristmills in town at the time are a reflection of the continued agricultural base. There were the Trout Brook Grist Mill on North Main where Trout Brook crosses near American School for the Deaf, and the grist mill next to the Elmwood Creamery in today’s Beachland Park. Daniels Mill Company owned a gristmill on the corner of Simsbury Road and Bloomfield Avenue.  Daniels Mill Co. was established in 1835, according to the directory at the back of the atlas.  Here, the publishers listed “well-known citizens, representing the business, professional and educational interest of the city, through whose hearty support alone the completion of this volume has been made possible.” Daniels Mill sold wholesale and retail flour, feed, grain, hay and straw. “Grain by the carload” was their specialty.  Their headquarters at 40 Elm Street in Hartford represented the close connection between the economies of Hartford and West Hartford.

Farmers specialized in greenhouse grown plants as well. There were greenhouses on Whiting Lane owned by Alfred Whiting. Next to the Hartford Brick Company on New Park Avenue stood the greenhouses of Charles K. Swenson, one of the many Swedish immigrants who worked with plants. W.E. Wallace sold nursery goods on the corner of Farmington Avenue and Quaker Lane from his greenhouse. According to Hall’s book, Wales Andrews had four greenhouses on the corner of New Britain Avenue and Grove Street where he specialized in growing cucumbers.

Many successful businessmen who worked in Hartford, lived in West Hartford and supported the making of the Atlas are listed in the directory in the back of the book. Charles M. Beach of the Beach Dye Works, J.J. Enders of State Savings Bank, J.L. English, secretary of Aetna Life who lived on Fern Street, and Bernard Caya, contractor lived on Prospect Avenue. F.C. Rockwell, who was the head of the Bonsilate Box Co. lived on Prospect Avenue.  He subdivided the land along the Boulevard as he looked forward to one of the first suburban developments in town.

E.H. Arnold & Sons used the pond from the dammed up Trout Brook at Farmington Avenue to harvest ice. His Trout Brook Ice and Feed Company needed five buildings to take care of its business. Headquarters for Arnold’s building were on Asylum Avenue downtown.  His company was both wholesale and retail selling ice and grain.

By 1896, West Hartford also had its share of industry. The clay soil led to brick making as a lucrative business. There were three brick companies in town. On New Park Avenue, with railroad spurs right into their yards were the Hartford Brick Company and across the tracks, the Charter Oak Brick Company. On the corner of Prospect and Caya Avenue was the Dennis & Co. Brick Manufacturers.

![Brickmakers used the clay soil in the southeast section of town to build several lucrative businesses. The Phoenix Brick Company, Park Brick Company, and the brickyards of Michael Kane lined the railroad line in the industrial section of town. Source: Noah Webster House & West Hartford Historical Society.](images/05-brickyard-web.jpg)

Along the railroad tracks in the southeast section of town industry grew. The Whitlock Coil and Pipe Company was across the tracks from the Goodwin Brothers Pottery. Whitlock Coil and Pipe opened its doors in 1892 and manufactured coiled pipe for use with steam boilers. The Goodwin Brothers began the pottery business to take advantage of the clay, just as the brickmakers did. They sold their jugs and jars across the continent.

For entertainment, on the corner of Prospect and Farmington where St. John’s Episcopal Church stands today, was the Prospect Casino. On Prospect and New Park, race enthusiasts could go to the Charter Oak Driving Park. There was a bandstand, a grandstand, and a half-mile track. Both of these establishments depended on Hartford residents for their success.

The center was beginning to be a retail center. Where the present day library sits was Burr's Carriage Repository and Hardware Store. Buckland’s Store and Post Office stood at the corner of Main and Farmington. But, these are the only two retail establishments in the center.  The real growth came in the 1930s.

Economically, West Hartford continued to depend on Hartford. Farmers sold their produce to Hartford residents, the railroad that passed through the southeast corner of town connected goods to the city center, and Hartford businessmen brought value as they began to settle in the residential suburb. L.J. Richards’ *Atlas* confirms that West Hartford’s prosperity depended on Hartford’s economy. In 1896, residents and businesses knew that their prosperity depended on the city. Today, many West Hartford residents continue to understand how West Hartford’s economy is tied to that of Hartford and the region that surrounds it.
