## Elmwood Suburbs {-}

*Originally appeared in West Hartford Life, June 2011. Thank you to Jeffrey Murray, Conard High School junior, whose research paper, “Elmwood: From Rural Community to Working Class Suburb,” won the 2011 Freeman and Mary Meyer Prize for Excellence in Local History.*

In the early 20th century, the Elmwood section of West Hartford developed its suburban character on a parallel to West Hartford center’s development. The same ingredients nourished growth in both places: transportation in the form of the trolley, farmers ready to sell their land to developers, real estate developers, and people looking to move out of the city. It all added up to a growth in population and an eclectic mix of residential, industrial, commercial, religious and educational institutions. This mix of buildings and people gives Elmwood the separate identity it retains today.

In 1900, when the trolley company laid a track down New Britain Avenue ending at East Street (now Quaker Lane), suburban development picked up. Before the trolley, residents could jump on the steam train running through the southeast corner of town for $24 per year. But in 1899, the train raised the rates to $60 per year and passengers lobbied to bring the trolley to Elmwood. Within a year the line opened.

As people moved out of Hartford and New Britain and into West Hartford, government services expanded. In 1900 the town added onto the Elmwood School, built as a two-room schoolhouse in 1888.

In 1901, the West End Land Company bought land in Elmwood on the present site of Yale and Florence Streets. Their handbills to sell the properties advertised free trolley rides. Four years later, F.C. Rockwell, who developed the Boulevard in the Center between Main and Trout Brook, sold land on New Britain Avenue to developer Terry Chapin. This land was subdivided by 1909 into more than 60 lots.

Wallace B. Goodwin, grandson of Harvey Goodwin, the founder of Goodwin Pottery, a local industry since the early 1800s, began to develop Elmwood with small single-family homes. He wanted to sell lots to people of moderate means. Goodwin also wanted to retain the agricultural nature of the residential area. In an advertisement for “Bungalow Farms,” on Newington Road he wrote, “If you could own your own home with a real little farm, where you could raise your own vegetables and chickens and be in Hartford or New Britain within fifteen or twenty minutes’ ride, now wouldn’t that be ideal?” He sold “acre lots and bungalows” in a “beautiful restricted section.” He added that the lots were “close to Elmwood Trolley and Railroad Stations.” Goodwin appeared in the ad, holding a plot of land with a bungalow, set on a country road.

![Wallace B. Goodwin, in the real estate and insurance business, was a direct descendant of the founder of Goodwin Pottery. In 1936 he bought land west of Ridgewood Road to create a development around Wood Pond and Woodridge Lake, once the ice business ended. Source: Display Ad 65, The Hartford Courant, May 24, 1914.](images/05-bungalow-farms.jpg)

In 1913, Goodwin planned to develop an Elmwood that would be distinct from developments in the center of town. Mentioning New Britain in his ad and suggesting that residents could grow their own vegetables were attempts to market a suburban neighborhood with rural charm that differed from the developments in the center of town.

On April 25, 1915, the *Hartford Courant* reported that Goodwin bought land from F.W. Talcott on the east side of East Street for developing this “splendid tract” in a “restricted way.” Goodwin called the area “Burgoyne Gardens.” Houses built on this tract had a view of Talcott Mountain and Charter Oak Park, across Trout Brook from the development. Sewers and piped in water both served this neighborhood. Goodwin had room for about 40 homes on the plot and he planned to build both single and two-family homes.

Goodwin’s development was within walking distance of a post office, library, and school with easy access to the trolley and train, which could whisk commuters into Hartford. The post office built in 1873, was a sign that Elmwood had a separate identity from West Hartford, which became independent from Hartford in 1854, just 19 years earlier. Also in 1873 the Elmwood Community Church set up a Sunday school, which met at the Elmwood School. In 1876, this group of Congregationalists built the Elmwood Chapel at New Britain Avenue and Grove Street. In 1926 this church moved to its present location on Newington Road. By the mid 1920s, the population of Elmwood stood at about 2,000.

Meanwhile, Wallace B. Goodwin continued to expand his reach from real estate developer to purveyor of insurance on furniture and buildings, mortgages, and selling ready-built sheds to be used as garages.

In 1917, the *Catholic Transcript* reported that the Elmwood church, St. Brigid, was the first Catholic Church to be erected in West Hartford. According to the *Transcript*, “The Town is fast growing and the new church, which is at the southern end, promises one day to be a considerable Catholic center.” The Church started as a mission of St. Lawrence O’Toole Church, in Hartford just about a mile east of Cambridge Street and New Britain Avenue.

Elmwood continued to develop its own identity as a working class suburb with manufacturing and farms, and an active political life. The area residents saw themselves as outsiders from those who lived in the town center. In an attempt to get fire protection in Elmwood in 1919, the “Men’s Union” “turned out in full battalion strength” to a special fire district meeting at the Town Hall in the center of town. They hired cars to take them to the town hall and surprised the “unsuspecting townsmen of the north end.” Those running the meeting were met by “a storm of protest.”

The Elmwood men got their way when the Fire District voted to give fire hydrants to Elmwood by increasing the mill rate by one mill. The Men’s Union’s next step was to establish their own fire station in town which finally came to fruition in 1919. It was clear that the increased fire protection would add to the value of houses in Elmwood.

In 1922, Talcott Junior High opened on land contributed by the Talcott Estate. Talcott and Plant Junior Highs were among the first junior high schools built in Connecticut. Six years later in 1928, as the population in Elmwood grew, the town tore down the Elmwood School and replaced it with the Elmwood Grammar School fashioned after the Beach Park School on Steele Road and the Morley School on Fern Street.

The *Hartford Courant* claimed that this subdivision was “an excellent location for the suburban dweller.” By 1925, those who moved to Elmwood made a choice to live in a community proud of their factories and railroad tracks as well as the churches, schools, library and post office which helped to develop an identity that makes a uniquely Elmwood section of town.
