## Biking in West Hartford {-}

*Originally appeared in West Hartford Life, July 2012*

In 2012, West Hartford’s Bicycle Advisory Committee meets the second Monday of every month to make West Hartford a more bike friendly town. Bike enthusiasts yearn for bike lanes and safe places to ride on the roads. Twentieth century plans for roads were all about cars; bicyclists are trying to change that.

West Hartford’s history as a bike town goes way back to the Charter Oak Race Track well before the “bike craze” of the 1890s. Back then, the bike craze led to athletic competitions, a new way to get to work, a new leisure time activity, and safer roads.

In September 1878, two Hartford physicians who purchased Columbia bikes proposed that the Charter Oak Race track add bicycle racing. In May 1879, the *Hartford Courant* reported that people were talking about a bicycle tournament at Charter Oak Park and that Hartford had some good bicycle riders ready to compete.

On June 13, 1879 George W. Pomroy of the Oakwood Hotel gave a purse of $100 [about $2,200 today] for a bicycle race at the Charter Oak Race Track. It was the best two out of three in mile heats. On the Fourth of July 1879, Charter Oak Park sponsored bicycle contests along with horse racing, and a sack race.

Mr. G.W. Pomroy at the Oakwood Hotel was particularly active in arranging the bicycle race. The crowd loved the race and pushed Pomroy to set up another race. According to the *Courant*, “The interest in bicycles is greatly on the increase in Hartford, since their manufacture has begun here at the Weed works, and many young men have become engaged in the use of the machine. A considerable number are very expert in its use, and with more entering a very entertaining race could be arranged.”

Albert A. Pope, who founded Boston’s Pope Manufacturing Company, became an enthusiast about bikes at the 1876 Philadelphia Exposition. He started to import bikes from England in 1878 and took out US patents on the European models. Col. Pope wanted bikes to be made in America and so he approached Hartford’s Weed Sewing Machine Company who used interchangeable parts and by the end of September 1878, they manufactured 50 bicycles with the large front wheel. To produce the Duplex Excelsior copies, Weed produced 77 unique parts and the only part that came from a supplier was the rubber tire.

Pope dubbed the new bicycle “Columbia.” His use of the hollow tube and ball bearings distinguished his bikes from others. According to an 1878 *Hartford Courant* article, “Mr. Pope... who resides ten miles from the city [Boston], rides to and from his place daily on one of these vehicles, unless the weather is stormy.” Further, the article stated that the bicycle craze in England had gone on for years and that an amateur rider had ridden a 3 minute 10 second mile.

By 1881, The Hartford Wheel Club organized monthly races at Charter Oak Park. On Saturday, June 25, 1881, at 3:00 pm, the amateur competitors biked from Capitol Avenue and Washington Street to the park. The 50 bicyclists, including five racers from New Britain were divided into three classes. It was the biggest gathering of bicyclists ever. The winning racer rode the mile in 3:25 from a standing start. The three judges included George B. Day, son of George Day the leader of the Weed Sewing Machine Company that was building the bicycles.

In the summer of 1882, Mr. Hyde of the Charter Oak Park Hotel and Mr. William B. Smith leased Charter Oak Park for the Fourth of July. They offered prizes worth $2,000 for trotting races, bicycle races and foot races. They offered a “shore dinner.”

![This drawing, originally published in Harper’s Weekly (1885) by illustrator Albert Berghaus, shows the final heat of the one-mile open amateur bicycle race at Charter Oak Park in 1885. Note the crowds of spectators in the covered grandstands and the tall viewing platform to the right. The Connecticut Bicycle Club sponsored this series of races over a two-day tournament. At least 7,000 spectators attended. Source: The Connecticut Historical Society.](images/05-bike-racing.jpg)

In September 1884, the Connecticut Bicycle Club mounted a race with prizes of $1,000. Hundreds of people lined the streets for a parade of over 100 bikers. They scheduled 12 races with riders from Hartford, Springfield and Boston. The top racer had a time of 3 minutes 3 seconds. Five thousand people came to the races in the first large-scale bike race West Hartford had seen. Colonel Pope was one of the officials of the races. The *Courant* reported:

> Never before in this country has a more successful one day’s tournament been held, and never before in any race in the world has such good time been made as in the mile race... A comparison between such racing and horse racing must necessarily be to the advantage of the former sport, for there was no grumbling on the result of the contest and no boisterous language, and the auditors knew that the struggles they viewed between the race were honest and that the best man always won.

By the early 1890s, Pope developed a bicycle trust, which controlled all bicycle patents in the United States. For all bikes manufactured in the US he got $10 per bike. Pope changed the size of the front wheel to be equal in size to the back and had the rider sit between the wheels. This made the bicycles even easier to ride and democratized the athletic pursuit. The bicycle craze blossomed with this new invention in the 1890s. According to Ellsworth Grant in his article “The Miracle on Capital Avenue,” in the *Hog River Journal* in 2002, Weed employed 600 men making these “safety” bicycles. In the mid 1890s, Pope lorded over 18 acres of factory space on Capitol Avenue. He employed almost 4,000 people and produced 50,000 bicycles a year.

According to Pope, the main problem for bicyclists was that there were not safe, macadamized roads to ride. In 1880, he was one of the founders of the “League of American Wheelmen” to lobby local governments for improved roads. The late nineteenth century bicyclists long before the invention of the automobile spurred the “Good Roads Movement.” By the 1890s, much of West Hartford’s town budget was in building hard top roads.

Today, bicyclists are back at it, trying to improve the roads for riding. The context has changed dramatically as the gas-powered automobile is the main impetus for improved roads. But bicyclists want car drivers to share the road and allow them to feel safe as physicians once again encourage their patients to bike to keep fit.
