## Charter Oak School {-}

*Originally appeared in West Hartford Life, May 2013*

In March 2013, West Hartford’s Board of Education voted to build the first new elementary school since Norfeldt School was built in 1964. A new Charter Oak School, with a price tag of $40 million (with the town paying about $8 million), will open in 2016. The present school houses 270 students and the new school will have room for 560 students from the neighborhood and magnet students from all over town. Charter Oak’s scope and size has changed many times in its history. This investment in a state of the art building will help to do what Board of Education Chair Madeleine McKernan dreamed of over 40 years ago: to provide an equal opportunity for all students no matter where they live in West Hartford.

In 1884, the Common School district of West Hartford built the original elementary school in the neighborhood. The one room schoolhouse on the south side of Flatbush Avenue (near the present day Home Depot) at first housed all eight grades, but as the population grew, three more rooms were added, and only K-4 students could fit in Charter Oak. Older students went to Smith School, or the Elmwood School on New Britain Avenue. This little four room Charter Oak area school had a capacity of 100 students. The current Charter Oak School was built in 1930 to accommodate kindergarten to grade 6.

The architect, Russell Barker planned for a 15-room building for 560 students with a price tag of $290,000. Superintendent Lloyd Bugbee planned this school as one of the first “modern” schools in the “American perpendicular” style with silver and black colors on the front of the building. One innovation in the building was the inlaid linoleum floor in the kindergarten room with inlaid children’s stories. Architects planned a library in the middle of the school.

Miss Bernice Patterson took on the role of teaching principal of the 4-room schoolhouse in 1924. In 1930, when the new school opened, she became the first principal. She served as principal for 22 years when Miss Harriet Foley replaced her.

A 2 ½ inch piece of the trunk section of the famous Charter Oak tree was displayed in the main corridor. Walter Korder, a local artist, received New Deal money in the 1930s to paint several fairy tale paintings that still hang in the building.

In 1941, the town took the playground behind the school to make fields. The school then acquired play space in the front of the school on Oakwood Avenue. In 1954, the School Board, built a cafeteria in the remodeled basement, after parents advocated for it so children would not need to walk home for lunch. Charter Oak students ate a hot lunch just like those who attended the new schools like Webster Hill (1949), Bugbee (1952), Duffy (1954), and Whiting Lane (1954).

In 1957, Building and Grounds added a fence around the entire play area. In 1958 a gym was added, again to keep up with the new schools being built. In 1963, enrollment declined as eminent domain forced families out of homes along the I-84 corridor. Charter Oak lost 60 students in that one year.

In September 1972, school administrators hoped to build a new large elementary school for 1,000 students for $4 million to replace Smith and Charter Oak. In 1972, the *Hartford Courant* reported that the Board of Education wanted “to replace the aging Smith, Charter Oak and Elmwood Schools.” The Board scaled down its plans to a 700 student school to replace just Smith and Charter Oak. But a lack of parental support led the Board to drop the proposal.

According to Board Chair Madeline McKernan, the main impetus for the new school was to provide an equal education to students in all areas of town. The Board felt that Charter Oak and Smith’s buildings did not provide an equal education for students in the poorest areas of town.

Instead, in November, the Board decided to renovate the existing Charter Oak and expand it so that Smith School could be closed. Parents at Smith promptly organized a group called Save our Schools (SOS) to make sure that Smith did not get shut down. The Board of Education backed off and allowed both schools to remain open and in 1974 voted for funds to rehab each school. In 1975, the Board of Education decided to close the Elmwood School due to declining enrollment. In the early 1980s, Smith closed as well.

Since the early 1990s, West Hartford’s Board of Education has been under pressure to racially integrate its elementary schools. The 1968 Racial Balance Act requires towns to integrate within their district by making sure that no school has a racial balance that is 25% above or below the town’s percentage for students of color. The 1994-5 K-2, 3-5 plan attempted to ameliorate this racial imbalance, but public outcry led to the Board of Education rescinding the program which led to three magnet elementary schools instead, hoping for voluntary integration. Charter Oak became one of those magnets.

In March 2013, a 20-member committee decided to build a new Charter Oak School rather than revamp the old. New diversity school legislation, designed by Senator Beth Bye and Representative Andrew Fleischmann, passed in 2012, allows for the town to receive up to 80 percent construction cost for reimbursement if the school is being built with a plan to reach racial balance goals. Regular construction reimbursement for West Hartford is 40%.

The story of Charter Oak School, a school named after a rebellious Connecticut event to protect democracy in the 1600s, represents much about our town. It was the third elementary school, after Beach Park and Morley, to be built in town. Its original architectural plan broke new ground and its changing demographics point to the change in West Hartford’s population in the past 40 years. Though the housing stock in its neighborhood has changed little, the skin color and languages of those who live in these houses has changed. The parents’ desire for a state of the art school to provide the best environment for their children, on the drawing board for the second time in 40 years, will soon become a reality.
