## A Day in This Town’s History: August 10, 1899 {-}

*Originally appeared in West Hartford Life, July 2009*

An August 10, 1899 news brief from the *Hartford Courant* opens a window into West Hartford at the turn of the 20th century. This seven-paragraph article has 272 words and provides a sense of the fabric of a town changing from a farm town into a suburb.

> Item one:
> Mrs. F.H. Stadtmuller as a 'Ceres" presided at the meeting of the Grange Tuesday evening. The hall was prettily decorated with stalks of corn and golden rod. Papers upon grains were read by Mrs. S.P. Griswold, D.G. Francis, Dr. Ganunack, Mrs. P.R. Day and Mrs. Paullson. It has been decided to postpone the matter of an excursion for the present.

Imagine Mrs. Stadtmuller dressed like the Roman goddess of agriculture, wearing a garland of ears of corn. Ceres was an elected position in the Grange, which started as a secret organization in town in 1887 with 32 charter members. The purpose of the Grange was to improve social connections and fight the economic backwardness of farmers.

The interests of West Hartford Grange 58 included education, improvement in public highways, rural mail delivery and town affairs. Yearly, they prepared exhibits for the annual state fairs at Charter Oak Park. According to Hall's History of West Hartford, even in 1930, the Grange continued "its organization and its interest in the town."

Stadtmuller presided over the meeting, introducing the five speakers, three of whom were women. In 1900, as this town's population topped 3,000, some suburban developments like Buena Vista and West Hartford Heights were beginning as the trolley made transportation to Hartford easier.

While "grains" were being celebrated, however, the production of grain acreage in New England dwindled. Between 1880 and 1930, almost 19 million acres in New England were taken out of farming, and the number of farms declined by 31 percent.

The surviving farms in town specialized in dairy and market gardens providing plantings for suburban homes. Mrs. Stadtmuller was the wife of Frank E. Stadtmuller, who from 1885 to 1907 managed the Beach's Vine Hill Farm, which occupied acreage from New Britain Avenue to South Main Street to South Quaker Lane. This dairy farm was a model for the state in producing "baby's milk." While Vine Hill continued to prosper for another two decades, farmland was becoming more valuable for residential housing than for farming. Perhaps the Grange was glorifying an agricultural life that they saw slipping away.

> Item two:
> The Rev. John Freeborg held a meeting for the Swedish people at the Baptist Church. A considerable number of Swedes are employed in town and they are interested to hear preaching in their own language and attend the meetings as well.

By 1900, Swedes were one of the largest immigrant groups in town. Between 1851 and 1930 as much as 25 percent of the Swedish population emigrated to the United States. A second wave of immigration in the 1880s and 1890s found young Swedes settling in Connecticut near urban areas.

In 1970, this town had the highest percentage of people of Swedish background in the state. Swedes settled in the Park Road area, building two- and three-family houses and starting businesses.

At one time, the building owned by Bazilians was a Swedish grocery story. Still remaining on Park Road are Hall's Market, where you can still buy Swedish sausage called korv, and A.C. Petersen's.

According to Butterworth, Grant and Woodworth in *Celebrate! West Hartford* (2003), 20 Swedish immigrants from West Hartford, New Britain and Hartford formed a Methodist church in 1895. They built their first church on the corner of Lockwood Terrace and the Boulevard in 1921. Today that church is the Boulevard Baptist Church. The Swedish Methodist Church finally moved to Berkshire Road and New Britain Avenue and today is known as the West Hartford United Methodist Church.

The ability of a Swede who was probably a Methodist to speak at a Baptist Church speaks to the interdenominational sharing in our town. The town's many denominations have shared pulpits in times of disaster and overcrowding.

> Item three:
> Millie Fulton, youngest daughter of C.W. Fulton, received a bad cut just below the knee from a piece of glass while playing about the mill pond the other day. Dr. Alcott, who was called, was obliged to sew up the wound.

The mill pond on Trout Brook was on the north side of Farmington Avenue. This pond was used in the winters to harvest ice, but in the summer must have been a great place, except for the glass, to go for a swim.

Dr. Ralph W.E. Alcott was one of the doctors in town at the turn of the century. In the birth records, his name appears as attending to the delivery of babies in people’s homes before the advent of having babies in hospitals. He was involved in promoting the development of a sewer system here at the turn of the century as an important development to protect against the spread of disease.

> Item four:
> Misses Helen and Elizabeth Hubbard are at Branford for a week. Mrs. E.M. Peck is visiting relatives in West Haven. A daughter was born recently to Mr. and Mrs. John Hoye.

These three tidbits of information reflect on the small town that this was in 1899. Vacations and visits were noted weekly. A trip to Branford was not so difficult for residents because of the train lines that ran to the shore. By the 1880s, with the rise of factories, taking a week-long vacation became popular. Many residents owned or rented cottages on the Connecticut shore.

> Item five:
> A resident of Charter Oak was before Justice A.C. Sternberg last night charged with stealing corn from the garden of Mrs. E.A. Talcott near East Street, Elmwood. The accused was found in the corn after dark by Herbert Talcott, but claimed that he was there for other purposes and was an honest man. Bags found on the ground he disclaimed owning. The accused was supported in his testimony by Mrs. Teresa Buck of Charter Oak. As the theft was not proved, the case was nulled. There has been considerable complaint of the theft of garden truck from the region bordering on Charter Oak.

In the alleged burglary in the 1899 paper, a frustrated farmer, Mrs. E.A. Talcott, tried to find who was stealing her corn. A character witness, vouching for the innocence of the accused, helped to get the case nulled. There was no lack of tension in turn of the century West Hartford.

Judge Adolph C. Sternberg served in the state legislature from 1895-96. He was a German immigrant and the son of a highly educated man who moved here in 1854. He grew up with seven brothers and one sister on the southern end of Mountain Road where it meets Sedgwick Road.

Sternberg, as well as being a judge, helped move this town from the town meeting to the town council manager system of government. In 1916, there was so much controversy over the valuation of agricultural and residential land between farmers and suburbanites that residents rejected the assessment list and the town could collect no taxes for that year, having to borrow to pay its expenses. This controversy moved the town to adopt a new town charter in 1919 that made it the first town in the state to adopt this progressive form of government.

This news from the summer of 1899 describes a farm town with community organizations, immigrants, people wealthy enough to go on week-long vacations and law breaking. The *Hartford Courant* kept people apprised of not only the political and organizational news, but also of the social fabric of the town that helped to stitch us into a community.
