## The Prospect Casino {-}

*Originally appeared in West Hartford Life, May 2009*

An article in the *Hartford Courant* from February 25, 1901, “Casino to Close: Clubhouse on Farmington Avenue to be Leased or Sold,” caught my eye recently. The subtitle read “It has not been much patronized of late, Golf and the Country Club at Farmington Avenue proving stronger attractions—Pleasant Building, but Little Used this Winter.”

I had known the casino was on the southwest corner of Farmington Avenue and Prospect near where St. John’s Episcopal Church stands today. It struck me as not quite right that a “dry town” would have a casino, but I had never seen much more than a mention of the place in town.

The term casino did not always refer to a place for gambling and West Hartford’s casino was far from our present definition of a casino. Originally the term referred to a small Italian villa, summerhouse or pavilion built for pleasure, usually on the grounds of a larger Italian villa. Its meaning changed through the 19th century, but this original meaning seemed a better fit for the “casino” built in West Hartford in 1894.

On January 30, 1894, residents of the West End of Hartford and the east end of West Hartford met at Whiting Lane Schoolhouse to organize building “a clubhouse and casino” to act as a social club on Farmington Avenue. It was named: “The Neighborhood Club Company.” A group of 20 men paid subscriptions worth $5,000 on the way to the needed amount of $7,000. The purpose of the meeting was to talk about building the hall to be “suitable for such amusements as are desired.” H.C. Judd, F.G. Whitmore, Anson Brainerd, and John O. Enders were four of the founders.

The club chose among a dozen architectural plans. An 1894 *Courant* article described it:

> a low pitched roof rises at the front to a height sufficient for two floors and is surmounted by a platform where a flag staff rises to a height of fifty feet from the ground. From the roof projects a pleasing dormer balcony. The style of architecture is semi-colonial.

Inside, the clubhouse had a reception hall, an office, a ladies’ parlor, reading room, billiard room, assembly hall (66 x 44 feet) with a capacity for seating 500 people for dinner. They built a stage in this room as well. On the second floor, there was an office for the secretary, and a lounging and smoking room. In the basement they built two bowling alleys, a kitchen, dressing rooms, and baths. The building was heated by hot water, and lit, “for the present,” by gas. A wide veranda surrounded the clubhouse on two sides. In the backyard, they planned to build three tennis courts.

By time the building was finished, its costs had more than tripled to $23,000. Of the 140 stockholders, about 60 percent of the members lived in West Hartford along Farmington Avenue and Prospect. The other 40 percent lived in the city. According to the rules of the club, “it is intended that the tone of the club life shall be at all times elevating and that nothing in the nature of gaming or carousal shall ever be allowed.” They planned for “ladies and young people” to be part of the club. Clearly built before the term casino evolved, the rules were clear: betting and gambling were prohibited by the by-laws as was selling or keeping liquor.

Members held lectures, listened to musicians, hosted theatrical performances, had fairs, and hosted balls. Members went to the casino to read, play games, and just talk. They allowed the Farmington Avenue Christian Association to hold services there until they found a permanent home.

The opening party for the club in February 1895 was a real gala! The members decorated the building in “Oriental Luxuriance” and “well-known society people (who) danced the hours away.” A *Courant* reporter wrote:

> Society was out in full force and the company was brilliant in the costumes of the ladies, handsome gowns, beautiful bouquets and other accessories of charming toilets. There was a large number of well known people present, and while the chief attraction was the dancing in the ballroom there was a good deal of social chat in the spacious parlors and in the brilliant rooms.

Over time the members changed their club’s name from the Neighborhood to the Casino Club. The building was used often for theatrical performances, dances and receptions. When it was warm, the managers enclosed the verandah in cloth in the evening. Women and children came to the club frequently and it kept its reputation as a family club.

However, in 1896, the Hartford Golf Club opened. In the late 1890s, the Farmington Golf Club on Outlook Avenue opened. The Fern Street Golf Club was also a going concern at the same time. According to the *Courant*, interest in the Casino Club fell off when the golf clubs opened.

In February 1901, the members decided to close the Casino and they sold the building at a loss for $15,000 to Dr. Naylor. He planned to convert the casino into a home, but never moved in. He leased the building for various functions including entertainment, and Miss B.A. Hollister’s ladies’ gymnastic class.

On December 18, 1902 a spectacular fire burned the casino to the ground. The fire began in the rear of the building at about 9:30 at night. Neighbors made the call to the Hartford Fire Department and several companies arrived, but they were not allowed to start fighting the fire until Chief Eaton, who was two and a third miles away, arrived and gave special orders to fight the fire across the city line.

The fire companies took more than two hours to put the fire out. Hartford residents complained about having to pay their tax money for fire protection for West Hartford. In fact, many people moved to West Hartford because the tax rate was lower. However, Hartford seemed to supply both police and fire protection to the growing suburb of just over 3,000 residents. There had been talk of a new West Hartford fire district, but the West Hartford selectmen did not vote to fund one until 1909 and the fire company was finally completed in 1915, not far from the site of the fire.

As this new upper middle class moved to West Hartford, they organized, developed, and built new ways to spend their leisure time. The Prospect Casino had a short life, but it was an important symbol of the change in West Hartford from farm town to suburb. Those who worked in Hartford’s white-collar jobs organized and joined private clubs for their recreation. These clubs, as well as their new residences in the suburbs, helped define this new middle class.
