## Sewers, Water, and Streetlights {-}

*Originally appeared in West Hartford Life, April 2006*

Between 1870 and 1920, West Hartford was transforming from a farm town to a suburban town. As it did, its government reacted by regulating construction and by building an infrastructure of bridges, sewers, water mains and paved roads. The population grew from about 1,500 residents who lived on farms, to 9,000 strong as housing developed in the center and along Farmington Avenue. The new, suburban citizens pushed for services that Hartford dwellers already enjoyed.

The Noah Webster House and West Hartford Historical Society archive holds many town records that describe these changes. One of them, *Special Acts of the General Assembly, 1854-1913*, provides a window into the infrastructure growth in town as well as the relationship between local and state governments. Annual Town Reports from 1870 also tell a story of how the town grew.

In 1888, when Hiram Hurlburt represented West Hartford, the General Assembly, established a Board of Health in each town. This Board of Health made rules that impacted the town budget and homeowners. It provided instructions for “privy, cesspools, drains and garbage.” This law lead to the town digging sewers. It also established rules for selling food. No carcasses of calf, pig or lamb could be sold here. It also required residents of town to report any cases of croup, scarlet fever, diphtheria, typhoid, typhus, cholera, or yellow fever. The state was ahead of federal regulations as it was not until 1906 that the U.S. Congress passed the Meat Inspection Act.

The growing population and hence the growing amount of sewage seeping into Trout Brook, led the General Assembly in 1893 to authorize the town of West Hartford to construct sewers. The town decided where the sewers would go and the local property owners had to pay for the spur that went to their home. They made a deal with Hartford to hook up to their system as well, and to pay Hartford a fee for the hook up. Developer Frederick C. Rockwell was West Hartford’s Representative to the General Assembly when this law was passed. Rockwell had some interest in these sewers as he built the first housing development in town on the Boulevard between Trout Brook and Main Street. He owned the land and began to build houses in the 1890s. After the sewers were built, the next step was, in 1913 to build a sewage disposal plant. In the same year the town got the power to grant building permits.

In 1895, the General Assembly made it the duty of the Hartford Board of Water Commissioners to lay connecting pipes and furnish water to the residents in West Hartford who applied and paid for their water. Hartford’s water came from the reservoir in West Hartford, so by-passed the town itself. Adolph Sternberg was West Hartford’s representative to the General Assembly at this time. He was one of nine children of Charles Sternberg, a German immigrant lawyer who, in 1854, came to West Hartford to farm.

In 1897, the General Assembly allowed for the town to appoint a Water Commission and establish building lines. It gave the town the power to lay pipes and ask property owners to pay for the pipes that went across their property.

In 1903, when Representative G. F. Scarborough sat in the General Assembly, the West Hartford town government got the power to build sidewalks, but at the property owners’ expense.

In 1907, Democrat Charles Edward Beach served the town at the General Assembly. Charles Edward was the son of Charles M. Beach, a Hartford businessman who bought land in West Hartford in 1859 and built Vine Hill Farm on the corner of New Britain Avenue and South Main. By 1900, Charles Edward managed the farm. He also was the town surveyor and served as selectman. As a representative at the State House, he helped establish a Special Commission to “inquire into the management of affairs” in town. It seems as though the town had a difficult time collecting taxes. Between 1888 and 1894 the tax collector books were missing. Beach, the only Democrat to serve between 1857 and 1925, seemed to be checking up on Republican politicians who controlled the town. Six years later, in 1913, the town established a Board of Finance to exercise supervision of financial affairs in the town.

The following table, which shows the growth in population, budget, and the allocation of funds within that budget, is a window into building the infrastructure of the town.

| Year | Population | Budget   | Highways | Streetlights | Budget per person |
|------|------------|----------|----------|--------------|-------------------|
| 1870 | 1533       | $27,000  | 10%      | 0%           | $18               |
| 1880 | 1828       | $34,000  | 18%      | 0%           | $18               |
| 1890 | 1930       | $37,000  | 17%      | 0%           | $19               |
| 1900 | 3186       | $56,900  | 15%      | 0%           | $18               |
| 1910 | 4808       | $150,000 | 8%       | 5%           | $31               |
| 1920 | 8854       | $410,000 | 5%       | 2%           | $46               |

Over 50 years, the amount of money spent in town grew 15 times while the population grew 6 times. The percentage of budget money spent on highways and bridges peaked around 1890. The installation of streetlights occurred over a short period of time. Clearly by 1920, the town provided more services to its constituents.

One important piece of the infrastructure, education, became a larger percentage of the budget in the 1920s when seven schools were built: Beach Park, Morley, Smith, and Elmwood elementary schools, Plant and Talcott Junior Highs, and Hall High. After the town built up its infrastructure, it paved the way for more housing developments and attracted many new residents to enjoy the amenities of sewers, piped in water and street lights that had before, only existed in the city.
