## Abraham Janes, Blacksmith {-}

*Originally appeared in West Hartford Life, February 2012*

My article this month started by researching what was happening in Town 100 years ago. That search took me to the *Historical Hartford Courant*, just a click away through the West Hartford Public Library online service. There, I found that a January 14, 1912 fire raged for five hours at Abraham Janes’ Blacksmith and Carriage Shop, 921 Farmington Avenue. The fire displaced two families, and destroyed over $12,000 worth of property. Janes would later rebuild his carriage and blacksmith shop and run it well into the 1920s.

That sounded like a story to me: perseverance and grit with community support. So, I’d write about the fire and how the Janes business was rebuilt. Initially, I found two articles on the fire and thought I was set.

At the time of the fire, Mr. Janes, his wife, their six children and an apprentice lived over the repository of his blacksmith shop. Walter Payne, an employee of the Hartford Water Board and his wife and three children lived over the blacksmith shop. The first floor of the building was a paint shop, blacksmith shop, the repository and an office. The basement had two forges, wood working machinery and storage booths.

When the fire broke out, Mr. Janes and two others rescued the eight sleeping children just before they were consumed by fire. West Hartford’s volunteer Fountain Hose Company rushed to put out the fire. The nearby Congregational Church’s bell called the volunteer firemen who rushed to the scene. The row of houses on Nichols Court that ran parallel to Raymond Road, (then School Street), did not catch fire because the night was so still. Reports claimed the temperature was 16 below zero.

Janes had insured the property for $11,000. The loss was close to $12,000. The Payne family was only able to save a small trunk of clothing and a few bedclothes. Several wagons and sleighs and three cars were saved, but another car burned. A month later, the insurance company had still not paid Janes. This stopped Janes’ attempts to build a temporary shed to continue jobbing and horseshoeing. Janes, according to the Courant, had not been idle, attending to his customers at their homes or elsewhere as soon as he got the materials needed to shoe. His plans were to rebuild a one-story shop on the foundation of the burned building. Still, he took a loss and had to borrow money to keep his son in college.

Part of the story about fires is not just about how the victims reacted, but how the community kicked in. According to the *Courant*, the response was “generous.” The women of the First Church met in the parlor the next Monday morning to work on articles of clothing for the Janes children. The pastor of the Paynes South Park Methodist Church asked for help for their 6, 4, and 2 year old children. Congregants donated $75 to the Paynes.

But who was this man, Janes? Like most life stories, his was complicated. There were articles about him running afoul of the law – passing a standing trolley, trying to collect money from customers who stiffed him, and in 1931, having his house on Quaker Lane go into foreclosure.

A continued search led me to more features on Janes. As cars became the mode of transportation, and as the role of a blacksmith changed from shoeing horses to specialty work, the *Courant* memorialized him in one article “Childhood Trade Brings Him Fame: Abraham Janes of West Hartford Follows Art of Smithy His Father Taught Him As A Boy in Newfoundland," (1927) and a year later, “Abraham Janes, Artist in Wrought Iron Work: Sparks Fly From the Anvil Where, Under an Expert’s Hands, Modern Iron Becomes Latches, Grills, and Lanterns in the Style of Other Days” (1928).

In these articles I found out that Abraham Janes was born in 1872 in Brigus, Newfoundland, and grew up there where he apprenticed to his blacksmith father for 10 years. At age 17 Janes went to the Arctic on Peary’s first polar expedition. He set up a forge on Turnavik Island, mending the dog sleds and iron needed for exploration over the northern ice and for the ship. In 1898, at age 26, he emigrated to Hartford and opened his shop on Farmington Avenue. For the 27 years of his traditional blacksmith shop, he claimed, he made 53 vehicles per year and shoed hundreds of horses. One day he shod a pair of horses in 34 minutes without assistance. On another day, in 18 hours, he shod 53 horses. When there was a strike and riot in Ansonia in 1901, the cavalry was called out to stop the strike. Janes and an assistant went to the stables and, working under pressure , shod 43 horses between 2am and 7am

Janes got involved in the community as well. After the shop burned, he moved to Quaker Lane between Farmington and Park. In 1912, he joined on with Theodore Roosevelt’s Bull Moose Party, attending a local convention. In 1913 he was elected gatekeeper of the Grange. He served as a member of the Fountain Hose Company No. 1 apparatus committee, being part of rebuilding the combination truck to equip it for fire fighting. He was the head of the committee to build a new firehouse shed a few years after the fire burned his place of work.

And, the *Courant* reported, that Janes’ work changed with the times. By the late 1920s, Janes, at age 56, still worked at the shop, but made thumb latches, butterfly hinges, grills, and balcony railings for bars and clubs as far away as New York and New Jersey. Janes fashioned all the hand-wrought iron at the Hartford Theological Seminary (now the University of Connecticut Law School), the window grills on the Fire Department in Hartford, the balconies and stair rail at the Fuller Brush building, the Spanish Balconies at the Hartford Club dining rooms, and iron work on West Hartford homes on Sycamore, Albany Avenue, and Whiting Lane.

As I searched for Janes’ obituary, to round out his story, it was not in the *Courant*. One of his 10 siblings died in 1940 and Abraham Janes was listed as living in Memphis, Tennessee. His wife, Lillian Janes died in 1957 at age 84, while living on Lancaster Road and her obituary claimed she died a widow. She left four sons and three daughters, three of whom lived in West Hartford.

Janes’ story was more of a puzzle than I thought. Where he was between 1931 and 1957 is not clear. In a Google search I found a family genealogy website produced by one of his 37 grandchildren. Several comments under his photograph helped to put flesh on his bones. One grandchild said:

> Grandpa Janes (Abraham) was a good looking man, my Dad once said he didn't smoke, drink or swear and had only one weakness: women. My Dad was attending Norwich University when the separation occurred between our grandparents. He left school and went home to help support the family.

I’m left to speculate that Abraham left Lillian sometime during the Depression, perhaps as the house went into foreclosure. Perhaps his trips to New York City to sell his specialized wares opened up new horizons. Losing his house to foreclosure might have been too much for his pride to stay in West Hartford. Or maybe, like his grandson suggested, there was another woman that drew him away from his adopted town. I think there are some readers who may remember his shop on Farmington Avenue or knew his family. Can you help me fill in the story? Research that started with a fire 100 years ago led to a master craftsman who changed with the times but whose full story is still not complete.
