## James Talcott, Merchant and Philanthropist {-}

*Originally appeared in West Hartford Life, April 2003*

As the town plans for a new middle school on the east side of town, I wonder what we'll call it. How have we named other schools? What does it say about the historical context and about the town’s values? School names can be an interesting source of information about both.

Talcott Junior High, on the corner of Quaker Lane and New Britain Avenue opened in 1922. Its opening was part of a reorganization of the town schools as they moved away from both the one room schoolhouse and the kindergarten to grade 8 school. James Talcott (1835-1916), lived in town for 19 years, and was “a successful merchant and member of a family long active in town and school affairs.” He moved to New York City at 19 to become a merchant and lived there until his death at the age of 81. His contact with the town seemed minimal after he left, but his career and public life in New York made him a man to emulate.

William Hurd Hillyer, James Talcott’s 1937 biographer, described him as a man who prospered on individual initiative, responsibility, morality, ethics, integrity, honesty, being honorable, kindly and steadfast and having a spirit of cooperation. He tied these values to the Puritan work ethic as well as Talcott’s pure English lineage. These values are part of the civic education public schools try to teach.

James Talcott descended from a man who shared the same name and migrated to America with Thomas Hooker in 1632. John Talcott was one of the founders of Hartford with Thomas Hooker in 1636 and Talcott Street in Hartford is named after him. He served as a Court Magistrate, was a Deputy from 1637 to 1652, and was Treasurer of the colony from 1654 to his death in 1660. His son, John Talcott, Jr. succeeded his father as Treasurer of the colony. Another descendant, Joseph Talcott was Governor of Connecticut from 1725 to 1742.

Samuel Talcott of West Hartford built a mill near the pottery in 1828 where he and his sons carried on a thriving wool business for years. Talcott’s sheep provided wool for his woolen business. They had a fulling shop where the cloth was made ready for market and stored. The businesses were part of his 1000 acres of land which extended from New Britain Avenue as far as Oakwood Avenue, on the west side of Quaker Lane near where Trout Brook crosses the road.

Samuel Talcott’s son Seth took over the mill and he was the father to James (remember him!). As a young man, James and his ox team had the task of bringing goods to market in Hartford. When his brother opened up a woolen knitting mill in New Britain, James got involved at the outset as a merchant. As a man of just 19, he set out for New York City in 1854, and set up shop. This was right when West Hartford became an independent town.

In the 1850s merchants were the pillars of capital and lived in the big cities. They were generally the wealthiest men and were civic leaders. As a merchant, James Talcott sold his brothers’ goods to stores like New York’s A.T. Stewart, the biggest retail merchant in the country, and Philadelphia’s Wanamakers, the country’s first department store. He was successful, according to Hillyer, because of his honesty and integrity, and because the knitted woolen goods from this brother’s factory in New Britain were so good.

Once established in New York City, James Talcott married Henrietta Francis in 1861. Her uncle had a farm in West Hartford. James probably met her on a Thanksgiving break where he spent a few days every year with his parents in West Hartford. James and Henrietta bought a house at 20 West 39th Street – a four-story brick house. He lived there for 12 years and his three sons J. Frederick, Arthur and Frank were born there. They later had two daughters.

Every Saturday afternoon, Mrs. Talcott drove in the family carriage downtown to bring Mr. Talcott home. She never drove to the front of his building on Franklin Street because both she and Mr. Talcott believed that it would have been “unnecessarily ostentatious” for him to step into a fine carriage with a coachman and footman in front of his business.

In 1876 they bought a five story brownstone for $90,000 cash at 7 West 57th Street. This was a new and fashionable part of the city which had become so because William H. Vanderbilt and other wealthy New Yorkers had built imposing homes there. But probably more important was the opening of Central Park where New Yorkers could skate, sleigh, ride, drive, and play outdoor games like archery, croquet, and lawn tennis. Talcott had enough money and social standing to be a part of this West Side life.

In this home, well staffed with servants, there was a routine. Mrs. Talcott served tea at five o’clock each day. Friends usually came by to visit at this time. Dinner was always served at 7:30 and Mr. Talcott always dressed “in full evening dress” for the occasion whether there were guests or not. He served no wine or liquor, but an imported sparkling mineral water.

Talcott showed a deep interest in religion and took an active part in church affairs. Talcott joined the Broadway Tabernacle Church (Congregational) and became a member of the Church Committee at age 30 when, traditionally, this group was made of the elders of the church. He found time for mission work in Bethany Parish at 34th and 10th, in one of the poorest sections of the city.

James Talcott was a Republican and he was mentioned as a candidate for Mayor of New York City in 1890, but never ran. He was a protectionist and one of the staunchest supporters of the American Protective Tariff League, a position that most merchants took. He spent time fighting Democratically controlled Tammany Hall.

As a philanthropist he gave away 10 percent of his wealth. He saw himself as a steward of his wealth. Some of his interests included a library built at the Northfield School, Massachusetts, a dormitory built at Oberlin College, the Grace Talcott Hospital at Shunteh-foo, China, planting an arboretum at Mt. Holyoke College, and endowing a professorship for religion at Barnard College. He was one of the founders of the Jerry McAuley Water Street Mission, the Cremorne Mission and the Home for Intemperate Men.

In 1897, Talcott gave books and money to help establish West Hartford’s free public library. Until then, the library was part of the First Congregational Church.

In his later years, Talcott devoted his life to peace. He went to Lake Mohonk, America’s peace center each fall. He supported peace in trade and in politics. Talcott was 80 when war broke out in Europe and he expressed his disapproval. He died peacefully in 1916 at Lake Mohonk, before the U.S. entered the war.

The 1920s, the post World War I era, was a time when “the business of America was business.” The town’s population grew to almost 9,000 by 1920, and middle class professionals started to move to West Hartford, the streetcar suburb. James Talcott’s career must have appealed to them because of his monetary success, his moral and ethical purity, and his charitable works. Many other members of the family were involved in West Hartford governmental affairs, but the town officials chose this self-made business leader, this champion of hard work, integrity, honesty and success to be a role model for the town.
