## Troup 12 {-}

*Originally appeared in West Hartford Life, July 2010*

In June 2010, Adam Brown and Jeremy Schmitt both earned their Eagle Scout Award from Troop 12 at the First Congregational Church of Christ. Their journey, through more than 20 merit badges, countless weekends of camping, weekly meetings, popcorn sales, weeks at Yawgoog Summer Camp in Rhode Island and the demand to “do a good deed daily” added two more young men to the roster of about 1.8 million who have received this award since 1910. Four percent of those who start in scouting finally earn the award.

Jeremy and Adam are part of a strong scouting tradition in West Hartford. Troop 12 was founded in 1910 at the First Church. In 1936, the Universalist Church started Troop 44. Troop 136 is attached to the Westminster Presbyterian Church. Troop 146 began at the Methodist Church in 1941.

William H. Hall in his book *West Hartford* (1930) devoted three pages to “The Boys Brigade and Boy Scout Troop 12.” Minister Thomas Hodgdon of the Congregational Church organized the forerunner of Boy Scout Troop 12, the Boys Brigade, as part of an international organization started in Scotland in 1883. The activities included a mix of military drill, Bible study and camping. By 1905, about 14,000 12 to 18 year old boys across the United States joined the organization.

West Hartford’s group was called Company C. The impetus for the group back in Scotland came from a man who had trouble keeping order in his Sunday School classes and who believed that discipline instilled in the young men would help keep them in the church and out of trouble.

The original purpose of the Boys Brigade was "the advancement of Christ's Kingdom among Boys and the promotion of habits of Reverence, Discipline, Self-Respect, and all that tends toward a true Christian Manliness."

Reverend Thomas Hodgdon started the group and 30 boys joined. To be a member, boys had to swear off alcohol, tobacco, and obscene language. They wore military uniforms. Hodgdon met with the boys weekly; the first part of each meeting was religious. Then the boys marched to the old Town Hall on the northwest corner of Main and Farmington, where they performed military drills with dummy rifles.

In May, the boys performed their Annual Exhibition Drill and the townspeople came to watch. The best “driller” won a prize after keen competition. On Memorial Day they escorted the veterans to the cemetery.

Camping was an important part of the Boys Brigade in Scotland and in West Hartford as well. The boys went to camp for two weeks each June. Two years they went to the Aqueduct on the Farmington River. In 1909 they camped at the Connecticut shore for two weeks. Campers conducted mock battles, played sports and stood guard at night.

British Army Maj. Gen. Robert S.S. Baden-Powell, who fought in the war against the Boers in South Africa (1899-1902), saw 7,000 Boys Brigaders drill in Glasgow. He was impressed by their enthusiasm but believed the program could be expanded to include more of what he defined as scouting. When he formed the Boy Scouts in 1910, many Boys Brigades, like West Hartford’s Company C, transformed into Boy Scout troops.

Between 1910 and 1913, Connecticut Boy Scout Troop 12 raised $600 to buy lumber and supplies to build a cabin on the old Porter estate on the eastern slope of Talcott Mountain, just west of the Canal Road. Samuel Valentine owned the land and he allowed the boys to build on his property. The cabin had a sleeping loft and a stone fireplace and became known as Camp Valentine.

On the 200th anniversary of the First Church in May 1913, officials dedicated the cabin. The cabin was built by the labor of scoutmasters and the Boy Scouts. 150 people gathered including parents and friends of scouts, Campfire Girls and other bicentennial guests. Twenty-two Boy Scouts in uniform lined the veranda of the camp as their leaders related the short history of the troop. Though the Scouts are a religious organization, Troop 12 was established as a non-denominational troop.

Reverend Henry B. Roberts dedicated the cabin with the following words:

> We dedicate this house for noble uses of the Boy Scouts, their parents, and friends; for the cultivation of the pleasures of comradeship and friendship, for the increase of our knowledge of the birds, the trees, the rocks and the precious things of the earth; for the promotion of mutual helpfulness and the cultivation of deftness of hand, and readiness of heart, to give help and succor to those who are in need of our kindness and assistance; for the honor of our church, the good name of our town, and the increase of true patriotism.

At the camp, activities included first aid to the injured, swimming, and hiking all to build character, independence and perseverance.

The moving force behind the troop was Rev. Hodgdon who had a son who was a patrol leader. Arthur R. Thompson was appointed scoutmaster in 1911 when the troop formed. Thompson was an explorer and naturalist. In the summer of 1894, he traveled with a group toward the North Pole. He was shipwrecked on the coast of Greenland. In 1898, he took an extended trip to Alaska where he panned for gold. Thompson wrote two books about his adventures and encouraged his troop to have an adventurous spirit.

From 1915 to 1928, Dr. Edwin H. Munger served as scoutmaster. He was an enthusiastic leader who trained and drilled the boys efficiently. He studied nature and took the boys on hikes exploring the birds, flowers, trees, ferns, and rocks. On his death, the man who became scoutmaster eulogized Munger by saying

“The Town of West Hartford has been exceedingly fortunate in having had a real Scoutmaster in the late Dr. E.H. Munger, for under his guidance Scouting in the Town has taken a very high rank. Troop 12 has been, since its organization in 1911, one of the leading troops in the East, with an average of 31 boys each year registered.”

By 1928, 17 years after its founding, Troop 12 had produced 40 Eagle Scouts, an average of more than two per year. Though Camp Valentine is gone, Troop 12 lives on.Their first Eagle Scout ceremony in six years was performed at the church in late June, promoting two scouts to Eagle, one being my son. These boys are part of a long line of young men who persevered to earn the Eagle Scout badge.
