## Elmwood’s Frank Stadtmuller {-}

*Originally appeared in West Hartford Life, May 2006*

Frank Stadtmuller came to public prominence as West Hartford was changing from a rural town to a suburb. He was a progressive farmer who advocated a role for farming in 20th century Connecticut and West Hartford.

As a Democrat in an overwhelmingly Republican town, Stadtmuller held positions as Justice of the Peace, a member of the school committee, head of the West Hartford Democratic Caucus, Town Selectman, Vestryman at St. John’s Episcopal Church, West Hartford’s Building Inspector, and West Hartford’s Health Officer. In the state, he served as the President of the Sheepbreeder’s Association, President of the Connecticut Dairymen’s Association, and the State Agricultural Commissioner. Stadtmuller always listed his place of residence as Elmwood.

Stadtmuller was born in 1861 on the Vine Hill Farm owned by Charles Mason Beach. His father Louis Stadtmuller was a German immigrant who worked for the Beaches. At age 6, the family moved to New Haven and Stadtmuller grew up there and graduated from Yale. He returned to Vine Hill in 1885 and, at age 24, took over the management of the farm for the next 30 years. He worked hand in hand with Beach’s son, Charles Edward who was one year younger than Stadtmuller.

Stadtmuller championed progressive farming. He and Charles Beach were the “inventors” of “baby’s milk” or what was known as “sanitary milk” in Connecticut. To produce baby’s milk, they kept the cows clean and the milkers free from disease. Each day, they tested the milk in the lab. Before the 1890s, infants only drank mother’s milk. Beach and Stadtmuller marketed cow’s milk to children.

![Stadtmuller is most well known for being the originator of the certified milk business in Connecticut, between 1890 and 1920. His work force at Vine Hill farm is dressed in whites with caps carrying covered buckets of milk. Their attempt to improve the sanitation milking cows led to advertising this milk for babies as “Clinical Nursery Milk.” Source: Noah Webster House & West Hartford Historical Society.](images/05-Stadtmuller.jpg)

Stadtmuller was a businessman and an advocate as well as a farmer. He believed that milk had to be marketed and he believed the state had a role to play in doing this by inspecting milk, certifying its cleanliness, and providing price supports. In 1907, at a meeting of the Connecticut Dairymen’s Association, Stadtmuller gave a talk on problems with the low market price of milk.

However, having regulations and enforcement were two different things. At the state dairymen’s convention in 1913, the president of the group, Warren Davis, said that municipal milk inspection was “a joke.” He argued that the legislature would not appropriate enough money for inspection and that the inspection should be done by the State Health Department, rather than local health officers.

Stadtmuller believed that when each municipality inspected milk, the standards varied a great deal. The producer who lived closest to the point of distribution was inspected much more than the one further away and he believed that a state standard would help the situation. In 1917, as the State Dairy and Food Commissioner, he arrested the First Selectman of Southbury and four others for selling “watered milk.” These men felt the pressure of the cost of producing milk. Stadtmuller could use these men both as an example of the need for standards and the hard time that milk producers had producing a profit of any kind.

In 1914, in a speech before a meeting of the Men’s Union of the First Congregational Church, Stadtmuller decried the plight of the farmer in Connecticut, claiming that many of their problems were based on poor distribution of goods and the lack of cooperation between farmers. He also believed that the price of milk had to go up two cents per quart or even more men would give up dairy farming.

In that same year, as President of the Hartford County Rural Improvement Association, Stadtmuller encouraged those in attendance to value agriculture. Hartford County in 1909 produced $6 million worth of agricultural goods. He knew of large areas of “wasteland” that had gone to brush that could double Hartford County’s agricultural production. He urged “the children to stay on the farm instead of flocking to the city.” Cooperation among producers, he said, would lead to success.

Stadtmuller’s idea of an organization came to fruition in 1915 when his Hartford Country Rural Improvement Association (of which he was President) and the Board of Trade came together to discuss how they could help each other to save agriculture for the county. The amount of farmland decreased every decade, farmers moved west, and the many no longer thought of New England as an agricultural region. Stadtmuller seemed at his best when he used his position in various agencies to bring people together.

Stadtmuller also helped found and lead the West Hartford Business Men’s Association. In November 1910, they held a meeting on the subject of a public utilities commission. Stadtmuller’s Association called in two speakers from Hartford, Normand Allen and Ralph O. Wells, who explained the reasons that a commission was needed to control the “great public service corporations.” Allen, the owner of the Sage Allen Department Store explained that there “was no opposition to the great corporations.” He believed that there needed to be a way to secure the safety of employees on railways, to be sure that electric and gas meters measured use fairly, and that rates for electric and gas be controlled because they were unfair.

Allen proposed a public utilities commission of three to five men being paid $7,500 a piece to regulate the industry. The other speaker, Ralph O. Wells was concerned with the “baleful influence of the lobby in Connecticut legislation.” He believed that the Legislature was not controlled by reason but by corporations trading votes and “log rolling” to get what they needed. He believed that the electric and gas corporations had much too much power.

Stadtmuller believed that government regulation and associational cooperation could improve life for farmers and consumers. During the 1930s, with Franklin Roosevelt’s New Deal, the federal government, for the first time introduced price supports for agricultural products and established a “cost yardstick” for the cost of electrical power. In the 1910s, Elmwood’s Frank Stadtmuller (1861-1918) already brought these issues to the public’s eyes. Where many historians argue that the push for more government intervention in the economy came from the federal level, in fact the ideas were brewing on the local level right here in West Hartford a quarter of a century earlier, during the Progressive Era.
