## William H. Hall and West Hartford in 1902 {-}

*Originally appeared in West Hartford Life, April 2009*

When the Rutherford Building opened in West Hartford Center in 1902, William Hall presented an “Historical Sketch of West Hartford” at the dedication of the building. Hall served as Superintendent and was the unofficial Town Historian. His 28-page speech describes a town based on democracy and cooperation, a town beholden to its forefathers with education as its highest calling.

His dedication began with the story of the arrival of the first English settlers to Hartford in 1636. He said that these settlers not only found a beautiful location, but also established a true republic with its Fundamental Orders written in 1638, established by “the people themselves.” Hall knew why Connecticut was called the Constitution State.

Hall used Lincoln’s words “of the people, by the people, and for the people” to describe the use of the Town Meeting which worked so well in our community. Hall made a point to recognize the vote by the Hartford settlers to set aside common land for the benefit of all between Quaker Lane and Prospect Avenue. In 1902, Hall marveled that on this stretch of land that large portions of the territory were being used by the Hartford Golf Club, Elizabeth Park and Charter Oak Park, for “the use and benefit of the public.”

Hall was interested in civic virtue. Each section of his speech outlined an inheritance of public service, or actions that were for the good of all, not the aggrandizement of the individual. The first government of the town came out of the church. At the annual meeting, a Society Committee of three church members was chosen to run the town. Soon a committee of five took charge of the schools. They later became the Board of School Visitors, and then the Board of Education. The minister was always a member of the school visitors. According to Hall the five Visitors went to a school and then made a “call at one of the taverns for a mug of flip” before moving on to the next school.

Hall believed he could characterize West Hartford residents as industrious and thrifty based on the lack of a poor house. Only a few needed public aid each year.

Hall editorialized that “the worship of God, and the instruction and training of the children, are fundamental principles in all good government and society.” He believed that there were public schools here as early 1713 when the first church was built. When the town met to build three new school buildings in 1745, the meeting minutes recorded that the committee dispose of the old school houses. One of these buildings was the “old gambrel roofed brick school house,” built around 1745 near the Old Burial Ground on North Main Street. In Hall’s words, “within its walls, on side benches, often in a crowded condition, successive generations of noble and worthy citizens were trained.” On Sundays, the schoolhouse was used for Sunday School classes. “There is no doubt” according to Hall, “that the people of West Hartford, in those days, as in our own time, were public spirited, conformed to good customs, obeyed the laws and improved their privileges, and therefore established schools very early.”

Until 1795, the ecclesiastical society took care of the schools. By 1780, there were five schools in town, all on Main Street. Hall believed that one was located in the south end, one near the residence of Paul Thomson (near Park Road) and called the Popple School, because of the numbers of poplar trees, one in the Center, another called the Chestnut Hill School, and finally one in the north end. There were also schools in West Lane, Mountain Street, Prospect Hill and the Quakers ran one school. At that time, West Hartford had a population of about 1000 people, about 125 families.

From 1796 until 1855, a School Society, established by the General Assembly to separate church and state, managed the schools. The School Society broke the town into nine school districts. Each one had meetings each year to establish the policy and kept records of those meetings. In West Hartford, citizens actively participated in running the schools. Hall documents that the West District held eight meetings in one year to decide where to build a new schoolhouse. Because students were required to pay for their schooling with wood, the purchase of wood stoves was a big event. The South School District established a committee of three to discuss the purchase of one of these stoves.

Schools were open for eleven months a year, in the winter run by male teachers and in the summer by dames or female teachers. Hall records the pay for the men at $42 for 16 weeks and that for a dame (usually the best female scholar at the school) at $9 for nine weeks.

In 1845, shareholders started the West Hartford Academy. The 58 stockholders operated a flourishing school through 1865 whose pupils included boarders from out of town.

Hall pushed the school district to consolidate and it did so in 1885. Subsequently, the town began to manage the schools. Hall argued that this consolidation led to a marked improvement in the schools. Hall continued to praise the democratic process and the participation of townspeople in the workings of the schools. In his speech’s conclusion he proclaims:

> Let us not forget, however, that our highest duty, our noblest endeavor, our grandest opportunity and our true success as a community are to be found in such use and improvement of all these advantages and blessings as will result in the training of our children and youth in character and life so that they may most worthily serve God and their fellow men in their day and generation.

Hall’s focus on community, hard work, education, and democracy continue to drive the town today when its population is twenty times larger than in 1902. Though the physical manifestations of these values have changed with 15 public school buildings and a Town Council rather than Town Meeting form of government, their importance to the community continue with an active citizenry imbued with civic virtue and education at their core.
