## Recalling the Days of Luna Park {-}

*Originally appeared in West Hartford Life, May 2008*

Imagine yourself in West Hartford on June 23, 1906. Luna Park, an amusement park, is set to open on New Park and Flatbush Avenues.

You’ve watched the construction and the hiring of more than 100 employees to run the park. You’d heard about the Columbia Exposition in 1893, Coney Island’s Luna Park that opened in 1904, and the St. Louis World’s Fair in 1904.

This opening is not on that grand a scale, but news articles from the *Hartford Courant* make allusions to these events.

At 2 p.m. on that Saturday afternoon, Governor Henry Roberts officially opened the park, flanked by Hartford’s Mayor Henney and West Hartford’s town selectmen. The Colt Band kicked off the celebration, playing the “Star Spangled Banner,” followed by exploding cannons.

There you were, in your hometown of about 5,000 people. Luna Park was Greater Hartford’s “first big metropolitan outdoor place of entertainment” and likely you would have been part of this opening celebration.

The Chatford Construction Company from New Haven invested $200,000 to build the park, starting in March 1906. At least 150 workmen built the midway, concessions and rides.

The day before the park opened, the men worked until 8 at night when, for the first time, they turned on the 50,000 lights. The *Courant* said “the illumination was spectacular in the extreme and the White City stood out in the darkness like some magic city flashed into being by the wave of a wizard’s wand.” A crowd had gathered both from the city and surrounding neighborhoods to witness the final touches on the amusement park. The park of pleasure offered a host of entertainment.

After paying a 5 cent entrance fee, you could see the Old Mill, Palace of Fun, Fatal Wedding, Streets of India, Ferris Wheel, Photograph Gallery, Snake Charmers, Temple of Mirth, Circle Swing, Penny Arcade, Miniature Railway, Pony Circus, Mammoth Carnival, Helter Skelter, Fortune Tellers, San Francisco Disaster, Rifle Gallery, Japanese Tea Room, Glass Blowers and a big ballroom, the biggest building on the grounds.

West Hartford residents were thrilled with the number of construction jobs and then with the work at the park. A May 6, 1906 help wanted ad in the *Courant* called for 109 employees to be hired at the park including female cashiers, male ticket takers, guides, ticket sellers, scenic car brakemen, Old Mill employees, property men, circus ring employees, hostlers (stablemen), garage men, engineers, electricians, gardeners, watchmen, police, musicians, lecturers, cooks and “colored” nurses.

Luna Park shared the property with the Charter Oak Park race track that opened in 1873 at the corner of Flatbush and Oakwood avenues. The 120-acre park, bounded by Flatbush Avenue, Quaker Lane, Prospect Avenue, Talcott Road and Oakwood Avenue, had a one-mile horse racing track.

This park put West Hartford on the map of harness racing. Daily trotting races, which climaxed with Race Week over Labor Day, drew thousands to town for the daily summer trotting races and betting ranging from $100 to $20,000.

![This 1926 map shows signs that the Horse Race Track is no longer in use, and Luna Amusement Park has gone out of business. Its main purpose was for the Connecticut State Agricultural Fair.
Source: Noah Webster House & West Hartford Historical Society.](images/05-luna-park-state-fair.jpg)

Luna Park drew people to town, too. But the shining new park brought with it problems as well.

At the end of May 1906, the Consolidated Railways Company asked the town to make the trolley to Luna Park a double track. The selectmen authorized the company to construct a double track, but it wasn’t ready for the park opening in late June.

When the park opened on June 23, there was trouble. On June 26, police discovered three cases of pickpockets who got $75 from their victims. As the *Courant* put it, “the opening of a large place of amusement like Luna Park naturally draws some from the underworld.”

Just three weeks after the park opened on July 15, the Rev. T.M. Hodgdon from the First Church of Christ Congregational, “preached a forceful sermon upon the desecration of the Lord’s Day at Luna Park.” Reverend Hodgdon argued that West Hartford was humiliated in the eyes of neighboring towns for letting Luna Park open on Sunday.

Management of the park, he believed, was happy to pay a $50 fine per week. Reverend Hodgdon believed the park could be open on Sunday, but they could not charge admissions fees or run the amusements because the law prohibited the doing of “any secular business or labor, except works of necessity or mercy.”

He referred to reports of liquor sales in this dry town and gambling in the neighborhood. According to the newspaper report, while peanut vendors were prosecuted for trespassing at the park, police did not enforce the laws against liquor or gambling.

On July 18, Louis Dubrowski was found guilty of trespassing with his peanut and popcorn wagon, which he set up on New Park Avenue at the front of the park property. The rule was that he could not have his cart in one place for more than five minutes. Witnesses claimed he was there from three to five minutes. A court interpreter, who translated from Polish for “the prisoner,” as he was called in the newspaper article, addressed the court saying “the Constitution of the United States allowed everyone to make an honest living and inquired why the gamblers who frequented the Luna Park region were not arrested instead of a poor man with a family to support.”

The prisoner was set free as long as he agreed not to go back to Luna Park.

Just two days later, a near riot erupted among the immigrant workers trying to finish the trolley tracks. The work to double track the trolley had moved slowly and park officials put pressure on the trolley company to finish their work because it affected the attendance.

The trolley company imported a gang of Italians, Hungarians, and Poles from New Haven to work on the Luna Park end of the track while local immigrant men worked on the Sisson Avenue end. The company paid the New Haven men $1.75 per hour while paying the local men $1.50.

When the local men did not get a raise, they threatened the New Haven men with violence and there were rumors that the Hartford men had guns. The New Haven men refused to go back to work for fear of their safety.

The general manager of New Haven’s Consolidated Railway Company came to the scene accompanied by the West Hartford’s Deputy Sheriff Foote and seven policemen from the Hartford police and surrounded the New Haven workers, making it safe for them to go back to work.

If the Hartford men did not go back to work at the old rate, they were told they would lose their jobs. About 30 men returned. The local men not only called for a raise in their pay, but also a decrease in the work day from 10 to 9 hours. The local men did not go to work on July 19. In response, the trolley company brought up another gang of workers from New Haven to complete the job.

Was this park “good” for West Hartford? If you were there, you would have felt the excitement of manufactured fun, big crowds and city lights.

For town officials, it wasn’t as simple as that. Workers, peanut vendors, immigrant laborers and Sunday amusement seekers pressed the bounds of what was acceptable in a 1906 suburban town.
