## William Howard Taft comes to West Hartford {-}

*Originally appeared in West Hartford Life, July 2011*

What would you do if the President came to town? The people in West Hartford were faced with that very question in the summer of 1911. William Howard Taft’s visit to the Connecticut State Fair on September 7 mobilized the West Hartford Grange selectmen led by Frederick E. Duffy, the Hartford police and city council, Governor Simeon Baldwin, local citizens and peace activists looking to arbitrate rather than fight about diplomatic issues.

Every September, starting in the early 20th century, the Connecticut Fair Association held its harvest fair on the grounds of the Charter Oak Race Track on New Park Avenue. The Fair ran concurrently with Race Week, which started on Labor Day when the most important horse races were run. Luna Park opened on the site in 1906 and attracted the amusement park crowd, who also attended the State Fair. The three attractions pulled in tens of thousands of visitors.

Each year, the Connecticut Fair, a private venture established for profit, named one day as Grange Day and encouraged the Grange to find a nationally known speaker.

When September 7 was set for Grange Day in 1911, the Connecticut Fair went ahead and secured President William Howard Taft as the speaker. The Grange said that the fair had broken its agreement and declared the engagement off.

Taft was in his third year as president, after serving as Teddy Roosevelt’s Vice-President for four years. Taft was a Republican who believed in Progressive ideas. He opposed trusts, and in 1911 brought suits against American Tobacco, Standard Oil, and US Steel. Taft also supported a protective tariff, which the conservative wing of the party supported.

For the Grange leadership, Taft’s invitation was anathema. On August 2, West Hartford’s Frederick E. Duffy, a Democrat and executive officer of the State Grange was quoted in the *Hartford Times* saying “the Grange cannot consistently participate in the reception to be tendered for President Taft when he comes to Hartford. The Grange is opposed to the Reciprocity Idea in all its aspects, and as President Taft has been the leader in that movement the Grange does not care to take part in any event in which he is a guest.”

Duffy, who owned Meadowbrook Farm in West Hartford, traveled to Washington earlier in the year to testify in hearings against the Reciprocity Treaty. The 1911 treaty negotiated with Canada’s Liberal government provided for free trade in natural products and the reduction of duties on a variety of other products. In August 1911, the US Congress ratified the treaty but when Canada’s Liberal Government lost the general election in September 1911, the Canadian government never ratified the treaty. When Taft planned his trip to Connecticut, this treaty was much in the news.

Duffy believed that free trade would hurt U.S. farmers and Taft should know just how strongly the farmers felt. Duffy said that they meant no slur on Taft, but that Duffy was “very much opposed to the President’s stand on reciprocity.”

Most of all, the Grange, who had been representing farmers for over 35 years, believed reciprocity would help the middleman, those who would trade in the increased volume of goods, much more than it would help the farmer. The Connecticut Grange, which began in 1876, tried to support and protect small farmers in their relationship to the state and federal governments. By 1910, there were 25,00 Grangers in Connecticut.

But just like in unions, the rank and file did not always agree with the leadership. On the reciprocity question, many Grangers were able to separate their beliefs about Reciprocity and the visit of the President to their town. In local politics, however, Democrat Duffy would not relent. His position led L.J. Masury to resign from the West Hartford Board of Education rather than serve on the board with Duffy because of his active stand against President Taft and his visit.

Grangers who went to a Field Day at Lake Compounce on August 25 also expressed their opinion about Taft coming to the Connecticut State Fair. Some in the Grange wanted to boycott the Fair because of Taft’s presence but many claimed not to be opposed to the President himself.

Meanwhile, town and city governments rolled into action. On August 8, Hartford’s Board of Police Commissioners discussed Taft’s visit to the Connecticut Fair. The Hartford Police Department had jurisdiction over Charter Oak Park even though it was in West Hartford. The police regularly stood at the gates and patrolled inside the park. With the President’s planned visit, the cost of police protection at the West Hartford site increased even more. Hartford’s Board of Commissioners questioned their role in West Hartford. Newspaper articles claimed that other for-profit organizations had to pay for their own police protection, but not the Connecticut Fair Association. This issue would not be resolved until West Hartford had its first paid police eight years later.

Just ten days before Taft’s arrival, West Hartford’s selectmen resolved that they should develop a committee whose purpose it was to prepare the town to officially welcome Taft. The Selectmen named Judge William Case the chairman of the committee of 192 men. Frederick Duffy was notably missing from the list of the town elite. By time September rolled around, West Hartford closed schools for the Thursday Taft visited to allow the children to visit the Connecticut Fair and see the President

On September 7, Taft arrived in Hartford’s Union Station from Boston on his private railway car. Democratic Governor Simeon Baldwin met him and led the opening ceremonies and the parade as they rode in an automobile from the train station to the newly opened Supreme Court and State Library building where he had lunch among Connecticut’s finest.

The car then took him and his entourage including U.S. Attorney General George Wickersham to the Fair where Taft delivered his speech to an estimated 30,000 people who completely filled the Charter Oak Race Track from fence to fence.

Taft made a nod to those at the fair, saying that farmers increasingly needed to use the scientific principles in farming to increase the value of farmland. He noted that in Connecticut with two representatives from each town in the General Assembly that farmers had a particular hold on political power.

Then he moved into the topic of his speech: the “duty of the American nation to promote worldwide peace.” On August 3, 1911, the United States, France and Britain signed a series of treaties on international arbitration to settle international disputes. Taft’s excitement and interest in this topic came at a time of militarization in Europe, and imperialism in Central and Latin America. In Taft’s speech he used arguments that would appear again eight years later when the Senate debated the Versailles Treaty.

Taft spoke of permanent peace to relieve nations of preparation for war. He believed tariffs could be arbitrated and that these negotiations would not take away power from the U.S. Senate. Just three years later a “war to end all wars” broke out in Europe.

For September 7, 1911, West Hartford focused on the visit of the President. As Taft was whisked back to his personal train car, and taken back to Boston and then his summer home in Beverly, Massachusetts, West Hartford’s residents were left to mend their political disagreements, think about a professional police force, enjoy the rest of Race Week, and perhaps, dream of international peace.
