## West Hartford 1905 {-}

*Originally appeared in West Hartford Life, May 2014*

Between 1885 and 1925, more than 80 percent of West Hartford residents had jobs that were not based on farming. The economic nature of the town changed as farming became more specialized, transportation to Hartford improved with the horse trolley, and developers began buying up land and luring Hartford residents out to the suburbs. Yet, even though West Hartford was changing from a farm town to a suburb by 1905, farmers, as well as florists, and gardeners who made their living off the land continued to play a significant role running the town. While it may seem that farmers would carry traditional political and economic values, in fact, those in West Hartford helped to reshape our community.

The town grew in the 1890s from 1,920 to 3,186 in 1900 and increased another 60% by 1910 to 4,806. While the town retained its rural look with plenty of land still farmed, the types of farms and variety of jobs of the newcomers to town helped change the character of the town.

In 1905, *Geer’s City Directory* collected information on West Hartford residents, listing their place of residence, their job and its location, and whether they owned their own home. West Hartford’s labor force worked as clerks in Hartford’s insurance industry, as machinists at Pratt and Whitney and as carpenters, civil engineers, and Charter Oak Bank cashiers. The Arnolds ran the Trout Brook Ice and Feed Company on Farmington Avenue and many women worked at St. Mary’s Home on Steele Road. West Hartford residents did white collar work, worked in manufacturing in both Hartford and West Hartford, did artisanal work as harness makers, blacksmiths, masons, and hostlers and did service work as butlers, domestics, drivers, and coachmen. This wide variety of occupations reflected a town making the shift from farm to suburb and in a town in which the wealthier residents employed service workers.

The most surprising part of the data is the number of people still involved in working off the land. But, the type of land use varied more as those working the land specialized. Data from the directory reveals that about 12 percent of the workers listed were farmers. In the United States, farmers made up about 38 percent of the workforce in 1900 and 31 percent in 1910. West Hartford was moving away from its rural roots, to a mixed economy.

At the same time, those living off the land included gardeners, vegetable gardeners, landscape gardeners, milk dealers and peddlers, florists, farm hands, and tobacco workers.

The son of German immigrants, Frank Stadtmuller, was a progressive farmer who advocated a role for farming in 20th century Connecticut and West Hartford. He managed Vine Hill Farm owned by Charles Beach from 1885 to 1915 and invented the idea of “baby’s milk” by testing milk in the lab each day and keeping the cows clean and milkers free from disease. Stadtmuller, who lived on the farm, encouraged farming in West Hartford and encouraged farmers to also run efficient businesses. On his dairy farm, he marketed his product, and he believed that the state played a role as well in inspecting milk, certifying cleanliness, and providing price supports. These changes show that, though there were still many farmers in town, some farmers, at least, saw the benefits of government support and modern marketing techniques.

Stadtmuller, in his second role as State Dairy and Food Commissioner, urged farmers to improve distribution of their goods and to cooperate. He urged the government to provide price supports for milk, so that farmers did not give up dairy farming, and sell their lucrative farmland to developers.

The Thomson family, James, Paul, Wallace and Jennette owned all four corners of the intersection of Park and South Main where they established a florist business. Paul Thomson was listed as florist at the corner of Park and Main. James, who died by 1909, was the founder of Hartford’s Brown-Thomson department store, and like some other industrialists, moved to what was becoming the suburbs, to establish a “gentleman's farm.” Wallace Thomson, his son, established the family greenhouses in 1899, providing vegetables and produce to the farmer’s markets throughout the Hartford area. Wallace’s son Pomeroy, went on to Cornell and came back to the West Hartford greenhouses in the early 1930s to grow carnations that sold wholesale and to supply the florist trade. Adjoining the greenhouses, was Thomson’s florist shop. Wallace Thomson, like Stadtmuller, was also involved in town government and served on West Hartford’s first Town Council from 1921 to 1931.

Frederick Duffy moved to town in 1900 and bought the old John Whitman House on North Main near Asylum Avenue. Listed as a farmer, Duffy studied and developed a herd of Jersey cows which produced a superior quality of milk and cream. He had these dairy products delivered each day to Hartford families. At the same time, Duffy promoted agriculture in the state and served as a judge at stock exhibits across the country. Duffy served on West Hartford’s School Board and as a member of the first Town Council in 1921. In the 1940s, he headed the West Hartford Housing Authority.

A.C. Sternberg and his son farmed at the corner of Sedgwick Road and Mountain Road. He owned the area to the east of the West District School. He had five barns and several houses on his property. From 1895 to 1896 A.C. Sternberg served as the representative to the Connecticut General Assembly from West Hartford.

In 1916, a contentious quarrel between farmers and suburbanites over the value of land led to taxpayers rejecting the assessment list. The town could not collect its taxes and had to borrow a year’s expenses. Sternberg headed a seven-member committee which studied the problem and recommended that the town move from the town meeting form of government to a council manager system with a zoning plan to control and encourage development on farmland being put up for sale.

While the number of farmers in the country, in Connecticut, and in West Hartford declined, they retained political power. Stadtmuller, Thomson, Duffy and Sternberg all served in elective office in the town and seemed to be a progressive force in the politics of the town. Their dedication to working the land did not necessarily mean their politics were traditional as they were elected to a Town Council manager system of government which was the first in the state of Connecticut.
