## Alfred Plant {-}

*Originally appeared in West Hartford Life, May 2012*

On April 20, 1921, businessman and community leader Alfred E. Plant died at age 48. Within three weeks, the Board of Education, of which he had been a part for at least 11 years, decided to name the new junior high school after him.

When the school board voted to name the new Junior High Building after him, they cited his “faithful service as a member of the board...” and that “his interest in the welfare of the schools was unfailing and the action by the school board will meet with general favor by the residents of the town.” Plant Junior High opened in 1922 as one of the first junior high schools in the state.

Alfred E. Plant was born in 1873 in the northwestern part of England. His hometown Macclesfield, was most known for manufacturing silk. At age 23, Plant married Hannah Grimshaw and six years later in 1902, they emigrated from England to Hartford.

Plant got a job at Aetna in that year. He joined the Accident and Liability Department when it was formed and at his early death, was one of its oldest members. He served as secretary to two successive vice presidents of the company. Plant was an insurance man on the ground floor of Hartford’s growth as the insurance capital. Plant moved to the United States during the Progressive Era when reformers began to question the power of industrial capitalists. This new Aetna department handled the new business of employers’ liability and workmen’s compensation insurance.

As Plant settled into town, he got involved in community activities. By 1909, Plant was elected secretary of the West Hartford Republican Party. Republicans controlled the politics of the town in the Progressive Era. Republicans were the party of Lincoln and Theodore Roosevelt and a party that had begun to regulate business to protect consumers.

He joined the First Congregational Church in the town’s center and by 1911 was a leader in the Men and Religion Forward Movement, an attempt by men across the country to increase the number of male churchgoers. Plant ran monthly meetings that attracted more than 60 men from around town. The minister of the First Congregational Church Rev. T. M. Hodgdon spoke and the West Hartford Glee Club sang to attract men back to the fold.

Plant also served as a master of Wyllys Lodge, No. 99 and was a charter member of the Syria Grotto. Masons founded West Hartford’s Wyllys Lodge in 1866. The Masons were a fraternal organization with their roots in 18th century England. Before the Masonic Temple was built on South Main Street just South of Farmington Avenue, they met in the old high school building on North Main Street near the Old Burial Ground. When Plant died, plans were in the works to build the new Temple that opened in 1923.

Plant served his community as an appointed member of the Town School Committee. He quickly became the clerk/secretary and served until his death. In the 1910s when the population grew from 5,000 to 9,000 over the decade, the school population grew just as fast. From 1915 with a school population of 1,350 to 1925 with a school population of 3,250, the school committee was busy. Superintendent William Hall oversaw the building of eight new buildings over this period of time. School committee members sat on committees, which dealt with the nuts and bolts of supplies and the library, as only a few people worked for pay in the central office.

In 1911, Plant and his wife bought a lot and built a home on the outskirts of the center on Pleasant Street, off Farmington Avenue halfway between Main Street and Mountain Road. They raised their son and two daughters there. In 1918 during World War I, their son Alfred G. Plant enlisted in the Army. The son continued to live in West Hartford after his father died and had a long career at the Aetna.

Plant’s death at age 48 left his widow Hannah and three children just coming to adulthood. His commitment to his community clear, the school committee named the new school after him.

Fifty-seven years later, when Plant Junior High closed in 1979, the PTO moved to re-name King Philip Junior High after Alfred Plant, but those efforts did not come to fruition.

It took over three years for the town to decide what to do with the school after it closed. But, in October 1982 after a 41-month discussion, the U.S. Department of Housing and Urban Development approved a grant of $6 million for the West Hartford Housing Authority to develop 100 low-income units for the poor.

The West Hartford Housing Authority formed as a non-profit in 1942 when the town, funded by the federal government, built 300 housing units for defense workers during World War II. The housing authority manages and rehabilitates affordable housing and develops and operates programs for low-income residents.

In 1982, the average family income in town stood at $30,000, giving West Hartford a reputation of being wealthy. Average home prices were about $80,000. But almost 30 percent of the 61,000 residents were older than 60. In 1982, second to Hartford, West Hartford had the most elderly poor in the region. Almost 800 West Hartford residents lived on less than $6,000 a year.

In 1982, there were three places in West Hartford where the poor elderly could live: privately owned Federation Square with 85 units, and the publicly owned Fellowship Housing with 170 units and Elm Grove housing with 40 units.

Over the next six years, builders reconfigured the junior high into housing for the elderly and those with disabilities. Federal, state, and local dignitaries dedicated the new facility in January 1986.

In April 2012, officials re-christened the Alfred E. Plant Building with 42 new housing units added to the original 95. The Plant project began in the fall of 2010 with a price tag of $21 million. Alfred E. Plant would be proud.

West Hartford governments have long named their public places after local people. Kennedy and Eisenhower Parks aside, local names adorn the schools, parks and public buildings of the town. Knowing the history behind the names reinforces the civic engagement of West Hartford residents; our citizens argue it is this engagement that makes our town so vibrant.
