## Mary Beach’s trip to the Mediterranean {-}

*Originally appeared in West Hartford Life, August 2001*

Just back from a classical tour of Greece, I was fascinated to reach back in the files of the Noah Webster House and find Mary Beach’s 102-page diary of a tour she took in the Mediterranean in early 1912. Mary, born in 1858, was the third of three daughters and two sons of Charles M. Beach, a Hartford merchant in dyes and chemicals and a gentleman farmer in West Hartford.

Mary’s ability to take a three-month trip to Europe in 1912 at age 54, rested to a great degree on the business accomplishments of her father. Charles M. Beach’s success allowed him to move to West Hartford in 1859 when he bought the land on the northeast corner of New Britain Avenue and South Main Street, stretching east to Quaker Lane. He established a farm, run scientifically, that produced the first sterilized cow’s milk suitable for babies, called “babies’ milk.” Charles M.’s success on Vine Hill Farm in business and agriculture led to a very comfortable life for him and his family.

Mary took her first trip to Europe at age 20, in 1878. Though we have no written record from this trip, her 1912 diary notes that she was at Solfaterra, Italy at the site of an active volcano which she found “much more wonderful than when I was here 34 yrs. ago – and even more scary!” Her trip at age 20 was part of a new movement among the upper class to send daughters on the grand tour to complete their education.

![Mary Beach’s diary entry of February 22, 1912 describes her visit to Cairo -- which she found depressing. She tells of visiting the mummies of Rameses II and a drive along the side of the Nile with views of the Pyramids. She describes riding a camel for the first time. Source: Noah Webster House & West Hartford Historical Society.](images/05-mary-beach-diary.jpg)

We often think that “in the old days” people were not as mobile as we are today with airplanes, busses, and high-speed ferries, but Mary’s trip from January 10 to April 30, 1912 constituted a grand tour of the Mediterranean, the envy of any modern traveler.

Tourism as an industry began to appear in the United States in the late 19th century. As wealth accumulated with industrialization and people were able to separate work from family, the middle and upper classes had distinct periods of vacation time. In 1910, President Taft suggested that a vacation should be two to three months long. People agreed that the pressures of modern life necessitated an annual vacation. Spurred by paintings and photographs of the west and the growth of national parks, and the transcontinental railroad completed in 1869, travel in the United States grew into an industry.

In the two decades before World War I, an estimated 200,000 upper class Americans traveled to Europe each year. Travel agencies could be counted on to make all the necessary arrangements for transatlantic crossings and Continental tours that cost between $400 and $600. At this time, an average male factory worker made, at most, $1,000 per year.

Mary Beach’s trip began in New York City on January 10, 1912 aboard the SS Adriatic. She traveled with a group that included her sisters Edith and Frances. After nine days on the Atlantic, they arrived in the Azores where she was “delighted with the quaint town –- so clean & fresh & yet so mediaeval with many town street gates and arches, & elaborate stucco doorways.”

The group then went to Madeira, Gibraltar, Algiers, Nice, Genoa, Naples, Cairo and the Aswan Dam, Jerusalem, Constantinople, Athens, Corinth, Naples, Pompeii, Amalfi, Sorrento, Rome (at Easter), and northern Italy before returning home after a full three months.

Mary’s trip, like those in the 21st century, included sightseeing, shopping, and learning. When she left Egypt, she noted, “None of us cared for Alexandria nor for Port Said, except that at the latter shopping was good and reasonable.”

At Constantinople, Mary noted that at the Hippodrome she saw a “broken twisted bronze column, which once supported the famous tripod of the Priestess of Delphi of which Miss Hamilton [Edith Hamilton’s *Mythology*] had told me when I was a child of 8 or 9.” Mary’s classical education was reinforced by her travel.

On trips like Mary’s, the sites were important, but the dynamics of the group also added to the trip. “The next morning March 8 we reached Piraeus and just after lunch E.B. (Edith, her sister) and I took a run up to Athens and photographed the Acropolis from the street on the further side. Had not time to climb. On my return I bought Mr. O. a 3p. box of matches with a picture on it of the Acropolis, etc. and found he had bought me a jar of honey from Hymettus (strained) which is very delicate and yet highly flavored and which we are greatly enjoying. It is not overrated at all. Thought continually of F.B. White and his love of the place.” Traveling provided a milieu in which to build relationships, which she might not have back home.

On returning to Athens after visiting Constantinople, the tour took them to the Acropolis as well as to the countryside. Mary was interested in both antiquities and the present day situation in Greece. Upon arriving, she wrote “Drove this morning & saw modern Athens with its handsome public building copying the ancient style; one of the finest cities we have seen, Byron’s monument, the beautiful modern stadium (for the 1896 Olympics).” She noted the ongoing archaeological work: “excavations are begun on the Roman market place [next] to the Forum which are to extend to the base of the Acropolis and to be turned into a public park. The Archaeological Soc. have both and expect to pull down all the modern houses (all of a humble sort) in this portion of the city to carry out this place.”

She also noted the quaintness of what she considered traditional life. “On the edge of the sea, we saw a most picturesque sight of a peasant and his wife and daughters with a large herd of goats, sheep, 2 donkeys and sheep herder dogs. The man with his short petticoats, the woman and girls with crooks and yellow handkerchiefs, trying to make a goat give its newborn twin kids their dinner. We tumbled out of the carriage and tried to get photos. The family were very fine & noble looking, with attractive manners, at first even refusing the money we offered after posing for us. We were delighted with them.”

Mary Beach’s tour must have made West Hartford look new and small when she returned. The town had about 5,000 people and was becoming more of a suburb, but its oldest buildings were but 250 years old. She did not feel that she would keep up with any of the “fellow travelers” in her group when she got home, but her outlook on the world must have been altered by these three months.

In the past 50 years, travel has been democratized by being more accessible to more of the population, but trips like that of Mary Beach in 1878 and 1912 set a standard for vacations and tourism.
