## Historic Homes: Developing a Sense of Community {-}

*Originally appeared in West Hartford Life, September 2005*

In our fast-moving world, the permanence of our architecture inspires us to discover our sense of place. By observing houses in town, we can gain a better sense of our cultural roots, the history of the town and our human-made environment.

Homes are prized by the families who live in them; visiting them can provide us a direct connection to the past.

The Noah Webster House’s first historic house tour on September 17, 2005 will give us that chance. Five homes in the south end of town will be open to the public, three built in the colonial period, one in 1847 and one in 1900. Each provides a glimpse into the history of the town, the craftsmanship of architectural detail, and daily life in another time and place.

The first two houses on the tour are owned by the town: the Sarah Whitman Hooker House at 1237 New Britain Avenue, built in 1735, and the Noah Webster House and West Hartford Historical Society at 227 South Main Street, built in 1747.

The Sarah Whitman Hooker House was originally built in the 1720s and served both as a tavern and residence in the 18th, 19th, and 20th centuries. The house has been renovated several times and its restoration in the last 30 years reflects the lives of those who lived inside.

Recently the house has been in the news with the naming of the new middle school after an enslaved man Bristow who bought his freedom in 1775 from the owners of the house, Thomas Hart and Sarah Whitman Hooker. Hooker’s house was also used as a prison for Tories during the American Revolution.

In 1807 Sarah Whitman Hooker added on to the house and the changes were made in the Georgian style of architecture. The central chimney was taken out and two chimneys were put in, producing a central hallway with two rooms on each side. The roof was rebuilt to add a full second floor. This house has been restored to a time period in the late 18th and early 19th centuries. On the house tour, you will be invited into the first floor.

The Noah Webster House is restored to the year 1774 and represents a classic two-over-two colonial saltbox. In the 18th century the Websters owned 80 acres of land stretching west down the hill from Main Street.

Though only a few of the present furnishings actually belonged to Noah, the house has period furniture which shows the difference in lifestyle 230 years ago. In this house, compare the “new” lean-to kitchen and fireplace from the late 18th century, which was built to save on wood and heat, to the original. Notice how the furniture is moveable and how rooms served more and different purposes than they do today. The new reproduction kitchen allows the museum to continue to be a hands-on museum without further endangering the original house.

The third house, and one of the three private homes to be opened, is the Benjamin Colton House at 25 Sedgwick Road, built in 1769. This was built by the son of the second minister of the West Division. Reverend Colton was the minister of the first church in the West Division from 1713-1759. His first son George and grandsons Chester and George became ministers in other Connecticut towns.

In the early 20th century, the Scarboroughs lived in the house. Clarence Scarborough served in World War I and kept the salutation “colonel” throughout his life. Note the setting of the house and imagine how the number of houses and farmland changed, particularly in the early 20th century.

Residents of this home led the opposition to the building of the proposed Frank Lloyd Wright Theater on the corner of South Main Street and Sedgwick Road in the early 1950s.

The fourth house is the Buckley-Coffing House, 272 South Main Street, built in 1847. It has 11 rooms, six fireplaces and an eclectic architectural style. This house is one of the few remaining mid-19th century farmhouses in town.

The town’s population of about 1,000 in 1774 grew to only about 1,200 in 1854; not that many houses were built in those 75 years. This is a vernacular farmhouse with elements of Greek Revival and Italianate style.

George Buckley sold the house to Charles Coffing in 1863. Coffing’s son inherited the house two years later. The property was still run as a farm until it was subdivided in the 1930s and then Webster HIll School was built behind it in the late 1940s.

The newest house on the tour is the Charles E. Beach House at 18 Brightwood Lane, built from 1901 to 1902. In 1859 his father, Charles M. Beach, the owner of a chemical and dye company in Hartford, bought a piece of land on the northeast corner of New Britain Avenue and South Main Street. He added to the property and became a gentleman farmer, developing a herd of high-grade cows on his Vine Hill Farm.

These cows produced some of the first sterilized baby’s milk. One of his sons, Charles E. Beach, managed the farm. Beach was a civil engineer who did all the surveying and engineering work for the town.

Beach was elected to the board of selectmen and was elected as a Democratic representative to the General Assembly, possibly the first Democrat ever from the town.

Charles M. Beach built a shingle style 20-room house with three stories, multiple dormers, balconies and seven fireplaces. The first floor of the home, which will be open in the house tour, includes seven ornamental woods and remarkable wood craftsmanship.

There are at most 20 shingle-style homes in town and this home has not been altered much from when it was built more than 100 years ago. You will notice two other Beach-built homes as you drive on Brightwood Lane.

Look at the view into Hartford and imagine owning all four corners of New Britain Avenue and South Main, and the property down to South Quaker Lane, including Beachland Park.

Sir Winston Churchill said “we shape our buildings and then our buildings shape us.” This local house tour is a chance to take a look not only at the physical structures and styles of the human-made environment, but it can also help us wonder how people more than 200 years ago lived their daily lives and developed their sense of community.

The tour will run from noon to 4 p.m. and the cost is $20. Stop at all five houses or choose the ones you want to see. Refreshments will be served at the Noah Webster House.
