## The Site that Became Blue Back Square {-}

*Originally appeared in West Hartford Life, December 2007*

Noah Webster’s statue, complete with a new finger, is repositioned in the town’s center and the three square blocks that are Blue Back Square have come to life in a mix of retail, restaurants, office space and housing. It is already difficult to remember what used to be in these lots. A look back 100 years gives a window into how much and how often land use changes.

Blue Back Square occupies twenty acres with 200,000 square feet of retail space, 200,000 square feet of office space, two parking garages with about 1,000 spaces, apartments, condominiums, a renovated public library, and a passive public park on the southeast corner of Raymond and Memorial Drives. Just two years ago, it included the Grody car dealership, which was a toxic site, three 3-family houses, the Hayes-Velhage American Legion post, a town parking lot, the Board of Education building, and green space.

![Hayes-Velage American Legion Hall sat at the corner of Raymond Road and Memorial Drive. It was one of the casualties of Blue Back Square when it was taken down in 2005 for the new development. Both Hayes and Velhage died in World War I. Grody Chevrolet car dealership appears behind on Raymond Road. Source: Noah Webster House & West Hartford Historical Society.](images/05-blue-back-legion.jpg)

When the developers and the Town of West Hartford first put together their development plans, Blue Back’s 20 acres were taxed at a value of $3.5 million. Completed, the developers believed the market value would reach $110 million. Already by 2006, Blue Back became the single largest taxpayer in town.

How else has this site changed in a century? A look at the *Atlas of the City of Hartford, Connecticut, including, also, the town of West Hartford*, 1896 and 1909 shows the plot of land which is now Blue Back Square. You can go online to the West Hartford Public Library site, click on Local History, then [West Hartford Historical Maps](http://www.westhartfordlibrary.org/services/local_history/historical_maps.asp).

On the edge of Goodman Green, on the land which is now the public library, was the Masonic Hall. The Masonic Hall is now on the west side of Goodman Green. South of the Masonic Hall was W.A. Burr’s Carriage Repository & Hardware Store. What is now Memorial Drive was a road with no name. On the site of the present Hartford Hospital and New York Sports Club building stood the town’s second Center School, built in 1896. Until this school was built, high school students attended the first Center School at 14 North Main Street

In 1896, at the site of the present Town Hall, there were four residences: Mrs. Margaret W. Seyms, Mrs. Charles Cain, and J. P. Oviatt all who had houses made of wood. Mrs. Seyms had four out buildings on her property. Asher Rogers owned a very small plot and small house, carved out of the lot of the Oviatt’s. W.A. Burr owned the land on the southside of the block bounded on the south by what is now Burr Street. In 1896, the land was subdivided, with no houses yet built.

Not too much changed on this block in the next 13 years even though West Hartford’s population nearly tripled from around 1,800 to about 4,800 by 1909. The buildings and owners showed continuity. On the southeast edge of Goodman Green stood the Masonic Hall and W.A. Burr’s Carriage and Hardware Store remained. The town added another brick building to the schoolyard at the corner of Raymond Road and School Street (now Memorial Drive). High and elementary school students shared the new school building until 1910 when the high school took over the whole Center School building and the elementary school children went into the new Whitman School built right next door. This building appeared on the 1909 map. This site now includes the parking garage, the condominiums and the Hartford Hospital building.

In 1924, the new high school, named after William H. Hall opened on the west side of the block right along South Main Street. The Center School became known as the Rutherford Building and was kept as a town building and in the 1940s and 1950s served as an annex for Hall High. Take a look at the name of the Hartford Hospital building in Blue Back Square – over the main entrance appears the name “Rutherford Building.”

W.A. Burr continued to own the south side of the block. The Seyms property had been transferred from Margaret to G. H. Seyms. Three of the outbuildings were subdivided into two separate lots. C.F. Scarborough owned the Cain property. There were three buildings on his property. John Gridley purchased the Asher Rogers house and lot. Along Burr Street, three houses were built and there were owners for six of the 11 subdivided lots.

In 1936, the town used federal funds provided through the PWA to build both the Noah Webster Library and the Town Hall. The library, built in 1918 on the corner of North Main and Brace Road, lasted only 18 years. The new Town Hall building replaced the third building of First Congregational Church which stood at the site of the Veteran’s Memorial. The Town Hall, with its grand gold cupola, served that purpose from 1936 until 1987 when the former Hall High was renovated and the town offices moved there. At the same time, the town sold its education building on Steele Road and the education offices moved into the former Town Hall. As the town tried to consolidate its services, and with the push of the Blue Back Square developers, the education offices moved into the Town Hall in 2006. The old Town Hall serves as Fleming’s Steak House and the Bow Tie Cinemas.

Those who have visited Blue Back Square, will recognize the familiar Noah Webster statue and the cupola and front entrance on a new building at the site of the old Town Hall. The four and five story buildings down the hill give the new three-block area a very different feel. The streets are alive with shoppers and workers and a new Rutherford Building replaces one on the same site named over 80 years ago. The change seems drastic when you stand at the corner of Memorial and Isham Roads. Do you think the sense of loss and gain match what people thought 70 years ago when the library and town hall replaced Burr’s Carriage and Hardware Store?
