## American School for the Deaf {-}

*Originally appeared in West Hartford Life, October 2011*

After ten years of discussions, the American School for the Deaf is razing its iconic Gallaudet Hall and erecting a new building in its place. Since 2009, the main building at the American School for the Deaf, with its 175,000 square feet of space, was limited by health and safety officials because it had deteriorated to a point where it was unsafe for students. Executive Director Ed Pelletier wants to build a new 60,000 square foot facility for $20 million that will better serve the needs of the school. Pelletier argued that rehabbing Gallaudet Hall will cost $45 million.

In 1914, officials from the American School for the Deaf began to plan the new building which became Gallaudet Hall. The buildings on Asylum Avenue in Hartford were old and not fireproof and the directors of the school worried about getting students out in case of a fire. They were concerned about the mobility of the “defective children” who could not hear.

When they looked for a new site, they wanted it to be big enough to teach the boys how to farm, which according to a *Hartford Courant* article in November 1920, was a “vocation which as deaf mutes, they were most fitted to follow.”

On August 4, 1917, officials from the American School for the Deaf recorded the transfer of 92 acres of land on North Main Street just north of Fern Street for $30,000. On May 10, 1918, the *Hartford Courant* reported that the school would not move from its 690 Asylum Avenue (where Asylum and Farmington split) location until after the Great War ended.

When the land was bought in 1917, the directors estimated it would cost $350,000 to build the new building, based on labor and building conditions. They planned to build it for 200 students.

On March 12, 1919, representatives of ASD in Hartford appeared before the Appropriations Committee to get their support for $300,000 to build the Hall. The American School for the Deaf was incorporated in 1816 after a petition signed by 63 citizens made its way to the legislature. In 1816, the state gave the school $5,000. The school opened in 1817 with seven students and became the first permanent school for the deaf in the United States. In 1819, Congress gave ASD 22,000 acres of land, which they sold to build the school on Asylum Avenue. The original building was completed in 1821. At its original site, the school was “in the country.” But by 1919, it was surrounded by buildings. The school planned to sell its building and land in Hartford, to build Gallaudet Hall at an estimated cost of $500,000. According to Trinity Professor Henry A. Perkins, who was President of ASD, “the present ones [buildings] are antiquated, the new buildings will be fireproof. Other states will probably withdraw their pupils as they build schools of their own,” if the state would not appropriate the money.

On May 13, 1919, Governor Marcus Holcomb signed a bill to provide $250,000 to build the school and to equip it. Two days later, the Hartford Fire Insurance Company bought the Asylum Avenue building from ASD directors for $250,000. Hartford Fire planned to raze the building within four months.

When the state appropriated the $250,000 for building the new school, they had to approve the plans that included a fireproof brick building, with a “maximum of light and convenience.” According to Professor Perkins from Trinity who was chair of the ASD Board, the “new building will be of attractive appearance, although it will not be ornamental to any great extent.” The architectural firm Isaac A. Allen, Inc. of Hartford designed a colonial style building. It set a trend for the buildings later built in the center of town including Hall High School, which is the present town hall building built in 1924, the Town Hall and Noah Webster Library built in the mid 1930s and the First Congregational Church built in the 1940s.

The cornerstone was laid on July 22, 1920. As they built the building, right at the end of World War I, they had much difficulty getting materials. Tile ordered in June 1919 arrived 10 months later. In March 1921, the trustees asked the legislature for an additional $100,000 because of cost overruns.

The building committee wanted the new building to be “substantial, durable, and reasonably attractive.” The architects planned for an imposing three-storied administration building with 286 feet frontage, and 40-foot depth. The two wings of three stories held classroom buildings and the south wing had a covered passageway to connect it to a separate building for the primary grades. Attached to the north wing were the heating plant, boilers, workshops, and laundry. The structure included two grassy courtyards between the two wings of the main building, which separated the dining room. The kitchen was built as a separate building. The administrative building had a reception room, executive offices, library, 11 classrooms, a club room (one for girls and one for boys), locker rooms, and toilet facilities.

The second floor included 14 classrooms, a study hall for girls and one for boys, a room for a supervisor and a matron, and the girls’ dorms in the south and the boys’ dorms in the north wing. The assembly hall over the dining hall was two stories, had a stage, was set up to show movies, and could seat 250 people. Above the kitchen were “women servants’” quarters.

On the third floor was an infirmary, and living quarters for nurses and attendants. It included an art room, three sewing rooms, a room for a cooking class, and six more dorm rooms for teachers or students.

In March 22, 1922, Governor Templeton dedicated the buildings which served the school well for almost 90 years.

In 2011, architect Tai Soo Kim will design the new building which will be located to the east of Gallaudet Hall. When it is completed, Gallaudet Hall will be taken down and architects and landscapers will design a quad in between the new building and the gym. The cupola from Gallaudet Hall will sit in the middle of this quad.

For members of the ASD community, the decision to raze Gallaudet Hall has been long and agonizing. But the realities of the 21st century technology and the changes in ASD students have led them to this decision.

When Gallaudet Hall was built in 1921, most of the students who attended the school became deaf after they learned language. In the 21st century, almost all ASD students are born deaf with multiple obstacles to learning added onto their deafness. This new building will be able to serve these students more effectively.
