## Women Win the Right to Vote {-}

*Originally appeared in West Hartford Life, January 2010*

On November 12, 1920, just after the first national election in which all United States women had the right to vote, Katherine Ludington, President of the Connecticut Woman Suffrage Association spoke at a meeting commemorating 50 years of activism. With the national suffrage amendment just three months old, she proclaimed “not paper imitations of citizens but women of purpose and practical information will be the result of the citizenship campaign the association is to conduct.” She proclaimed that the CWSA would build a state organization that would be a “non-partisan civic organization—a league of women voters.”

West Hartford women in the late 1910s and 1920s got involved in the Connecticut Woman Suffrage Association and the newly formed League. West Hartford was a rapidly developing suburban town of about 9,000 people, the population almost doubling in the previous World War I decade. Many of the families who moved from Hartford to West Hartford during this time period held white-collar jobs at Hartford’s growing insurance companies.

West Hartford’s Mary S. Deming held leadership roles in the suffrage movement and the League of Women Voters and ran for election to West Hartford’s new Town Council in 1922. Like most women involved in women’s rights, she took her role as citizen seriously, and got involved in many different issues between 1918 and 1922.

Mary E. Smith married William Deming sometime between 1916 and 1918. William became a secretary of Connecticut Mutual Life Insurance Company in 1906 at age 49. He had been employed since 1875 when he first got a job, straight from high school, as a clerk. He belonged to the Hartford Golf Club, the Hartford Club, the Twentieth Century Club, the Republican Club, and the Hartford Yacht Club. His first wife died in 1909 of typhoid fever at age 52 at their summer home in Sachem’s Head, Guilford. He owned a home at 47 Highland Street in West Hartford.

Mary Deming’s first mention in the *Hartford Courant* is on July 30, 1918, 14 months after the United States entered World War I. She was in charge of enrolling the first group of women as nurses to enlist at Liberty College in Hartford’s City Hall Square. The *Hartford Courant* noted that some women were married, most were employed, and the women represented many ethnic and socio-economic groups. Deming was in charge of the booth that recruited the nurses.

When the United States entered World War I, suffragists around the country wondered if they should jump into the war effort if they themselves were denied the rights of citizenship. In Connecticut, the great majority of women involved in the suffrage movement believed that their aid in the war effort would help change President Woodrow Wilson’s mind about woman suffrage and speed along the movement. Deming knew that citizenship included more than the vote and she jumped into the war effort at the very start.

In April 1919, Mary Deming appeared in a *Hartford Courant* photograph with eleven other women as one of the “Suffrage Workers for Liberty Loan.” Even after the war ended in November 1918, the federal government needed to borrow money from its citizens to pay for the war through the sale of liberty bonds.

In January 1919, the Social and Personal section of the *Courant* showed Mrs. Deming resuming her Monday, Wednesday Friday Red Cross classes in First Aid. Her interest in health was useful during wartime.

Mary S. Deming, also written about as Mrs. William H. Deming, was involved in the leadership of the suffrage movement. She led fundraising in Hartford County and raised $100,000 in May 1919. The point of the campaign was to raise money for citizenship work and public services to be offered by the Connecticut Woman Suffrage Association. Many men and women not actively involved in the suffrage movement jumped in to help out. Deming helped to formulate the campaign that sought subscriptions from individuals from every community in the state during the second week of June 1919. Team captains reported daily on their progress. She helped organize each county for the work. This type of grassroots campaigning continues to mark the work of the League of Women Voters.

Right after this campaign, Mr. Deming died at the end of June 1919. He was 61 years old. Mary, now a widow, continued her political work.

When women won the right to vote in August 1920, Mary continued her political work. She moved, as most women did, to affiliate with the League of Women Voters. She became chair of the Legislative Committee, and spent much time at the state capitol, following bills through hearings. Authors Nicholas Kristoff and Shirley WuDunn in their new book, *Half the Sky* (2009), argue that the woman’s right to vote, led to a elected officials paying attention to their new female constituents. They particularly point to the passage of the Shepard-Towner Act (1922) for maternal and infant care as part of their evidence.

Deming was part of these new voters. On March 18, 1922, she wrote a letter to the *Hartford Courant* in support of the Shepard-Towner Bill, which would provide federal moneys for maternal and infant health. The *Courant*, a Republican newspaper, opposed the Act, worried about federal intrusion into what they considered to be a local issue. Deming countered by using statistics that 200,000 babies died in 1919 in the United States and 20,000 mothers died in childbirth. She called this a “national disgrace.” The United States ranked 7th among 20 developed nations in the death rate of children under one and 17th on the list of maternal mortality.

Deming countered the *Courant* editors’ fear of federal aid saying that it was a 50:50 proposition with the federal government and state governments splitting the cost. She argued that the *Courant* supported the Good Roads Act under which Connecticut accepted over two million dollars for good roads, and she believed that the state should be willing to accept money for maternal and infant health. Connecticut stood to gain $45,000 for maternal and infant health over the period of two years. She assured readers that a state agency would administer the act.

Later in 1922, Deming and one other women were candidates running for Town Council. According to the *Courant*, “she has been interested in politics for some time and attended sessions of the Legislature as chairman of the legislative committee of the League of Women Voters.” Though neither woman won, they exercised their rights as a citizen in getting in the race. Like the first women who were finally elected in West Hartford in the 1960s, her League experience pushed her to take part in the public world.

The League of Women Voters of Greater Hartford has been working feverishly over the past six months to put together a display on the 90-year history of the Connecticut League since it began November 1920. Go visit the Legislative Office Building in the month of January 2010 and you will learn how the League defined active citizenship. The Greater Hartford Chapter has been active over the past 90 years. They work to be sure that women do not just exercise their right of citizenship at the ballot box. They work to insure that voters, both men and women, are informed, run for office, and lobby their representatives. Their issues change with the times, but their bipartisan movement, remains to make people good citizens and make sure government is of, by, and for the people. Look at Mary Deming’s example 90 years ago.
