## West Hartford and World War I {-}

*Originally appeared in Joseph M. Donahue, The Connecticut Veterans Memorial West Hartford (2006).*

Of the 314 West Hartford citizens who fought in World War I, 292 made it back home. Twenty-two men died according to the war memorial on the east side of the West Hartford Town Hall.

The United States likes to believe it played a pivotal role in the Great War. U.S. casualties equaled about one percent of the 10 million killed during the war. Testimony to the small sacrifice Americans paid compared to the British, French, Russians, and Germans is that the first West Hartford man died in battle on October 4, 1918 just five weeks before the five year war ended. Statistics on 14 casualties reveal that three men died in September, eight in November, and three in March of 1919. Of the 14, only four died of battle wounds.

In 1918, West Hartford had a population of about 8,000 people. About 15 percent of the men in town served in the war. The first call for men to sign up for the draft, required men between the ages of 22 and 35 to report. When the government asked, in September 1918 for men to register for the draft, it called for all men between the ages of 18 and 46. In West Hartford, at the Town Hall, then located in the old Congregational Church building on the northwest corner of Main and Farmington Avenue, they had three interpreters there to translate in French, Swedish and Italian.

The West Hartford men who went off to “keep the world safe for democracy” were a mixed bunch and reflected the diversity of the town over 80 years ago. One young man who served, Pietro Bradinini, arrived in France on October 4, 1918 and served in the motor corps. Both Adolphe Brodeur and Rudolf Krieger probably fought against former countrymen from Germany. The October 22, 1918 meeting minutes of West Hartford’s War Bureau reported that F.S. Echols of Walbridge Road, a neighborhood with larger homes in the east end was killed in battle. Frank Velhage, whose family owned a farm near the present day Charter Oak School was the son of French Canadian immigrants. Today the American Legion Hall is named after him. Clarence Scarborough also served in the war. His parents lived in the colonial Colton house on Sedgwick Road not too far from South Main Street.

![The Noah Webster House & West Hartford Historical Society retains a file of all people who fought in World War I. Sgt. Adolphe Brodeur was called back from the Mexican border, fighting Pancho Villa, to enter the fighting in the Great War. He saw fighting at Chateau Thierry, St. Mihiel, and Meuse Argonne. He was gassed on November 1, 1918 and found to be 10 percent disabled by the government. Source: Noah Webster House & West Hartford Historical Society, World War I Collection.](images/06-brodeur-web.jpg)

Walter O. Korder, the artist who painted the history mural in the Old Hall High Library, the nursery rhymes at Charter Oak, and the portrait of Frederick U. Conard, in Conard’s library, also served in World War I.

World War I was the first to allow women to officially serve in the military. Four women from West Hartford served: Ida Butler, Dorothy Dressler Carpenter, Beatrice Cook, and Mary Rees. After six months of training in New Haven and Boston, Carpenter served as a Reconstruction aide at Fort Dix in New Jersey, helping amputees in 1919 re-adjust to civilian life.

Making the world safe for democracy led to a draft which is not so democratic. President Wilson ran on a platform of keeping us out of war. But when the time came, he got the Office of War Information going to convince men that they should sign up. This draft, unlike that of the Civil War, did not allow men to buy substitutes. People of all economic strata had to sacrifice for the greater good, as defined by the wartime government.
