## Edith Beach’s Influence on West Hartford {-}

*Originally appeared in West Hartford Life, April 2008*

Edith Beach, aged 54, is listed in the 1910 U.S. Census with an occupation of “none.” This is not too surprising for an upper class woman at the turn of the 20th century, but for a historian, this word masks the life of Beach and many women like her who had an impact on their community.

Edith’s father, Charles Beach, was the head of West Hartford’s Red Cross War Bureau during the Great War from 1917 to 1918. Beach led a committee of about 20 people and the group coordinated volunteer activities, sent condolences to families who lost young men in service and ran the Liberty Loan campaigns to get people to buy bonds to support the war effort.

In the October 22, 1918 War Bureau meeting minutes, the committee voted for Miss Edith Beach and Miss Mary Beach to be “made members of the War Bureau.” The Misses Beach, including their sister Frances, had run a “French Market” at the Vine Hill Farm on October 12 which attracted 1,180 people and raised $56,938.62 (equivalent to about $1 million today). Getting a thousand people out of a population of about 6,500 and raising about $9 per West Hartford resident seemed to be quite a feat.

![West Hartford’s French Market, organized by Edith Beach and her sisters Mary and Frances, answered the call from President Wilson for a Columbus Day patriotic celebration and to raise funds by selling bonds for the “Fourth Liberty Loan Drive.” The market ran from noon to 9 p.m. on October 12. Beach wrote that this Market “demonstrates the adaptability of women to a class of work which has heretofore been monopolized by men.” Source: Noah Webster House & West Hartford Historical Society.](images/06-edith-beach.jpg)

What attracted people to the farm and how did Edith Beach come to run the French Market?

Charles Beach first bought land in West Hartford 1859. The head of Beach Brothers Company, a chemical and dye making company in Hartford, Beach summered in a house on South Main Street just northeast of New Britain Avenue. He built one of the biggest dairy farms in Connecticut after buying out six farms on the four corners of New Britain Avenue and South Main. He owned clear down to Trout Brook.

Charles Beach hired Frank Stadtmueller to run the farm. They produced “baby’s milk” with over 200 cows, by cleaning up the farm, the cows, the barns, the tools, and the milk pails. “Baby’s milk” was shipped in bottles by train all over and gave Vine Hill its reputation. More than 30 men worked on the farm in its heyday before the Great War, taking care of the cows and the 12 work horses, working the grist mill, bottling milk, making cream and butter, cutting ice from the pond, and working in the blacksmith shop. Many of these men boarded in what is now the Sarah Whitman Hooker House museum on the southeast corner of New Britain and Main.

After Charles Beach died in 1910, and with the build up to the Great War, production on the farm declined. Farm hands became factory workers, Bloomfield’s Woodford Farm took over production of baby’s milk, and production declined.

In 1910, Edith, her two sisters, her brother Charles Beach and his two children, an Irish servant and a German servant all lived in the huge house their father built, now situated on Brightwood Lane. It is in this context that Edith organized the French Market.

Up until this time, she had been involved in many activities acceptable to upper class women. She and her sisters never married, but did help raise their nephews as their sister-in-law died in childbirth. Edith tutored young Teddy and took him on drives through town. She took driving lessons in 1905 and was one of the first women in West Hartford to own a car.

Her daily diary serves as more of a chronicle than a reflective journal, but a day in January 1902 included luncheon with Mrs. Washburn and Mrs. Bingham, framing photographs she had taken, sewing and working on a stole. On that day she received letters from Bishop Donne and Mrs. Elizabeth Colt. She also wrote a report to the newspapers on the work of the Visiting Nurses, a group for which she gave many volunteer hours.

When President Wilson called for towns to raise money for the Liberty Loan and Red Cross Drives, Edith Beach was there to help. In May 1918, she and 75 West Hartford women organized a drive to raise $10,000 for the Second Red Cross War Fund. The campaign kicked off on May 20th with an automobile parade through the principal residential portion of the town. The cars were decorated with the “Stars and Stripes,” the colors of the Allied Countries and with Red Cross banners. Even though the wealthy East Side of town was rolled into the Hartford campaign, the women still believed they could make their goal.

On Monday, Tuesday, and Wednesday, the 75 women, divided into 14 teams, each headed by a woman who owned a car, canvassed every home in town. With a population of 6,500, they got 2,400 pledges and contributions. They raised $12,100, going 21% over their goal. Those who reported on the drive believed that the “percentage to total residents equal, if not better, than any town in the country.”

Their unparalleled success was most likely helped by the passage of the Sedition and Espionage Acts in 1917 and 1918. These laws allowed officials to arrest people who spoke out against the war. Perhaps refusing to buy bonds could be construed as an anti-war stance.

When Edith organized the French Market in October 1918, she was responding to President Woodrow Wilson’s call for a Columbus Day patriotic celebration, and his call for bond money to give to “Food for France” and to the Fourth Liberty Loan Drive.

Edith borrowed the strategy of the summer drive and divided the town into 11 sections and her teams led a canvass of every house in town. The canvassers sold tickets to the French Market for 25 cents each and asked for donations to the market which included canned goods, preserves, a pig, and fruit.

At the market, the Beaches set up 12 booths with the donated articles. They arranged for seven speakers, five of whom were soldiers, and a nine-piece band.

Vine Hill Farm was transformed to look like a French Market. The automobile corps transported people to the market. Edith Beach led the drive with 86 women volunteering to help.

The highpoint of the afternoon was a pageant known as the Marseillaise Battalion. There on the corner of Main and New Britain Avenue, Beach’s friend Inez Temple produced a “dramatic incident of the French Revolution when the national anthem of the French attained its fame.”

In Beach’s write up of the drive, she wrote that the organization of the drive “is not only an interesting story but demonstrates the adaptability of women to a class of work which has heretofore been monopolized by the men.”

Beach’s activities, at age 61, put her in a public sphere that showed women’s patriotism and a role that far exceeded the delineation of “none” as found in the census. Wartime often altered the roles of men and women and the Great War was no exception. For Beach, the community building led to her running New York City’s YMCA just four years later. Historians have to wonder how much of her public activity was caused by her father’s death and how much by her own sense of independence and feminism.
