## West Hartford Women during World War I {-}

*Originally appeared in West Hartford Life, May 2001*

When the United States entered World War I, women’s role helping to win the war at home transformed the home front. Women’s domestic duties took on political overtones. Proper food preparation became a patriotic duty and domestic skills like knitting became another way to win the war. Women got the chance to publicly organize and work alongside men in ways not accepted during peacetime.

For the first time in U.S. History, women officially enlisted in the armed forces. Of the 314 West Hartford citizens who served, four were women. Ida Butler, Dorothy Dressler Carpenter, Beatrice Cook, and Mary A. Rees all served. For instance, Carpenter served as a Reconstruction Aid at Fort Dix in New Jersey in 1919 helping amputees learn how to manage in civilian life.

Most women in West Hartford participated in the war by helping the men overseas and by sacrificing on the home front. On West Hartford’s War Bureau, women used their skills in the public and private worlds. Seven of the 20 people on the committee at its first meeting November 21, 1917, were women. The Secretary, Mary Buckland, contacted all the “boys” in the service from West Hartford. She wrote a letter to each one, telling them that the Bureau would keep in touch with them and “render every possible service... ” so that “we may all have the opportunity to demonstrate to you, to the best of our ability, our deep appreciation of your sacrifice for your country and for the ones at home.”

The federal government did not impose rationing or price controls during World War I, but it did urge people to voluntarily conserve. The West Hartford War Bureau established a Conservation Committee in February 1918 to address rising prices and shortages. In February, Chairman of the committee, Mrs. Newlands, who had recently attended a State Council meeting at the Capitol, reported that the cost of yarn had skyrocketed. Members attempted to control the price by buying the yarn through the War Bureau. War Bureau members also worried about the use of gasoline by delivery trucks. The War Bureau asked merchants, like those at Burnham’s Grocery in the center of town to make just one delivery per day, saving both men and gasoline. The Conservation Committee also urged the people to “carry their own bundles” rather than expect delivery.

By October of 1918, the West Hartford Branch of the Red Cross had sewing, knitting, and surgical dressing departments. They opened their rooms every day except Saturdays from December 1917 to August 1918. From then on, they opened Tuesday and Thursday. With a total population of less than 9,000, West Hartford women produced 1,225 pairs of socks on the five knitting machines. Nearly 400 women knit by hand and made 1,143 garments during the year. Most of these items were sent to the U.S. soldiers, weathering a tough winter in northeastern France. The surgical dressing department made 52,439 dressings through July. Members of the Sewing Department operated six sewing machines and made 3,217 garments. Women at the Elmwood Library Club and the North End Auxiliary also contributed to these totals.

It seemed like the war effort reached everyone. The Civilian Relief Committee, made up of three women officers and four men on the executive committee, divided the town into nine districts. Each district had a captain and assistant workers to thoroughly canvas the town for records of all men in service in the Army or Navy. By February of 1918, the Committee collected 145 names. The workers encouraged the families to buy War Risk Insurance, the first mass sale of life insurance in U.S. History.

This canvas also helped on the Liberty Loan Drives. The United States raised one-quarter of the money needed to fight the war through selling war bonds. The government sponsored four Liberty Loan Drives. Both men and women went door to door to sell them. Children in schools bought stamps and filled their books. When they were full, they turned the books in for a bond. The Fourth Liberty Loan Drive, to begin November 11, 1918, included efforts by the YWCA, Knights of Columbus, War Camp Community Fund, Jewish Relief, Public Library, and Salvation Army.

The citizens also organized community activities to raise money for the bond drives. The Women’s Committee put together a cookbook and raised $43.75 to donate to the bond drive. For the Third Liberty Loan Drive, West Hartford had a quota of $469,000 and raised $604,000. The Chairman of the committee, W.S. Griswold, praised the Women’s Committee for its help in raising the money.

Another way women got involved in the war effort was through the Home Garden and Food Production Committee. Certain processed foods could easily be sent overseas. The federal government urged citizens to grow Liberty Gardens and can their own food so that it could maximize the amount of food sent overseas. In 1917, the Town gave $7,000 to this committee to buy a thresher and reaper to assist the farmers in town. The Connecticut agricultural extension taught classes in canning. With the advent of factory canning, many women had lost the art, but with the war, the government taught women once again how to do this. In 1917, Connecticut led all states in the union in community canning work by canning over 25,000 quarts of produce “by the community method.”

On Thanksgiving Day 1918, after Armistice Day, a directive from the State Council of Defense told people what they should eat on Thanksgiving Day. The State Council sent a directive to the public reminding them, that even though the war was over, there were 180 million people in Europe either “ground down by the iron heel of Germany” or who suffered greatly during the war. The directive urged women “to make yours a real dinner of Thanksgiving and not a feast.” They recommended that women use home-grown or Connecticut grown products, that they not to use food that could be shipped to the “hungry millions,” and they not plan more food than was “needed for a comfortable meal.” Beef, butter, sugar, and canned vegetables and fruits could all be sent overseas. Women’s civic responsibility, according to the government, was to “show these millions that they may still have confidence in America.”

The Great War, as experienced by West Hartford’s women, offered an elevated role for their domestic duties and new possibilities for public action. Historians often ask whether the changes brought by the war led to lasting changes in gender roles. Because much of the government rhetoric asked women to do this work as a sacrifice for the war effort, when the war ended, much that was gained was then lost. However, no one could take away the experiences of independence, responsibility or recognition they received for helping to win the war.
