## Superintendent Lloyd Bugbee {-}

*Originally appeared in West Hartford Life, March 2010*

West Hartford’s population growth between 1910 and 1920, led to an emergency situation in the schools, as buildings were not constructed fast enough to keep up with the growing student population. At the same time, the administration couldn’t keep track of its teachers. Superintendent William H. Hall led the school system through this growth (1897-1922), but when he retired in 1922, his successor Lloyd Bugbee, jumped into action.

In 1922-3, Superintendent Bugbee asked the Connecticut State Board of Education to survey West Hartford’s schools. The 151-page survey provided Bugbee the outside pressure to accomplish much of what he may already have known needed to be done. As soon as the State Board published its survey, several towns asked for copies and the state department printed 350 copies for its own distribution.

Lloyd Bugbee was hired in 1917 at age 27 as the principal of West Hartford’s high school. He grew up in Vermont, graduated from Dartmouth College, and then did graduate work at Columbia Teacher’s College. When Bugbee took over for the 74 year old Hall, it was truly a changing of the guard.

Until 1917, William H. Hall served as both principal and superintendent and had no staff to support him. Between 1913 and 1922, high school enrollment jumped from 105 to 343. While the population grew about 84%, the high school enrollment grew over 300%. Under Hall, two new junior highs were built and construction began on the high school. Bugbee was known for both building the infrastructure and developing an innovative curriculum in West Hartford.

Bugbee had to address the overcrowding in the elementary schools. With a school population that almost doubled from 1910 to 1920 to 1,769 pupils, Bugbee had to find places for the students to attend school. Ten classrooms were so crowded that they had to go on double sessions.

Under his administration, 12 new schools opened. He added courses in the high school that included aeronautics, driver education, and nature study. And Columbia University’s Teachers’ College named the new elementary curriculum exemplary.

The State Board of Education Survey, published in 1923, recommended improved supervision along with a building program which entailed spending about $100,000 over two years. The Survey called for hiring a supervisor for the elementary schools while Bugbee would supervise the junior and senior high schools. The Board of Education hired that person. The survey called for establishing special classes for adult education. And, as schools began to take on more responsibilities than just the 3 R’s, the survey recommended West Hartford hire a school physician, dental hygienist, and director of physical education right away.

Bugbee used the report to act. In 1923, West Hartford began its adult education division by offering its first three classes at the Elmwood School. Also, Bugbee promoted the West Hartford public schools outside the town. He took on leadership roles in the region as well. In his second year as Superintendent, Bugbee chaired the fall meeting of the Connecticut State Teachers’ Association held at Hartford Public High School.

West Hartford excelled in writing elementary school curriculum. By January 1926, Teachers College at Columbia University commended Superintendent Bugbee on the new elementary curriculum. Bugbee, his elementary school supervisor Ethel Merriman and a committee of teachers designed a course of study in history and geography judged to be one of the top 25 out of several hundred submitted to the college.

West Hartford pioneered in foreign language instruction. In April 1926, Bugbee addressed a New York City conference of eastern junior high schools to describe West Hartford’s introduction of foreign languages in the eighth grade. Students spent one-semester learning word origins, six weeks of Latin, and five weeks of French, to learn the principles of words. The curriculum introduced all students to the study of language in an innovative way. Bugbee encouraged the implementation of exploratory courses for eighth graders.

The Beach Park School also helped put West Hartford on the educational map. With five acres of land donated by T. Belknap Beach in 1925, the Beach Park School was the first in West Hartford to be built in a park-like setting. Beach wrote in the deed that no trees could be cut except for park purposes. The architecture of the building was more like a home than an institution. The colonial structure and color scheme for the three-classroom building, finished in 1926, were a departure for school buildings. A national education journal wrote an article about the school and educators visited from across the country.

Bugbee’s idea was to develop a school with the “happy atmosphere and freedom which the preschool child enjoys at home. It is a place where children may live together working, playing and learning as they might do in a happy family.” The building enhanced the teachers’ abilities to reach these goals. In 1929, Bugbee wrote “This home-like and livable atmosphere is probably one of the most outstanding evidences of progressive education.”

Teachers and administrators in Connecticut viewed Bugbee as a leader. He was a regular at the state teacher’s convention. In 1927, he was elected by 200 state delegates to represent Connecticut at the National Teacher’s convention in Minneapolis.

The *Hartford Courant* praised Bugbee in 1929 for urging the town to buy school sites before the town was ready to build and before neighborhoods were built. Bugbee claimed this was a policy established by William H. Hall. In 1929, the town bought the site on Park Road on which Sedgwick School was built. It also bought two properties in the northern, undeveloped section of town. The *Courant* article claimed “Superintendent Bugbee is considered invaluable to the town by many officials because of his acute vision in school matters.”

By 1930, in his ninth year as Superintendent, Bugbee’s reputation continued to grow. Franklin E. Pierce, state supervisor of secondary education commended Bugbee for following through with a ten-year survey following high school graduates. Pierce commended the survey for following not just students who went to college but also those who went straight into the workforce. Bugbee used the survey to ascertain what advantage students got from the West Hartford.

While the Connecticut State Department’s Survey in 1923 was critical of the school system, Bugbee, at the young age of 32, used it to legitimize many of the changes he wanted to bring to the town. Bugbee’s leadership put the West Hartford schools in the vanguard in Connecticut and the nation.
