## The League of Women Voters: Building Leaders in a Democracy {-}

*Originally appeared in West Hartford Life, June 2002 and October 2010*

In February 1920, six months before ratification of the 19th Amendment, suffragists founded the League of Women Voters on national, state and local levels to crusade for “the success of democracy.” The founders of the non-partisan organization calculated that their job would take five years to teach the 20 million new women voters how to participate in a democracy and then they would disband.

The West Hartford League formed two years after the state and national Leagues and just three years after women won the right to vote. In 1920, West Hartford’s 9,000 residents lived in a suburb. There were still farms in the north and south ends of town, but the percentage of people in town who worked in farming declined. Some residents worked in West Hartford factories like Spencer Turbine or Whitlock Coil and Pipe, while many of the new residents took the trolley to insurance jobs in Hartford. The new houses built on farmland attracted middle class families, in which wives left the workplace upon marriage and often had time for, and an interest in, volunteer work.

The West Hartford’s League of Women Voters, established in 1923, has been a vibrant community organization dedicated to building leadership and “a better informed, more intelligent electorate.” The League’s longevity and success is based on several factors. They have specific goals based on civic engagement in a democracy, they build a sense of community within the organization, and provide many different types of activities for members, taking advantage of their strengths and abilities.

Women’s political roles expanded in the 1920s and the League reflected this. At the same time, many women held onto their traditional roles in society and in the organization. The sense of community built by the League played a large role in the League’s success. Through the mid-1920s, many of the League meetings worked around an elegant tea. Attendees dressed in their best clothes including hats and white gloves. At first, luncheons were held in the Masonic Hall, and by the late 1920s, luncheon meetings were held at the West Hartford Country Club (today Buena Vista) and the Hartford Golf Club. The Hospitality Chair was one of the most important women on the Board. These luncheon meetings catered to women who, though they did not work for wages, maintained a concern about the political world. This sense of community, fostered by these luncheons, gave the League staying power.

The activist women realized that socializing did not do enough to educate new voters. League member Charlotte Lundgaard led a drive to register more voters. Only 23% of the West Hartford electorate voted in 1922, and the League took it upon itself to target West Hartford’s 2,200 women voters who had not registered. The League bought 1,100-penny postcards, at a cost of $11 and sent them to eligible voters. On registration day in 1923, they set up a tent in the center of town, provided babysitting, and served coffee. League President Mrs. E.E. Stiles, said that the league would organize a “motor corps” to drive women to the Town Hall to register to vote. The drive netted 940 new voters. The movement was non-partisan and the idea was to “waken the women to their civic responsibilities.”

At the local election in mid-March 1924, West Hartford residents cast twice as many ballots as ever before in West Hartford’s history. Lundgaard entered a contest with *The Woman’s Home Companion* magazine on behalf of the League and won the $150 prize! The magazine editors knew only 26% of newly enfranchised women had exercised the franchise and they encouraged groups to share their success stories. Lundgaard wrote in her application for the national award that even if not a single voter had been registered, “the labor of that enterprise would have been worth it to ascertain what League “team power” was. Our organization worked as a man that day, with magnificent esprit de corps.” Lundgaard’s definition of success in this case was working like “a man,” despite the fact that all the work was done by women. In this sense, Lundgaard bought into the male idea of success, but did it all with women power.

Once the women were registered to vote, the League offered classes to educate new voters. Members needed to know about state and local issues and chairs of committees took on the task of educating their members. In the 1920s and 1930s, the League sponsored “Citizenship Schools,” which organized speakers to talk about the problems of the day. Both men and women attended these “schools” and the League provided childcare for mothers with young children.

Those who came to the March 1924 meeting heard Mr. Christopher M. Gallup, president of the West Hartford Chamber of Commerce, talk about West Hartford elections. Gallup, an officer at Travelers Insurance Company, and a one time chair of the West Hartford Democratic Party, was one of the first advocates in West Hartford for the Council-Manager system of government and he helped make West Hartford the first in Connecticut to adopt this system in 1919. Gallup and his wife lived on Steele Road, and Mrs. Gallup served as Secretary on the Board of the League. She became involved in the national League and traveled as a delegate to several national conventions in the 1920s.

In 1924, the League sponsored an exhibit entitled “The Fair Tariff.” In June 1925, they spent $1.85 on a Child Labor Study Guide from the national organization. They set up study committees about town government, education, and planning and zoning. These committees provided leadership roles for women who had for so long been kept out of the public sphere.

League members also raised money. In the 1920s and 1930s, the League used rummage sales, bridge parties, tea dances, and yearly dues to raise money. Committees formed to organize each event.

The League served as a training ground for women who got involved in politics. In 1929, Grace (Mrs. William) Honiss, the Vice President of the League ran and won election as the first woman to the Town Council. In that same year, she was elected chair of the board of directors of the West Hartford Library. In 1931, the school board appointed Mrs. Edward Lorenz as its first woman. Louise Duffy was appointed to the school board in 1938. The Board was appointed well into the 1950s. Before entering formal political office, all three women were longtime members of the League.

This wide-ranging, bipartisan organization offered numerous opportunities for women to get involved in the political world. Though many historians see the 1920s as a time of frivolity and flappers, characterized as the “Roaring Twenties,” many women continued to pursue the reforms that had started in the Progressive Era before World War I.

Anne O’Hare McCormick, the first woman to win a Pulitzer Prize in journalism, for her work as a foreign correspondent for the *New York Times*, was the inspiration for a pen and ink drawing of a woman with a broom on the front cover of the 1945-6 West Hartford League of Women Voters pamphlet. The League, and McCormick believed that women should find careers and not be intimidated by men. They also believed women would help clean up politics.

In this organization, women educated themselves about political issues, learned from speakers at meetings, and studied national and local political issues. They enjoyed the social activities like tea dances and fancy luncheons at the country club and used them to build support and community. For others, organizing fundraisers gave them a means to develop a sense of worth and a sense of community. For still others, the experience with the League led them into the male dominated world of politics. League women went with a broom in their hands to clean up abuses of power as they saw them, while they tried to broaden the electorate and wholeheartedly support democracy.

![In 1953, the League continued to push for women’s representation in local government. League President Ruth B. Gibson advocated for a woman to be appointed to the Board of Education. Source: “Your Vote Your Town Folder,” Greater Hartford League of Women Voters Papers, Courtesy of Noah Webster House & West Hartford Historical Society.](images/07-lwv-leaders-web.jpg)
