## The Story of Susie Butler Andrews {-}

*Originally appeared in West Hartford Life, December 2004*

You’ll find the name Susie B. Andrews as the owner of land in West Hartford center in the 1909 *Atlas of the City of Hartford and Town of West Hartford* and the 1923 Sanborn Maps. Often women whose names appeared as property owners were actually holding land that their husbands controlled. But, in Andrews’ case, the *Historical and Architectural Resource Survey of the Town of West Hartford* (1982) by the Connecticut Historic Preservation Office tells us more. Susie B. Andrews, the study claims, “did a great deal to shape early West Hartford Center, building and managing commercial and residential properties.” How did she help shape the center as it moved from residential to commercial?

According to her grandson, C. Allan Borchert, Susie grew up on the northeast corner of Main Street and Farmington Avenue. Her house was torn down to build the West Hartford Trust Company (now Bank of America). When she married Myron Andrews, a banker at the Colonial Bank in Hartford, she moved to 12 North Main Street. She was a shrewd business woman, who, Borchert recalled, was a tough negotiator. He remembered his grandfather in the early 1930s bemoaning her death in 1930 while he worked on his dairy farm. “If only Susie were here,” his grandfather said.

The first residential development in the town center came when Frederick Rockwell bought and subdivided the King family farmland southeast of the center in 1896. Rockwell laid out parcels on Burr Street and had a grand plan for Boulevard which came to fruition between Memorial Drive and South Main Street. The houses in this subdivision were built between 1900 and the mid 1920s.

The second residential development, northwest of the center was named West Hartford Heights. Developers subdivided this land around 1900, and the lots sold, but houses were not built until after 1914 when amenities like paved streets, electricity, and water were available. Susie Andrews laid out Dale Road in 1912 and subdivided the property.

The development of West Hartford Center and the suburbanization of the town coincided with the improvement of transportation to West Hartford. In 1889, horse railway tracks were laid down Farmington Avenue and by 1894, the trolley was electrified. Those who worked in downtown Hartford had a regular, dependable transportation to and from Hartford, making the farm town more desirable as a residence.

Susie B. Andrews had designs on the center. When the population grew from about 3,000 in 1900 to 33,000 by 1940, the retail needs of the town grew as well. Andrews owned land on the north side of Farmington Avenue, west of Main Street and on North Main Street. Even before West Hartford’s zoning laws went into effect, Andrews knew that it was a good idea to separate residential and commercial.

One of Andrews’ residential development properties still stands at 9 Dale Road. This was one of the first houses built on Dale Street and is a beauty salon today. She also rehabilitated the building at 10 Dale Road which was probably an original barn to her childhood home on Farmington Avenue.

To make way for the commercial development, Andrews moved several houses from Farmington Avenue to Whitman Street. The house at 30-32 Whitman Avenue was moved in 1912 when Andrews laid out Dale Road. Frederick Brace’s house originally stood on Farmington Avenue on the east side of the present Dale Road. Around 1850, he set up the first omnibus route between West Hartford and Hartford allowing town residents to commute to Hartford. It operated until the horse railway took over in 1889. This building is thought to have been the Old Academy Building on South Main Street until about 1840 when it was moved to Brace’s property on Farmington Avenue and then moved again to Whitman Avenue.

Susie Andrews moved the colonial revival house built in 1912 which now stands on 75 Brace Road. Most houses along Brace were not built for at least another 10 years when amenities like piped water became available. This house was moved to its location from the corner of Farmington and Dale Street in the 1930s to make room for a commercial building. Myron and Susie Andrews’ son M. Morris Andrews built, owned and lived in this house which was just north of Farmington Avenue and Main Street. This house is identical to the one at 1022 Farmington Avenue.

![The colonial revival house, built in 1912, was moved from Farmington Avenue and Dale Street to 75 Brace Road in the 1930s to make room for commercial development. It was sold in 1970 by Butler Realty and is now a commercial property. Source: Town of West Hartford, CT Vision Government Solutions, parcel photos.](images/07-andrews-brace-rd.jpg)

It seemed that Susie got the area ready for commercial development. But the Depression hit and then she died in 1930 of tuberculosis. At that time, her business became the Andrews Corporation with each of her four children owning an equal share. Borchert remembers the family having lots of investments in land and property, but having very little money. When Borchert’s father died in the early 1930s, he and his mother and sister moved in with his grandfather at 10 North Main. He remembers his grandfather owning a dairy farm which he sold to A.C. Peterson’s farm in Bloomfield in the early 1930s. When his grandfather died, his mother took in boarders to survive.

The commercial building at 984-992 Farmington Avenue (In 2004, housing Chico’s, the Elbow Room, and eight other stores) was built in 1935 by the Andrews Corporation, inheritors of the property of Susie B. Andrews. The commercial buildings like these with storefronts for about ten shops were just starting to come into existence and were just beginning to be known as malls.

The 10-12 North Main Street building, now housing Sally and Bob’s, and the YMCA offices, was built in 1938 and was one of the first large office and commercial buildings in the center. It has details from the Colonial Revival style of architecture, and in that way, matches what was then the West Hartford Bank & Trust building from 1926 and the government buildings including the Noah Webster Library, the Town Hall and Hall High School. It was probably built by Susie and Myron Andrew’s son Morris. This building was built on the site of Susie B. and Morris Andrews’ residence. By this time, Borchert and his mother had moved to another one of the residential properties the family owned, first at 44 Whitman Avenue and then at 32 Grennan Road

The commercial building at 994-1000 Farmington Avenue, built in 1938, was also part of the Andrews retail empire. The Butler Building, named after Susie’s family name (the B stands for Butler) was built on the site of Susie Butler’s childhood home. This commercial building, influenced by the Colonial revival style, has much more architectural detail than the one to its east. Susie’s son Morris probably built the Butler Building as well.

Susie B. Andrews was indeed a businesswoman. According to her grandson, she was also a woman of many talents. She was an excellent artist, painting scenes from her travels to Maine, Bermuda and some from the local scenery. She never sold any of her artwork, but each of her children has many of her paintings,

It is surprising that there was so much development, both residential and commercial, in West Hartford in the 1930s, during the Great Depression. Susie Andrews was instrumental in setting the path for this development. Andrews’ management of land in the first three decades of the 20th century helped to shape both residential and commercial development in the center. These commercial buildings have stood the test of time. Andrews’ attempt to separate commercial and residential properties has held to a great extent as neighbors fight the encroachment of businesses in their neighborhoods. Ironically, Dale Road, Susie’s first real residential neighborhood is almost all commercial today.
