## Amateur Radio in West Hartford {-}

*Originally appeared in West Hartford Life, August 2010*

Town Councilman Steve Adler and Dr. Rick Liftig are two of the more than 175 ham radio operators who live in West Hartford. In a day of instant communication through the internet and cell phone, these amateur operators seem something of an anomaly. In June 2010, Mayor Scott Slifka presented a proclamation to representatives of the American Radio Relay League (ARRL) in recognition of West Hartford’s tie to the growth and support of this organization as he recognized amateur radio’s deep roots in West Hartford. Their communication system serves as a community service in times of disaster as well as a hobby, which three million people enjoy worldwide.

Different from the telegraph, which sent a Morse Code message by impulses over a wire, amateur radio operators send messages over the air waves. The U.S Government through the Commerce Department began licensing operators in 1912.

Hartford’s Hiram Percy Maxim founded the Amateur Radio Relay League in 1914 when he wanted to send a message from Hartford to Springfield and did not have a strong enough signal to do so. He contacted a relay in Windsor Locks and his Morse Code message made it to its intended receiver. Maxim, who invented the Maxim Silencer for guns (1909), and the car muffler, was a radio enthusiast who helped to develop a network of amateur radio operators. In 1914, he was a member of the Hartford Radio Club, but realized there would be an advantage to a wider network of hams. By September 1914, their network grew to over 230 stations. Just 15 months later, there were 600 stations and the ARRL published its first bulletin *QST* (meaning Calling all Radio Amateurs) to help coordinate the actions of the operators.

When the United States joined the Great War in 1917, the Department of Commerce sent a letter to all amateurs ordering them off the air. During the war, the ARRL coordinated the recruitment of operators into the armed services where they continued to hone their skills for the public good.

In 1918, at the war’s end, the U.S. Government tried to control the transmission of messages under the Department of the Navy, but the ARRL lobbied Congress to allow individuals to control their transmissions and they quashed several bills in Congress allowing them to do so. The ARRL under Maxim’s watch, provided technical advice and assistance to amateur radio enthusiasts, and regulated them before the Federal Communication Commission was founded in 1934.

With Maxim the first ARRL headquarters inhabited “a couple of shabby rooms” on Main Street in downtown Hartford. In 1925 the staff of 18 moved to 1711 Park Street. West Hartford’s role really began in 1931, when the ARRL built its headquarters at 38 LaSalle Road, where Coldwell Banker was in 2010. This new location housed the League in a two-story building. They had a $200,000 budget and 28 full time employees.

Many amateur radio geeks moved to town who worked at ARRL headquarters. They found housing in the old Selden Hill farmhouse on top of Buena Vista. Rilla and Henry Selden lived in the house up on the bluff and their seven children had grown and moved away. Mrs. Selden posted “Rooms for Tourists” sign down on Farmington Avenue near the Reservoir. Two men from the ARRL station looked for a place to live, they found, not only a “home,” but also a great radio location where they could experiment.

Associate Editor Ross Hull, an Australian, and Managing Editor Clark Rodimon of *QST* were some of the first boarders to move in. Rodimon invented the first two-way five-meter contact between Hartford and Boston –- over 100 miles in 1934 from Selden Hill. Hull was known worldwide for his pioneering work in developing the VHF and UHF spectrum for the 56, 112 and 224 MHz amateur bands. According to Rilla Selden, “they strung up a big contraption among the trees. Then Ross talked to a half a dozen fellows in Boston and none of them would believe he was in Hartford.” Hull had strung a high gain beam array in the trees. The amateur radio operators in Boston spent the next half hour “discussing that bootlegger who claims to be in Hartford.” They could not believe that the signal could be sent 100 miles. Hull proved that radio beams could go beyond the horizon and “bend” to the curvature of the earth.

The various boarders continued to experiment on Selden Hill. They scaled the old slate roof to put up transmission lines and they built sky-wires for fun on a Saturday afternoon. Even in 1944, according to an article “The Legend of Selden Hill,” in *QST*, remains of these structures still existed.

These amateurs were not just satisfied with experimenting with words over the airwaves. They built radio controlled gliders and airplanes. Selden Hill’s steep slope provided a great spot to use as a launch pad. One of these gliders, with a wingspan of 16 feet is at the ARRL station in Newington today.

In the early 1930s, Ross Hull experimented with television at Selden Hill. He wanted to “reduce to amateur practice” the complicated nature of sending pictures over the airwaves. He tried several television experiments in 1937 that debunked the professional opinions that the maximum range of television transmission was 30 to 40 miles. In fact, he successfully received NBC’s transmissions from the Empire State Building over 100 miles away in 1937. Hull criticized the professional television industry for their commercialism. Because the equipment was so much more expensive, amateurs had more difficulty experimenting. Hull moved to Bolton in 1938 where he accidentally contacted 6,000 volts while working on his experimental television receiver and died.

According to present day amateur radio operator Rick Liftig "Virtually all of our modern communication techniques derived from these experiments."  Almost 70 years later, amateur radio operators continue to help the public by radioing in times of emergency during natural disasters. Their dedication to public service and their dedication to their hobby symbolize the community involvement that continues to make West Hartford such a vibrant town. Perhaps an historical marker on LaSalle would help keep this 20th century history alive!
