## Dr. Caroline Hamilton {-}

*Originally appeared in West Hartford Life, August 2012*

Recently, the daughter of a good friend left for Thailand for a year’s service. Part adventurer, and part human rights activist, Katherine will be teaching English to Buddhist monks in Chang Mai, Thailand. The rise in interest in human rights issues, student exchanges, and college student travel around the globe, are all part of a 21st century global outlook. This generational shift, however, is far from new. Take a look at Caroline Hamilton.

On September 12, 1944, Dr. Caroline Hamilton died at age 83. Her obituary stated that she was a native of West Hartford, a graduate of Smith College, and a graduate of the Women’s Medical College of the New York Infirmary for Women and Children. It went on to say that “From 1892 to her retirement in 1932, Dr. Hamilton was medical missionary at the Azariah Smith Memorial Hospital, Aintab, Turkey, in charge of medical services for Moslem women.”

In 1930, William H. Hall, West Hartford’s retired Superintendent of Schools, devoted two pages in his book *West Hartford* to Dr. Hamilton. In his section entitled Biographical Notes, Hall wrote about four West Hartford families, and 24 individuals, two who were women.

According to Hall, Hamilton was born to Benedict and Electa Hamilton at their home on the south side of Farmington Avenue just east of Trout Brook, on a 70 acre farm near the present site of Kingswood Oxford School. Hamilton went to the West Hartford High School after it was opened in 1872 on North Main Street as the second floor of the Center District School. She went on to graduate from Hartford High School in 1880 and then Smith College in 1885 at age 24.

Hamilton graduated from the New York Women’s Medical College (1863-1918) in 1888. She enrolled in the school when the founder Dr. Clemence S. Lozier was still running the school. Founded in 1863 with seven women, by 1888, 219 women doctors moved into practices from Maine to California. She interned at the hospital for a year, and then got involved in “college settlement work” as a physician, just at the time that Jane Addams and Lillian Wald established Settlement Houses in Chicago and New York City. Wald and other settlement workers tried to ensure that all members of society, including women and children, immigrants and the poor, and people of all ethnicities and religious groups could realize the promise of American ideals of "life, liberty and the pursuit of happiness."

Hamilton also found time to teach in the Medical College where she got her degree and was a resident physician at the New York Infant Asylum which provided care for abandoned children. The Asylum also provided obstetrical care for unwed or indigent women.

She did more graduate study in New York and in 1892, at age 31, the American Board of Missions appointed her to the hospital in Aintab, Turkey where she worked from 1892 to 1932. A Hartford Courant article from September 19, 1893 quoted an article in Harper’s Bazaar saying that the Ottoman Sultan had granted permission ”for a woman physician to engage in her profession within his domain.” Caroline Hamilton was sent at the expense of a “Boston lady” and she set up a hospital for women and children in Aintab.

![A memorial record for Hamilton from the American Board of Commissioners for Foreign Missions in Aintab, Turkey tells of her work for 40 years (1892 - 1932). Hamilton saw over 1000 patients per year, focusing on women’s health. The memorial tells that she was aided by Elizabeth Trowbridge, her close friend who lived with her for over 39 years in Turkey, and then they “found a home together” in Holyoke, MA, when they returned. Source: Amerikan Bord Heyeti (American Board), Istanbul, "Memorial records for Caroline F. Hamilton."](images/07-hamilton.jpg)

Hamilton’s work took her beyond the walls of the hospital in Aintab to help heal the sick and needy people in all parts of the city, going to individual homes in some cases, exposing herself to great danger. She also worked for the mission church and school. She played the organ, taught Sunday School, and conducted services.

Hamilton was in what we now know as Turkey during the Armenian genocide (1915-18). When Hamilton was in Aintab, she lived through three massacres, including one in which the perpetrators came to the gates of the hospital to destroy all the inmates.

In 1915, the city of Aintab near the Syrian border had 40,000 Armenians who were Christians, and by 1922 there were only 3,000 remaining. The Turks forced the Armenians to march into the desert to the east, leaving them with no supplies and no protection. They took their belongings and some were put in concentration camps. Historians estimate that as many as one million Armenians died in the genocide and 500,000 left Turkey.

In the middle of the genocide, in October 1917, a report from a returning missionary described Hamilton’s worth to the Turks. The Turks worried that she would leave when the United States entered the Great War. Though the U.S. never fought in Turkey, we allied with the Turk’s enemies. Hamilton was not in good health as she had contracted typhus in 1915 and never fully recovered. The other missionaries tried to get her to leave, but she pledged to stay until the war ended. Some city residents tried to get her to take on citizenship so that she would not be expelled from the country. Though she stayed, she was persecuted, having stones thrown at her when she visited patients and finally she took a soldier with her when she made home visits.

Her hospital for women and children was transformed during the war into a military hospital with ties to the Red Cross. Hamilton preached Christianity to the wounded soldiers. At the same time, she had to listen to soldiers boast of their role in the genocide.

Hamilton also cared for 12,000 refugee women and children. The missionary described Hamilton sewing a woman’s nose that had been almost cut off. The patient then went on to become one of the best workers in the hospital.

On February 16, 1920, the *New York Times* reported that The American Committee for Relief in the Near East said that Americans had escaped from several towns where Armenians were being massacred. Armenians were destitute and many were sick and wounded. Hamilton evacuated from Aintab and was safely in Marash with 16 other missionary workers.

In that same month, Hamilton came back to the US and spoke before the Smith College Club where she argued that the U.S. had to take action and move beyond its ignorance and indifference. She claimed that the U.S. was better suited than either the French or British to carry out this military action.

President Woodrow Wilson tried to help sustain the Armenian state which was established in 1918. Opposition from the Republican Party and a lack of troops led to the Armenian state collapsing in November 1920.

Hamilton left Turkey for 18 months from August 1920 to February 1922 when the Turkish government carried out more massacres against the Armenians and her hospital had to be abandoned. At that time, she went to Beirut where she ran an orphanage for 300 children.

Throughout her 37 years abroad in Aintab, Turkey and in Lebanon, Hamilton remained a member of the First Congregational Church in West Hartford. She wrote letters to church members and received gifts of money and supplies at Christmas from the church’s Bible School. When she came back to the United States on furlough, she addressed missionary meetings, not just at the First Church, but at churches throughout the area.

Hamilton’s work, which started more than 120 years ago brought one of the first woman physicians from the U.S. to a country where she witnessed mass murder. Her motivations, probably to live the life of an independent woman, and to play an important medical role in a place where she was “other” and could have more power, may not be too different from young people's motivation for mission trips today. Hamilton’s Christian missionary zeal sets her in a different era, but her idea to use her expertise to help those in need still holds sway today.
