## William H. Hall and our “Highest Duty” {-}

*Originally appeared in West Hartford Life, February 2010*

My friend, Trinity Professor Jack Dougherty, and I were recently debating when it was that West Hartford began promoting its successful public schools as a selling point to attract families to settle in West Hartford versus surrounding towns. He held that West Hartford did not start competing for residents via their schools until the late 1950s. It seems like the commitment to good schools as a part of the civic virtue of the town, however, starts earlier.

A look at the schools’ history begins with one-room schoolhouses. By 1902, the town had consolidated its nine school districts. Adolph C. Sternberg was the Acting School Visitor (head of schools) until 1896. He was served in the General Assembly from 1895-6. He felt that the schools needed more skilled supervision than he could give them, and he arranged to have the Secretary of the State Board of Education, Prof. Charles D. Hine, assume the supervisor position until 1897. When Hine realized it was more than a part-time job, he hired high school principal William H. Hall and the position transformed into the Superintendent of Schools. Hall held that position for 25 years until 1922 when he was 77. Upon Hall’s retirement, Lloyd Bugbee, the Principal of the West Hartford High School, a youngster compared to Hall, stepped in and served as Superintendent until 1947.

![William H. Hall, (1845-1934), the first historian of the town, wrote his history of West Hartford when he was 83 years old, and published it in 1930. He was born in West Hartford. In 1872, at age 27, Hall was hired as principal of the old West Hartford High School. This photo, taken in 1875, is in his time as principal. At age 83, he was still involved in the schools, teaching local history for an hour per week to the 5th and 6th graders at the big elementary schools in town. Source: Noah Webster House & West Hartford Historical Society.](images/07-hall.jpg)

There is some early evidence of pride in the town’s schools. In 1902, William H. Hall, wrote “A Historical Sketch of West Hartford” for the dedication of the new red brick Town Hall, in which he praised the school system. At the time, the town had about 3,000 residents and was still a farm town. Hall was the Superintendent and a town historian in his own right, and he used his speech to glorify and celebrate the town.

He related the history of West Hartford from 1679 –- the first settlement –- to 1902. He believed that to understand the present, the citizens needed to not only know the past, but also understand their indebtedness to those who came before them. From 1713 to 1796, according to Hall, the Ecclesiastical Society of the West Division supported five schools up and down Main Street. He argued, “our fathers made very wise and generous provision for the educational interests of the community,” an expression of civic virtue.

From 1796 to 1855, the state gained a role in school governance as the General Assembly established a School Fund with the proceeds from the sale of Western Reserve lands in Ohio. A state-mandated School Society managed the funds for the West Division (West Hartford). By 1885 the schools were consolidated under the town’s new government.

Hall believed that the successful town residents who went to schools here demonstrated how good the schools were. Hall listed Noah Webster, Theodore Sedgwick who became Speaker of the House and a U.S. Senator, Titus Hosmer, a member of Congress, John Woodruff a judge in New York State, Benjamin Burr who helped establish the glove industry in Gloversville, New York, James Seymour, banker, Ebenezer Belden, printer and publisher of the first daily newspaper in New York City, more than 25 ministers, including Lemuel Haynes, a “colored boy” born here and who became a successful minister in Vermont. His examples of success seem to be individuals who gave back to their communities. Hall concluded:

> We certainly have good people, good homes, good churches, good schools, good laws, good officials, good roads and good public buildings. But none of these are so good that they do not admit of improvement, and it should be our constant aim to attain to that which is not simply better, but best.

> Let us not forget, however, that our highest duty, our noblest endeavor, our grandest opportunity and our true success as a community are to be found in such use and improvement of all these advantages and blessings as will result in the training of our children and youth in character and life so that they may most worthily serve God and their fellowmen in their day and generation.

Hall’s priority to make educating children the “highest duty” led to big changes in the school system. As the population grew, so did his plans for the school system. West Hartford was on the cutting edge when it opened two junior high schools in 1922, only the second and third junior highs in the state. Ground had already been broken for the new high school.

When Lloyd Bugbee became Superintendent in 1922, he requested that the State Department of Education do a report on the state of West Hartford’s schools. State Commissioner A. B. Meredith spoke at Webster Hall in the Noah Webster Library, invited by the Democratic Women’s Club to deliver his report. William Hall presided over the meeting. While Supt. Bugbee praised his teachers, Meredith and the State Board criticized the town for falling behind in both its buildings and its student achievement.

Meredith pointed out the physical needs of the schools and the changes needed in the course of study. There was a desperate need for a new high school, and yet the cornerstone had already been laid. Three of the seven elementary schools were so crowded that they ran double sessions. Again, Bugbee quickly responded with the Beach Park School (1926), Morley School (1926), an eight-room addition on Smith School (1926) and Elmwood School (1928). As for student achievement, the elementary students were performing only slightly above average; the State Board felt Bugbee could expect more. Perhaps Bugbee was willing to receive the criticism and used it to his advantage to galvanize the public to support his building program.

Still, there were some anecdotal signs of good results. On February 11, 1924, the *Hartford Courant* headline read “West Hartford’s Schools Praised: Men Prepared there Do Well at College, Say Dartmouth Authorities.” Dartmouth College sent several commendations to the Superintendent “commenting on the splendid preparatory training received by graduates of the West Hartford Schools.”

Though its schools were not yet used to sell houses by 1925, the town leaders started to define civic virtue through caring about its schools. They did not yet provide the draw to the town that they would in the next 15 years.
