## Ruth Dadourian: A Stalwart for Justice {-}

*June 2018*

Connecticut is often seen as the “land of steady habits,” with a conservative base that did not take to political change very readily. This held true for the Connecticut state legislature’s lack of ability to pass the woman’s suffrage amendment until after it became a federal amendment in 1920. But in other ways, women like West Hartford’s Ruth Dadourian (1892-1983) led the way for rights for women and justice for many others.

Ruth and her husband Haroutune lived much of their adult life in Hartford. In 1950, after Prof. Dadourian retired from Trinity College, they built a house on the Old Mill Pond north of the American School for the Deaf, and moved to 177 North Main Street, West Hartford to live out their retirement years.

Ruth McIntire was born in Italy in the late 1890s, and by time she graduated from Radcliffe in 1912, she was an accomplished linguist knowing Italian, Russian and French. She took part in her first woman’s suffrage demonstration when she was a student at Radcliffe College. There she met her husband, H.H. Dadourian who became a math professor at Trinity College in the late 1910s.

Ruth Dadourian’s first job was as a publicist for the National Child Labor Committee. In 1918, Dadourian wrote a pamphlet for the National Child Labor Commission decrying child labor. She found children as young as five working in the beet fields. Dadourian’s main academic interests were in child welfare and labor, public health education and labor laws.

When she first arrived in Hartford, she didn’t know many people but brought with her a desire to work for justice. While shopping downtown, she discovered the Connecticut Woman Suffrage Association headquarters. She walked in and was “greeted with open arms,” a young woman interested in suffrage. She said, before she knew it, she was on the board of the organization.

Dadourian actively participated in the Connecticut Woman Suffrage Association. When the Connecticut Woman’s Party, led by Katharine Houghton Hepburn, split off from the group in 1917, there was not the same rancor between the two groups as existed on the national level. In fact, Dadourian argued that “the Woman’s Party was really the spearhead and then we (CWSA) could follow through... The more outrageous they were, the better off we were.”

When women won the right to vote, Dadourian knew the battle for women’s rights was not over. She knew that the campaign had not just been to win the vote, but women had to continue to educate both suffragists and their opponents, and make policy makers know women would actually participate in political matters. In 1920, she said, “Even if we wanted to, could we possible escape the responsibility of victory?”

On March 21, 1921, Dadourian appeared at a hearing for House Bill No. 722, providing for the extension of the personal tax to women. Assessing this $2 tax collected each year by each municipality would show that women had “equal franchise rights” with men. If men failed to pay, they were imprisoned. Male legislators seemed to think it would not be the right thing to imprison women so were hesitant to pass the bill. Dadourian, the legislative secretary of the Connecticut League of Women Voters, favored extending the personal tax to women, but suggested exemptions, possibly in the case of mothers, to demonstrate that women were, in fact, equal.

In 1923, Ruth Dadourian was instrumental in starting the West Hartford League of Women Voters. She served as the director of the state league from 1926 and then became its president and lobbyist from 1934 to 1935.

On March 19, 1927, Dadourian wrote a letter to the editor of the *Hartford Courant* in support of women serving on juries. She argued that hundreds of women from all over the state supported this bill and packed the hearing. The lobbying effort was thorough. Urban and rural women testified from every part of Connecticut. Women who served on juries from surrounding states testified as did judges, lawyers, and prosecuting attorneys. Dadourian wondered if those against the bill believed that Connecticut women were “inferior in intelligence and ability to women in the twenty-one states where they are now serving.”

There were those who believed that the state should hold a referendum to poll women on whether they wanted to serve on juries because the opposition claimed they did not. Dadourian argued “our representatives are elected to use their best judgment in enacting wise legislation for the State.” In 1927, Connecticut had 15 women in the legislature, more than in any other state and women had every other legal right men had.

Dadourian and her husband also weighed in on international affairs. After the Russian Revolution of 1917, the United States did not recognize the new revolutionary government. In 1930, she and her husband, a native of Armenia and fluent in Turkish, Armenian, Russian and French took a seven month study tour to Europe. When they returned, the Dadourians advocated for diplomatic and commercial recognition of the Soviet government, which finally came in 1933. They praised the Soviet people for their “enthusiasm and willing sacrifice... in their efforts to attain the Communist ideals.”

Mrs. Dadourian argued that before the war, two-thirds of the Russian population were illiterate. Just 13 years later in 1930, only one-third was illiterate. The government built hospitals and nurseries for women workers. The Dadourians saw that the Russian Soviet people sacrificed greatly for the changes made by the Communist government. The institutional changes that impressed the Dadourians the most were communal apartments with communal kitchens to free thousands of women from kitchen drudgery; parks for children, and a penal system, which the Dadourians believed did not use retribution. One wonders if they felt the effects of the McCarthy questioning 20 years later.

During the New Deal, Ruth was supervisor of the Division of Women's and Professional Projects of the Works Progress Administration in Connecticut. During Governor Wilbur Cross’s tenure, the Connecticut League of Women Voters presented the state with a memorial tablet commemorating 31 women who according to Dadourian, “built up public opinion which resulted in women winning the franchise.”  Isabella Beecher Hooker, a nine-year-old great-granddaughter of Isabella Beecher Hooker unveiled the tablet. You can still find it in the south corridor of the Capitol.

In 1935, Dadourian chaired the Connecticut Committee for Ratification of the Child Labor Amendment. (She must have known Louise Duffy who supported it as well.) Dadourian wanted the National Recovery Administration Codes, which banned child labor in many occupations, and was set to expire in 1935, to continue through a constitutional amendment. This law was never passed.

In 1934, both Ruth and her husband Haroutune appeared in a publication called *The Red Network: A “Who’s Who” and Handbook of Radicalism for Patriots*. In this book she and her husband were listed under a group called “communist recommended authors,” a group officially endorsed by the Soviet Union Review, an organ of the Soviet government in Washington D.C. The pamphlet publicized their leftist leanings, probably based on their glowing reports of the Soviet Union after their travels.

In 1941, Governor Robert Hurley (a West Hartford resident) appointed Dadourian to the Board of Trustees of the University of Connecticut. Just two months later she was appointed field representative to assist the chair of the woman’s divisions of local defense councils and volunteer offices in planning and carrying out their activities. She served as chair of the statewide conference for women in defense.

Bob Stewart, retired Trinity professor of mathematics, remembered Ruth Dadourian after she had a stroke. She invited guests over for dinner. When it was time for dinner, it took Dadourian about ten minutes to make her way from the living room to the dining room, but according to Stewart, everyone in the room knew enough not to ask her if she needed help.  She was very strong willed and had few soft edges, remembered Stewart.

But people enjoyed being in her presence. They knew what she stood for and they wanted her on their side.
