## A Trip Back in Time to Westmoor Farm {-}

*Originally appeared in West Hartford Life, January 2006*

In 1925, Major A. Raymond Ellis bought 46 acres of land from Frank R. Scott on Flagg Road. He remodeled the barn, house and cottage to accommodate his pack of hounds to lead fox hunts at what he named Westmoor Farm. I usually think of West Hartford in 1930 as a developed suburb, but with a population of about 25,000, the town still retained some of its rural character.

The new suburban residential development was predominantly on the east side along Farmington Avenue near Hartford and along North and South Main near the center. West of Main Street from Albany Avenue to New Britain Avenue still remained pasture and cropland.

The land that the Major bought was originally the property of one of the earliest settlers in town, Thomas Merrill. Born in 1714, Merrill sold the farmland to Abijah Flagg in 1786. The land remained in the Flagg family for about 140 years; the last Flagg to own the property, Willis operated a dairy farm with 30 cows until about 1915. He grew vegetables as well and sold them at a stand he owned in nearby Bishop’s Corner. In 1922 he sold the land to Frank Scott and in 1925 Raymond Ellis bought the property.

Ellis was an architect by profession. He moved to the United States from Nova Scotia in the late 1890s and then moved to Hartford in 1908 after finishing architectural school at MIT. When he bought Flagg’s land and buildings he remodeled them to accommodate riding horses as well as his pack of dogs. Ellis served in the cavalry in World War I. He helped with the reconstruction work in France in 1918 and 1919, using his skills as an architect.

In 1922, just before he bought Westmoor, Ellis was named architectural editor of *Women’s Home Companion* magazine. By 1929, over 650 houses of Ellis’ design had been built, in part because of his connection to the magazine. He designed the Park River Bridge, the main building of the Hartford Hospital, the Connecticut Institute for the Blind, and the Isolation hospital at the McCook Memorial Hospital in Hartford.

At Westmoor, Major Ellis built a riding and jumping course. He also created what he named the “Westmoor Farms Polo Club” in a cleared field on his property. Those who had played polo at the Hartford Golf Club when it was in Hartford had been looking for a place to play since the Club moved to West Hartford around the turn of the century.

Ellis developed a fox hunt team and fox hunt. To lead a fox hunt, one needs open fields, water, and pastures for galloping horses that follow the pack of hounds. He had a pack of dogs trained and run by a man he hired. The fox hunts at Westmoor were done by “drag”: a set fox skin was dragged cross-country to leave a scent trail for the hounds. His hunt was cited in a book by A. Henry Higginson and in an English book called *Bailey’s Hunting Directory* from 1926 to 1930.

Ellis held two horse shows on his property to entertain those in the neighborhood and make them more friendly to the idea of the hunt. The drag hounds went out three days a week from the middle of March to the middle of May and from the middle of September until snow and ice made the area unrideable. At that time, there were only a few neighbors to win over.

Charles Allen Hunter (1874-1961) bought the land from Hartford Connecticut Trust in 1939 after the bank foreclosed on Ellis in the depths of the Depression. Hunter began to use it for a summer home starting in 1939, the year of his retirement. Hunter had been Vice President at Connecticut Bank and Trust when he retired after 45 years at age 65.

Hunter hired a German immigrant horseman named William Wouters. From 1939 to the late 1960s, Wouters ran his business of breaking horses from Hunter’s stables in return for taking care of Mr. Hunter’s gelding. Wouters lived in a two bedroom apartment above the tack room in the stables. In 1984, at age 91, Wouters still lived in the stable. Wouters took care of the horses of wealthy girls attending Ethel Walker School and jeweler Bill Savitt who liked to ride.

Wouters’ first worked at the Westmoor Farms Polo Club owned by architect and retired cavalry officer Major Ellis. Wouters transported horses for club members and saved enough money to buy a horse and wagon to carry building materials. In the early 1920s, Wouters opened his own boarding stables on Albany Avenue at Bishops Corner. When Hunter moved out to Westmoor in 1939, he convinced Wouters to come back to keep his business and take care of Hunter’s horses. Wouters expanded his business to board race horses from Narragansett, RI and Lincoln and Suffolk Downs in Boston. He exercised the animals at Westmoor before racing season began again in the spring.

In 1961, Hunter died. In his will, he left 56 acres to the town of West Hartford along with a large house, servants quarters, a large barn, stable, several smaller buildings, pasture, brook and pond. He was married to Leila Clark Hunter who according to his will could continue to use the property until her death. When she died in January 1973, the town had to decide what to do with the property.

By 1973, the neighborhood surrounding Westmoor Farms had changed considerably. Houses on Blue Ridge started to be built in the late 1930s through the 1950s. On Flagg Road, at least ten homes were built between 1956 and 1957. The suburban town had grown to a population of 62,382 by 1960. Neighbors had opinions about what should happen to the property.

In February 1974, the Conservation Commission in West Hartford recommended that eight acres of the land be used for an equestrian center for riding instruction and boarding horses. The indoor equestrian ring was to be about the size of the Veterans Memorial Ice Skating Rink, 85 by 185 feet on the southwest corner of the property out of sight of Flagg Road. They would build six paddocks and add some riding trails with his bequest. This they thought could provide a revenue stream for the town.

Besides the equestrian ring, the town planned to add a parking lot for about 70 cars, picnic facilities near the parking area with playground equipment, public bathrooms, a barnyard zoo, and a boardwalk and wood chip and gravel trails through the Hunter property. Hunter’s estate not only left the land, but also a sizable sum of $2.3 million to be used for maintenance of the park. The town received one-half the income from this trust, of about $130,000 per year.

The reality of 2005 shows us that the park was much less developed in the final analysis. Neighbors on Flagg Road vehemently fought the development, and the park stayed in a fairly natural state. The idea of the equestrian ring, which was truly an extension of what Wouters had been doing for about 30 years lasted but a few months before the neighbors had convinced the town that this was not in their best interests.

Today, the vestiges of horses on the farm are few, but for a developed inner ring suburb, Westmoor Park still gives a sense of those rural days less than a century ago, when most residents were farmers and there was enough open land for a fox hunt.

Read more about the fox hunt in a pamphlet written by Robert Anderson called *Westmoor Hunt, 1925-30* found at the Noah Webster House. A folder in the WHPL vertical file on Westmoor Park tells the history of the park in newspaper articles.
