## Evolution of the Town Manager Form of Government {-}

*Originally appeared in West Hartford Life, June 2006*

West Hartford’s town meeting served as a check on local governmental power from 1854 to 1919.  For 65 years, the town meeting election of three selectmen and appointments to numerous boards seemed to serve the town well. But, as the population tripled from about 3,000 in 1900 to about 9,000 in 1920, the town meeting became unwieldy. There were no auditoriums big enough for the meetings and with the added services provided by the town, government had grown into something more than volunteers could handle.

By 1917, the state passed an ordinance allowing the town of West Hartford to move to a town manager system of government which seemed like it would be more responsive to the town’s needs.  In 1919, the town adopted the council-manager form of government which put the power to run the town in a Town Manager, and the power to make policy in the hands of a 15 member Town Council. West Hartford was the first town in Connecticut to adopt this form of government.

The Town Council hired Benjamin Miller as our first Town Manager in 1919. He grew up in Avon, and took a two year business course at the New Britain Seminary. He served in Avon as selectman, founder of the Avon Library, chair of the school board, Judge of Probate and Democratic Representative to the General Assembly. During World War I, he was chair of the Draft Board for the Farmington Valley including West Hartford. When he became Town Manager, the three main issues facing the town were construction, maintaining and paving roads, zoning and running and building schools. The first charter called for the Town Council to appoint the Town Manager, Town Treasurer, Tax Collector, Controller, Town Engineer, Building Inspector, Town Auditors and Constables. They also had the power to appoint commissions and commissioners.

Under Miller, in 1923, the town established the first comprehensive zoning ordinance to regulate land use in Connecticut and a Town Planning and Zoning Commission. The town hired its first paid police chief in 1923. In 1925, candidates for Town Council ran as members of a party, rather than as non-partisan candidates. The grand list grew from $19 million to $65 million. In 1929, the first woman, Grace Honiss, a vice president of the League of Women Voters became the first woman elected to the Town Council. And the town built Plant Junior High (1922), Talcott Junior High (1922), Hall High (1924), Beach Park School (1926), Smith School (1926), Elmwood School (1928), added onto Charter Oak School (1930), and Sedgwick School (1931).

But all was not well with Miller’s administration. He was a Democrat and Republicans dominated the Council throughout the 1920s. It was unclear where power lay –- with the Town Manager or with Commissioners. Commissioners felt they had the right to appoint people to paid positions like Town Engineer and Building Inspector, and seemed to have used these positions as patronage. The Town Manager believed he should have the power to appoint the paid positions by merit, but this power seemed to have been taken away from him by the early 1930s. He resigned in 1933, under stress.

When Miller left in 1933, he sued the town for back pay from his original contract made in 1919. He started at $4,000 per year and his salary increased to $4,800. However, once the depression hit, Miller’s pay was cut from a high of $4,800 to $4,400, ostensibly due to the financial problems associated with the Depression. But, Miller also left amid tension over loss of power in his job and the rise in the power of the town commissions headed by Town Council Members. He also left as the Great Depression deepened and the town pushed to have its employees take pay cuts.

Within 15 years, the government charter already needed reform. By 1930, the population rose to almost 25,000 and the system of government had not fulfilled its original promise. In February, 1934, the Town Council hired a professor from Bowdoin College to study the way the town government worked, with an eye on proposing a more “businesslike plan of government.” The first report to the Town Council on the new plan for government claimed that by 1933, the town manager position had sunk to “innocuous desuetude,” meaning “disuse.” Apparently, Miller had fallen out of favor and spent little time at his job as his power got siphoned away by Town Council members, some of whom served as Commissioners. 

By September 1933, the Town Engineer who had been appointed by the Republican controlled Engineering Commission, Rodney Loomis, was running the town as the Town Manager. He retained both posts until he was finally made the official Town Manager. New Town Manager Rodney Loomis’ salary had soared to $7,500 by 1935.

Loomis took much of the power away from the commissions by also serving as Director of Public Works, Director of the Police and Fire departments and the head of the Tax Department. In 1934, the 10 Republicans and 5 Democrats on the council agreed to this shift in power, believing Loomis had the best interests of the town in mind. Republican Max L. Goldenthal was President of the Council for the three years he served. While Loomis served, he convinced the Council to take advantage of building money provided through the federal government’s Work Progress Administration as part of the New Deal.  The town built a town hall and library, financed about 45% by the federal government, on land that the First Church sold to the town to stay afloat during the Depression. The Democrats aligned themselves with the West Hartford Taxpayers Association, which submitted an alternative budget each year.

The new 1935 charter reduced the Council to seven members, five elected by district and two at large. The charter established the position of Council President which in 1947 became “mayor.” The council seemed willing to give up the day to day running of the town to Loomis where the previous councils were not so willing with Miller.

Loomis was known for being “gruff and business-like” and he ran the town efficiently. He stayed in his position for 22 years, until 1955, one year longer than Barry Feldman who just resigned after 21 years on the job.

In 2006, West Hartford is only on its ninth town manager in 87 years. A council that agrees to be a policy making body, not an administrative body, and a non-partisan manager seem to be a successful combination. At this rate, new Town Manager Jim Francis should take us through to 2020!
