## Helen Van Dyck Brown and the Oxford School {-}

*Originally appeared in West Hartford Life, August 2003. Sources for this article include the interview by Mims Butterworth, The Kingswood-Oxford Magazine Spring and Winter 2002, and Oxford Remembers.*

In a democracy based on merit, education is often viewed as the path to a successful life. Most people who consider education in this way speak about public schools. In West Hartford, realtors would tell you that many people move to town for the public education system.

But, every year about 10% of the secondary school students in town attend private schools. West Hartford has several private and parochial schools and the Oxford School, which was founded in 1909 and merged with Kingswood in 1972, is one of them.

Mims Butterworth’s interview with Helen van Dyck Brown in 1997 illuminates the value of a private school education. She taught science at Oxford from 1931 to 1970, and lived in West Hartford in the Sunnyreach neighborhood, just north of the University of Hartford off Bloomfield Avenue, starting in 1940. Her personality, her intellect and, some might argue, her antics made for a memorable teacher and a memorable education for her students. Van Dyck Brown graduated from Barnard College in 1927 with a major in Biology and a minor in the Fine Arts. When she went to Oxford, she taught both Biology and art.

Oxford was first established as a “country day school.” In the early 20th century, there were private boarding schools, but the philosophy of the day school was that teachers and parents had to work together to shape the bodies, minds and character of young people in a setting away from the hazards of the city in a wholesome school environment. When the school was founded, Hartford had over 100,000 people, while West Hartford had only about 4,800 residents and was still more of a farm town than a suburb.

What makes a private school worth paying for? For some it is the low teacher to student ratio and the high level of involvement of the faculty members in the school community. It is the sense of belonging that is built around a common moral and educational purpose, shared ideals, and the sense of empowerment and control that comes with a small, private community.

The Oxford community was just such a place; teachers pulled on their strengths and interests to foster lifelong learning. Before van Dyck arrived at Oxford, it enrolled students from Kindergarten through the 12th grade. In 1924 for instance, Oxford had an enrollment of 103 students, 81 girls in the junior school and 22 girls in the high school.

By 1931, enrollment had grown to over 250 despite the Depression. Between 15 and 20 girls graduated each year from Oxford in the 1930s. Until the 1930s, most girls attended Oxford and then went on to boarding school and “finished” there. Often only four or five students graduated from the school in the 1920s. But, starting in 1936, the school discontinued the primary grades and focused more on being a college preparatory school.

For van Dyck Brown, after she married in 1933 and had her own two children, she sent them to Oxford’s Junior School. In the 7th grade, she sent them to Hartford’s Noah Webster Elementary School. She said that in the early 1940s, “We didn’t think much of the West Hartford School system, so we sent them to Noah Webster.” She thought the Hartford Public Schools could provide “a rough and tumble type of schooling to make it in the world.” Her sons went there for two years until they could go to Loomis.

When van Dyck arrived at Oxford, the curriculum depended, to a great degree on the background of the teachers. The philosophy was to expose students to a breadth of academic subjects and the arts. Girls took American History, English, French, Latin, mathematics, geography, penmanship, spelling, physical education, cooking and sewing classes, gym, singing, and piano. Each day began with a non-denominational Protestant chapel service. By the 1940s, service became a top priority and students got involved in community service projects as a regular part of the school experience. Promoting democracy and individual responsibility were official visions of the school. The administration and teachers wanted to educate the heart, the body, and the mind.

Van Dyck remembered lunch time when teachers and students were served a hot dinner. The faculty and students ate together and the faculty was to remind students of their table manners in their continuous effort to educate the whole child.

In good weather, the students walked from Highland Street up Fern Street past the hill where Mt. St. Joseph Academy stood (Vanderbilt or now West Hill) until the paving ended at Quaker Lane. Dancing, basketball, track and field, soccer, and gymnastics were some of the physical activities provided for the young women.

When she first arrived, during the Depression, she did not have a full schedule and she was asked to teach manuscript writing. This was a new movement, to teach what we would call “printing” today, instead of script. Van Dyck read up on it and taught it. She gave a lecture on it to parents and this is how she met her husband, Wallace Brown. He was a doctor in Hartford, and had a daughter attending the school. She was only one of two married women teachers at Oxford in the 1930s.

Faculty members realized their fortunes were tied up with the school as well, and when van Dyck first arrived at Oxford, she and other faculty members agreed to take a 20% pay cut.

Van Dyck was famous for her science course. She turned the “Nature Study” program at the Oxford School into a Science Department in the 1930s. Van Dyck hired a chemistry teacher and taught a General Science course to give the school a Science Department. That was in 1933. Van Dyck Brown’s reputation was to bring the real world into her classroom, teaching ecology early on, and getting the students involved in labs.

Van Dyck Brown was also famous for adding a course in basic auto repair. She taught the girls about engine parts and how to do basic maintenance repairs. One student claimed this was the most valuable course she ever took.

In a tribute of “Van” written by colleague Muriel Forbes, she describes her room as the Porch Room which looked out on Prospect Avenue and had quotations on the blackboard, not necessarily about Biology, but about life. She challenged the students to think about their relevance to what they were studying and to their lives outside the classroom. This practice fit well with the model of educating the whole student.

In early June 2003, the Kingswood-Oxford Middle School at 695 Prospect Avenue saw its last private school students. Many of the buildings will soon be torn down, though the original mansion, bought by Oxford in 1924, will remain and the town of West Hartford will build a magnet middle school incorporating this building. The spirit of a love for learning, building a sense of community, and educating head, heart and body will continue at 695 Prospect Avenue, but this time as a public school.
