## The League of Women Voters: Defining Citizenship {-}

*Originally appeared in West Hartford Life, October 2010*

In February 1920, suffragists founded the League of Women Voters to crusade for “the success of democracy.” The founders of the non-partisan organization figured that their job would take five years to teach the 20 million new women voters how to participate in a democracy and then they would disband.

Ninety years later, the League continues its work. The West Hartford League, founded in 1923, continues to educate voters and help get out the vote, making West Hartford a model town for civic engagement. How League members defined what an educated voter knew is instructive to us as we look to vote in November 2010.

When the West Hartford League first began in 1923, according to past-president Mary Everett, the meetings were social. The League secretary noted “November 3, at the home of Mrs. S” where members gathered in hats and gloves and drank tea, socialized and often listened to a speaker.

Soon, though the activist women realized that socializing was not doing enough to educate new voters. By February 1924, Mrs. E.E. Stiles president, said that the league would organize a “motor corps” to drive women to the Town Hall to register to vote. The League targeted West Hartford’s 2,200 women voters who had not registered. The movement was purely non-partisan and the idea was to “waken the women to their civic responsibilities.” They registered 940 voters out of a population of 9,000.

At the local election in mid-March 1924, West Hartford residents cast twice as many ballots as ever before in West Hartford’s history. Mrs. Ivar Lundgaard, of the West Hartford League entered a contest with *The Woman’s Home Companion* magazine on behalf of the League and won! The magazine editors knew only 26% of newly enfranchised women had exercised the franchise and they encouraged groups to share their success stories. The West Hartford League won $150.

Once the women were registered to vote, the League offered classes to educate new voters. Members needed to know about state and local issues and chairs of committees took on the task of educating their members. Those who came to the March 1924 meeting heard Mr. Christopher M. Gallop, president of the West Hartford Chamber of Commerce, talk about West Hartford elections. Gallup, an officer at Travelers Insurance Company, was one of the first advocates in West Hartford for the Council-Manager system of government and he helped make West Hartford the first in Connecticut to adopt this system in 1919. Gallup and his wife lived on Steele Road, and Mrs. Gallup served as Secretary on the Board of the League. She became involved in the national League and traveled as a delegate to several national conventions in the 1920s.

Gallop lectured on how to vote in local elections. In the 1920s, voters chose their 15 Town Council members by district. Voters chose five councilors from the East District, five from the Center, three from the Charter Oak District, one from South District, and one from Elmwood. Republicans controlled the town, but the Council was seen as a bipartisan affair, with healthy debate about police protection, roads, and educational spending.

The Town Council appointed the Board of Education. Women were thought to have more interest in education, but the first women did not get appointed to the Board until 1931. Two women were appointed in that year, Grace Honiss and Mrs. Edward Lorenz; they both had been elected to the Town Council as well.

Louise Duffy, president of the Parent Teachers Association spoke on “Two Types of Politicians” and distinguished between machine politicians, who she said worked for their own interest, and the type of politician who served the common good. Duffy, who had just come off her loss in a 1924 state election, was married to Ward Duffy, the editor of the *Hartford Times*. She had a reputation as a liberal with an iron will.

That year, Duffy ran for State Senator as a Democrat in the 5th Senatorial District. She shared the podium at a political rally at Yale in October 1924 with New York’s Governor Alfred Smith and Alabama Governor Brandon. Duffy ran against West Hartford’s Republican Representative Huntington P. Meech. Duffy did not carry a single town in the district. According to the *Hartford Courant*, “no doubt many Democrats voted against her on account of her pledge to vote for ratification of the federal Child Labor Amendment if elected.” Though she lost this election, her advocacy for democracy and for children continued, as she became chair of the State Child Welfare Association, a member of the Library Board, and a member of the Board of Education for 11 years from the late 1930s to the 1940s. She was a delegate to the Democratic National Convention from West Hartford in 1932.

While Duffy ran for Senate she served as the chair of the special committee on the Citizenship School of the League. Duffy organized the first school conducted by a local unit in the state. She ran the “school” over the course of three weeks.

The first set of lectures was on the machinery of national, state, county, and town government. Professors from Trinity College and Columbia University ran these sessions. The second course focused on World Politics. Lectures included The World Today and America’s Part in It, History of the Peace Movement, Europe and the World Peace Movement, and How Shall We Lessen the Possibility of War?

The second set of lectures addressed political culture in the United States with sessions dedicated to a History of Political Parties in the United States, a Study of Platforms focusing on economic and political theories, honesty in government, education, civil service, conservation, foreign relations, tariff, taxes and finance, agriculture, labor, railroads, and civil liberties.

Even without television and the internet, Duffy’s attendees must have felt well equipped to cast their votes in November. The next spring she ran again, this time for Town Council from the Center District and lost. However, she continued working for the common good through the league, the Parent Teacher Association and then the Board of Education.

As election day draws near in 2010, the League of Women Voters, now 90 years old in Connecticut and 87 years old in West Hartford, continues its bipartisan work to educate voters through candidate debates and voter profiles. In 2010, the press has so few reporters covering local elections, finding out about the candidates and their issues is left to the League and our local access channel WHCTV. Their work to forge a successful democracy is an on-going project for all citizens.
