## A West Hartford Woman’s “Success” at Travelers Insurance Company {-}

*Originally appeared in West Hartford Life, March 2013*

West Hartford’s Eleanor Boyle’s obituary from August 14, 2012 said, “Prior to retiring in 1985, Eleanor was a Purchasing Agent at Travelers Insurance Company for 47 years.” When I read this line, I realized I had interviewed Boyle 27 years earlier in 1989 for a study of working women at Travelers. Her successful career at Travelers from 1938 to 1985 symbolized the role of women in the white collar workplace in the mid- 20th century.

Successful careers for insurance men and women took distinct paths into the 1980s. Though the same success rhetoric was trumpeted to men and women, the company made sure that “success” applied differently to men and women. While successful men became company officers, women rose to become an officer’s private secretary, or a supervisor of women in the steno or typing pool.

In the new white collar workplaces of the 20th century corporation, management developed job ladders which men climbed, not through years of experience, but by merit. Men advanced by being comparatively better than other men. This encouraged the competitive spirit between white-collar workers while blue-collar workers tended to develop a more cooperative spirit.

For a long time, labor historians and employers assumed women did not strive for success or have ambition. Eleanor Boyle belies that assumption. Historians, like the employers, assumed women would be docile and compliant in the workplace. These historians assumed that women resigned themselves to their fates in boring and repetitive jobs with few if any chances for meaningful promotion. Most women expected that they would work only for a few years until they married, and therefore had no reason to be ambitious.

But for women like Boyle, who never married, their work lives broke the mold. Women’s historians have taken a different look and showed that women developed their own work culture to take some control of their workday and developed a woman controlled culture at work. And, at Travelers, women were encouraged to “push for success.”

Boyle entered the workforce a month shy of her 18th birthday in 1938, near the end of the Great Depression. She vividly remembered her first day at work in the stenographic department. She had applied ten times before she finally got the job. Boyle graduated from Stafford Springs High School and because she couldn’t get a job, she moved in with her aunt in Hartford and went to Morse’s Business School. The Depression hadn’t let up, so she went to Morse’s during the summer and then after Labor Day. She said she used to cry when she saw the other kids on the bus going to to work because she didn’t have a job. Finally in the Fall of 1938 she was hired at $14 per week. By that time, the federal government had started taking a Social Security out and her wages didn’t go far.

Boyle worked first as as an ediphone operator where she had “things in her ears all day long.” She took dictation from cylinders. By 1940, she went out and took dictation directly from an officer and then come back to the steno pool and typed it up. She worked in the steno pool for about 4 ½ years. Her supervisors kept track of her production by measuring the amount she typed with a ruler.

Then she got the opportunity to take dictation from Miss Gilbert, an officer in the Group Department steno pool, whose “girl had left.” She was a “nervous wreck” on her try out, but got the job as her secretary. According to Boyle, “all the women in the stenographic were women; there weren’t any men in those days.” She worked for Howard for eight years.

In 1950, she was promoted to an administrative assistant of the steno pool. Finally in 1959, after 21 years at the Travelers, she became the first woman buyer in the Purchasing Department. When she was offered the job, Mr. Smith told her to go home and sleep on it to decide if she wanted it. Boyle asked if this was a better opportunity, and Smith replied “yes.” Boyle said, “I don’t have to go home and sleep on it, I’ll take it.” For Boyle, perseverance, loyalty, and good work paid off in a higher position with the company.

Once she joined the purchasing department, none of the men with the same job helped her. They didn’t want her there. She had two friends who helped her. One was a secretary (with whom she shared an apartment) to the Purchasing Agent and another was the secretary to another officer who took her work and typed the orders to help her. According to Boyle, “the men were trying to defeat me and have me give up. But I was determined that I was going to make it. So I plugged along and it was a very interesting and very challenging job.” She found that the sales people from whom she bought various items also helped her.

In 1966 her big boss promoted her to Assistant Purchasing agent, but they never made her an officer. She said they played this promotion up in the paper as she was the first woman given the opportunity to be a buyer. But still, she did not get cooperation from any of the men in the office. She said “I always had the feeling that I had to work much harder at it than they (the men) did because they were watching all the time... hoping I’d stub my toe, but I guess they eventually respected me.”

Near her retirement in the early 1980s, she compared her salary with a young male co-worker who had been at the company for only a few years. She found that after more than 45 years at the Travelers, she made only $1,000 more per year than he did. She was never made a company officer.

Finally, by the mid-1980s, when Boyle was ready to retire, she found that they were starting to promote women. Even in the mid-1980s, she said, there was still a feeling that they weren’t going to push a woman. Or they would have “little pets” who they would promote, but there was not a program to promote women. Finally, they gradually began to bring “girls” into jobs. In the end, Boyle said she “had a very happy time in the Travelers.” But she still resented that “of all I gave to the company, they didn’t make me an officer.”

While opportunities for young women began to open up, and Boyle could say that for women “times have changed,” she was stuck with a set of lower expectations for women that kept her from reaching her potential or getting the pay and benefits that she could have earned had she been a man.
