## Remembering Beach Park School {-}

*Originally appeared in West Hartford Life, September 2000*

West Hartford has long prided itself on its excellent school system. Even before it came out from under the shadow of Hartford’s nationally recognized schools, West Hartford believed it was on the leading edge of educational philosophy and innovation. Whereas excellence today is measured by standardized national and state tests, in the first half of the 20th century, some educators measured success differently.

In 1949, West Hartford Superintendent Lloyd Bugbee ran a school system which claimed to set trends around the country. He wrote:

> The things which we prize most, cannot be pictured, viz. the kind voices, the happy, eager faces, the glad exclamations, the joy of accomplished tasks, the pride in work well done, the growing children, and the general hum of happy industry. More and more do we need to seek the teacher who considers these to be of equal importance to the accumulation of facts --- the teacher who desires to make each individual child in her classroom a more complete, wholesome and happy personality.

Bugbee believed that the education provided at the Beach Park School, built on Steele Road and opened in February 1926 embodied this philosophy.

As West Hartford’s population grew at the turn of the century from 3,100 in 1900 to 8,800 in 1920, the town had to adjust the way it educated its children. Superintendent William H. Hall consolidated the system of one-room district schools spread throughout the town in the early part of the century. These one-room schoolhouses had desks nailed to the floor and teachers who taught mainly by rote. The town began to invest in larger elementary schools, building Charter Oak School, in 1884 for grades K through 8 and the Center School (later Whitman School, the Hall High School Annex, and the Police Station) in 1896 as an elementary school. The Seymour School (later Smith School) opened in 1915.

But it was the Beach Park School that helped put West Hartford on the educational map. With five acres of land donated by T. Belknap Beach (grandson of the founder of Travelers Insurance Co.) in 1925, the Beach Park School was the first in West Hartford to be built in a park-like setting. Beach wrote in the deed that no trees could be cut except for park purposes. The architect designed a building that was more like a home than an institution. The colonial structure and color scheme for the three-classroom building, finished in 1926, were a departure for school buildings.

The Kindergarten Room exemplified this new educational philosophy. By the 1920s, educators realized the importance of education before students could grasp the “3 R’s.” The Kindergarten room resembled a large beautiful living room. It had an open fireplace at one end of the room, a four-foot basin with live goldfish, a piano, a slide, doll furniture, children’s rockers, and a sand table. Instead of bolting furniture to the floor, teachers could move the new furniture to adjust the classroom to the children’s daily needs. Educator John Dewey’s Progressive education ideas found a home in West Hartford.

According to Bugbee, a school should have a “happy atmosphere and freedom which the preschool child enjoys at home. It is a place where children may live together working, playing and learning as they might do in a happy family.” The building enhanced the teachers’ abilities to reach these goals.

The curriculum in the Kindergarten and the two primary classrooms, combining Grades One and Two, and the other, Grades Three and Four, began with the child’s interest and experiences. The teachers at Beach Park believed students learned by doing. They believed that once children had lived through an actual experience, it became the pupils’ own with a much fuller meaning than reading from a book. Thus, students took excursions and wrote and performed plays that gave them skills to meet a changing world.

West Hartford’s practice of establishing a “model school” began with Beach Park. In 1927, the Fern Street School and in 1928 the Elmwood School both opened, patterned after the Beach Park School. Educators based both on the progressive education model, built in park-like settings, with movable furniture.

Beach Park’s three-room schoolhouse was soon bursting at its seams. West Hartford’s population grew from about 8,800 in 1920 to about 25,000 in 1930 to 44,000 in 1950. When the Hartford Golf Club sold some of its land, now known as Golf Acres, for development, enrollment grew even more. In 1929 the school added four classrooms giving the school one classroom per grade. In 1947, after a legal battle, the town took down trees to build a ball field. In 1949, administrators added an auditorium/playroom, a small kitchen, and a teachers’ room. The last remodeling as a public school came in 1961 adding an enlarged office and a conference room.

By the 1960s, Beach Park had become something of an anomaly in town. With 13 other elementary schools, all at least twice as large, Beach Park became, according to a 1972 *West Hartford News* editorial, something of a “private country day school serving wealthy and socially prominent families in the northeast quadrant of town.” It was the only elementary school in town without a cafeteria. Students still walked home for lunch. Parent volunteers staffed the library. The public school closed in 1972, the victim of a restrictive deed, the beginning of declining school enrollment in West Hartford, and a desire for socio-economic integration in the elementary schools.

In 1999, the Beach Park School reopened as Saint Joseph College School for Young Children. Much of the philosophy of the public school, embodied in both educational values and architecture, has been retained at the pre-school. The homelike atmosphere, the use of the outdoor woods as classroom, and the idea that education is based on actual real life situations are all part of the early childhood education center.

The practice of model schools continues with West Hartford’s magnet schools, which have included Smith, Charter Oak and Norfeldt. School administrators give teachers in these schools the freedom to try innovative educational techniques in the hopes that they will become an integral part of the curriculum of the other schools. Town-wide math and science curriculum and foreign language instruction in 4th and 5th grades are a result of the innovations in these magnet schools. The School for Young Children in the restored Beach Park School is one of two Model Lab Schools in Connecticut. Visitors from all over visit the school just as they had visited the Beach Park School over a half a century ago.

In 1949, Superintendent Lloyd Bugbee argued:

> If knowledge is to be loved for its own sake that which is now abstract and remote would be wedded in some way to practical life... We believe that the system at the Beach Park School is calculated to foster the child’s curiosity, to make the desire for knowledge a chronic and habitual one and to familiarize each child with the best methods of acquiring it by his own efforts.

Bugbee’s educational philosophy, articulated in relationship to the Beach Park School, continues to make West Hartford’s school system excellent today.
