## Atwood Collins {-}

*Originally appeared in West Hartford Life, July 2003*

In 1997, the Noah Webster House began an oral history project and collected ten interviews with long time residents. Atwood Collins (1917-2004) was one of those interviews. His story helps to develop the texture of life in the growing suburban town for a successful young lawyer.

When Atwood Collins’ mother gave birth to him in 1917, she was at home on 35 North Quaker Lane. Their home was surrounded by a dairy farm owned by the Griswold family, and as he looked toward Fern and Asylum, he saw farmland, not houses. In the 1920s in West Hartford, daily life would have been a lot different than it is today. The population stood at about 9,000, the trolley had been running through town for almost 30 years, and cars were starting to be used for commuting, not just leisure time drives.

Collins’ childhood reflects more the life of a rural town than a suburb. Collins remembered sledding from Mt. St. Joseph Academy, which the Sisters of Mercy opened in 1908, on West Hill to the pond at the base of the hill. At the corner of Frederick Street, on land still owned by Mt. St. Joseph, Collins remembered a baseball diamond.

The horses from Troop B, what we now know as the Governor's Foot Guard, were housed at the armory on Farmington Avenue, in smelling distance of his house.

In kindergarten and first grade, Collins attended the East School on the corner of Farmington Avenue and Whiting Lane. From second grade to sixth, he went to the Fern Street School on the corner of Bretton Road and Fern Street. Morley School opened in the late 1920s at the end of his time there. Then he went to Kingswood, which moved from the Mark Twain House in 1922 to its present location. In his day, in the late 20s and early 30s, Collins related, Kingswood Masters wore mortar boards during the day and they wore black gowns to class. Only seniors could walk on the green around which the four classroom buildings stood.

Where Wood Pond is today, Collins remembered the Trout Brook Ice and Feed Company’s ice storage building. Korszak Ziolkowski, the man who carved the Noah Webster Statue in 1941, lived near there. He remembers the iceman coming every week to his house with ice tongs and a block of ice over his back. He remembered an Italian man who drove a vegetable truck through their neighborhood as well.

M.J. Burnhams, the grocery story in the center was where everyone shopped (until it closed in 1958), according to Collins. From Quaker Lane, his family would have gone west on Farmington Avenue, which, until the late 1920s was not paved between Trout Brook and Main Street. Steps lined the front of the store. Burnham had, according to Collins, a “tremendous following; everybody loved him.” Everyone who shopped there had credit and they paid for their groceries per month. According to Collins, “MJ Burnham was a real institution.”

![Myron Burnham opened his grocery store in 1898. At its peak, he had 60 employees, including people who delivered groceries, stockers, and switchboard operators. When the grocery closed in 1958, the First National Supermarket, a grocery chain, opened just south on South Main Street and Burnham’s building was torn down to make way for its parking lot. Source: Noah Webster House & West Hartford Historical Society](images/07-collins-burhnam-web.jpg)

Collins graduated from Yale College and then Yale Law School in 1942. Right out of law school, at age 24, Collins was appointed State Department Vice-Consul in Punta Renas, Costa Rica. He first went to the School of Economic Warfare, US State Department in Washington D.C. to get trained on economic warfare where he “learned how to put Germans and Italians out of business in all of Latin America.”

The State Department had a blacklist. When he got to his town in Costa Rica, he must have been shocked to find Germans in the street goose-stepping. The Germans and the Italians sank two boats in the harbor to make trade difficult. Part of Collins’ work was to document Argentina’s Juan Peron’s complicity with the Germans during the war. This helps explain why so many former Nazis escaped to Argentina after the war.

He did this work for two years, and then served in the Army from 1944 to 1946, participating in the Occupation. In 1945, as the Political and Liaison Officer to the U.S. Delegation, he attended the San Francisco Peace Conference. He was at the first meeting of the United Nations as a specialist in Latin American affairs representing the State Department. When the war ended, President Truman sent him to the Nuremberg War Crimes Trials where he interrogated Von Ribbentrop, the Foreign Minister of Nazi Germany, 1938-1945. Von Ribbentrop was convicted of helping to start World War II and engineering the Holocaust. In October 1946, he was the first of those sentenced to be hanged.

Collins’ keen recollection of these events revealed just how important they were to the development of his world view.

When Collins’ turned back to civilian life and professional life in 1946, Day, Berry & Howard, hired him as a lawyer at $25 per week. There were 12 men on the stationery at that time. Mr. Conning of Conning and Co. lived next door to Collins and advised him to invest in Connecticut General stock. He did, and that, according to Collins, is what allowed him to live.

Collins raised his family in Sunset Farms and became a member of the Asylum Hill Congregational Church in Hartford. He gave back to the community through his work as a founder of University of Hartford, President of the Board of the Mark Twain House, the board of the American School for the Deaf, and he served on the West Hartford Town Plan and Zoning Commission.

Collins’ oral history, which can be listened to at the Noah Webster House, is a reminder that our memories of growing up are an important part of a larger enterprise. Matched with other primary sources, these memories can help us to understand the events and values of life at other points in time. His experiences in the military and at the Nuremberg Trials helped him to understand the importance of a participatory democracy which he helped to build here in this growing suburb.
