## Women in the General Assembly {-}

*Originally appeared in West Hartford Life, October 2006*

On November 7, 2006, West Hartford voters will have the chance to do something they haven’t done in 22 years: elect a woman to the state legislature. Republican Barbara Carpenter and Democrat Beth Bye are squaring off in the 19th District, guaranteeing that the 19th District will be represented by a woman.

West Hartford has a long history of electing women to public office, but the road to elective office has not always been easy. Most of those elected came through the “training ground” of the League of Women Voters, not through traditional political channels.

The League began as a continuation of the Connecticut Woman Suffrage Association. Louise Duffy helped organize the West Hartford League in September 1923, (two years after the state and national Leagues) just three years after women won the right to vote. The leadership in the Connecticut Woman’s Suffrage Association and the Connecticut Women’s Party became the leadership in the League.

In 1929, Grace (Mrs. William T.) Honiss, the Vice President of the League was elected as the first woman to the West Hartford Town Council. At that time, candidates ran in each of five districts to gain a West Hartford Town Council seat. Honiss, of Concord Street was a Republican and ran unopposed. She graduated from Wheaton College in 1921, so may have been only about 30 when first elected. She was elected again in 1930 and 1931.

In 1930, a *Hartford Courant* article proclaimed, “Women Want School Board Memberships.” A group of women circulated a petition to the Town Council, asking for a study to enlarge the Board to make room for women to serve. Until 1958, the Board of Education was appointed by the Town Council. Honiss started the petition among women in the League of Women Voters. The petition had some effect as Honiss was appointed to the Board in 1931 at the same time she served on the Town Council.

In 1931, Mrs. Edward Lorenz, at age 45, was elected to the Town Council. She, like Mrs. Honiss, was also appointed to the School Board. Lorenz lived on West Hill Drive and was involved in the League of Women Voters, the YWCA, the Charity Organization Society, and the Community Chest.

Louise Duffy, as early as 1934, was considered to be one of the “New Guard” leaders of the Democratic Party in the state at the same time as she served as the Vice President of the Connecticut State League of Women Voters. Duffy was an avid Democrat and she was involved on the local, state and national levels. She was the vice president of the Connecticut Federation of Democratic Women’s club. One of her favorite memories was sitting in the front row for Franklin Roosevelt’s speech which included “we have nothing to fear, but fear itself.” She was the chair of the state Child Welfare Association and a member of the Connecticut Public Welfare Council. She also helped to found the Hall High PTO. Duffy served on the town’s library board from 1936 to 1938. She was appointed to the school board in 1938 and served until 1948. In 1946, as a member of the League and the Board of Education, she helped write a press release urging the Town Council to appoint another woman to the Board of Education. Because of her dedication to the education of children, in 1950, the Board of Education decided to name the next elementary school for her.

Between 1948 and 1974, a number of women won election to the Town Council and the Board of Education. But it took until 1974, for a West Hartford woman to be elected to statewide office.

In 1973, Democrat Joan Kemler began her bid to be the first West Hartford woman elected to the state legislature. Kemler got her start in politics, like the three women before her, in the League of Women Voters. In the early 1970s, Kemler was Vice President of the United Way of Greater Hartford. As a woman, Kemler was shunned by Democratic Party Chair Harry Kleinman and the Democratic Party and was forced to a primary. In the primary, she defeated the party endorsed candidate and a petitioning candidate, both male. Kemler was interested in expanding Project Concern (now Project Choice) busing program and was accused of supporting “reverse busing.” In the campaign, she stated clearly that she did not support reverse busing.

Kemler believed that some people were interested in her candidacy because she was a woman. In the November election, she won 6,800 to 3,500. She was elected five times from the 18th District between 1975 and 1984.

Republican Dorothy Barnes was the second woman elected to statewide office for three terms from 1977 to 1982. She first ran for the 21st Assembly District which included Elmwood and Farmington. She ran against Tom Clark first in 1974 and ran again in 1976.

Republican Maureen Baronian served the town in the state legislature for three terms between 1981 and 1986. She was a stockbroker who ran and won in 1980.

Republican Anne Streeter served in the state Senate from 1981 to 1986 after serving on the Town Council from 1975 to 1981.

Though neither candidate for the 19th Assembly District in 2006 had their political education in the League of Women Voters, both women will be beneficiaries of the League’s involvement in local elections. When they square off in the League’s debate and answer the Voter Guide Questionnaire, they will become part of the League’s legacy here in town.
