## Studying African-American Migration to the Suburbs {-}

*Originally appeared with co-author Katie Campbell in West Hartford Life, September 2010*

A few months ago, this column was about the discovery of restrictive covenants in West Hartford in the 1940s. Developers restricted where African-Americans could live in town and that clearly affected settlement patterns in the quickly growing suburb. But what were the patterns before the suburban developments?

We do know that African-Americans were enslaved in West Hartford during the time of the American Revolution and we know that some, like Bristow, bought their freedom and lived in their own households.

It is not clear how autonomous African-Americans were through the 19th century and into the 20th century, but by 1930, it is clear that three quarters of West Hartford’s African-Americans lived as servants in white people’s homes. They lived in nine of 15 census districts, with the largest number in the Northeast section of town, in the Hartford Golf Club area.

As an historical source, the 1930 Census is rich. It reveals street addresses, home ownership, gender, race, place of birth, parents’ place of birth and occupation. While the census is but a list of information, it provides data on people who may not leave other records and provides a more complex picture of the emerging suburb.

The patterns of African-American settlement in Hartford in the early 20th century have been studied by sociologist Kurt Schlichting, of Fairfield University, and his colleagues in his 2006 article “Residential Segregation and the Beginning of the Great Migration of African-Americans to Hartford, Connecticut: a GIS-Based Analysis.” Schlichting and others explore the movement of African-Americans to Hartford in the first 20 years of the 20th century. His study showed a large increase in the African-American population in Hartford.

“In 1900, over 80% of the total African-American population of the country lived in the southern states of the former Confederacy. During that decade from 1910 to 1920, about half a million migrants made the journey north,” he said.

By 1920, African-Americans made up 3.1% of Hartford’s population and by 1930 it was up to 4%. Their level of independence depended on the jobs they could get.

By 1930, some African-Americans moved to the suburbs. West Hartford’s population grew to about 25,000 by 1930. But only 129 African-Americans were recorded in the 1930 census pages, making up 0.5% of the town’s total residents. Of these 129 people, only 30, or about a quarter, lived in a household they headed themselves.

One example of an African-American headed household was the Robinson family, who owned their home at 1070 Farmington Avenue, across from Riggs Avenue. The house was valued at $30,000. The head of household, Burrest, was 58 years old and had been married to Elizabeth for 22 years. He was born in Connecticut and his parents were born in Virginia and Massachusetts. He was a steamfitter and his wife was not employed. Burrest’s brother James was widowed and lived with the Robinsons. He was a gardener who helped to maintain the household. Economically, the Robinsons were independent.

The Backer family, who were white, lived on Arundel Avenue, not far from the Robinson’s Farmington Avenue home. Lloyd Backer, a 39-year-old, married Nettiebelle who was 33. He was an assistant general agent with an insurance company. The Backers had four children ages six months to eight years old. The wife Nettiebelle, who was not employed, was born in Mississippi and her parents were born in the South as well. They hired Mary McMiller, a 24-year-old “Negro servant,” to care for their family. Mary was not married. She was born in Georgia, but had probably moved north with the great migration of African-Americans during the World War I decade.

We can’t know what the dynamic was within the household, with the southern mistress. We can only guess about whether Mary ever interacted with the Robinsons, even though they lived about five blocks from each other.

We can imagine that Mary was busy.

On Mountain Road, an African-American family, the Plummers, and a white family, the Dewings, were considered part of the same household. Alexander and Gladys Plummer had been married for three years and in 1930 were listed as butler and cook, probably for the Dewing family. The Dewings, Harold (born in North Carolina) and Marjorie (born in New York), were both 46 years old and had been married for 21 years. Their house was worth $50,000.

Dewing was a real estate official. They had three teenage children in the household. It seems likely that the Plummers lived in a rear apartment or an out-building on the Dewing property and took care of the Dewing family.

Bloomfield’s demographic snapshot was quite different. That town’s population in 1930 had only reached 3,247, only one-eighth the size of West Hartford. The non-white residents recorded in the census numbers 121, almost as many as in West Hartford, and they made up a larger percentage of the town’s population at 4%. The east side of Bloomfield was nearly 5% nonwhite.

Unlike in West Hartford, there were no non-white servants in Bloomfield. In fact, 99% of non-whites in Bloomfield lived in a household that was headed by a non-white.

The majority of African-Americans living in West Hartford had varying degrees of autonomy. It is curious that both of the white families who had live-in servants had an adult born in the South.

Historians await the release of the manuscript census from 1940 in 2012 to see if these servant relations persisted and if there was an increase in economically independent African-American households. But from the patterns established in Bloomfield, it seems more likely that those African-Americans with means would choose Hartford’s northern rather than its western neighbor.

*Note: Katie Campbell is a senior at Trinity College working on the “On the Line” project with Prof. Jack Dougherty. She completed the 1930 census research and provided basic outlines of this article. Read more at <http://ontheline.trincoll.edu>.*
