## “Harmony, Cooperation and West Hartford First” {-}

*Originally appeared in West Hartford Life, January 2008*

A recent trip to Franklin D. Roosevelt’s library and home in Hyde Park, New York sparked a new interest in West Hartford during the Great Depression. It reminded me of asking my grandmother about the Depression when I was a young teacher. My grandfather had lost all his money in the 1929 stock market crash and my grandparents had gone from having two houses (one in Bronxville and one in Litchfield) and eight servants, to one house in Litchfield and one Irish servant named Bridie who worked for room and board. I still remember Grandma’s reply to my question about how the Depression affected her. “It brought the family together.” She remembered, in what historians argue is memory, not history.

In West Hartford, memories would definitely differ over the impact of the Depression. Welfare cases went up from 29 in 1929 to over 500 in 1934. Police officers and teachers took a 10% pay cut. But statistics that show growth in the town provide a more complicated picture than the grim national statistics and provide a view into a community that both suffered and thrived in the 1930s.

City directories, found both in the Town Hall and the Noah Webster Public Library provide a statistical view into a town on the move in the 1930s. Information from the 1930 and 1934 volumes represent ways citizens and government had to adjust to an economic downturn in which 1/3 of the workforce was out of work by 1934.

The 1930 and 1934 *Geer’s City Directory* pages about West Hartford start with the quote, “Harmony, Cooperation and West Hartford First.” Each volume provided a page of current statistics and a page on the town’s history. The tables below represent some of the changes town residents faced in the early 1930s.

Table 1: West Hartford Population and Services

| Year      | Population | Native born | Bonded debt | Library volumes | Telephones | Churches |
|-----------|------------|-------------|-------------|-----------------|------------|----------|
| 1930      | 24,936     | 85%         | $2,514,000  | 11,148          | 5,475      | 9        |
| 1934 est. | 26,817     | 85%         | NA          | 24,778          | 7,600      | 10       |

This first table shows the population growing by 7.5% in just four years. The number of telephones increased by almost 40%. This phone increase is partially due to families adding phone in their household, but may also show the ubiquity of phones by the mid-1930s. The phone became a necessary household item. During times of depression, use of the library increased. This must have included an increase in the use of tax dollars for the more than doubling of the number of volumes in the library. Even those without money could enjoy reading during the Depression.

Table 2: West Hartford Property and Financials

| Year | Assessed valuation | Mill rate | Bank deposits| Real estate transfers | Building permits | Value of permits |
|------|--------------------|-----------|---------------------------|----------------------|-----------------------|-------------------------------|------------------|
| 1930 | $70,471,990        | 20        | $2,055,663                |  1847                  | 345                           | $6,315,945       |
| 1934 | $64,458,830        | 16        | $1,800,000                |  1050                  | 93                            | $1,216,251       |

The statistics in Table 2 demonstrate a distinct economic downturn. The Grand List declined by almost 9 percent and the mill rate declined 20%. Clearly revenues for town government were down. West Hartford Bank and Trust, which opened in 1926, lost 12 percent of its assets in the economic downturn. Like other banks, it had to close because of Franklin Roosevelt’s Bank Holiday, directed in March of 1933. But it reopened and most investors kept their money there. Sale of homes dropped by 43%. The value of permits to build declined by 80% showing that building declined precipitously.

FDR’s New Deal stepped into the building vacuum by establishing the Public Works Administration, which sponsored the building of both the Town Hall and the Noah Webster Library in 1935.

Table 3: West Hartford Public Schools

| Year | Public School Pupils | Teachers | Pupils per Teacher |
|------|----------------|--------|----------|--------------------|
| 1930 |  4011   | 180      | 15                 |
| 1934 |  5078   | 189      | 27                 |

The rapid growth in West Hartford’s population from 1920 to 1930 led to the construction of six new school buildings: Beach Park (1926), Morley (1927), Elmwood (1928), Talcott Junior High (1922), Plant Junior High (1922), and Hall High School (1924). But who would guess that in the first four years of the Depression, when the Grand List and the mill rate declined, that the school population would increase by 27 percent? And yet, the number of teachers grew by only 5 percent. Student teacher ratios almost doubled in just four years. The increase must have challenged the teachers and administration; at the same time, teaching is seen as a “depression-proof” employment in that the number of students attending schools tends to increase during economic downturns.

Table 4: West Hartford Private Schools

| Year | Private Schools                   | Pupils | Pupils per teacher |
|------|-----------------------------------|--------|--------------------|
|      | Mt. St. Joseph Seminary for Girls | 181    | 9                  |
|      | Kingswood School for Boys         | 160    | 11                 |
|      | American School for the Deaf      | 212    | 7                  |
| 1930 | Total                             | 553    |                    |
|      | Mt. St. Joseph Seminary for Girls | 105    | 6                  |
|      | Mt. St. Joseph College            | 95     | 5                  |
|      | Kingswood School for Boys         | 150    | 11                 |
|      | American School for the Deaf      | 230    | 8                  |
|      | Oxford School for Girls           | 205    | 5                  |
|      | Fernwood School for Boys          | 25     | 8                  |
|      | Laidlaw Boarding and Day School   | 15     | 15                 |
|      | Westford School                   | 26     | 8                  |
| 1934 | Total                             | 851    |                    |

At the same time as the public schools student teacher ratio almost doubled, the private schools in town expanded and kept two to five times as many teachers per pupil as the public schools. Though times were hard, increasingly, West Hartford residents sent their children to private schools, both parochial and independent, with an increase of 53% over four years. When times were hard, parents chose small class sizes for their children. West Hartford’s first post-secondary school arrived in 1932 with the opening of Mt. St. Joseph College, a junior college that began with 63 students. By 1933, the college became a four-year school, established primarily to train teachers. It wasn’t until 1936 that the college moved to its present location on Asylum and Steele and was renamed St. Joseph College.

To survive the Depression, West Hartford’s government and business communities certainly yearned for “harmony, [and] cooperation...” to make “West Hartford first.” By analyzing the statistics of the era, the challenging times display contradictory evidence about standards of living dependent on economic status and age. West Hartford’s experiences in the early years of the Depression remind me how my grandmother’s memory could paint over the real difficulties people faced.
