## Universalists Celebrate 75 Years in Town {-}

*Originally appeared in West Hartford Life, July 2006*

The Universalist Church of West Hartford (originally known as the Church of the Redeemer) moved out of Hartford 75 years ago, following the pattern of St. John’s Episcopal Church which moved out of the city in 1907. St. Brigid Roman Catholic Church was established in Elmwood in 1918 as a mission church of St. Lawrence O’Toole in Hartford, and presaged the move of Congregation Beth Israel in 1936. The movement of these houses of worship fueled and reflected the movement of people to West Hartford and increased the religious diversity of the town.

West Hartford’s only church until 1855 was the Congregational Church in the center of town. St. James Episcopal (1855) on South Main Street where Friendly’s is today, and the Baptist Church (1859) on the site of the Farmington Savings Bank in the center were followed by the Elmwood Chapel (1876). St. John’s and St. Brigid brought the number of churches in town to five.

In 1920 the Swedish Methodist Church on the Boulevard was built and the next year a Swedish Lutheran Church opened on Park Road near Oakwood Avenue, reflecting the large number of Swedes who moved here in the first two decades of the 20th century.

In 1926, St. Thomas the Apostle moved to Farmington Avenue, just east of Trout Brook and then in 1931, the Church of the Redeemer (the Universalist Church) opened on Fern Street. It was the first church built in town north of Farmington Avenue, and it was built on open land. In 1936, a third house of worship, Congregation Beth Israel, moved out of Hartford to Farmington Avenue following the suburbanization trend of the Episcopal and Universalist churches, bringing the total number of houses of worship to ten.

West Hartford was well on its way to being a suburb when the Universalist Church opened at the beginning of the Great Depression. The population grew from about 9,000 to about 25,000 in the previous decade. Between 1922 and 1931, the town built eight schools including three junior high schools and a high school. The only two built north of Farmington Avenue were the Beach Park School on Steele Road and Morley School on Fern Street, showing that development in the north and west ends of town was only beginning.

The Universalist Church of West Hartford opened its doors to the townspeople on Monday, April 5, 1931. According to the *Hartford Courant*, “throngs of people visited the buildings of the new Church of the Redeemer, on Fern Street, West Hartford.” In 2006, the church celebrated its 75th year in West Hartford; its tradition of being a free liberal faith continues.

When the church was built on Fern Street, there was only one other house, built in 1930, on the stretch of Fern Street between Trout Brook and Main Street. Plots had been laid out in the neighborhood just to the north, with a number of houses on Linwold Street built between 1928 and 1931.

About this time, the town had begun to feel the effects of the Great Depression and Town Manager Benjamin Miller developed public works jobs for unemployed men in town, working in the town parks, helping to dig sewers and work on the roads. The welfare rolls increased, and Miller felt it was necessary for the government to intervene to stop the downward cycle. He would have embraced the building of the Church of the Redeemer at 433 Fern Street for it provided jobs for masons, bricklayers, electricians, plumbers and carpenters.

The Church of the Redeemer’s journey to Fern Street began back in 1821, when Boston’s Hosea Ballou preached in Hartford, proclaiming that there was no punishment for sins after death. He preached that love, not sin, was the most powerful force in religion. He believed that atonement, or as he called it, reconciliation, not damnation, was at the core of a person’s relationship with God. He preached about the holiness and happiness of all people; he believed that the spirit of the gospel of the Son of God was to love your enemies, and render good for evil.

Ballou’s beliefs were radical in the early 19th century, especially when the ideas of the Second Great Awakening swept the eastern seaboard as evangelicals tried to fend off the spread of religious rationalism. According to these religious revivalists, converts had to submit totally to a vengeful and all powerful God. Those who were “born again” believed that a life of good works on earth could earn grace in the eyes of God at death. The Universalists reacted to the evangelical belief that there was judgment at death. For Universalists, God was a God of love who did not judge. They were laughed at and ridiculed for this belief. When Ballou first started preaching, there were about 18 Universalists ministers in the whole country, and by the time he was buried in 1852, there were over 800,000 Universalists. In 2006, there are over 1,000 congregations in the United States.

Ballou’s message hit fertile ground in Hartford and disgruntled Congregationalists formed the “First Independent Universalist Society of the City of Hartford” and by 1824, built their first meeting house on Central Row across from the Old State House. By 1860, this building was too small and the church moved to the location of the present day Travelers Tower. In 1906, the church moved west to Asylum Hill. There was a time in the 20th century when it was thought the Universalists would merge with the Asylum Hill Congregational Church, but it kept its own identity. Each of the first three sites was prime real estate and each sale paid the expense of building the next church.

In November 1929, just a week after the stock market crashed, the church voted to erect a new building in West Hartford. They gathered $13,000 within the next eight weeks to buy the plot of land, and with the uncertainty of the economy, their hope, and their faith, they went ahead with their plan. Walter Crabtree, a Hartford architect designed this colonial revival church as well as many houses in West Hartford in the 1930s. The congregation laid the cornerstone in 1930, and the building was finished in the early spring 1931 at a cost of $185,000. Richard McLaughlin was the first minister in West Hartford.

The congregation continued to grow at the Church of the Redeemer. In 1961, the Unitarians and Universalists merged to become the Unitarian Universalist Association. In 1962, the name of the West Hartford Church changed to The Universalist Church of West Hartford, and an addition was built which included classrooms and a multi-purpose hall. The membership of the church peaked in the late 60s and early 70s, just as the population of West Hartford topped out at about 73,000. The church is growing again, signaled by the reinstatement of two services on Sunday in 2001, with the vigorous leadership of Rev. Jan K. Nielsen, providing a home for religious liberals from around the region. Today the Universalist Church of West Hartford is one of the twenty largest UUA congregations in the country.

The town of West Hartford matured as a suburb in the last 75 years. The area around the Universalist Church is completely developed. West Hartford offers almost 40 different houses of worship, which is four times more than the ten offered 75 years ago. The wide variety of religious choices is a unique strength of the town.
