## Shelter from the Storm {-}

*Originally appeared in West Hartford Life, December 2011*

Conard High School’s transformation into a shelter from November 1 to 8, 2011, marshaled many town and social services to care for more than 350 people who visited the shelter daily. This unprecedented use of the school during the natural disaster caused by the early snowstorm made me wonder how the town dealt with the flood in 1955.

West Hartford’s response to the ’55 flood got tangled up in World War II housing which the town had been trying to demolish for four years.

The Lanham Act, passed in 1940, permitted the use of federal funds to build public housing for defense industry workers. The government shifted from building housing for the poor to building housing for war workers as war industries began to boom. As workers migrated to the cities to take factory jobs they needed places to live. The federal government made this part of the war effort, suspending traditional public housing construction but expediting the construction of war worker housing administered by local public housing authorities.

West Hartford’s three war housing projects, Elmwood Acres (on Elmhurst Street) with 300 units, Oakwood Acres (where Kennedy Park is today) with 335 units, and South Quaker Terrace with 159 units, (on Quaker Lane near the National Guard) all opened between 1942 and 1943. Oakwood Acres and South Quaker Terrace had a total of 494 housing units. Elmwood Acres consisted of small single-family homes and duplexes that are still inhabited.

According to the Lanham Act, when the war ended, the housing would be torn down. The Oakwood and Trout Brook Acres housing was built very quickly and was not meant to last. And, post-war, towns worried about the developments becoming low-income housing.

Just two months after the war ended, the town appointed an Advisory Committee on the Disposition of War Housing. At its first meeting in December 1945 over 100 South Quaker Lane tenants sought aid from federal, state and local officials who told them they had to move to Oakwood Acres. A spokesman for 40 families at South Quaker Terrace said adult members of most of the families signed a petition that would be sent to Governor Baldwin, Senators McMahon and Hart, U.S. Representative Herman P. Koppelmann and Councilman Cassens.

Among the residents were 11 veterans who felt that moving would be a hardship. Veterans found it difficult to rent, and their advocates argued that those in Trout Brook Acres had not been able to find rentals because of the acute housing shortage.

The Town Council relented and did not tear down the housing projects. Then again in 1951, the town’s Advisory Committee for the Disposition of War Housing met at the Town Hall to map out a request to extend the life of West Hartford’s two temporary federal housing projects. The town scheduled both to be razed by the government in July 1952. Veterans groups continued to be concerned because they were not able to find housing. They asked the government to build permanent low-cost veterans housing, but until then, wanted the town to keep the World War II housing up.

In 1953, once again the Federal Public Housing Administration tried to tear down the housing. But the West Hartford Housing Authority fought it using the power of US Senator William Purtell. At that time, the projects were full of tenants with 369 families on the waiting list. These projects were no small thing for the town. Almost 1,400 children lived there with over 700 school-aged children. The federal government gave another reprieve.

By 1955, the housing was close to demolition with just 78 families still living there and 257 vacancies. Then in August 1955, storm Connie rained five inches and five days later hurricane Diane dropped 14 inches in 34 hours. The flooding began on August 19.

On August 23, 1955, the West Hartford Housing Authority got permission to reopen the units in Oakwood Acres to house homeless families from Farmington and Unionville. Just five days later, 30 flood families moved in with 20 more families on the way. To be accepted into the housing project, all the evacuees needed was a letter from the Red Cross.

While there were no residents left at South Quaker Terrace, the Hannon-Hatch Post took over one of their buildings as a base to arrange to receive and distribute furniture, stoves, and refrigerators. West Hartford welcomed the Unionville residents.

On September 1, the Board of Education voted to admit the “children of refugee families” into local schools. By that time, there were 55 refugee families in the housing project with room for 250 more. Superintendent Edward Thorne thought that the town might have to hire more teachers at Charter Oak and Smith Schools to accommodate these new children. Thorne also reported on problems of our own as the flood had caused washouts at Talcott and Bugbee, and caused boiler room problems at Morley and Smith.

A year after the flood, 15 of the flood families still lived at Oakwood Acres as the town moved to final demolition. Finally in January 1957, the last families moved out of Oakwood Acres and the town demolished the last 10 of 27 apartment buildings and the community building. In its 15 years of existence, a total of 2,803 families had lived there. During that time, according to the chair of the West Hartford Housing Authority, not one family had been evicted.

In some quarters, West Hartford has a reputation for being exclusive; we do pride ourselves on taking care of our own community. But in these two natural disasters separated by 56 years, the town reached out to those beyond its borders. In 1955, West Hartford housed people from Farmington and Unionville, albeit in rickety housing scheduled to be torn down five years earlier. And in 2011, the town opened the doors of one of its high schools and drew people from surrounding communities as well as West Hartford. We should be proud of our commitment to help those in need.
