## Wolcott School and Wolcott Park {-}

*Originally appeared in West Hartford Life, December 2005*

The pending Blue Back Square development has many townspeople worrying that the “character of the town” will change and somehow be lost. Some people think that the Board of Education building, the Town Hall from 1937 to 1989, should not be sold or changed because of its historic value.

The story of the Wolcott Farm in the southwest section of town can give some insight into how the use of land has evolved with economic and technological change as land moved from the private to the public sector.

Chester Francis owned 141 acres of land in the southwest corner of town, south of New Britain Avenue in the early 1800s. In 1882, Francis’s son Samuel inherited 50 of his 141 acres and lived there until 1899. He had lived in the area since before the Civil War and built a house there in 1861. It is this house which became the Wolcott farmhouse.

In 1899, the Long family bought the property, and reports showed that Long developed a “model farm,” just as Charles Beach had developed in the property up the hill that is now partially Beachland Park. Long planted an orchard with apple, pear, cherry and quince trees. He planted one half acre of asparagus and had a huge vineyard out of which he made 2 to 3 hogsheads of wine per year. He had a small herd of cows and a least three teams of horses.

In 1902, Long sold the farm to a dentist named Chapman who suffered economically during the Panic of 1907. Chapman hired Henry A. Wolcott to draw up plans for several large buildings on the property. Chapman could not pay Wolcott because of the economic downturn, and ended up selling Wolcott the farm for a small amount of money and the mortgage. In August, 1907, Wolcott moved from his house at 46 South Main where the present Town Hall is, to the farmhouse.

Henry and his wife Annie built up a vegetable and egg business as a result of the Panic of 1907. There was very little building and Wolcott, a civil engineer, had to close down his Hartford office. Wolcott had made his living designing and supervising factory construction. He designed the West Hartford Armory among many other buildings. By 1910 he converted an upstairs room in the house to a drafting room and began again to make money surveying and designing buildings again. His office remained in his house. He served as Second Selectman for West Hartford in 1909 and served on various boards, including the Board of Education, until 1933. He represented West Hartford in the General Assembly for four years in the 1920s.

The Wolcott Farm was never a large dairy farm, like Charles Beach’s Vine Hill. His son, Henry F. Wolcott remembered his father’s farm as having 4 or 5 cows, from which they got their own milk, cheese and butter. They raised one or two pigs and cured them in the smoke house. They had 40 to 50 chickens and sold eggs. Later on they had sheep as well. They grew corn, wheat, oats, rye, and vegetables. A wheat field stood where Wolcott School is today. Wolcott was most known for his vegetables. There are residents who still remember buying vegetables at his roadside stand which operated until 1966.

Wolcott’s son, Henry F., remembered the game on the farm. Lloyd Bugbee, the Superintendent of Schools, used to hunt pheasant on the farm. The Wolcott children recalled shooting raccoons which caused havoc with the horses with their holes in the fields. Ruth Wolcott, Henry F.’s sister, remembered eating raccoon meat. She also remembered catching and cooking snapper, frogs and eel from the pond which is now behind the baseball field at the park.

Ruth also remembered her father cutting ice out of the pond in the winter. They stored it in the lower barnyard beyond the cow barn. Like the Trout Brook Ice and Feed Company, they packed the ice in sawdust and it lasted through the summer to keep their ice boxes cool.

In 1953, the Town of West Hartford bought the 50 acre Wolcott Farm for the purpose of building an elementary school. Elmwood School, built in 1928, the present Elmwood Community Center, and Duffy, which opened in 1952 were overcrowded. The Wolcotts sold the property with the understanding that Henry F. Wolcott’s wife Susan could remain in the homestead as long as she wanted. The school opened in April of 1957 after the students had done half-day sessions at Elmwood School from September.

In 1967, when Susan died, the town went ahead with its plans to make the northern section of the Wolcott land into a park. The 28 acre park officially opened in 1972 with 300 townspeople attending the ceremony, ending with a municipal ball. Henry F. Wolcott believed his father would have been delighted by the park. He had always wanted it to be one.

This piece of property, which was farmed for over 200 years, has served the town well in its last 50 as a school and last 30 as a park. In the 1950s, when 10 new schools were built, more public land was needed and the town was willing to give up some of its tax base for the public good. The suburban neighborhoods which surround the original farmland are symbolic of the rapid change from farm town to suburb. Wolcott’s name reminds us that it was but a generation ago that farms still existed here.

How does a town keep in touch with its past and yet keep up with new needs and desires of its citizens? How can the government’s need to build an infrastructure, keep taxes reasonable, and the developers desire to make a profit be balanced in the 21st century and how does it differ from 1950s? These decisions are made over and over again by the town leaders, the citizens, and those business people who can alter the landscape, but only the citizens control the character of the town.
