## Governor Robert Hurley {-}

*Originally appeared in West Hartford Life, August 2011*

On April 9, 1942, a caravan of 30 cars drove by 99 Outlook Avenue, jubilant in the Republican Town Council sweep of the local elections. 99 Outlook was the home of Connecticut’s Governor at the time: Robert A. Hurley. A Democrat, Hurley was likely not amused by the makeshift parade of cars.

Robert and Evelyn Hurley moved to West Hartford from Bridgeport in 1937 when he was appointed Commissioner of Public Works. Robert Hurley (1895-1968) was born to Irish immigrants, attended Cheshire Academy and studied engineering at Lehigh University. He worked as a hod (brick) carrier to support himself at Lehigh. He was a four-sport athlete, starring in football and baseball; he played professionally in both sports after a stint in the US Navy on submarines during World War I. He then started a construction company in his hometown and in 1925, at age 30, he married a Bridgeport native, Evelyn Hedberg, a nurse. They had a son and two daughters.

Hurley got involved in state government, in 1935, when he was 40 during the Great Depression when he served as the director of Fairfield County’s Works Progress Administration (WPA). When the 1936 Flood hit, then Democratic Governor Wilbur Cross named Hurley a special representative to coordinate relief activities between Hartford and the federal government. He then stepped up to coordinate the WPA for the entire state.

Hurley was an “ardent supporter” of President Franklin D. Roosevelt and a big supporter of the New Deal.

When Governor Cross appointed Hurley as Connecticut’s first Public Works Commissioner in 1937, Hurley moved to Outlook Avenue in West Hartford. Hurley stepped into a hornet’s nest in state government. Cross wanted him to oversee road planning, construction and repairs, while others believed that the Commissioner of the State Highway Department should be in charge. Cross believed the Highway Department was in cahoots with real estate agents employed by the State Highway Department who were benefiting by purchasing land along the planned route for the Merritt Parkway.

Hurley issued a report that was damning towards the Highway Commissioner and the report called for the Commissioner to resign.

Hurley used his record as Commissioner of Public Works to run for Governor. He seemed to run on Roosevelt’s coattails. The sitting Governor at the time was Republican Raymond Baldwin who had defeated the Democrat Cross in 1939. Hurley defeated Cross in the Democratic Convention and went on to defeat the incumbent Republican Governor by almost 14,000 votes.

Hurley was only the fourth Democratic Governor out of 25 Governors in the previous 56 years. He was, as the *Hartford Courant* reported, “West Hartford’s leading Democrat,” who represented the New Deal Democrats that West Hartford Republicans wanted to taunt.

Hurley served for one term. He introduced programs that helped both workers and the unemployed. He helped electrify some rural areas of Connecticut. He established Bradley Field as an airport and pushed the state to prepare for war. He developed “Connecticut’s Compact for Victory” pledging that all of Connecticut’s resources and industrial might and skills and energies of workers would be used in service to the U.S.

When Hurley became Governor, he appointed several men from West Hartford to fill out his administration. He re-appointed Dr. Stanley H. Osborn as Commissioner of Public Health. He appointed West Hartford’s George L. Burke to be the new Commissioner of Public Works, the position Hurley held when he became Governor.

Hurley also seemed to be an integral part of town life based on his speaking engagements in 1941, his first year in office.

In April 1941, the West Hartford Grange gave Governor Hurley and his wife Evelyn the third and fourth degrees at a ceremony at the Masonic Hall on South Main Street. Hurley spoke as if the U.S. were on a war footing, saying “the Grange must continue to live up to its ideals, but if we are to continue down the path of democracy we must crush out the rule head of intolerance... Eternal vigilance is the price of liberty and American would rather die than give it up.”

In May 1941, Governor Hurley broke ground for the foundation of the Noah Webster Memorial Statue. About 60 people gathered to hear the Governor honor Webster as “the town’s most famous citizen.” A WPA band sang Auld Lang Syne, and Korszak Ziolkowski, the sculptor, was the master of ceremonies.

Later on in the month, Hurley spoke before one of the largest Memorial Day crowds in the town’s history. He gave his speech at the North Green Cemetery and spoke about the war in Europe. He said that the U.S. had warned the Axis: “an attack upon any base which may endanger the integrity of the Western Hemisphere will be resisted with force.” He spoke about fighting for freedom of religion, speech, press and assembly to stop the totalitarian state which took away citizen rights, and against governments that had the ability to “intern us in concentration camps and inflict upon us the cruelest tortures which were ever devised.”

On June 13, 1941, Governor Hurley gave the commencement address at St. Joseph College when 49 young women graduated. Hurley again spoke of the war saying “We must not try to escape the consequences of the wrath of a Hitler, a Mussolini, a Stalin or any of those who follow their bloody emblems... we must not seek comfort by hiding from reality.” He claimed “women’s education plays a vital part in this world” emphasizing “those human values upon which society depends for its very life.”

Hurley ran for reelection in 1942, but lost to former Governor Baldwin by 26,000 votes, the man he had defeated just two years before. Baldwin proceeded to abolish the State Department of Public Works, which had led to Hurley’s political success.

In 1944, Hurley won the Democratic nomination for Governor, but lost to Baldwin, again by 26,000 votes, even though it was a presidential year in which FDR won his fourth term. Hurley retired from politics, and allowed the Democratic Party to unite after it had split into factions.

In December 1944, the federal government appointed Hurley to the Surplus Property Disposal Board. He was confirmed by the Senate and he flew to Washington DC to take up his duties.

Hurley retired from government work and became vice president of the Narragansett Machine Company in Rhode Island, but continued to live in West Hartford. Hurley Hall at the University of Connecticut is named after him. In 1947, Hurley headed a manufacturing company that made silver and stainless steel ware called the Old Colony Silver Company.

If you go to Fairview Cemetery, in section 9 in the southwest section, you can see the Hurley headstone in the second row up a slight hill. You would never know that Hurley had been Governor. The nondescript moss covered stone reads Beloved Husband Robert A. Hurley, His Beloved Wife Evelyn L. Hurley, Father and Mother of Joan, Robert & Sally. The stone does not tell that Robert A. Hurley was Connecticut’s first Roman Catholic Governor when he served from 1941-43.
