## The Vanguard of America {-}

Originally appeared in West Hartford Life, February 2001

> West Hartford Public Schools ranked number one among peer municipalities!!  
> West Hartford Public Library ranked number one in Connecticut!!  
> An award-winning calendar displaying our parks!!  
> The highest voter turnout among peer municipalities for the 2000 election!!  

Superlatives abound in West Hartford. Mayor Rob Bouvier, in his "State of the Town" speech in 2001, regaled the town with its accomplishments---which are not just the result of one year’s work, but are part of a long history of the town being at the forefront of serving its citizens.

West Hartford has never been shy about selling itself to the world. Today we have banners around town touting our accomplishments. In 1940, the Chamber of Commerce proclaimed in a 16-page booklet called *Vanguard of America: A Small Town that Grew Up*, that read:

> West Hartford can rightfully claim position among those communities that are the highest fulfillment of the dreams and decisions, heartaches and toil that founded America.

What type of a community were we in 1940 and how did the Chamber of Commerce portray us?

When the pamphlet was written, the country and the town were just starting to make their way out of the Great Depression. Many residents suffered during the economic downturn, but the town as a whole grew. The population in 1930 was about 25,000 and reached 44,000 by 1940, a growth of 76 percent. Architects designed houses with 1½ baths, attached garages, and architectural detail that attracted urban dwellers to the growing suburb. Many of these houses appeared in national magazines as examples of houses with charm and appeal for the middle class life.

The Chamber of Commerce claimed that we were a vanguard because of our political system. West Hartford was the first town in Connecticut to adopt the council-manager system of government in 1919. We were the first town in Connecticut to have a planning commission that established zoning laws in the mid 1920s. We were the first town in the state to have the unit system of realty appraisal that “meant equitable taxation for rich or poor, merchant or industrialist.” This political organization provided a means to run the town by trained experts, not elected officials.

Probably because of the Town Manager, Republican West Hartford readily took advantage of Franklin Roosevelt’s New Deal programs including the Public Works Administration. This program, established to provide work for the unemployed and to build public works, funded 45% of the Town Hall and Library built in the mid-1930s.

In 1940, the Chamber of Commerce claimed that West Hartford had the largest per capita income tax of any town in the United States and the lowest welfare percentage in the state.

The pamphlet claimed that West Hartford’s schools were “among the finest schools, public or private, in the United States.” A survey of 200 secondary schools, including private schools, completed by the Cooperative Study of Secondary School Standards in Washington, D.C. rated Hall High among the top ten of the 200 surveyed. And yet, the Chamber of Commerce boasted that the town was economical in its school spending. We were 132nd out of 169 towns in percentage of income spent on schools. We were 51st in the amount spent per pupil.

In 1940, the town was proud that 45% of its students went to college. And it was proud of the type of education students got in the town: one that made citizens of a democracy understand their freedom and use it for good purpose. By 2000, the public high schools boasted that over 90% of their students went on to college, a sign of both the need for a college education in the work world and the growth in the number of colleges available. American Government, a required course in both the town and the state, continues to teach students how to be good citizens.

The Chamber was also proud of the houses of worship here in 1940. There were a total of twelve: two Congregational, two Baptist, two Roman Catholic, two Episcopal, a Swedish Methodist, a Swedish Lutheran, a Universalist, and one synagogue. The Chamber believed that this showed a commitment to religious liberty, one of the foundations of democracy.

In 2000 in West Hartford, with a population which grew 50% since 1940, there were 37 houses of worship including five Congregational, four Baptist, seven Roman Catholic, two Episcopal, one Lutheran, a Unitarian Universalist, and nine others and eight Jewish houses of worship split between one Reform, two Conservative and five Orthodox. The Chinese Baptist Church, a Society of Friends, a Spanish Pentecostal Church and a Jehovah’s Witness underline the increasing diversity of the town in the 21st century.

The town was one of the first in Connecticut to hire a recreation director. In 1940, the town already boasted three parks: Beachland, Fern and Elizabeth. In 1940, the “Fern Street playfield” had a large swimming pool, a small children’s wading pool, nine lawn tennis courts, paddle tennis courts, horseshoe courts, a softball diamond, a picnic grove with benches, and fireplaces and playground apparatus. At Beachland Park, residents could sail boats in the summer and ice skate in the winter. They also had paddle tennis and horseshoe courts. Since then, the town has added Eisenhower, Kennedy, Wolcott, Westmoor, and Spice Bush Swamp to its parkland.

The Chamber of Commerce tried to attract businesses as well as residents to the town. In the last section of their pamphlet, they encouraged “modern business executives” to consider the town as a site for their business. They stressed that land was available, schools were good, and the political structure of the town led to equitable tax rates. Economic planners today continue to try to lure businesses to the town with all the same arguments except that there is little open land left in the town.

What is the basis for all these superlatives about our town? Those who have lived here for a while experience the pride that people have in West Hartford and for good reason. West Hartford’s citizens are proud of the democracy in which they live, appreciate the services the town offers, and take advantage of the opportunities available. They believe, like the Chamber of Commerce did in 1940 on the eve of America’s entrance into World War II, that:

> We are only one rather small American town, but we know that we can continue to find within our experience and under our flag the means for nobler and more joyful lives.
