## Democracy and the Town Hall {-}

*Originally appeared in West Hartford Life, November 2001*

Democracy is a messy system. Decisions can take years to make because democracy provides ways for every manner of people to express their opinion and it often ends up dividing a community. Sometimes democracy is infuriating: representatives hesitate and compromise too soon, elected leaders often face unjust criticism, and it is often difficult to question the majority. But this messy process, occurring over and over again, and what it symbolizes helps define our democratic tradition.

West Hartford’s Town Hall history is fraught with democratic hesitation and expressions of opinions. Not only did West Hartfordites fight about building new Town Halls, they spent much time arguing about what to do with the old ones. Between 1934 and 1957, the local leadership and the citizens joined together to build the new town hall and then squabbled for 20 years about what to do with the old building. West Hartford was a solidly Republican town from its independence in 1854 until the 1970s. Even so, political tension existed, and Republicans were not afraid to take advantage of help from the Democratic federal government in the 1930s to build.

Studies of the need for a new Town Hall came as early as February 1934, from three civic groups – the Chamber of Commerce, the Civitan Club, and the Exchange Club. They wrote a letter to the Town Council providing reasons for a new municipal building after a prolonged and careful study of the town’s need. The Council drafted plans for a “civic center” in the ensuing year, but chose to act on the town hall when they saw the possibility of some federal money to help pay for the building.

By June 1935, in the heart of the Great Depression, West Hartford town officials clamored for a new Town Hall. Max Goldenthal, President (no Mayor until the 1950s) of the Town Council appointed a committee of three men to study allowing West Hartford to take advantage of money provided under a new grant plan of the Projects Works Administration (PWA). The town thought they could get 45% of the building costs paid by the federal government. Many Republican towns refused to take the federal money

Many Republican towns refused to accept money from Franklin D. Roosevelt’s New Deal programs, disagreeing with his premise that it was the role of the federal government to help out at the local level. In fact, once the building plan had been presented in October, Mr. Ludlow, the president of the town’s taxpayers’ association said “We are lending approval to the scheme of the New Deal. How can we Republicans accept this grant this year and then next year oppose the administration?”

But Ludlow’s ideas were in the minority and the town went ahead with plans for the new town hall. Chosen to present the project to the town was Councilmen D. Hayes Murphy, President of Wiremold, and Dennis Ahern, a local builder.

At the well-attended public hearing, Louis N. Denniston, representing the West Hartford Chamber of Commerce, gave a brief history of the present town hall, which was the remade third building of the First Congregational Church, situated on the northwest corner of Farmington and North Main and presently the site of of our peace memorial. Controversy had raged over the inadequacy and safety hazards in the building for years. Denniston argued that the present building was unsafe. West Hartford, he argued, was one of the wealthiest communities in the country for its size. He believed it should have “a building in harmony with its position.”

By October 23, 1935, the Town Council approved building the new Town Hall and hired architects to draw a plan. The federal government wanted things to move quickly and the Council agreed that there wasn’t time to have competitive bids between architects. On October 29, the Council voted to accept the $141,300 grant from the PWA. Total cost of the project was about $314,000, which included $100,000 for buying the land from the First Congregational Church that lay just south of the church. The plan had to be in place by December.

Only six months elapsed from the idea to breaking ground on December 10. The federal government, to help get more men back to work during the Depression, pushed this speedy timetable. When the building opened 13 months later, the federal reports showed that the project had employed a total of 635 men. A daily average of 185 men from the building trades and allied industries were employed for about eight months. At least 460 men gained employment off-site to provide materials for the building. The federal government funded 40% of the cost of five town halls in Connecticut by 1937 for a total of $1,000,000.

The building process went smoothly, but the plans hit a temporary snag when, in October, a group of townspeople protested the felling of ten old maples in front of the almost-completed South Main Street building. The street, town officials said, had to be widened. David J. Raynsford, a 90 year old resident, said “Folks out here do about as they like,” as he protested taking the trees down. He said, “Those trees are over a hundred – it took a lot of time for them to grow. And now they’re turning them into cord-wood. It isn’t right.” Though these protesters may have supported the building, they balked at what they saw as destroying the environment.

Mrs. Roy D. Bassette, secretary of the West Hartford Garden Club wanted an injunction to stop the cutting. She started protesting a week before, but not enough people came to her aid for legal action.

Town Manager Rodney L. Loomis said that the trees would be made into stove wood and would be distributed to people cared for by the Welfare Department.

This building, according to the townspeople, represented the messiness democracy. At the dedication of the building, U.S. District Attorney Robert P. Butler, alluding to political events in Europe, said:

> May this building which we here dedicate, be the spiritual as well as the physical temple of constitutional self-government... The sovereignty of man will sometimes be denied, his rights of free self-government will sometimes be surrendered as we have seen them denied and surrendered before our very eyes these past few years. But make no mistake, these things are only temporary. Sooner or later the deceived and deluded peoples will reclaim their heritage. The right of democratic self-government cannot be wholly destroyed.

Getting rid of the old town hall ended up as one of those messy decisions about which many people had a say. One of the selling points of the town hall project was that the town could sell the site of the old town hall on the northwest corner of Farmington and South Main to get money to pay against the cost of the new building. But, in true democratic fashion, where sovereignty lies with the people, voters voted in a 1937 referendum not to sell the property or the buildings. But, by 1939, two years after the opening of the Town Hall, the three buildings on the site – the old Town Hall (built in 1835), its brick annex, and the old library still stood vacant. The old Town Hall was in such bad shape that most people felt it was unsafe to occupy. But others believed it was a historical building worth saving.

Mrs. Bassette, the woman who wanted to save the trees, also wanted to save the building. In a letter to the Town Council she wrote:

> Symbolically the old Town Hall is more than just a bit of architecture occupying a valuable piece of land. It is the roots of our community, and together with all town halls throughout the country it is the roots of America. Such a thing should not be destroyed for a comparatively small amount of money, when many times that amount would never pay for the historical and spiritual value of this building.

In January 1942, the Chamber of Commerce President proposed that the abandoned buildings be set up as an emergency hospital to care for the injured in case of an air raid. The building was never used as an emergency hospital, but was used as a billet for quartermaster troops assigned to the Farmington Avenue Armory and as an examining station by the Selective Service during the war. In 1947, the town tried to sell the property and claimed, in the real estate boom, that they had bids of up to $175,000 for the land. One bid was from Best & Co. department store wanting to build a suburban store. Town Council candidates in the 1947 election made a campaign issue out of the land, hoping that the proceeds could be used to build a veterans hall. Another town referendum, this one on April 8, 1947 allowed townspeople to vote.

Various town groups weighed in on selling the property, but the townspeople voted 2 to 1 to save the land and the buildings. In June, the council voted for funds to demolish the brick annex and it was knocked down by the end of the summer.

In 1956, the old Town Hall still stood vacant, 19 years after the new town hall opened. Attempts to put it to use were prohibitively expensive and the building was an eyesore. But the local government was not sure how long the 1947 referendum bound them to keep the land.

Finally on March 27, 1957 the Council ordered the building to be razed. The site became a park and the stone benches were made from the old church steps. It was reported “it is significant to note that West Hartford has taken the leadership in providing a small park within a high commercial district.”

The town moved quickly to get the new Town Hall built, but agonized over the old town hall building because of what it symbolized -- not so much for the value of the building. We can still identify with the power of these symbols and the importance of a democratic process, no matter how messy.
