## West Hartford Emigres: The Soviet Jewish Experience {-}

*Originally appeared in West Hartford Life, March 2005*

Zhenya Tseytlin, a West Hartford immigrant from Odessa on the Black Sea, was in the fifth grade when the Germans invaded the Soviet Union during World War II. The Germans and Romanians drove the Jewish people out of Odessa and took them to a camp where they were to be killed. In March, 1942, the occupiers took mothers and children out in a field to be shot. Zhenya’s mother told her to run. Zhenya said, “I was crying. I didn’t want to go, but some force pushed me out of that mass. I started running towards the woods. Alone!” Zhenya heard shots and screams. She kept running and found a pile of grass in which she hid for the night.

The next day, 10 year old Zhenya wandered from village to village to find some help. She knocked on the door of a house in one village and a 24 year old woman with children took her in. Zhenya recounted, “I was starving... She was such a noble person... She didn’t ask if I was Jewish.” Zhenya stayed with the family for two years and her life was saved.

This is just one of the stories of Soviet émigrés to the greater Hartford area recounted in “Witness to War, 1941-5: The Soviet Jewish Experience,” an exhibit at the Noah Webster House for several months this winter. Dr. Betty Hoffman, from St. Joseph College, interviewed forty Jewish men and women who survived World War II in the Soviet Union and many settled in West Hartford. This exhibit depicts how Jews, both those who served in the military and civilians, survived World War II.

The Russian émigrés have stories to tell of survival in circumstances that were not as bad as those in Germany, but were stunningly depraved. Now on their retirement here in West Hartford, hoping for better lives for their children and grandchildren, these émigrés have memories that altered their lives dramatically.

Many Jewish families who emigrated to West Hartford in the 1990s felt as though they would be treated more fairly in the Soviet Union after the Russian Revolution in 1917. As Russian citizens adapted to a new secular order, the practice of religion was outlawed. The idea of equality promised by a Communist state drew many Jews from other parts of Europe. At first, the ideal of equality helped the Jews, but by 1932, they had to carry around a Jewish designation and it was used to discriminate against them in education, employment, and housing. Most protected themselves by dropping behaviors which marked them as Jewish.

When Hitler invaded the USSR in 1941, the Red Army retreated and Jews like Zhenya Tseytlin were at greater risk, but they were more able to survive than if they had been in Germany.

The Jews were controlled by the Einsatzgruppen, sent in by the Germans as part of the Nazi invasion force, whose job was to get rid of what they considered to be undesirables. Jews were sent to ghettos, forced to work, and killed outright. The Einsatzgruppen murdered one million Jews between 1941 and 1942. At Babi Yar 30,000 were killed in two days in September 1941.

Lida Prokopets, another Odessa resident, worked in a Jewish infirmary as a nursing aid when the war began and she worked through the 79 day siege of her city. The Germans and the Romanians occupied the city and looked for Communists and Jews. She remembered a hanging pole set up in each marketplace where Jews and Communists were publicly hung.

Prokopets, a West Hartford resident who emigrated in the early 1990s, related that neighbors would not take them in because they were Jewish. They secretly moved to the shed in their backyard that had been used for firewood. Four members of her family stayed there. A woman in the neighborhood gave them food. One day a car arrived with Romanians who had come to find them. Her mother “took off her wedding ring and another ring she had hidden. She said “let us go,” gave them the rings, and we went to my sister.” In one more month, the police came and took them. Pokopets survived.

Mark Aronov, another West Hartford resident, was a student at the Moscow Medical Institute when war broke out. Because there were so many casualties, Aronov, training to be a surgeon, became instead, a specialist in medical triage. Nina Aronov remembered fleeing town and traveling for two years. She lived in a village, and picked potatoes. She had no clothes. Her mother found a cotton bag, sewed it, and painted it to make her a skirt.

Sometimes Jews were confined to ghettos where the occupiers killed the Jews systematically by starving them, from disease or exposure, or from outright brutality and murder. West Hartford resident Frima Leykikh, remembered how the commandant of the ghetto “used to come in and ask how many corpses were taken out that day. He was told four, five wagons. He stated that it was not enough. They had to take out more.”

This exhibit is the brainchild of Dr. Hoffman and was funded by the Jewish Historical Society of Greater Hartford, the Connecticut Humanities Council, the Jewish Federation of Greater Hartford, and the Fisher Foundation. It originally opened two years ago at the Greater Hartford Jewish Community Center in West Hartford and has traveled as far as Nashville, Tennessee. Its opening at the Noah Webster House signals a new collaboration with the Noah Webster House and West Hartford Historical Society as they try to reach out to a wider public and make it known that they want to represent the history of all West Hartford residents.

The history of West Hartford is also a compilation of the many stories of those who live in town. This exhibit will open your eyes to the breadth of experience, suffering and hope of an important segment of our population and its offspring.
