## Recalling 140 Who Gave Their Lives During World War II {-}

*Originally appeared in West Hartford Life, May 2005*

Of the 225 total West Hartford war casualties, 140 of them died in World War II (1941-45). Two men died in 1941, six in 1942, 22 in 1943, 54 in 1944, 51 in 1945 and 4 in 1946. The 139 men and one woman who gave their lives in war, give us a chronology of World War II. Their family stories tell us who was left behind on the homefront. Here is a glimpse at 14 of the 140 service people who sacrificed their lives for their country.

West Hartford’s first casualty, Gordon Sterling, aged 22, died in the attack at Pearl Harbor. He was in the Air Force and was one of the only people to engage the Japanese. From his plane, he shot down one of six Japanese planes before his plane was downed and he was killed. The playing field behind Charter Oak School was dedicated in May 1943, and named after the first West Hartford casualty. It is now known as Sterling Field.

![Lt. Gordon Sterling (1919-1941) grew up on Argyle Avenue. His father worked at the Underwood Typewriter factory. Gordon was a Boy Scout. He, graduated from Hall High School and enrolled at Trinity College in 1937. He took private flying lessons, and in September 1940 he enlisted in the Army Air Corps. He died at Pearl Harbor. Used with permission from “Together We Served,” <https://army.togetherweserved.com>](images/08-sterling-web.jpg)

In March and October 1942, two men were killed in the Pacific, Lewis Davis who was missing in action south of Java and Adam Fahnestock in New Guinea. Fahnstock of Pilgrim Road was 32 at his death. He was a member of the Air Force. Davis, of Lincoln Avenue was 27 when he was reported missing in March 1942 but was not declared dead until December 1945.

The first casualty in 1943 was in North Africa. The United States engaged the Italian African forces in 1942 and 1943. Two men, William G. Hale and James W. Hatch were both killed in plane crashes in January and April in North Africa. Army Air Force Second Lieutenant Hale of North Quaker Lane was 23 when his plane crashed. He left his wife of five months in West Hartford, and two older brothers in the service. Hatch, of Norwood Road, was 24 when his pursuit plane crashed in Tebourba, Tunisia in April 1943. Hatch was a graduate of the Kingswood School and Yale University. Hatch’s father was president of the Bush Manufacturing Company and had employed his son on his graduation in 1941. The VFW Hannon Hatch Post is named after him.

After the allies defeated the North African armies, they invaded Sicily and then the mainland of Italy. Rodney MacGregor and James Hannon were killed in the Italian campaign. MacGregor, age 23, was the pilot of a troop transport plan that was shot down. Hannon, of 32 Vera Street, was killed in action in Italy in November 1943. He worked at Colt’s before he enlisted. He left his mother, a brother in the Air Force, and two sisters. (He is the other half of the Hannon-Hatch Post.) Seven more West Hartford men were killed in the assault on Italy.

During World War II 140,000 women served with the Women’s Army Corps (WAC). The only woman casualty from West Hartford was Mary O’Dell, aged 27, a member of the WACs. She was employed at Aetna when she enlisted in early 1942 and probably performed clerical work in the service. O’Dell received her training at the Fort Des Moines Officer’s Candidate School. A graduate of Hall High, she left behind her parents at 82 Griswold Drive.

In 1943, more men died in the Pacific islands: New Georgia Isle, Solomon Isle, Gilbert Isles, New Hebrides, and the Philippines. The men who died were in the Army, Air Force, and Marines. Lieutenant George J. Bolles, of 273 South Quaker Lane was West Hartford’s 30th casualty. According to the *Metropolitan West Hartford News*, Bolles “heard the news of the Jap treachery at Pearl Harbor on Sunday December 7th and enlisted on Monday, December 8th.” He was killed after his B-24 Liberator had “inflicted heavy damage on enemy shipping” when his plane was returning to its base in New Guinea and the plane disappeared.

The invasion of France at D-Day in June 1944 included many West Hartford men, 14 of whom were killed in that country from June to December. The first West Hartford man killed in France was Richard S. Kuehner, 749 Farmington Avenue, of the Air Force. He was killed “in action during the invasion of Normandy” after D-Day. He was a fighter pilot of a P-47 Thunderbolt. Radioman Wilbur Allen, aged 21 of 1478 Boulevard, was killed in his minesweeper on his way to the invasion of France. He had been employed by the *Hartford Times* and left his mother and two sisters.

William J. Stone, age 20 of Edgemere Avenue, was killed in the Battle of the Bulge on November 15, 1944 in Belgium. Stone had been missing since September. His Golden Lion 106th infantry battalion held back the full weight of Germany’s Von Rundstedt’s breakthrough to give the Army command time to regroup. This battle was, according to the *Metropolitan News*, a “saga of courage seldom equaled.” It was the heaviest bombardment ever witnessed by the armed forces. Over 8000 men were either killed or captured in the Battle of the Bulge. Stone, who graduated from Talcott Junior High and completed two years at Hall, left his parents, a brother and three sisters.

Frank J. Concatelli, aged 25, a private in the army was the first man to be killed in Germany. He was killed at Puffendorf on November 17, 1944. Concatelli was one of the first seven members of an armored division to enter Germany during the American invasion of Germany on September 18. He lived at 69 Hillcrest and left his parents and four brothers, two of whom were in the service, and two sisters.

In the Pacific, many men were killed in the Philippines starting with Sanford Perkins, Jr. of the Navy on December 18, 1944. Six more men were killed on the island of Luzon in 1945. Perkins was part of a bombing squadron with the USS WASP, operating against enemy Japanese airfield in South Luzon. He braved relentless fire from the Japanese anti- aircraft guns. Perkins deployed his division of fighter bombers to “execute a vigorous and successful attack on the target fighting his plane boldly to score a direct hit on a large airfield building and repeatedly strafing hostile anti-aircraft positions. He was a graduate of Yale Univesity and the grandson of the former editor of the *Hartford Times*. He lived at 82 Van Buren Avenue.

The Carey brothers died in their plane over Indochina in 1945. They were inseparable, going to Loomis together and then Amherst College playing on the same football team. They each married a woman named Jeanne (and Jean) three days apart. They withdrew from college in 1940 and joined the army on the same day. They also died the same day as pilot and copilot.

West Hartford streets, schools, parks and buildings are often named after local men and women who made a difference to the town. I wonder if veterans who walk into the Hannon-Hatch Post realize that these two men died in a World War II battle. How many soccer, football and softball players know that when they play at Sterling Field, it is in memory of the first West Hartford casualty from World War II? Town leaders who name these public places want people to remember the deeds of those who went before them, and in this case, people who gave their lives for a cause bigger than themselves.
