## World War II Victory Gardens in West Hartford {-}

*Originally appeared in West Hartford Life, January 2011. Sources included news article scrapbooks compiled by the Recreation Department from its inception in 1940, currently in possession of the author.*

> It isn’t so much what the gardener gets out of the garden as what the garden does to the gardener. -- Lloyd Bugbee February 1, 1943

Sustainability and eating local are the bywords of the 2010s. One might think we’d invented something new! We have much to learn from World War II Victory Garden Program run by West Hartford’s Recreation Department in the 1940s.

When Japan bombed Hawaii on December 7, 1941, the United States went on war footing. The federal bureaucracy worked well in the 1930s to mobilize the economy and when war broke out, departments shifted to get the citizenry involved in the war effort.

From 1942 to 1945, Victory Gardens produced more than 40% of all the vegetable produce consumed nationally. Nearly 20 million Americans planted these gardens in backyards and empty lots. This was almost 60% of households. Victory gardeners harvested an estimated 9 to 10 million tons of vegetables, an amount that equaled the value of all commercial production of fresh vegetables.

The program played a key role in feeding Americans, but it also had an important psychological effect. It was a way for people to feel like they were doing their part on the homefront and a way to build community spirit. The Recreation Department wanted the Victory Gardens to be viewed not just as directly aiding the national defense. They were also important for developing the resourcefulness and initiative of those interested enough to make a reasonable effort.

In April 1942, West Hartford’s Recreation Director Jacob Feldman appointed Mrs. Howard D. Wilcox of South Main Street to supervise the West Hartford Victory Garden program. She worked directly with landscape expert Peter J. Cascio of 2600 Albany Avenue who chaired the Victory Garden Campaign. Most volunteers came from the Little Garden Club and the West Hartford Garden Club. These volunteers supervised students in the Victory Garden program from Hall, Beach Park, Center, Charter Oak, East, Elmwood, Morley, Sedgwick Elementary and Seymour Schools.

Wilcox recruited 50 volunteer leaders to supervise and inspect student gardens and neighborhood gardens. They helped solve gardening problems. Both Cascio and Wilcox were perplexed with how to supervise this many newly minted farmers, but the program went forward.

They started by having students draw garden plans in early April. They established a timetable to have the gardens spaded by April 20.

Wilcox and Cascio set up a rating system for each garden to be sure that food would be produced. They rated vegetable gardens on location, arrangement of rows, cultivation and care of the plants. For flower gardens, they considered landscaping, neatness, weeding, health and vigor of the plants.

A report on July 26, 1942 showed that 370 students were growing vegetables. Mrs. Hazel McCrampton replaced Wilcox as the Garden Supervisor and she inspected all the gardens and rated them. The gardens were very successful. Some of the more advanced gardens fed an entire family.

When the Town of West Hartford takes on any project, it wants to excel. Rudolph Whaples, Hartford County agent for the 4-H Club, said that “West Hartford has a larger number of children and more successful and better organized Victory Garden program than any other city or town in the state.” Similarly, in the 1942 report on the summer playground activities, the Director of Recreation said that the town’s Victory Garden project was hailed as the most outstanding in the entire state.

By July 30, 1942, the *Metropolitan News*, the forerunner to the *West Hartford News*, trumpeted that “Children’s Victory Gardens Successful; Leaders Praised.” The *News* reported that the average size of a garden was 8 feet by 12 feet but some were as large as 25 by 50 feet. The vegetable gardens supplied the family needs and in some cases they also had enough to can. They raised green beans, beets, cabbage, corn, cucumber, peppers, tomatoes, as well as unusual crops like tobacco, soybeans, celtuce (combination of lettuce and celery), kohlrabi, romaine, and okra. According to the *News*, Italian children raised “unusual greens for salads.” The children made up to three plantings on their plots of land.

In mid September, the Recreation Department and the West Hartford Defense Council sponsored a Victory Garden Harvest Show at Hall High. This Harvest Fair was just one among over 20,000 held in 40 states to celebrate their harvests and raise money for the Army and Navy Emergency Relief. The government sanctioned these shows. For West Hartford, this was the first Harvest Show in years.

The hope for the fair was not just to show off produce, but also to create a “better neighborhood spirit and increased interest in gardening. It is the patriotic duty of every gardener in the town to exhibit.”

By show day, volunteer farmers entered over 500 products in the fair. Several hundred people attended what was named “the first annual Victory Harvest Show.“ Judges awarded prizes for flowers, artistic arrangement, vegetables, fruits, houseplants, children’s flowers and vegetables, and children’s artistic arrangements.

In January 1943, the town was already planning for gardens for the next growing season. Recreation Director Jacob Feldman and Superintendent of Schools Lloyd Bugbee had been working on the program for weeks and they believed that they were the first community in the state to be so far ahead. For the 1943 season, the Recreation Department agreed to hire a professional market gardener to advise and guide gardeners throughout the season. They planned to put seeds together that were varieties suitable for this area and had good productivity. They also planned to supply a bi-weekly bulletin on gardening including dates for planting, reminders on tending the crops, warnings about pests and instructions on how to deal with them.

By February 1943, 800 local school children from every school in town had pledged to grow Victory Gardens. Representatives from West Hartford’s Men’s Clubs including Civitan, Hayes-Velhage Post, Exchange, Beth Israel, Kiwanis, Chamber of Commerce, Elmwood Community Church, and St. Patrick’s all agreed to promote victory gardening. The program more than doubled in participation in one year.

Superintendent Bugbee again encouraged local farmers saying “by cultivating, in typical Candide fashion, their own gardens, they will be able to realize a security, a creative satisfaction and a sense of “belonging,” so essential during this period of war created insecurity.”

The 2010s sustainability and locally grown movements include those same sentiments. Not only do they suggest that we gain more control of our food sources but we also build a sense of community that comes with a Community Supported Agriculture share or by visiting a local farmer’s market. Even better, grow your own garden and share with your neighbors.
