## Korczak Ziolkowski and Chief Standing Bear {-}

*Originally appeared in West Hartford Life, July 2013*

In June 2013, Conard High School Senior Emma Briggs travelled with Hawkwing to work on the Cheyenne River Reservation. She travelled to Thunderhead Mountain in the Black Hills of South Dakota to view the Crazy Horse monument. There, in the museum, to her surprise, she found this label under a photograph of Korczak Ziolkowski (1908-1982) and Chief Henry Standing Bear:

> Ziolkowski is well known in West Hartford as the sculptor of the Noah Webster statue, completed in 1941. At age 32, Ziolkowski sculpted Webster as a monument for the town. Before he entered World War II in 1943, Ziolkowski met Chief Henry Standing Bear to plan sculpting Crazy Horse into the Black Hills as a poignant counterpoint to Mt. Rushmore (1927-41).

The US government sent Chief Henry Standing Bear, born in South Dakota, to the Carlisle Indian School in Pennsylvania to forcibly assimilate him into white culture. He liked learning English and the ways of white people but used this knowledge to stand up for his culture. He fought with his pen, writing letters to the Commissioner of Indian Affairs, trying to assure Indians land ownership. In 1927, he ceremoniously inducted Calvin Coolidge into his Sioux tribe as “Leading Eagle.” Though he spent some time working on Buffalo Bill’s Wild West Show, his focus in later life was Indian history and the Crazy Horse statue.

In 1939, Ziolkowski, at age 21, went west to help noted sculptor Gutzum Borglum sculpt Mt. Rushmore. Standing Bear asked Borglum to add Crazy Horse to Mt. Rushmore, but Borglum turned him down. Ziolkowski and Standing Bear must have met on that visit, because in 1939 Standing Bear sent a letter to Ziolkowski asking him to go out to Pine Ridge, South Dakota where they met for three weeks. There, Ziolkowski learned about the traditional Indian way of life.

Ziolkowski remembered: “Standing Bear grew very angry when he spoke of the broken treaty of 1868. That was the one I’d read about in which the President [Andrew Johnson] promised the Black Hills would belong to the Indians forever. I remember how his old eyes flashed out of that dark mahogany face, then he would shake his head and fall silent for a long while.” Originally Standing Bear believed that the entire Crazy Horse project had to be completed by Indians, but there were no Indian sculptors. Ziolkowski stepped in.

In early May, 1943, Chief Standing Bear (1874-1953) traveled to West Hartford and stayed with Ziolkowski at 216 Sedgwick Road, the house with the turret as Sedgwick turns into Mountain Road near the West Hartford Art League.

Standing Bear had two objectives on his speaking tour: he wanted to interpret the little known ceremonies and customs of his people to eastern audiences. And he wanted to firm up plans with Ziolkowski so that he could convince officials in Washington D.C. that he should sculpt his cousin Crazy Horse out of the Black Hills.

Ziolkowski planned two public appearances for Standing Bear. On Friday, May 7, 1943, the Chief spoke at the Annual Sedgwick Boy Scouts Parents Night sponsored by the Boy Scouts and the West Hartford Police Department. In his talk he said he was on his way to Washington D.C. to “promote a greater degree of understanding and cooperation between the two races.” Standing Bear claimed, “the Indian understands the white man as the white man has never learned to understand the Indian.”

Ziolkowski also planned for him to perform on Sunday afternoon May 16 at 3:00 at the Hall High School Auditorium in the center of town. He was to appear in full ceremonial dress under the auspices of the Noah Webster Fife and Drum Corps. Townspeople needed to get tickets to get in. Ziolkowski recorded a hitherto unknown ancient chieftains song for folklore collections. Standing Bear described in detail the ceremony followed in making a tribal chieftain.

Preceding the presentation, Ziolkowski scheduled the Noah Webster Fife and Drum Corps to play a concert on the green along with the Mattatuck Drum Band of Waterbury playing military pieces at 2:45. The bands and Boy and Girl Scouts planned to parade to Hall with the Chief in full regalia.

Standing Bear also conferred with Korczak Ziolkowski before he went into the armed forces about the prospective Crazy Horse Memorial to be carved by the sculptor out of one of the granite hills of South Dakota which Crazy Horse defended so valiantly. Standing Bear and his fellow chiefs’ dream since the late 1930s would hopefully come to fruition at the end of the war.

In his 1943 visit to Washington, Standing Bear did not get approval for the monument. Harold Ickes, Secretary of the Interior, proclaimed “I will not have my mountains defaced.” Ziolkowski replied “Sir, I will not deface your mountain, my work will serve only to compliment nature.” Ickes carried the day.

But Standing Bear and Ziolkowski continued their work. Ziolkowski built a model out of 300 pounds of Tennessee marble, working at a personal expense of $40,000. The war interrupted Ziolkowski’s work, but when he was discharged, he hadn’t lost the desire to work with Chief Standing Bear.

In March 1946, Ziolkowski traveled to Washington where he again tried to convince government officials in the Office of Indian Affairs and Under Secretary of the Interior Oscar L. Chapman and this time, got their “moral backing.” Ziolkowski never took any government money for the project.

On April 28, 1947, Ziolkowski left his West Hartford home at 5:30 a.m. with a five car caravan and a party of seven for the Black Hills to begin work on the 400 foot long and 300 foot tall sculpture of Crazy Horse on the 8,000 foot mountain. He had 4 ½ tons of tools and equipment and the blessings of his wife who would meet him in July after recovering from illness. He was joined by a family of four from Maine, a man from Burlington and Kenneth Farber, a 21 year old son of Max I. Farber, assistant managing editor of the Hartford Times.

As he began his 2,000 mile trip, he did not know where his financial backing would come from, but he hoped tourists would contribute to support the project.

His hope to build a museum from the used stone removed from the mountain to house the ancient treasures of the Sioux Indians has come true as witnessed by West Hartford’s Emma Briggs. But his dream to build an Indian University on the site has not yet come to fruition. As work on this monument moves into its 65th year, Ziolkowski’s family carries on the work to memorialize the courageous Indian leader who won in battle against the U.S. government. Ziolkowski’s project and his West Hartford connection live on.
