## The Arsenal of Democracy {-}

*Originally appeared in West Hartford Life, May 2002*

At West Hartford’s May 1941 Memorial Day parade, Governor Robert A. Hurley, then a resident of 99 Outlook Avenue, declared:

> Those rights which we enjoy today of freedom of religion, speech, press and assembly can be lost, if we do not throw the full weight of our resources and manpower against the brute forces of totalitarianism, and in their place substitute a state which forbids individual worship; flings us into prison without trial; confiscates our property without compensation; inters us in concentration camps and inflict[s] upon us the most cruel tortures ever devised. . .The forces of world chaos are no less threatening to our security than were the elements of disunion in Lincoln’s day. We can survive only if we meet them with the same determination that he and the common people of his day did.

Hurley’s interventionist rhetoric ran counter to U.S. public opinion. Nearly 90% of the population opposed entrance in an almost two-year-old European war.

On the other hand, by May 1941, West Hartford’s economy already reaped the economic benefits of war, as we threw the “full weight of our resources and manpower” against the Axis. Pratt & Whitney, a division of Niles-Bement-Pond, opened in 1940 on New Park Avenue, the site of Charter Oak Park, Luna Park and the Connecticut State Fairgrounds where Home Depot is today. Pratt & Whitney Machine Tools manufactured precision gauges and machine tools already in high demand from the Allies.

![Pratt & Whitney built on the Charter Oak Race Track property and opened this factory in 1940. By December 1940 the factory ran 24 hours a day, 7 days a week and a year later employed almost 5,000 workers. The six CIO unions helped keep morale up through the war effort. Source: Noah Webster House & West Hartford Historical Society.](images/08-pratt-and-whitney.jpg)

By December of 1940, 3,586 employees worked 24 hours a day six days a week in capacity operations, a year before the United States entered World War II. Wages increased 27% between 1939 and 1940 and were 15% higher than they were in 1929, before the Depression. Prosperity crept back into town as Connecticut continued its role as the “arsenal of democracy” during wartime.

By December 17, 1941, just 10 days after Pearl Harbor, the workers at Pratt showed their unified support for the country’s war effort when they rallied at the plant. In a telegram sent to President Franklin Roosevelt, they said, “The employees of the Pratt & Whitney Plant. . . 4,600 strong, are unanimous in their support of your program and wish to assure you of their 100 percent effort in increasing production of machine tools, small tools and gages so urgently needed.”

According to President Clayton Burt, Pratt & Whitney produced three times as much in 1941 as their peak output in 1929. The machinists’ union leader said “We must pledge ourselves for more production.We must pledge ourselves for the complete defeat of fascism and triumph for democracy.”

From August 1940 to August 1942, the company expanded seven-fold. For this growth and production, the factory received the joint Army-Navy “E” flag won for excellence in war production.

The federal War Production Board, trying to maximize war production, encouraged companies to establish management-labor committees in early 1942. The *Hartford Times* featured Pratt & Whitney’s committee in an April 15, 1943 story. The committee, which included six CIO union men and six men from management, tried to increase production while maintaining a sane daily life for its workers. The committee dealt with a wide variety of problems including rationing, safety, and blood drives.

One of the main tasks of the committee was communication. They put up some 175 bulletin boards and plastered them with posters to induce each worker to increase his personal efforts in speeding up production. Twelve large informational bulletin boards posted war news, war maps, nutritional diets to maintain health, and cartoons to boost productivity and encourage a positive attitude toward war work.

The company instituted a suggestion box program. Pratt & Whitney gave a minimum prize of $5 for each accepted suggestion with no top limit. Management awarded prizes totaling $2,775 for 240 suggestions that helped make the plant more productive.

A subcommittee on worker transportation arranged carpools to save on gas and rubber. These committees also supervised war bond drives and Pratt never failed to go over the top on any of the drives.

With a seven-day week and 12-hour days, it was difficult to keep workers at work and absenteeism was a big problem and a joint subcommittee addressed that issue. A safety committee helped to reduce the frequency of injuries, thus increasing production. Hiring of a medical director and staff to take care of illnesses and promptly treat small injuries proved successful in keeping production going and helping the workers. These joint management labor councils served to keep the lid on labor demands during the war.

The local press and the federal government applauded production at Pratt and encouraged the joint union-management council through its War Production Board. However, it was an uneasy alliance. Workers and management believed what Governor Ray Baldwin pledged in his 1943 Memorial Day speech in West Hartford: “We must see that the materials and weapons needed are supplied to those who are fighting to maintain our liberty, who are beating down the forces of oppression and tyranny. We have a duty and a pledge to them.” But when the war ended, that common purpose no longer united them.

Just seven months after the Japanese surrendered in 1945, the workers at Pratt & Whitney went on strike to get their wages in line with production and inflation. The machinists struck for 20 weeks, from mid March until August 7. The company laid off over 4,500 workers from its peak production days to a low of 2,500. By the end of the strike, there were but 1,800 left at the factory. The *Metropolitan News* claimed the strike had “all the panoply of a ‘big league’ strike.” Workers were fined for picketing the homes of the business owners in town.

Governor Baldwin’s words on Memorial Day in 1943 were somewhat prophetic. He said that the Germans had misjudged us believing that “because we are a nation of many tongues and many kindreds we would disintegrate readily. But, we are held together indissolubly by a common bond of love of liberty and freedom.”

It was the common enemy in war that kept the Americans together. When the war ended, the “many tongues” spoke again for themselves, questioning personal sacrifices made in the war for the good of all. Workers in West Hartford, and around the country, spoke boldly for their individual and collective rights, which had been muted during the war. The federally imposed cooperation during the war improved life for workers only to an extent and when the forced cooperation imposed by the war emergency was lifted, the workers raised their voices once again.
