## Resistance to Public Housing and Integration during World War II {-}

*Originally appeared in West Hartford Life, April 2002. Much of this information comes from Katie Winterbottom’s research in Spring 1998. She won the Freeman and Mary Meyer in West Hartford History and her article was published in the Fall 1998 edition of The Spectator.*

On September 12, 1943, a West Hartford resident worried that their town would be “overrun by blacks much like what happened in the north end of Hartford.” What prompted this remark in the middle of World War II?

Many families migrated to the Hartford area during the war to get defense jobs. Nationwide, over four million workers, plus five million family members, migrated to defense plants. Hartford was a big draw for workers. Colt’s Firearms by 1941 was the largest private munitions maker in the United States and the only one that made machine guns. Billings and Spencer, Pratt and Whitney Tool, all prompted the Army and Navy Munitions Board to place the city on a list as one of the 14 most vital strategic industrial areas in the country. In West Hartford, New Departure, Abbott Ball Bearing, and Whitlock Coil and Pipe all received war contracts.

An estimated 18,000 people migrated to Hartford in 1941 alone, lured by jobs whose incomes rose from an average of $2,207 in 1938 to $5,208 in 1942, an increase of 136%. The housing shortage grew as the war progressed as more people moved to the area. Private developers could not get the materials to build because all building materials were controlled by the government and went to the war effort.

To address the housing crisis, the federal government awarded West Hartford $1,000,000 in 1943 to build housing for war workers and their families. West Hartford made plans to build 256 dormitory apartments and 72 single-family homes by June of that year.

When West Hartford received the subsidies for housing, citizens and public officials expressed their concern. The chief of West Hartford’s Housing Authority said he wanted “no slums in West Hartford.” He agreed to the project only after he was assured that the structures would be torn down at war’s end. Residents expressed concerns that this housing would bring people from the city and West Hartford seemed concerned about its reputation as a homogeneous, upper class suburb. The West Hartford Housing Authority imposed eligibility restrictions on housing residency: residents had to be from more than 50 miles away to qualify. West Hartford residents believed that this would insure that they would move back to their hometowns when the war was over.

When the two apartment complexes were finished, by September of 1943, only about 20 out of 300 apartments were rented in Oakwood Acres (on the present day site of Kennedy Park) and only 14 of 300 in Quaker Lane Acres (near where Quaker Lane and Trout Brook Drive meet). African American defense workers applied to live in the apartments but the town authorities refused to let them rent. A realtor believed that real estate values in the area would decline sharply “if Negroes in any considerable number moved into town.” The few people who had rented the government-subsidized apartments also expressed concern, arguing that they would move out if blacks moved in.

Residents looked to their U.S. Senators, Francis Maloney and John Danaher to establish whether blacks had to be allowed in. The Federal Housing Authority then investigated the situation and gave West Hartford an ultimatum: it was unconstitutional to exclude black war workers from the projects, and if the town authorities would not let them in, the federal government would take over the management of the housing.

Local residents continued to fight to exclude African Americans from the government housing. They evaded the federal orders by establishing that only African Americans who worked in what they called “essential industry” in West Hartford would be allowed to live in the new government housing. Only six blacks fit this criterion and none of them wanted to move into West Hartford. No African Americans lived in this housing during World War II.

The housing was never fully occupied during the war. Some West Hartford residents continued to be concerned with what they deemed to be “slums” and wanted them immediately demolished at war’s end.

However, millions of veterans came home at the end of the war, and high inflation, a continued housing shortage, and many veterans who got low paying jobs needed this housing as much as the war workers had.

The government aided the veterans by allowing them to move into the public housing developments occupied by war workers during the war, and the federal government paid 3/7 of the rent. In the late 1940s, the waiting list for the West Hartford housing stood at 1,500. Arguments to tear down the housing were countered with cries of patriotism and support of the veterans.

But, by 1951, the campaign to rid the town of the housing began. First, no new occupants could move in. Over the next five years, residents left by choice and through pressure. On April 1, 1956, the town demolished Oakwood Acres and South Quaker Terrace housing.

Elmwood Acres, the single-family homes on Elmhurst Drive were sold to a private owner. Rents increased $40 to $60 per month for the same house and some families had to leave town for economic reasons.

Because of the influx of people to the Hartford area caused by the dislocation of war production, the town of West Hartford had to make decisions about racial integration that it had not had to make before. When historians study war, they evaluate to what extent social dislocations resulting from wartime emergencies bring lasting change to society. They particularly look at the lives of African Americans, women, and the poor to see if they gained a bigger piece of the American pie in terms of social, economic or political status. In this particular case, those in political power and the citizenry in West Hartford resisted change by hanging on to local control. It was not until the turmoil of the civil rights movement in the 1960s that West Hartford directly addressed these issues again.
