## Mobilizing for World War II {-}

*Originally appeared in West Hartford Life, May 2011*

Most history textbooks analyze the decision to enter World War II as being a reaction to this singular bombing at Pearl Harbor, but in fact, the nation had been gearing up for war for at least a year and a half, not just on the federal level, but also in local towns like West Hartford. In 1941 in our town, men were signing up for the draft, factories were bulging with defense contracts, and local volunteers organized relief for those in war torn Britain. The economy and society were on a war footing before West Hartford’s Gordon Sterling was killed at Pearl Harbor. Once the United States declared war, those on the homefront responded.

In 1941, West Hartford’s mobilization for World War II was built on the fear of being attacked, building armaments, and helping those whose lives were already being devastated by war. West Hartford residents mobilized quickly for the war.

Since Germany’s invasion of Poland on September 1, 1939, the U.S. economy began to manufacture munitions and war supplies for the British, to defend them from, as President Franklin D. Roosevelt called them, “the aggressors.” Congress authorized a fivefold increase in the defense budget from $2 billion to $10 billion in 1940.

On September 25, 1940, FDR signed the first peacetime conscription law in United States history. This law required men between the ages of 21 and 35 to register with local draft boards. A maximum of 900,000 men were chosen through a lottery system and served for 12 months. Fifteen months later, Congress amended the law to include all men between 18 and 65.

On January 6, 1941, Franklin D. Roosevelt delivered a State of the Union Address that beckoned Americans to prepare for war.

In mid January 1941, the women of St. James Episcopal Church established a unit for British Relief to make layettes and children’s underwear to send to the British War Relief Society. The manager of the Park Road Department Store donated much of the raw materials needed to do the work. The women of the church set up to meet from 10 to 4 Monday to Friday. Women within the community helped out for the war effort before our country was officially at war.

The Lend-Lease Act, March 11, 1941, formally ended the U.S. pretense of neutrality. Hitler responded by ordering German subs to attack US vessels and the S.S. Robin Moor was sunk in May 1941. But the U.S. did not decide to enter the war militarily.

In 1941, the U.S. role was as an arsenal of democracy. On January 27, the War Department announced that West Hartford’s Pratt & Whitney Division, Niles-Bement-Pond Company won a $44,000 war contract to make gauges for the war effort. This factory, built in 1940, manufactured precision gauges and machine tools already in high demand from the Allies. Employment grew from 2,500 in 1939 to 4,600 in 1941. The plant ran 24 hours a day, 7 days a week.

In April 1941, the federal government began the sale of war bonds. In May, the federal government built war housing in the South Meadows of Hartford and in East Hartford. In June, the United Service Organizations drive to raise $50,000 went over the top. In June, a congressional committee announced that Connecticut would need 50,000 more workers in six months to keep up with defense contracts. And U.S. Housing Authority Administrator who visited Hartford in June pushed to speed up defense housing construction. There was talk of building defense housing in West Hartford.

With the attack on Pearl Harbor, West Hartford lost its first soldier in battle, Gordon T. Sterling. Sterling had been serving already for a year when he engaged in battle. From his plane he shot down one of six Japanese planes before his was shot down and he was killed. This attack spurred local residents to prepare for attacks on the mainland.

Two days after the Japanese attack and Sterling’s death, the assistant secretary of the American Radio Relay League of West Hartford revealed that “tens of thousands of radio amateurs” were ready to assist in civilian defense of the West Coast. In the previous year, the league supplied the United States military forces with valuable radio operators, who had been trained by local leagues.

By December 11, 18 women drivers and six suburban cars of the Hartford unit of the State Defense Council’s Women’s Motor Corps reported for duty at the State Armory. The women were under the command of Captain Mrs. Thomas Sergeant of West Hartford and served to transport guardsmen from armories to their assigned duties.

The fear of attack was palpable. Three days after Pearl Harbor, concerned parents held a meeting at the Beachland Park Clubhouse to express their “great concern” over the proximity of Charter Oak School to Niles-Bement-Pond defense plant just ¼ mile away from the school across Flatbush Avenue. The parents proposed that students be transferred to the Elmwood School. Within a week, Superintendent Lloyd Bugbee had calmed down the parents so that they had voted “complete confidence” in the Board of Education concerning the policy for school children to remain in buildings in case of an air raid. Bugbee also provided sand bags for extinguishing firebombs for each school.

At the same meeting more than 60 people volunteered to be air-raid wardens. They had to train at the air-raid warden school to be held at Hall High. West Hartford volunteers would man the air raid post in the Trinity College tower.

Twenty residents enrolled in the auxiliary firemen’s training school. They feared that plants like Holo Krome, Jacob Chuck, and Niles Bement Pond making goods for the defense industry bombs would be targets and citizens needed to be ready to douse fires. These 20 residents and over 70 high school students learned how to control incendiary magnesium bombs, also known as firebombs. These bombs were used in night raids, where bombers could not see their targets, but the consequent fires caused destruction. Surely West Hartford residents had read about Germany’s bombing of London in 1940-41.

Leaders in the Town Hall established a Volunteer Bureau and four days after Pearl Harbor, scores of people registered to help with first aid, home nursing, canteen, nutrition, motor corps, air raid warden, group leader, auxiliary fire and police service and demolition squad.

Arthur N. Rutherford, the head of the town’s building department led the town’s demolition team. He sent letters to over 300 builders and contractors and in a month he had mobilized plumbers, oil burner mechanics, electricians, carpenters, and other skilled tradesmen. He organized the town into four areas with 36 sectors to help rebuild in case the town was bombed. Rutherford also surveyed local schools to recommend buildings that would be suitable for air raid shelters. By January 18, 1942, builders and contractors pledged 250 vehicles for defense use. More than 600 emergency workers volunteered to work with the Defense unit to be ready to demolish buildings if they were bombed.

This Memorial Day 2011, the parade committee is honoring veterans from World War II. The youngest veterans, now in their mid 80s will be honored during the parade and in the program. As our veterans are recognized on Memorial Day, we should also remember the sacrifices made by those left on the homefront who supported those who fought the battles.
