## Christmas Carol Sing {-}

*Originally appeared in West Hartford Life, December 2010*

In the late 1940s, the West Hartford Recreation Department and the Chamber of Commerce sponsored a Christmas Carol Sing at the First Church and Goodman Green. On the north end of the green, town workers lit up a “Christmas Tree,” and as many as 5,000 town residents gathered for the sing and an appearance by Santa Claus.

The tradition began in 1930 as an interdenominational carol sing which attracted hundreds of people. In 1940, when West Hartford added a Recreation Department to town government, as Christmas became more commercialized, and West Hartford more affluent, the celebration changed.

Charles L. Rutherford, President of the Chamber of Commerce, rallied many local groups to help organize the first Christmas sing which included the Department of Recreation, the West Hartford Parent-Teacher Council, the West Hartford Exchange Club, the Kiwanis, the Civitan Club, the American Legion, and the Lions Club. On December 21, 1947, organizers expected 2,000 people to come to the 7 p.m. community Christmas Party, Carol Sing and Reception for Santa.

The 20-minute carol sing rang out from the portico of First Church of Christ Congregational. More than 250 trained choral singers from the First Church and St. Thomas the Apostle, and from Talcott Junior High led the carol sing from the portico steps under direction of Gordon Stearns, choir director and organist at the First Church. Two radio stations carried the sing.

Over 4,000 children and adults came to celebrate; the police were temporarily unable to bring “order out of the gaiety.” When Santa Claus arrived with a sleigh that had favors donated by 40 local businessmen, to distribute to the West Hartford children, it was hard to contain the crowd.

Rutherford and his committee wanted to emphasize that Christmas was about giving. His committee wanted to help war-torn France, and with the help of the American Friends Service Committee, they organized a drive for food and school supplies to send to elementary schools in northern France. The AFSC had just won a Nobel Prize for its post war relief work and aided Rutherford’s group in selecting two schools. A West Hartford school administrator sent directions for gift giving to every public and private school student in town.

The 4,000 townspeople who came to the Community Sing brought along 14 boxes of food and school supplies weighing two tons. Helpers packed the goods into duffle bags, took them to the American Legion Hall where they were packed and shipped by the Legionnaires.

The committee arranged for the goods to be sent to the École de Garçons in Caen and the École de Filles Valmy in LeHavre. The Germans burned the Valmy School to the ground a few hours before the liberation of LeHavre in 1944. When the goods arrived in February 1948, the schools still had not been rebuilt and classes were being held in temporary quarters. The head of the school wrote that the children were sons and daughters of laborers who did not have a lot to eat. The packages were well received and many thank you notes made it back to students in their classrooms.

The Carol Sing provided such a positive outpouring of goodwill, organizers geared up for 1948. This time organizers chose to send warm clothing and foodstuffs to “undernourished and ill-clad Sioux and Chippewa Indians in North Dakota.”

In 1948 the choir would have 500 voices. Frank Groff, new music director for WHPS, organized singers from the First Congregational Church, St. James Episcopal, St. John’s Evangelist, a Talcott Junior High School group, Hall High and a select group of 5th and 6th graders.

In 1948, the Chamber spearheaded the community event for a second time. The Christmas Party Committee corresponded with W.M. Simmerman, the Director of the Bureau of Indian Affairs. The BIA suggested the goods be sent to 1,500 children of the Turtle Mountain Chippewa and the Devils Lake Sioux near Belancourt, North Dakota. In 1948 there were about 33,000 Chippewa, half in Canada and half in the United States. The Sioux were descendants of Crazy Horse and Sitting Bull and lived in poverty on government allotments. Each elementary school student who brought and wrapped a gift, put a sticker on it which read “a Package for a Papoose from West Hartford Community Christmas Party, December 19, 1948.”

The committee in 1948 assured carolers and gift givers that there would not be bad weather because “We live right. That just couldn’t happen to us.” However, the carol sing, which planners thought would bring 5,000, got called off as the town was pelted with 10 inches of snow. The committee collected the gifts and sent them along to the Indians in South Dakota.

Meanwhile, as the snow began to fall in the late morning, the women of the Food for Israel Campaign started collecting packages to be sent to the Holy Land. They collected over 350 bundles that were sent by trailer to New York City to be shipped to Israel.

In 1949 the community supported the carol sing once again. This time, Frank Groff assembled an 800-voice choir from five churches with 600 school children’s voices.

The *West Hartford News* encouraged townspeople to bring presents of clothing, shoes, toys, infants’ wear, and woolen garments to the children at the Shaw Center in Charleston, S.C., a “welfare center for 1,200 Negro children.”

Since the end of World War II, the naval building program and other war activities were hit hard. The Carol Committee worked with the National Association for the Advancement of Colored People (NAACP) to find this group. The Shaw Center was made famous as the locale for George Gershwin’s operetta, "Porgy and Bess.”

The invitation in the *West Hartford News* read “A traditional, gay outing for the Family. Santa will bring favors for the children, and receive gifts of clothing for little Negro boys and girls in South Carolina.”

Rose Wathley, the elementary school supervisor and a member of the party committee once again organized the collection of goods from elementary school children. When the party was first established in 1947, and Wathley was on the committee, she pushed that children truly get more kick out of giving than receiving and it was her suggestion that instead of having Santa arrive at the Carol Sing with sacks of gifts for West Hartford kids, he would come to receive West Hartford children’s gifts for less fortunate boys and girls.

In 1949, the committee had a 30 foot trailer truck at the carol sing so that the gifts could be loaded right on the truck to take the next day to South Carolina to get there in time for Christmas. The trucking company provided the service free of charge. The 3500 attendees donated over 1500 gifts. When the gifts reached Charleston four days later, the Community Center held the biggest party of its kind ever in Charleston. There were three to four tons of gifts. The children, recruited through the Christmas Bureau of the Charleston Welfare Council, were grateful.

This community celebration showcased the varied community groups willing to work together for a common cause. Based on a Christian holiday, these celebrations are certainly the sign of a different time. Though the public celebration of Christmas is as big as ever, and the town encourages Christmas sales with its decorations, its involvement in a carol sing would not be seen as appropriate today. Supreme Court cases in the 1980s discouraged government support of Christian religious displays and West Hartford’s growing Jewish population must have forced elected officials to view its sponsorship differently after 1950.
