## West Hartford’s U.S. Senator William Purtell {-}

*Originally appeared in West Hartford Life, January 2007*

On July 29, 1959, Republican Senatorial candidate William Purtell addressed 150 women who belonged to the Hartford County Women’s Republican Association in Avon. He said women have the major influence in controlling the nation’s economy due to their role purchasing consumer goods for their homes. He then urged them to get involved and exert influence in political activities on the same level.

William Purtell’s awareness of women’s role in government surely came from his sister, Edna, who was the youngest suffragist at age 19 to go on a hunger strike with the National Woman’s Party in Washington. The suffragists were arrested in front of the White House in 1918 chanting, “Mr. President, how long must women wait for liberty?” Over 30 years later, Edna, who never married, still lived in West Hartford as did her brother William.

Born in 1897, William Purtell grew up in a poor family in Hartford and left high school after only two years. His first job was in a rail yard. This led him to his second job which was scheduling wartime rail shipments to Colt’s Firearms.

Purtell enlisted in World War I in 1917. Upon his return to West Hartford, in 1919, he spent ten years as a salesman. In September 1929, at age 32, he founded the Holo-Krome Screw Corporation. On the day the stock market crashed in 1929, Purtell and his two co-owners turned out their first innovative socket screw. No longer was a screw machine needed to produce these parts which made their production much less expensive. Purtell soon secured a patent for his cold-forged socket screw which allowed for the mass production of high tensile alloy steel socket screws.

Founding the company at the beginning of the Depression was not so easy, but early on Purtell realized that his company’s fortune was tied to his workers. He held his employees in high regard and they willingly took short paychecks at times when the company was in financial trouble. Purtell’s company introduced one of the first profit sharing programs for workers in the country. A breakthrough came for Holo-Krome when they sold the socket screw to Detroit’s auto manufacturers, putting the company on firm footing.

In 1936, Holo-Krome, with 40 workers, moved to Newington Road. By 1938, the company was doing so well that Purtell bought Billings and Spencer, a tool and forge firm. The company became a supplier of military parts during the Second World War. By 1946, Holo-Krome became a subsidiary of Veeder Root, a larger company that Purtell later headed. He also served as president of the Connecticut Manufacturers’ Association and as a director of the U.S. Chamber of Commerce.

Purtell was known for his speaking ability. He helped organized the American Legion in Connecticut and spoke on their behalf. He used his speaking engagements to talk about how solutions to social problems should be solved by private initiative. Only after the private sector tried to solve the problems, should the government step in. According to Jack Zaiman, the *Hartford Courant* political writer, Purtell was a great campaigner because he “was an industrialist, with a vibrant, peppery, glad-handing approach.”

In 1950, the Republican Party came to Purtell asking him to run for Governor. He said he did not want to run, but when they chose John Lodge, he changed his mind and went into the convention looking for the nomination despite the leadership backing Lodge. His skills as a speaker endeared him to many voters as he traveled around the state to garner delegates. But he lost the Republican nomination to John Lodge who ended up winning the election. Purtell continued to run his business, but kept his interest in politics

Connecticut’s Republican Governor John Lodge made amends with his adversary when he appointed West Hartford’s Purtell to the U.S. Senate seat after Brien McMahon of Norwalk died in office in the summer of 1952. Purtell was already running for the open Senate seat---he had won the nomination against Prescott Bush who was supported by the party. Prescott Bush (R) defeated Abe Ribicoff (D) in the November election for this seat and Purtell defeated incumbent Senator William Benton for the other Senate seat. In the course of six months, he held both of Connecticut’s Senatorial seats.

Purtell was an independent Republican who kept the party at arm's length. During the campaign, Wisconsin’s Senator Joseph McCarthy came to the state and spoke in Waterbury. Purtell did not appear with McCarthy, spurning his help. To voters, Purtell represented “clean independence, unmarred by political clichés.”

Purtell was most proud of his aid to deaf children and help to low income groups. Even though he saw his political career as “less than successful,” he had numerous accomplishments. He served as member of the Labor and Public Welfare Committee and the Committee on Interstate and Foreign Commerce. He served on subcommittees which dealt with juvenile delinquency, welfare and pension plan legislation and health. One of his most important assignments came when he was appointed by then Vice President Richard Nixon to the select committee to investigate lobbying. He was also an official observer at the United Nations Atoms for Peace conference in Geneva in 1955.

As a businessman, Purtell believed in “competitive capitalism” to solve the social problems of the day. In a speech before Jewish war veterans in 1956, he urged the private sector rather than the federal government to take care of social problems. In this way, Purtell argued, capitalism would always win out in the Cold War over communism. In 1956, Purtell traveled to Russia to try to open up investment opportunities for American businesses. Purtell also voted for price supports for tobacco farmers.

Purtell was viewed as a liberal Republican who supported increases in foreign aid, particularly to fight communism. He also supported a reduction in the age for women to collect Social Security to age 62. He protected the rights of children in urban areas in relationship to their rights to Social Security.

In 1956, at the Republican Convention, there were rumors that Purtell would run for Governor in 1958 against Abe Ribicoff, but he did not choose to do so. In an interesting turn of events, Purtell’s sister Edna was hired by Democratic Representative Tom Dodd to head his office of women’s concerns.

When Purtell ran for reelection in 1958, Democrat Thomas J. Dodd who lived on Concord Street in West Hartford defeated him. The circumstances for a Democrat were ripe in 1958 as it was the midterm election during a Republican presidency. Dodd was a real politician who worked the Democrats in the state. Purtell tried to attack Dodd on his record, without doing much to stand on his own record.

Back as a private citizen, Purtell ran a small machine tool shop in East Haddam. Bill Purtell died at his home on 6 Arlington Road at age 81 in 1978.

Purtell’s background as a business owner and his great speaking ability led him to success in politics. Though he never finished high school, he never felt that citizens should see that as something to emulate. Purtell never wanted to downplay the importance of an education and wrote a letter to the editor claiming that times had changed so much in the economy that he should not have been looked at as a role model for that reason. He continually stressed the importance of a good education for all citizens.
