## A Special Bond between West Hartford’s Jews and Israel {-}

*Originally appeared in West Hartford Life, July 2008*

The Greater Hartford Jewish Federation marked Israel’s 60th anniversary on June 1 with a celebration at West Hartford’s Mandell Jewish Community Center. This celebration marks more than 100 years of support for Israel in the Hartford region.

Ronnie Siegel of West Hartford, the event coordinator, was born in Israel the year it became an independent country. The JCC was a natural place for this event, as it has been a hub for the Jewish community in the Hartford region since 1962.

In *Making a Life, Building a Community: A History of the Jews of Hartford* (1997), David Dalin argues that the Hartford area was an early and important center of American Zionism. Zionists support the establishment and continuation of an independent state of Israel.

In the 1930s and 1940s, the Jews in Hartford were united about the need for the establishment of a Jewish state. The size and strength of this consensus was unmatched in other metropolitan areas. Dalin argues that:

> all members of the Hartford rabbinate, whatever their differences on other religious and ideological issues, shared a passionate and unequivocal commitment to the Zionist cause... Indeed, during the 1940s, Hartford was one of the few American cities with a large and historically venerable German Jewish Reform component in which the anti-Zionist American Council for Judaism did not establish a strong organizational foothold.

Perhaps it was the size of the region and its large proportion of Jewish residents that helped to unite the Jews. Dalin suggests it was leaders like Rabbi Abraham Feldman who helped unite all Hartford area Jews to the Zionist cause.

![Rabbi Abraham Feldman served Beth Israel from 1925 to 1968. The synagogue was the first to move to West Hartford in 1936. Feldman organized a local rabbinic organization that drew active participation of Orthodox, Conservative and Reform congregations. Source: Jewish Historical Society of Greater Hartford.](images/09-feldman-web.jpg)

The idea of a “land of Israel” goes back to Biblical times as told in Psalms and is found in the daily liturgy of the Jewish service. The theological ideas of Zion first found a political voice in the late 19th century as nationalism and socialism took hold in Europe.

In 1882, a group of Russian Jewish students went to Palestine, then a part of the Ottoman Empire, to begin an agricultural community.

In 1885, the Jewish Reform Movement in the United States adopted the “Pittsburgh Platform” that denounced building a political nation. The American Reform movement stated that it did not want to be a nation, but instead saw themselves as a “religious community” and did not expect to return to Palestine or establish a Jewish state.

Historically, this position made sense in the context of the late 19th century United States. Jews, and particularly German Jews, had reached a certain point of acceptance in the U.S. They believed that the freedom they experienced in the United States made a separate “Zion” unnecessary.

Isidore Wise is a good example of a man who “made it” in America. He and Gershon Fox, also Jewish, both owned department stores downtown. Wise was the president of Congregation Beth Israel (1907-1942) and owned Wise, Smith & Company, a department store on the west side of Main Street right across from G. Fox & Co. He was president of Beth Israel when the congregation was on Charter Oak Avenue in Hartford.

However, with increased Jewish immigration from Eastern Europe caused in part by continued pogroms in Russia, and more tension even within the Jewish community in the U.S., the ideas of the American Reform Movement began to shift in favor of a Zionist state.

Rabbi Abraham J. Feldman, who served Beth Israel from 1925-1968, was a leader in West Hartford and nationally, and an ardent Zionist as well as part of the American Reform Movement, beginning in his student days. At the University of Cincinnati, Feldman invited lawyer Louis D. Brandeis, a passionate Zionist, to come speak to the Jewish Honor Society called the Menorah Society in 1914.

Brandeis was a leader of the American Zionist movement. In 1916, Woodrow Wilson appointed him to the U.S. Supreme Court where he served until his death in 1939. Even while Brandeis served on the Supreme Court, he worked actively for the Zionist cause.

In 1918, at Hebrew Union College, Feldman challenged the president of the college to debate him on Zionism. Feldman was one of the key local and national players who took on the challenge of uniting Reform Judaism with Zionism. He brought those strong beliefs to town and continued to organize and support Zionism throughout his tenure at Beth Israel.

In 1921, the Hartford Jewish community held one of its first public events in support of Zionism when Chaim Weizmann, head of the World Zionist Organization, who went on to become the first president of Israel, came to Hartford with internationally renowned scientist Albert Einstein. They arrived in a motorcade of 500 cars and 15,000 spectators lined the streets.

Unlike most other cities, Hartford’s rabbis were united behind the Zionist idea. Einstein and Weizmann had lunch at the Hotel Garde and then both men addressed the packed house at the Capitol Theater, which at that time had the largest seating capacity of any theater in New England. The two men raised $100,000 for the World Zionist Organization.

By the time Israel proclaimed its independence in 1948, middle- and upper-class Jews had moved from the Front Street area of Hartford to its West and North Ends and into West Hartford.

Both Congregation Beth Israel (1936) and Beth David Synagogue (1943) had opened in town and Rabbi Feldman established a local rabbinic organization that drew the active participation of Orthodox, Conservative and Reform rabbis, ones with whom he vocally disagreed, but whose unity made the Jewish community stronger.

Unlike other metropolitan areas, the Hartford region’s Orthodox, Conservative and Reform congregations all supported Zionism early on. This support has not always been easy as unrest continues in the Middle East. West Hartford’s united celebration of Israel’s independence in 2008 shows, in part, a long history of Jewish cooperation in the Hartford region.
