## School Superintendent Edmund Thorne {-}

*Originally appeared in West Hartford Life, May 2007*

Edmund Thorne, the town’s third superintendent, headed the biggest school building program in town history. Building eleven new elementary and junior high and high school buildings stands out as the hallmark of his tenure from 1947 to 1964. But beyond the bricks and mortar, Thorne had an educational vision that put the town at the forefront of educational policy and practice.

In 1963, Thorne provided an overview of the changing issues in the schools in a 32 page annual report written for the Board of Education. Thorne’s hopes and concerns about the West Hartford Public Schools reveal much about the town, the state of education, and national trends.

Thorne had much to deal with coming out of World War II. A backlog of facilities problems as a result of putting off maintenance during the war led to replacing coal fired and hand stoked boilers. Town crews replaced roofs and plumbing. Physical plants needed to be repaired. The town not only built eleven new schools between 1949 and 1964 at a total cost of under $17 million, but it also modernized and made additions to nine older schools at a cost of under $5 million. Today, building just one middle school Bristow, cost about $24 million dollars.

The baby boom affected West Hartford more than other towns. A huge boom in desirable residential housing and the drive to live in this inner ring suburb led to the school population growing from about 5,000 in 1947 to 12,000 in 1963.

But Thorne’s interest went beyond finding spaces for the rapidly growing school population. He was also concerned with funding the schools, teacher salaries, special education, honors programs and learning that went beyond testing.

During World War II, teachers’ salaries did not keep pace with industry salaries. Many teachers left for higher paying jobs in the private sector. Teachers with less expertise and experience replaced these employees. Starting pay was $2,100, about $55 per week. The maximum salary was $4,200. Thorne believed in paying for quality. From 1961 to 1963, on the recommendation of a Citizen’s Committee, he awarded merit pay. However, difficulty in its administration led to its suspension. Thorne believed the difficulty in attracting good teachers also lay in a shortage of administrative, supervisory, and clerical staff.

When Lloyd Bugbee wrote his last annual report in 1947, he stated that out of 169 towns in the state, West Hartford was ranked 90th in per pupil expenditure. At the same time, the town was the 18th from the top in wealth per pupil. Thorne believed the town should provide more support for the schools.

According to Thorne, “in 1948 there were no educational provisions for physical, mental or emotional handicaps.” Thorne believed that every child should be educated to the highest level of his potential. In 1952, the first classes for “physically handicapped and “mentally retarded” children were introduced” at Duffy School. Soon after, services were added for blind and emotionally disturbed students. West Hartford led the way in special education.

In 1952, nationally, parents of handicapped students founded the Council on Mental Retardation to seek services for their children with mental retardation. By 1963, the West Hartford Public Schools offered speech and hearing therapists, and a special reading consultant to improve reading among “retarded readers.” Thorne introduced the first and “still the only special classes in any Connecticut public school system for children with emotional problems.”  West Hartford, by 1963, was acknowledged to have “one of the best special education programs” in the eastern United States.

In 1970, U.S. schools educated only one in five children with disabilities and many states had laws excluding certain students including children who were deaf, blind, emotionally disturbed, or “mentally retarded.” The federal law that required school districts to provide education for all handicapped children did not pass until 1975.

Thorne, like educators around the country, was pushed by the Soviet’s launching Sputnik in 1957. Public figures criticized the public schools for their failures. In reaction, Congress passed the National Defense Education Act to strengthen the teaching of math and science. Thorne, his administration, and his teachers instituted a number of changes to address the perceived science and math gap. At the high school, new honors courses in all academic subjects and accelerated courses in math were offered for the first time. English teachers were limited to 100 students. Science teachers replaced textbook-centered general science courses with lab-based courses.

The school system received grants to encourage programs for “gifted” students. The high school sponsored a lecture series each year covering topics not included in the regular course offerings. Students had the chance to be involved in the American Field Service exchange program. But Thorne was concerned that the anxiety to act quickly to improve the public school system was pushing creative approaches “based upon a democratic philosophy and long-range goals of what was best for America,” out of the picture.

Thorne worried that teachers could feel as though they needed to teach facts, not concepts. He argued that teachers:

> Must teach ideas that provoke thought and lead to further learning and that stimulate critical outlook. Pupils should be encouraged to question facts, seek explanations, anticipate outcomes and question the authority behind a statement or assertion. Students should ask themselves, ‘Is this the truth?’... students should be expected to learn that even scientists make mistakes as well as achieve successes, and that true learning is not achieved through an authoritative body of facts to be committed to memory but through an imaginative way of systematically exploring the unknown.

Thorne placed himself write in the middle of the Cold War ideology when he wrote, “If there is anything that is going to help America survive in the struggle between East and West, it is that of developing creative minds and creative individuals, rather than those who merely parrot back isolated factual information.”

Thorne's philosophy makes me think about how much the word "creative" has dropped out of the educational lexicon with the present day pressures on testing to ensure that students are learning. How much do external pressures to increase our technological, scientific and mathematical skills make students independent learners and creative thinkers for the 21st century? It seems like Superintendent Thorne would support creative work.
