## The Advent of the East-West Highway {-}

*Originally appeared in West Hartford Life, August 2000*

Camp Courant at Park Road and Trout Brook?
The Oakwood Gardens Housing Project?
Kane’s Woods?
The South Quaker Lane Housing Project?

These were all sites in West Hartford on one of the proposed routes for the new East-West Highway in the 1940s and 1950s.

The housing projects have been torn down, Camp Courant moved, and Kane’s Woods developed into a shopping center and apartments. The East-West Highway, now Interstate I-84, takes a more southerly route through town. How did the federal and state government convince the town to engage in this $25 million (in the early 1960s) infrastructure project?

Moves to the suburbs in the post-World War II period, according to most historians, were escapes into conformity and consumerism away from the complexity, activism, and excitement of the city. Americans were happy to retreat to their suburbs with the help of federal housing subsidies for GIs.

But a look at the state and federal governments’ attempt to put an east-west highway through West Hartford reveals a population ready and able to challenge authority. This fight, along with conflicts over building schools in the 1950s, made West Hartford a place shaped by conflict and community activism. Citizens of West Hartford fended off building the highway for more than 15 years.

By 1949, 60% of the traffic that entered Hartford came from West Hartford. The local east-west roads, New Britain Avenue, Park Road, and Farmington Avenue were clogged with traffic and the state felt an east-west highway would help solve the traffic problem. West Hartford’s population in 1950 stood at about 62,000, a leap of over 25% since 1940. The population grew as the insurance industry in Hartford prospered.

West Hartfordites, who fashioned themselves as the residents of an upscale residential community, did not believe the highway was necessary and thought it would split the town in half, and ruin its residential character. The first plans for the highway were floated in 1945. In this plan, the highway would have gone through the center of town. At the first public in 1948, 500 protesting residents showed up, forcing officials to move the meeting from the Town Hall to the Hall High Auditorium right next door. Townspeople expressed strong opposition to a proposed plan that would have sent the highway from Prospect Street at Warrenton directly west running between Boulevard and Farmington Avenue. Just west of the Kingswood School, it would turn south to follow Trout Brook to Taylor Road to meet the highway section from Corbins Corner.

In 1950, West Hartford’s Town Council approved a more southerly route that would have gone from Prospect at Park, through the World War II housing project, Oakwood Gardens (now Kennedy Park), up Oakwood Avenue and through the South

Quaker Lane World War II housing. But, the state did not follow through at that time. Planners had as many as eight possible routes for the highway by 1956.

In January 1956, 350 residents met at the Smith School to protest the highway and formed the East-West Residents Association, elected permanent officers and voted to oppose “Plan C” as proposed by the state highway department. Residents believed that widening the main east-west arteries, staggering work hours in Hartford, installing one-way streets at rush hour working in cooperation with the Hartford City Council, they could solve the traffic problem.

At a public hearing held at Smith School in September 1956, 300 residents as well as the clergy of the newly built St. Mark’s Parish (1947) protested the highway. The Town Council unanimously voted down the newest proposed route. The East-West Residents Association pushed the Town Council to commission still another study of the proposed routes.

Part of the 1956 plan was to build a connector from the highway at Park Road and Trout Brook north along Trout Brook to Farmington Avenue to improve the movement of north-south traffic. This would have eliminated Norfeldt baseball field, a town garage, two gas stations on the corner of Farmington Avenue and Trout Brook, Bess Eaton Doughnut, a new building containing the Nichols Cordial Shoppe, and Chicken Delight, among other buildings. Trout Brook Drive was still not completed between Boulevard and Farmington. Though residents worried that the opening of Connecticut Life Insurance Company in Bloomfield on January 1, 1957 would exacerbate traffic problems, they fought at more public hearings to stop the connector.

The Town Council appeal both to the Federal Bureau of Roads and the State Highway Department was denied in early 1960. Some local politicians believed they still might stop the road but most realized they could only revamp the plan by that point, particularly what they called then the “butterfly approaches” to the highway which residents saw taking up too much land.

The Federal Bureau of Roads finally approved the east-west highway project in January 1960, 15 years after the first plan was floated. Still, some Town Councilors wanted to appeal the decision because the federal government had not done enough to consider the economic consequences to the town. But the majority of the town was resigned to the highway. The state had already spent about $5 million buying properties along the route.

By 1961, the plan that would have taken 18 homes ten years earlier, took 144. This led to a loss of $5 million on the town’s grand list. By this time, resigned to the highway, some Town Councilors argued, that commercial property along the route, especially at Corbin’s Corner and Prospect would increase in value.

Plans moved forward to start construction in October 1962. But there was one more surprise in store for the residents just west of South Main Street and north of New Britain Avenue. Engineers decided that it was too difficult to run the highway over South Main Street. This meant that eight houses on Brightwood Lane would have to be torn down because of the grade of the hill needed when they dug under South Main Street. One of the houses belonged to former Mayor Harold Keith, a vehement opponent of the highway for at least ten years. Negotiations with the state highway department led to building the retaining wall south of the entrance to I-84 on South Main Street. All eight houses were saved.

The highway opened in the fall of 1964. The section from Corbins Corner to Trout Brook was attached to the new section, now known as the “West Hartford Curves” and went as far east as Prospect. The highway was not completed through Hartford until 1969.

West Hartford residents and their elected representatives were not complacent when the state and federal government tried to impose a plan that was perceived as being for the larger good. Residents organized and pushed their elected representatives to use every appeal to, as they saw it, save the character of their town. The calm veneer of the suburb hid a contentious residential population, concerned about the nature of their town. Simultaneously, battles concerning the fate of the World War II housing and building new schools came up yearly as residents fought to define the type of town in which they lived.
