## Schools for Democracy {-}

*Originally appeared in West Hartford Life, March 2001. Sources include “Histories of West Hartford Schools,” West Hartford Public Schools, 1964, found in the Conard High School Library; David Halberstam, The Fifties (1993); and James Patterson, Grand Expectations (1996).*

School buildings and elementary school districts often have been the way people identify their neighborhoods in West Hartford. 

Families in the 1920s and 1950s supported their children being redistricted in town as the population surged in each of these decades and new schools were built. The growth in West Hartford’s Public Schools mirrors the growth of West Hartford as a suburb.

Until the turn of the century, most West Hartford students went to one of the eight one- and two- room district school houses throughout the town. Charter Oak School, built in 1884, housed grades K through 8. The first Center School, just south of the Old Burial Ground, was built in the 1860s and housed the first high school students on its second floor. A new Center School (1896) was built as an elementary school and was later renamed Whitman School and then became the police station. The Seymour School (later Smith School) opened in 1915.

By 1920, West Hartford had a population of about 8,000 people, mostly living along the major east west thoroughfares of Farmington Avenue, Boulevard, Park Road, and New Britain Avenue. With the growth in automobile ownership in the 1920s, West Hartford’s population tripled to about 24,000 by 1930. During this decade, eight schools were built in town. Three elementary schools, Beach Park (1926), Morley (1927) and Elmwood (1928) opened in a two-year span. Three junior highs (grades 7 to 9) opened between 1922 and 1931: Plant (1922), Talcott (1922) and Sedgwick (1931) that originally opened as a K to 9 school. High school students moved from the second floor of the Center School to William Hall High School (now the Town Hall) when it opened its doors in 1924.

Both the Great Depression and World War II led to a decline in home building in most of the country, but in West Hartford, the population actually grew by 76 percent between 1930 and 1940. West Hartford land developers built and sold many new homes. Nationwide, housing starts fell from just over one million per year to about 100,000 between 1930 and 1945. During the war, it was difficult for builders to siphon supplies from the war industries to build new homes. When the war ended, the building began. Pent up savings, the baby boom, and highways all led to tremendous growth in West Hartford. West Hartford’s population grew from about 42,000 in 1950 to over 60,000 in 1960.

Between 1949 and 1959, the town built nine elementary schools including:

- Webster Hill (1949)
- Bugbee (1950)
- Duffy (1952)
- Whiting Lane (1954, replacing the old East School)
- King Philip (1955, also a junior high)
- Braeburn (1956)
- Wolcott (1957)
- Norfeldt (1957)
- Bridlepath (1959)

The town built the elementary schools where the developers built the houses. After World War II, developers began mass-producing houses. Before World War II, most builders built about five houses per year. After the war, because of the mass production of houses by men like William Levitt, whose teams of men could build 36 houses in one day, 180 per week and 8,000 per year, the pace of building increased.

When Bugbee was built in 1950, it was the only elementary school north of Fern Street and west of Trout Brook. Its district included one-third of the geographical area of the town and was served by six busses. Before 1950, “north end” kids attended Sedgwick or the small Beach Park School. The north end experienced rapid development. Look at the growth in Bugbee’s population over its first 3 years:

| September 1950 - June 1951 | from 365 to 418 students    |
|----------------------------|-----------------------------|
| September 1951 - June 1952 | from 529 to 584 students    |
| Summer 1952                | 150 students moved to Duffy |
| September 1952 - June 1953 | from 460 to 546 students    |

By 1957, the student population settled in around 500 with the opening of Duffy, King Philip, Braeburn, and Norfeldt. In the early 1960s, school officials were nervous about the potential development of the Hunter farm on Flagg Road. They saw this property as having “potential development of embarrassing proportions” if a developer purchased that land. Instead, the town acquired the property which became Westmoor Park.

When Conard High School opened in 1957, the high school population was divided for the first time. Hall High, in the center of town became a “walking school.” All those within a two-mile radius of the school attended. Those who lived in the north and south ends of town went to Conard. These districts did not change until the new Hall opened on North Main Street in 1970.

John Davison, a student at Sedgwick in the 1950s, and a former chair of the Board of Education, remembered his friends being redistricted yearly as Sedgwick became overcrowded and new elementary schools opened. Families moved to West Hartford for a school system that developed a national reputation for excellence. People came from around the nation and the world to view West Hartford’s new schools for both their architecture and their curricula.

In the early 1970s, West Hartford’s population peaked at 70,000 and in the next decade, the town lost 10,000 residents. In the 1970s and 1980s, the town closed several schools. Beach Park School was closed in 1972 (and now is St. Joseph School for Young Children), the Elmwood School was closed in 1975 (and now is the community center), Bridlepath (now Solomon Schecter), and Whitman (now the police station) all closed because of declining enrollment. Smith School closed and then reopened in 1995. Both Talcott and Plant Junior Highs (7th to 9th grade schools) closed in 1979. The two high schools took on the 9th graders and Sedgwick and King Philip became 6th through 8th grade middle schools. The closing of these schools was very controversial. Parents, concerned about which parts of town took the biggest hits, questioned whether schools were closed in the geographical areas with fewest students.

Redistricting in the 1920s and the 1950s did not carry the same political volatility as that of closing schools in the 1970s and 1980s nor of the redistricting in the mid-1990s. Growth in the 1920s and 1950s came with a robust economy and grand expectations. People wanted the best schools for their children, and during these times, the best schools were new ones. Growth fueled the idea that life continued to get better in the suburbs in the 1950s.

Today, parents and politicians look on redistricting with fear and trepidation. They worry that their children will be shuffled from one school to another, a move forced by a redistribution of the population, not necessarily growth. With the state law that mandates that a school’s population cannot exceed 25% above or below the average racial percentage for the town, some parents argue their children are being redistricted for political reasons. But the state and many parents agree that guaranteeing equal educational opportunity for all can only be had if the schools are not racially isolated. This, the state argues, is part of the foundation of democracy.
