## Regional Plan {-}

*Originally appeared in West Hartford Life, February 2011*

In 1954, insurance giant Connecticut General decided to move its headquarters out of downtown Hartford to suburban Bloomfield. This move mirrored the movement of families to the suburbs. Hartford’s population peaked in 1950 at 177,000 and in the next decade lost 15,000 residents. At the same time, West Hartford’s population grew by 18,000 residents. At its peak, Hartford’s population was quadruple West Hartford’s; now it is about double the number.

Amidst this change, business leaders spoke loudly and clearly about a need for regionalism. In January 1957, the Hartford Area Chamber of Commerce urged towns in the capitol region to become part of a regional planning group. The General Assembly passed a law in 1949, amended in 1955, which enabled towns to be part of such a group. In the late 1950s, both cities and suburbs were willing to talk.

Local governments voted regional planning their number one priority in a questionnaire sent out by the Chamber in 1956. In January 1957, Harold Keith, mayor of West Hartford came out firmly in favor of a regional planning authority. He asserted, “Planning cannot end at the boundaries of political subdivisions.”

In late January, Hartford Councilman James H. Kinsella and Hartford State Senator Harold S. Borden requested that the General Assembly’s Legislative Council study a plan to create a federated form of government in the Greater Hartford area to include the towns of Wethersfield, Newington, West Hartford, Bloomfield and Hartford. The two men recommended that this federated government elect a proportionate common council, a metropolitan board of education, a common tax base and assessment structure, consolidated system of budgeting, financing and purchasing, centralized engineering and public works department, a unified traffic authority, centralized public health and welfare department, consolidated park and recreation department, and a regional planning and zoning agency.

The bill did not pass, but it did not stop the *Hartford Courant* from running a three-part series entitled “The Challenge: a Study of the Future of Hartford and its Surrounding Communities,” investigating the idea of regionalism. In April 1957, their article looked at the pros and cons of a federated government in Toronto. Senator Burton believed that as suburbs grew, the city could help them, particularly in the realm of schools. He did not ingratiate himself to the suburbs when he said that their fire and police departments “weren’t worth a nickel.” Personalities aside, talk of regionalism abounded.

Almost 300 town officials attended a June 11, 1957 Regional Planning Conference sponsored by Governor Abraham Ribicoff and the Hartford Chamber of Commerce Regional Planning Committee and the Chamber’s organizations in surrounding towns. Participants from 18 towns listened to experts from around the country outline the advantages of regional planning groups.

At the conference, Democrat Ward Duffy, editor of the *Hartford Times* and West Hartford resident, led a panel discussion with Richard Brown, West Hartford’s Town Planner. Brown argued that small towns would not get swallowed up by the big city in regional planning, but instead “could swing Hartford by the tail.”

![Ward Duffy, editor of the *Hartford Times*, helped to lead discussions about regionalization in the Hartford area. He and his wife Louise Duffy lived in the Whitman House on 208 North Main Street, in the home where he grew up. His father, Frederick Duffy, was a school teacher, and the head of housing in West Hartford during World War II. Source: Noah Webster House & West Hartford Historical Society.](images/09-ward-duffy.jpg)

By November 1957, West Hartford’s Mayor Keith seemed fed up with the state dragging its feet in establishing a Regional Planning Commission, dictated by state statute. The Democratic-led Town Council, the first ever, with the first ever Democratic Mayor from 1955 to 1959, pushed for regional planning for the town. Keith criticized the State Development Commission for not setting up the region for the Hartford area. Keith was particularly concerned about the planning of the East-West highway, Interstate 84 whose route through West Hartford had gone through numerous iterations at this point. On September 10, 1958, the West Hartford Town Council voted unanimously to be part of the Capital Planning Region.

At the same time, the Chambers of Commerce continued their trumpet call for regionalism. In February 1958, James E. Kelley, president of the West Hartford Chamber established a committee representing 11 Chambers in the region. However, he noted, West Hartford was the only town that had endorsed participation in the Regional Planning Commission by that point.

By July 1958, the 22 towns went into the process of voting to be part of the Capital Area Regional Planning Authority. Sixty percent of the towns had to approve the Authority before it started operating. All towns had two votes except those over 50,000. This give Hartford six votes, and three votes each for West Hartford, East Hartford, and Manchester.

The purpose of the authority was to “further the orderly zoning of towns.” It would have a hand in industrial expansion, highway relocation, main park and recreational areas, water supplies, flood control and stream pollution. The planning group was established as an advisory group.

The towns in the Capitol region included Hartford, East Hartford, West Hartford, Windsor, East Windsor, South Windsor, Windsor Locks, Manchester, Glastonbury, Wethersfield, Rocky Hill, Newington, Bloomfield, Farmington, Avon, Simsbury, East Granby, Ellington, Vernon, Tolland and Bolton. By July 1958, Granby voted not to become part of the group. The decision to participate had to be made at Town Meeting.

In November, the West Hartford League of Women Voters took on the issue of regional planning and held three discussion groups at member’s homes throughout town. Two meetings were held during the day and one at night. One of the discussion leaders was Mrs. Richard Brown, the wife of West Hartford’s Town Planner. Another was Joan Kemler who went on to represent West Hartford in the General Assembly. The League wanted dialogue about regionalism and the talk only served to increase support among progressives in town.

Mayor Harold Keith also worked to sell the idea and held meetings during the year with community organizations like the Rotary and Civitans to get them to support the Authority.

When Keith chose not to run for re-election in 1959, he became chair of the CRPA. The Authority received $25,000 in federal funds and so built a two year plan to prepare base maps for the area concerning topography, soil, zoning, development, traffic, transit, public utilities and recreation.

This topic or regionalism came to my attention as I framed a 1959 West Hartford map drawn by the Capitol Region Planning Council. This map included the proposed east-west highway, with an off-ramp at Park Road that went north to empty out at Farmington Avenue. It included the proposed Route 291, which went north from the east west highway right through the MDC Reservoir. This part of the “regional plan” led to protest and its demise in the mid-1970s.

While the push for regionalism in the 1950s came in a time of prosperity when there was a large migration from city to suburb. Today talk of regionalism is a cry from those trying to trim municipal budgets in times of recession. Out of prosperity or recession, the idea of regionalism continues to have its followers.
