## The Korean War {-}

*Originally appeared in West Hartford Life, June 2005*

The Korean War armistice was signed on July 27, 1953 and when the news made it to Hugh Campbell, the manager of the Central Theater in West Hartford Center, he interrupted the film that was playing and joyfully announced the truce.

The next day he and his wife got a telegram from the Defense Department. Their son Raymond B. Campbell, aged 23, was killed in action on July 24, 1953, just three days before the armistice.

Campbell was a heavy machine gunner in the Marine Corps and enlisted in March 1951, nine months after the war began. He worked at Pratt and Whitney Aircraft after attending Hall High School. Campbell left his mother and father, and seven siblings. His brother, John was in the Army in Korea.

Like other wars, West Hartford felt the effects of the Korean War through the eleven men who died over a span of five years. The average age of those who died in the war was 24, with the youngest 20 and the oldest 30. Four of the eleven men were married and three had children. Seven of the eleven men died in hostile action. The U.S. suffered about 33,000 combat deaths and 20,000 from other causes. West Hartford men died in about this same ratio.

During the Korean War, 1.5 million men, 18 to 25, were drafted; another 1.3 million volunteered, primarily for the Navy and Air Force. The Korean War grew directly out of the division of Korea in August of 1945 into Soviet Union and the United States occupation zones. Both the Soviets and the Americans believed that Korea should be independent at war’s end, but needed to be occupied because it was not yet ready for self-government. When the Soviets entered the war against Japan on August 8, 1945, two days after the U.S. dropped the atomic bomb on Hiroshima, some Soviet troops entered Korea and a week later, Truman and Stalin agreed that the Soviets would occupy the area north of the 38th parallel and the U.S. would occupy the area south of that line.

In 1947, a United Nations resolution called for elections in Korea to create an independent government. The Soviets would not allow for an election to take place in the north and they installed communist Premier Kim Il Sung as leader, while Syngman Rhee was elected President of the south.

On June 25, 1950, North Korean troops, many fresh from the communist victory in China, attacked South Korea. United Nations forces, of which the United States made the majority, fought back. By the end of September, UN forces approached the 38th parallel. In October, UN forces crossed into North Korea.

The Chinese said they would enter the war if the UN forces moved into North Korea. China entered the war in late October 1950. When MacArthur ordered an “end-the-war offensive” in November, it was met by a Chinese offensive which renewed the war. These offensives forced the UN ground forces south for two months. It was this battle that led to the first three West Hartford casualties.

Kenneth Tackus, 111 Ridgewood Road, was killed in action at age 23 when he was fighting near the Chosin Reservoir in North Korea, December 1, 1950. He was in one of the infantry divisions which reached the Manchurian border in the northeastern part of Korea just before the Chinese attacked. Tackus went to Hall High and Fishburne Military Academy where he was valedictorian of his class. He graduated from West Point in June 1950 and was married the following day. He left behind his wife and his parents in West Hartford.

Bernard Kelly, of 75 South Street, was reported missing in action on December 2, 1950 in fighting around the Chosin Reservoir in Korea and the retreat to the Hungnam beachhead. He was in a heavy mortar battalion. His parents last heard from him on November 17, 1950, but were not told he was missing in action until February 1, 1951, two and a half months later.

Kelly enlisted in the Army when he turned 18. He went to West Hartford Schools and was employed at the Royal Typewriter when he enlisted. Three of his brothers served in World War II.

Gordon “Pete” Kuehner, Jr. of Farmington Avenue was the pilot of a B-26C based at Kunsan Air Force Base (K-8) en route to a target on a night intruder mission when his aircraft was lost on December 28, 1950. He was 28 when he died. This was the third time his mother received such a telegram. During World War II, her first telegram informed her that her youngest son Dick was killed in a fighter plane over France. A second telegram told that Pete was missing in the Aleutian Islands. This telegram was nullified when he was picked up by the Russians. His mother had hope, in February 1951 that her new telegram would be nullified as well.

Kuehner was married and had a three year old son who was named after his brother Dick, killed in WWII. His son Dick wouldn’t learn for sure that his father was dead for another three years. His wife and son were with him when he was stationed in the Philippines before the war in Korea broke out and Kuehner volunteered to go fight.

Kuehner’s last letter, delivered with the telegram, said “How long can a guy’s luck hold out? Well, I’m sure I want to fight this war here, not in the United States, not where those I love might be hurt.” Kuehner’s letter outlined the beliefs of the time of those fighting the Cold War.

In early 1951, MacArthur pushed to attack China. In April, Truman fired him. Washington’s objective was to restore the status quo.

Donald Sirman, aged 29 of Van Buren Avenue, died on June 14, 1951. He was the pilot of an F-80C Shooting Star fighter interceptor while on a combat mission and was shot down by North Korean anti-aircraft fire on July 7, 1950. He survived the crash and was taken a Prisoner of War. His parents knew he was alive because his name and picture were used in North Korean propaganda broadcasts. He died while a prisoner less than a year later.

Truce talks began in July 1951. Diplomats decided to split the country at the battle line, but could not resolve the issues over prisoners of war like Donald Sirman.

In 1952, the war continued mostly as air strikes on North Korea. At least 2 million Korean civilians and one million soldiers were killed. As many as one million Chinese may have been killed.

Frank E. Woodcock, aged 24 of 1199 New Britain Avenue was killed in action on August 17, 1952. He was a veteran of World War II and a member of the active reserve. He held a degree from the University of Vermont. He was employed by Niles Bement Pond before being recalled to the service. He left his wife and a 9 month old son in Elmwood, and his parents and four siblings in Vermont.

Robert Wegner of 127 South Quaker Lane, aged 22 died two weeks after he was wounded from a mine explosion on October 29, 1952. After the injury, he had his left leg amputated and was in danger of losing his right leg. He died about a week after the amputation. He was a football star at Hall High and attended the University of Connecticut for two years. He enlisted on his birthday in 1951 when he turned 21.

Like the other wars, West Hartford’s war dead mirror the action in the war. By knowing the men from the town who died, it makes us remember the cruel and ugly realities of war. Knowing the houses that men lived in, where their children grew up without them, and the fiancés who lost their lovers makes us think of this ultimate sacrifice. Some argue that brutal wars like in Korea keep there from being war again. Larry Phillipon’s ultimate sacrifice in Iraq at the beginning of May 2006 reminds us that the young, brave and strong continue to die for their country and that the effect of the pain at home seems never to diminish.
