## Conard High School Celebrates 50 Years {-}

*Originally appeared in West Hartford Life, November 2006*

This school year, Conard celebrates its 50th year. 15,000 students have graduated from the school and many choose to live in West Hartford and raise their children here. What was the school like 50 years ago?

With the tremendous growth in the town population after World War II, there was talk in the late 1940s of the need for a new high school in town. Hall High School opened in 1924 and was built for 700 students. In the next 25 years, the town grew from about 10,000 to 44,000 people. The last new school built was Sedgwick which opened in 1931. By the late 1940s Hall had over 1000 students in three grades. After much discussion about adding on to Hall in the center of town, the appointed Board of Education decided in early 1954 to build a new high school on a site in the south end of town.

Chairman of the Board of Education, Frederick U. Conard led the Board to this decision over his seven year tenure as Chair. The year he started as Chair, 1947, was the same time he became president of Niles Bement Pond Company, a part of Pratt Whitney (on the present day site of Home Depot). From 1919 to 1947, he was president of the Underwood Typewriter Company. He died at age 63, six weeks after the vote and the Board decided to name the new school after him.

As early as December 1956, the newspaper reported that Hall would go on double sessions for the first three months of school in 1957 because it was not clear that the building would be done in time. However, by March, Republican candidates for the Board of Education pushed the School Building Committee to have the building open for September 1. Builders could have the classroom building ready, but the gym and auditorium would not come on line until about three months later.

In February 1957, the Superintendent named Hall Principal, Henry Weyland to be Principal at the new high school. Town officials worried about how the new school would be perceived, and sending Weyland to Conard made sense. He served as principal until 1974. Henry Rives, vice-principal at Hall was promoted to be Hall’s principal.

Superintendent Edmund Thorne announced the school boundary lines at the same time. Those who attended King Philip and Talcott Junior High would attend Conard. All Plant Junior High students went to Hall, in the center of town and the students at Sedgwick were split. Hall became a walking school, with about 60 percent of the number of students at Conard. Its population differed from today in that it was a north and south end school until the new Hall building opened in 1970.

When school opened on September 4, 1957, the school day began at 8:30 at the high and junior high schools. Students had a seven period day. About 1,150 students entered Conard on the first day. Over 11,000 attended the West Hartford Public Schools, in 15 different schools, more students than in 2006.

Dress in the first years of the school was strictly defined. There were no dungarees, no t-shirts, and no sneakers or cowboy boots. Girls had to wear skirts. Leather jackets were banned because of their connection to motorcycle gangs.

The course selection book offered different choices in 1957. Choices for the three years were limited by requirements and fewer elective classes. One requirement since 1952, was Driver Education The town had one full time teacher in each high school to teach this class. This practice lasted into the late 1970s.

Academic departments have remained the same, though the content in each has changed. As early as 1963, the NEASC report on Conard encouraged history teachers to teach less about military battles. The first Advanced Placement classes made their way into the curriculum in the mid-1960s.

Home economics classes were strictly for girls. One course, taught girls the “basics of being a housewife.” Industrial Arts courses, including auto mechanics, drafting, and woodworking were designed strictly for boys. Changes in these programs came in the mid 1970s with federal pressure from Title IX.

The tradition of a school musical began in that school year. Music teacher William Lauer directed the first musical “Oklahoma.” Lauer began the tradition of having two casts, one for each night to give more students a chance to have lead roles. This tradition ended in the early 2000s.

When the school opened in 1957, boys could choose from eight sports teams. There were no interscholastic sports for girls. Girls joined the leaders club and played “competitively” on one day in the Fall. In 1970 girls competed in interscholastic Track and Field and not until 1986 did they reach parity with the boys with the number of sports teams.

On November 9, 1957, Conard played Hall in football for the first time and the contest was at Conard’s just completed stadium. Both teams came in with winning records, and each had a chance to win the CCIL championship. With Coach Bob McKee at the helm, his Chieftains defeated the Frank Robinson’s Hall Warriors 7-6. Today, in 2006, the grandson of Conard’s captain in that first game plays on the Conard team.

The Chieftains were boosted by the first appearance of the Pep Band, led by William Lauer, and the Pep Club with over 300 students dressed in scarlet and gray. More than 2,500 fans overflowed the stands to watch the first of many contests between these two rivals, many of which determined championships. On November 18, 2006, Conard and Hall will play their 50th football game. It looks like, just as in 1957, that a title might be at stake. The rivalry is just as fresh today as it was 50 years ago, but now it includes 26 teams with both girls and boys.

In June 2007, Conard will have its 50th graduation. There are some stirrings of a commemoration for these events. Those who graduated in the first class in 1958 are now in their mid-60s and do indeed have grandchildren old enough to be students at the high school. The traditions of learning and of school spirit are still alive and well.
