## A Layman Looks at Schools in West Hartford {-}

*Originally appeared in West Hartford Life, September 2003*

> Now, in a maturing society and a seething world we have come to recognize the imperative need for a wealth of wisdom added to a wealth of raw materials. We are looking to the schools, long accepted and long neglected, to supply citizens possessing greater foresight and leadership. -- Bice Clemow, publisher *West Hartford News*, 1951

In 1950, *Life Magazine* published a 63 question test that rated public schools. School superintendents throughout the U.S. helped develop the survey.

Bice Clemow, publisher of the *West Hartford News*, a parent and taxpayer in West Hartford, used the survey to rate each of West Hartford’s 13 public schools and all of the schools scored in the “average” range. Clemow found this distressing, as he considered West Hartford to be “an above average town.” He decided to study why the schools scored as average. Clemow saw improving schools as an answer to the “seething world” he refers to in his 1951 quote.

In 1951, Truman was president, the Soviets had detonated an atomic bomb, Mao had won the civil war in China, the Korean War broke out and the Cold War was waging. Senator Joseph McCarthy alleged that there were communists in the State Department. Amidst these internal and external attacks on democracy, many Americans felt that the public school system was the place to build democracy and be sure that citizens knew what freedom was. The better the school system, it was thought, the better the citizen.

West Hartford’s population grew from 24,941 to 33,776 between 1930 and 1940 and then to 44,402 by 1950. That represents a 76% increase in population in that 20 year span. Yet between 1931 and 1949 there were no new schools built. West Hartford Schools were at a space crisis in the 1940s and early 50s, and despite this, young families with children continued to move to the town.

The pressure mounted on the Board of Education to build schools. In 1943, 5,265 students attended the public schools. By 1953, 8,507 attended public school, a 62% increase in 10 years. By 1958 the school population had doubled to 11,563. School children made up 15% of the population in 1943 and 19% of the population in 1958. Families with children chose to move to West Hartford.

By 1951, Clemow believed that the townspeople needed to look a bit more closely at the public schools. He applied the categories of the *Life* survey by surveying the town’s school buildings, teachers, curriculum, and public opinion. His report, published in four installments from January 25 to February 15, seemed designed to drum up public interest in improving the schools.

Clemow found that the facilities were kept clean, but, he found them lacking in public hygiene. The East and Whitman schools did not have provisions for students to wash their hands in the bathrooms and in many schools there was not reliable hot water or soap. He was very concerned with physical education -- wanting there to be a gym and proper locker room facilities in each school. These did not exist except to a primitive extent in the high school. Each school had an auditorium, but some were too small to seat the whole school. The two new schools, Webster Hill and Bugbee, had auditoriums big enough to use as community facilities. He also found laboratory space to be “pitiful. In a scientific age, we are not measuring up at least in facilities... I am just saying that we haven’t a school plant -- speaking of all 13 buildings -- to match the homes along (to pick a street) Walbridge Road.”

When assessing the role of teachers in the school system, Clemow believed that higher salaries would bring better teachers. In 1950, there were 250 teachers in the system. Teachers in 1950 started at $50 a week, or $2,000 per year. Top salary was $84 per week or $4,800 after 17 years of teaching and 6 years of college training. With the cost of living rising, Clemow argued, the town needed to match teacher salaries with equivalents to the business world. This would keep morale high among teachers. Top salary at that point for a teacher was, “something less than a bus driver makes.” West Hartford made *Life’s* minimum starting wage. Until the 1950s, the town believed that the secure nature of a teaching job was enough to keep teachers in town, but Clemow believed that promising security was not enough.

The survey also pointed out shortcomings in teacher training. Clemow was concerned that it was difficult to graduate from a liberal arts college and go into teaching. The teachers colleges seemed to have a lock on teacher training in the 1940s and 1950s. Clemow supported a liberal arts education and continuing education in subject matter for teachers. Clemow also criticized the lack of a teacher evaluation system.

As far as the curriculum was concerned, Clemow was upset by its traditional nature. He wrote, “...the classroom courses are as firmly rooted as Gibraltar.” He found that there had been less than a 10% change in the number of courses provided for students since 1940. He believed this was because of the tie between the high school curriculum and college admissions. Little was done to encourage the study of local government through real life experiences.

And at the high school and junior high levels, Clemow believed there was too little interdisciplinary work. He believed the system did not do enough to recognize students as individuals. There was a 28 to 1 pupil to teacher ratio. The school system had developed a guidance program which did address the individual. Not enough was being done in physical education, but the health program was pretty good.

The survey asked about extracurricular activities and Clemow found every school to be wanting except in the area of the music program which had shown “magnificent growth.” There was not an institutionalized program for parent teacher conferences but the *Life* survey suggested one.

Clemow’s key for improving the schools lay with public advocacy. He did not see this happening in the town. In 1951, the Town Council appointed the Board of Education and few people even knew its five members. Very few citizens attended Board of Education meetings held every other Thursday evening.

Clemow argued that the Board of Education reflected the individual views of its members, guided by the Superintendent, not by the citizenry. The Board was remote from the people. Clemow called for a democratically elected Board. He believed it was important that board members had children in the public schools. He said “I think it might be a shock to West Hartford parents if, going back over the last generation, they knew how some Board of Education members came to serve and how many of them with children in private institutions were blind to the second class quality of education in the public schools.”

Clemow’s exposé spurred change. The town established a Citizens Committee to address these problems. It was difficult to get people to volunteer to sit on the committee. But in 1954 they published their report based around most of the issues that the *Life* survey raised.

Clemow’s four articles written in 1951 seem to have been a wake up call to the town. In 5 years, the Board was democratically elected. By 1958, the Board and administration revised the curriculum to add honors classes in all areas in the high school and pushed more homogeneous groupings. The town built seven elementary schools between 1952 and 1959. The problems with teacher salaries continued to be a bone of contention and did not get addressed until teachers unionized in the mid-1960s.

The tension between the four pillars of the school system, buildings, teachers, curriculum, and community involvement, still help determine the draw of West Hartford’s educational system within the Hartford region and throughout the country. West Hartford’s 1950s goal to be one of the top ten schools systems in the state led to more citizen involvement as together they strived to make the school system “above average” in an “above average” town.
