## Teachers and their Role in the Town {-}

*Originally appeared in West Hartford Life, January 2003*

This town has been known for its outstanding schools since the late 1920s, with the building of the Beach Park School on Steele Road. As a teacher for 25 years in the town, I've always been interested in where that reputation came from.

Quality education emanates from a combination of the actual buildings and environment within them, the teachers and their ideas, the administration and elected leadership on the Board of Education, and a supportive community that advocates for good schools. At times, these factors have worked in concert and at other times have been contentious.

The late 1950s and early 1960s there were many disagreements because of an explosion in the size of the school system, a community wary about the costs, and a distrustful relationship between teachers, the administration and the Board of Education.

Between 1940 and 1950, West Hartford's population grew from 44,402 to 62,382, for a growth of 40%. The school system doubled in size as the town built and opened nine elementary schools, one junior high and one high school. Boosted by a booming economy, easy mortgages and federal housing loans, the town flourished by so many measures.

In the consensus theory of history, so prevalent in the 1950s and 1960s, observers saw little conflict in the 1950s. Everyone enjoyed the economic boom, historians argued, and life was good for the thriving middle-class. This community reaped the benefits of this boom, but as in any change, benefits were not always distributed equally. Neither was conflict absent. Tensions between teachers, Board of Education members, the superintendent and taxpayers were palpable.

In 1959, the Board of Education, just recently an elected body, commissioned a report on community-teacher relations. The Board appointed a committee of 15 people, 10 men and five women, to study the level of teachers’ salaries, teacher evaluation and methods of rewarding superior teachers. This committee's job was to improve relations between the teachers and the townspeople.

Between 1956 and 1959, the taxpayers were not so willing to support the school expansion with tax increases. Two referenda to increase the school budget came before the town voters and the voters defeated both. This led to dissatisfaction among the teachers and a decline in morale that, many argued, made it difficult for them to do their work.

The Board of Education administered a survey among its teachers. The study was spawned by a 20% turnover rate among the 520 teachers in town at the end of the 1958-1959 school year.

According to the survey given, only 29% of the teachers believed residents had respect for teachers and only 19% felt citizens appreciated what teachers did. Only 11% felt local citizens were sympathetic to teachers’ problems. More than half the teachers, 52%, believed they were receiving a poor salary, while 100% of the teachers said their job as a teacher was interesting.

The Board of Education, the superintendent and the teachers showed concern about why they left: the general feeling among teachers was that they were leaving because salaries were so low. In 1959, 60% of the teachers had fewer than three years of experience in the five years previous, there was also a turnover of about 20% each year.

Statements made in the report like "the board in its communications with teachers ought to give due consideration to the fact that it is dealing with a group of professionally trained personnel" smacked of a contentious relationship.

In 1959, a new teacher earned $4,150. The highest paid teacher, after 14 years of service, earned $6,800. Teachers earned about $200 a year more for each year they served. In 2002, teachers of the top of the salary schedule, after 16 years of service, make twice the starting salary of about $36,000.

In the 1950s, there was a strong anti-union fervor in the country. The wild days of the 1930s, encouraged by the Wagner Act which made employers bargain with unions and the great gains labor made in the 1940s, were curtailed by the Taft-Hartley Act in 1947.

This act established an 80-day cooling off period before a union could go on strike, forbade federal workers from striking, made union members take oaths that they were not members of the Communist Party, and allowed businesses to sue unions that went on strike for breach of contract. Many residents seemed to share these anti-union feelings. During the Kennedy Administration, by Executive Order, JFK allowed for public employees to join unions. This led to teachers thinking more about their rights.

As a requirement to receive her paycheck, a recently retired West Hartford teacher remembers being asked to sign a pledge in the early 1960s that she would not go on strike. The West Hartford Education Association represented the teachers at the time, but it was not an official bargaining unit. In fact, the report stated, "the use of tactics resembling those of a teachers’ union as a bargainer for teachers is not likely to obtain understanding or sympathy in the eyes of the community."

It was not until 1965 that Connecticut's General Assembly passed a fair dismissal law that legislated due-process rights for public school teachers. This included passage of Connecticut's collective bargaining law that mandated negotiation of teacher contracts. But for local teachers, this was still six years away.

Those on the Citizens Committee on Community-Teacher Relations seemed to support President Eisenhower's belief that the United States, and West Hartford, should be a cooperative society in which major groups such as business, teachers and taxpayers could put aside their special interests to promote domestic harmony and economic stability.

The committee believed it could act as an arbiter to bring together the excessive special interests and restrain demands of the teachers while continuing to provide an excellent education for its children.

The committee was upset with how the WHEA had represented teachers in the 1958-59 school year. The WHEA wanted to foster good community relations, improve teachers’ status and improve teachers’ sense of professionalism, but the committee argued "that these aims have suffered seriously during the last 12 months as a result of tactics employed by the Association… It would seem that the WHEA should refrain from careless use of statistics, from the use of oral and written emotional statements and from attempting to bring excessive pressure to bear in the interest of a parent unanimity (among teachers)."

This barrage of statistics and invectives seem to be the only way teachers could get the board’s and the public's attention before there was collective bargaining.

One source of dissatisfaction among teachers was the use of a merit system of pay. Only 12% of teachers found satisfactory the present method of selecting teachers to receive the double increment merit awards. It was not clear to teachers what criteria were used to select teachers and if it was defined, teachers seemed not to know what it was. Teachers made known that favoritism by principals and a supposed cap on the number of teachers selected (which seemed to be one per school) led to much dissension among the teachers. The report notes that a committee of the administration and the WHEA were working on this.

It is easy for us teachers and taxpayers today to think this contention is all in the past. In 2002, when many residents see their property values tied closely to the high-quality educational system in town, many of these concerns seem so old.

But, look back just to 1994-95 when the schools were last redistricting to see a downturn in public satisfaction with the schools. The present upsurge in support for the school system and the influx of people with children to town show our educational system to be an attractive lure to West Hartford.

But the political tide can change and with the new federal education bill promising to name some of this town’s schools as failing, how will the teachers, the administrators and the taxpayers react?
