## What Was This Town Like Back in 1954? {-}

*Originally appeared in West Hartford Life, October 2002*

I spend time thinking about what makes this town unique. I ask the juniors and seniors in my local history class at Conard High School on their first day of class what a newcomer to the town should know about West Hartford and, at the beginning of the course, they usually come up with Noah Webster and the school system.

By the time the course is over, they learn about the panoply of architecture, the agricultural, industrial and suburban character of our town as its nature ebbed and flowed over time, about tensions in town over racial integration, school redistricting and highway building.

They see a town where democracy works and how the town manager system has effectively matured from 1919 when it was the first such system in Connecticut. They see a town that is proud of itself and reflective on its heritage.

Which parts of this heritage will we choose to highlight in our sesquicentennial celebration in 2004? Looking at what was said at the centennial in 1954 could be a guide.

So what was the 1954 message proclaimed during a time of tremendous growth in the town and during the Cold War?

In 1954, tensions abounded in town. The first study of an east-west Highway (I-84) in 1948 was still being debated six years later as engineers in the town continued to fight about the best path through town. Hall High School was opened in 1926 when the population of the town ahd about 15,000 people.

Hall was so overcrowded by 1950, when the population reached 44,000, that discussions about a new high school raised tensions. When Frederick U. Conard, head of the Board of Education, died in 1954, the town had agreed to build a new high school, but it did not open for another three years after rancorous debate about the proper site, size and attendance zones.

Controversy raged about what to do with the World War II housing built on Oakwood Avenue where Kennedy Park is today. Even though the plan was to knock the temporary housing down after the war, the shortage of housing, especially for veterans and their families, caused many to believe it should stay.

Townspeople lined up for and against razing the old Town Hall, the old building of the First Church which was in a state of disrepair and which the late town historian Nelson Burr said in his 1954 centennial speech, "I hope will never be torn down."

What did Burr say about the town in his commemorative address in 1954? He did use dissent and independence as themes to tie his message together, but for the most part, his address was celebratory in praising the sense of community and the exceptional nature of the town. His address, given on June 6, 1954 at the First Church of Christ, Congregational, was printed and published as “Three Centuries of a Yankee Town."

He started by extolling the dynamic energy of the town's founders. He felt that was reflected in 1954 in the youth in town. Two thirds of the town’s population was under 45 years of age and almost half were under 35. He saw this as a sign of "hopeful people" and of an "expectant spirit."

He continued that "independence was and is in West Hartford's blood."

The accepted belief that the residents’ desire for their own church in the West Division in 1710 was based on the distance from Hartford, but he believed it was based more on their "wish to handle their own business" than on geography. Residents could elect their own minister and teacher, who they looked up to as "a better educated neighbor, not in fear as to servile agents of the feudal lord."

Burr argued that dissent was essential to understanding the town. It started with establishing the church in 1713 and continued with dissenters from that church. In 1794, Quakers broke away to set up a Society of Friends. In 1843, Episcopalians established the church and in 1858, the Baptists built a church in the center.

He was impressed by the 153 seceders who signed the petition for independence in 1854 and the 95 who voted against secession. Among those who signed the petitions were Irish, German and Swedish immigrants who began to break the hold of the English majority. Here, Burr mused, was independence in the presence of dissent.

Burr argued that the town was founded on four principles that he called the "cornerstones of our civilization”:

- The right of individual property in land and homes which lead to a greater social equality than Europe and was the cornerstone of popular government.
- Religious liberty to administer our own church affairs.
- The sovereignty of a righteous God who made people morally responsible to God and their neighbor.
- The necessity of an educated citizenry to administer church and state and then the need for democratic schooling, generously supported.

He spent the rest of his address giving examples of how West Hartford lived out these tenets. Noah Webster, he argued, exemplified many of these ideas.

In the last part of his speech he characterized the town in the 20th century, first as three separate villages which didn't always agree on schools, churches and fire districts. He catalogued the change of the rural town as mansions began to be built on the Eastside after the Civil War and we began to "suburbanize.” Outside of the east side and the southeast industrial section, the town remained rural.

Burr argued that by 1920, these differences had been washed away with the wave of "suburbanization." Localism, he said, became meaningless as the school districts unified, one high school was built, fire districts merged, and the town manager system of government took hold.

He believed that religious and ethnic changes were "harmoniously accepted" and West Hartford became "an example of American suburbia at its best."

This consensus interpretation of West Hartford's past, so prevalent among historians in the 1950s, glossed over many of the tensions which also make this a unique town. Those tensions over schools, low-income housing, architectural heritage and traffic eliminate the heart and soul of the town searching to define itself.

What will the planners of the sesquicentennial think about over the next two years? Will they provide a forum for us to think about traffic problems, the racial imbalance in the town's elementary schools, or the issue of whether elected officials could more closely reflect the rich diversity of the town?

Will this be balanced with the celebration of the architectural richness of the town, of the amazing retail transformation of the town center over the past 50 years or of the continued excellence of its schools?
