## West Hartford in 1959 {-}

*Originally appeared in West Hartford Life, October 2009*

Fifty years ago, the *West Hartford News* published the Town Report written by Town Manager Donald Blatt who wanted to educate citizens on how the town government used their tax dollars. The Town’s population in 1959 was 60,000, just a few thousand less than the population in 2009. This report provides an interesting comparison of a town that was still growing in the 1950’s, with a mature West Hartford in 2009.

The Town Report celebrated “Highlights of the Year Gone By.” In 1958 the town celebrated Noah Webster’s bicentennial celebration. In 2008 we celebrated his 250th birthday. A new town charter went into effect that allowed for the election of the school board, at large election of nine Town Council members, and guaranteed minority party representation. These revisions remain today.

The town dedicated the Rutherford Building on Raymond Road and Memorial Drive, the remodeled north section of the Whitman School, as an Annex to the Town Hall. The building on that site today, built as part of the Blue Back Square development, is also called the Rutherford Building. The Town Hall with a gold dome on Main Street, built in 1936, now houses Flemings Steak House.

Bridlepath School in the western part of town was completed in 1959. When the population of West Hartford peaked in 1970 at 70,000 and then dropped back to 60,000, many schools in town were closed. Bridlepath closed as a public school in the 1970s.

In 1959, the town trumpeted its “continued program of sidewalk and sewer installation and street paving and reconstruction.” In 1959 though it was still legal to have a well and private septic system, the town was moving toward public water and sewers. The public works budget in the growing community made up almost 12% of the total budget. In 2009, with a developed infrastructure, public works make up only 1.6% of the budget.

While today, school officials worry about the H1/N1 virus, in 1959, “special clinics were held monthly during the year for West Hartford school children who were unable to receive polio injections from their private physicians. 1,087 were given during the year.” The Town Report charted the prevalence of chickenpox, measles, mumps and German measles from 1948 to 1958. A measles vaccine became available in 1963, mumps in 1967, German measles or rubella in 1969, and chicken pox in 1995. With the Health Department’s 1959 budget of $2,023, sanitation staff chronicled diseases and increased food and milk inspections.

As the 1959-60 school year got under way, the educational initiatives marked some changes in the town’s philosophy. One photograph is captioned “Schools respond to growing emphasis on Science,” responding to the national push that followed the Soviet launch of Sputnik in 1957. Funds from the National Defense Education Act (September 1958) encouraged the study of science, mathematics and foreign languages by funding professional development for teachers and building the infrastructure.

Superintendent Thorne managed a $5 million budget to educate 11,563 pupils at about $430 per pupil. Even in the 1950s, West Hartford prided itself on having an excellent school system and not spending the most per pupil. The school budget made up about 43% of the town budget. In 2009-10 Superintendent Sklarz’s education budget stood at about $123,000,000 with 10,000 school children for a cost of over $12,000 per student. This accounted for 61% of the budget. According to a purchasing power translator, this is about four times the per pupil cost of 50 years ago.

One major contributor to the increased costs of schools was the federal government’s mandate to educate all students that began with the Americans With Disabilities Act (1973) and then the Education for All Handicapped Children Act in 1975. These Acts have increased the cost of education considerably. In 2009, the Special Education budget made up close to 20 percent of the entire school budget.

In 1959, the system added honors courses in each subject area to strengthen the curriculum. Superintendent Thorne instituted an accelerated track in math allowing 8th graders to take high school level algebra. High School graduation requirements rose from 16 to 18 (in a three year high school) and the number of periods in the high school day increased from six to seven. Thorne encouraged a move to homogeneous groups in the elementary schools and formulated a program for “gifted” children.

For the 2009 to 2010 school year, the West Hartford Public School initiatives are based around the 2002 federal No Child Left Behind Act, which required testing of all students, with follow up for those who have not achieved. Students continue to have an accelerated track in Math, but now requirements for graduation include 21 ¾ credits (in a four year high school) and they attend an eight period day. State legislatures in 2009 showed some interest in raising the number of credits needed to graduate from a Connecticut high school, but the economic downturn ended this initiative.

Enrollment increased 119% from 1943 to 1959. The town built nine elementary schools over this time period, giving the town 21 school buildings. In 2009 there were 16 public schools and the student population had stabilized. Hall High School, built in 1924, had served as the only high school in town until Conard opened in 1957. Because of the age of Hall and its being landlocked in the center of town, in 1959, there was already talk of building another high school. However, according to the Town Report, “In light of the plans of the Archdiocese of Hartford to construct a high school in the near vicinity of the proposed North End High School, the target date for the latter has been postponed from 1961 to 1966-7.” Town officials felt that the opening of Northwest Catholic (1961) would take some enrollment pressure off the public schools. In 1959 there were 2 parochial schools in town and 11 private schools. The new Hall High School finally opened in 1970.

The picture on the cover of the 1959 report depicts an adult male showing an open book to an eager boy, about eight years old, who looks up at the adult. They stand in front of the Noah Webster Library. This image of the importance of books, of knowledge, of the passing of information from one generation to another remains at the core of the town government’s ideals fifty years later.
