## Economic Development, 1950s Style {-}

*Originally appeared in West Hartford Life, March 2003*

In early January 1962, the Town Planning and Zoning Commission unveiled a comprehensive Town Development Plan to guide land use in West Hartford into the 1980s. The main goal of this plan was to allow West Hartford to maintain its residential character, while allowing for industrial and commercial growth in specific areas of the city, and to move traffic.

What spawned this development plan? Why did the town feel compelled to draw up such a comprehensive plan at that particular time?

In the 1950s, West Hartford’s population grew from 44,402 to 62,382. And at the same time developers bought up farmland for housing developments and retail developers built strip malls in four different locations in town. Between 1949 and 1959, the town built 11 new schools. Town residents worried that building was out of control and that just anything could be put up if one had the money, or if the population kept growing

The 1962 plan projected a peak population of 85,000 and residents were concerned about what this meant for their quality of life in town. The Town Council spent meeting after meeting consumed by these development controversies as open space disappeared.

Commercial development caused tension between residents, the developers and the Town Council as the town weighed its tax base, its residential nature, and the desire of developers to make money and provide shopping facilities in town.

When Lord & Taylor moved to the southwest quadrant of Bishops Corner in 1955, most of West Hartford’s 62,000 residents shopped in downtown Hartford. This Lord & Taylor was the chain’s first ever suburban store outside of New York. A survey completed by developers in 1956 found that West Hartford residents spent only 35% of their consumer dollars in West Hartford.

![This was the fourth suburban Lord & Taylor, and the first outside of New York. Built in 1954, the store had a restaurant called the Bird Cage, like all the other stores. Note the farmland and the beginnings of suburbanization in the southwest quadrant of Bishop’s Corner. Note the Hartford Tennis Club and the land that became Westmoor Park at the top of the photo. Source: Noah Webster House & West Hartford Historical Society.](images/10-development.jpg)

In 1956, developer Five City Plaza, Inc. believed that there was a retail market in West Hartford and proposed a $7 million shopping center at Corbin’s Corner. The town held a series of five public hearings, which attracted over 1,000 people. The developers, represented by attorney Frederick U. Conard, Jr., tried to convince Democratic Mayor Harold Keith and the Town Council that this development would be good for the town. Issues covered at the hearing included traffic, the residential nature of the town, value of residential property nearby, and the ability of the nearby brook to absorb run-off from the massive parking area.

The plans called for 25 to 30 stores with Sears Roebuck as the anchor store. This Sears was planned to be the largest such store in New England. The Town Planning and Zoning Commission approved the plan for three separate buildings, cutting the size of the building farthest to the south, and not allowing Sears to have an automotive center.

The Town Council voted 5-2 to approve the development on February 13, 1957 and immediately they were criticized for their vote.

Of the two who voted the plan down, Republican Minority Leader Richard Smith argued that the elected officials were not doing enough to put the development in context. He argued that the development should not only be looked at from the standpoint of how it affected the geographical area, but also for its long term impact. He believed the plan needed to be part of a “comprehensive plan for the general area involved, which includes the large tract of land of the Minnie Corbin Kohn estate lying just to the west of the property here involved.” This area became Westfarms Mall 15 years later.

Residents of the southwest section of town appealed the Town Council’s approval to the Court of Common Pleas on the basis that the shopping center was too large for the area, would create traffic problems, and depreciate the value of their homes. The association also questioned whether this shopping center could be successful. Everett Clark, president of the Southwest Association claimed, “If it fails, the town will be left with a white elephant.”

The Common Court of Pleas rejected the appeal seven months later in September 1957. The judge believed he did not have jurisdiction and that this zoning question was a local matter. The property owners vowed to take the case to the state Supreme Court. The Supreme Court heard the case in June 1958, and in August the court voted unanimously to uphold the decision of West Hartford’s Town Council, then 16 months after council approval.

At the same time, the Town Council faced a proposal to build a shopping center on the southeast quadrant of Bishops Corner and the Council sent it back to the Zoning Commission for a definite recommendation.

In July 1958, the Common Pleas Court also ordered the Town Council to accept the petition for a $4 million shopping center on the northwest corner of South Main Street and New Britain Avenue. The Town Council did not approve this petition, filed in April 1956.

In February 1959, two years after the Town Council approved the plan, Corbin’s Corner residents voted to fight proposed changes in plans for the shopping center. They opposed a proposed fire and battery service building and plans to build a bowling alley in the basement of one of the buildings.

In the same month developers proposed another shopping center on the corner of Farmington Avenue and Boulevard with an A&P supermarket as the anchor store.

By June 10, 1959 the Town Council gave unanimous final approval to the Corbin’s Corner Plan requiring the developers to build a 6 ½ foot fence along the south side of the property, installing 28 foot high light poles, and prohibiting outside display of merchandise. Sears got approval for the automotive center, but the plan for a bowling alley was denied.

In July 1959, residents appealed the June action of the Town Council which changed the zone of some of the land included in Corbin’s Corners. They lost this appeal.

One of the last things the Democratically controlled Town Council did was to vote down the Farmington Avenue - Boulevard shopping center, claiming that it would decrease the value of homes in the area, despite the fact that the town planner had recommended its approval.

These contentious debates about town development allowed residents a say in the type of town they lived in, and many would argue, produced a better plan for development. In 2003, with a town with almost no open space, the town again is weighing its tax base, its residential nature, and the desires of developers to make money and provide shopping facilities in the center.

In February 2003, Scott Slifka proposed a new task force to be responsible for economic development in town. While West Hartford’s tax base has been somewhat stagnant for the past 20 years, there are some big new development possibilities both in Elmwood and in the center. The council believes that taking a proactive stance on development can ease some of the tensions of 45 years ago as developer’s desires to build and increase the tax base were balanced with retaining the special character of our town.
