## The Political and Economic Landscape in 1957 {-}

*Originally appeared in West Hartford Life, April 2007*

The political year 1957 began with a salvo from the Republican Town Chairman Samuel K. Lavery, accusing the Democrats on the Town Council of “violating the spirit of the town charter” and he threatened court action. Lavery claimed he needed to take court action “to teach the Democrat members of the Council the meaning of democracy and minority representation.”

The Democrats appointed Republicans to the Board of Assessors and the Board of Tax Review who had not been nominated by the Republican Party. While the Democrats followed the letter of the law by insuring minority representation, the Republican Party had no part in their appointments.

Republicans had controlled the town of West Hartford since its independence from Hartford in 1854. It was 101 years later in 1955 when Democrats first took control following a tax referendum. Harold Keith became the first Democratic Mayor. Keith named a new Town Manager, Donald Blatt in 1956, and Republicans, though having a 2 to 1 majority in voter registration, had to play the role of minority party for the first time ever.

When historians look at the past, they see it both in a mirror and through a window. Some events look very different. Others seem so similar to the present day that we see ourselves perfectly in the looking glass of the “old days.”

Fifty years ago, West Hartford was in one of its greatest spurts of growth economically, educationally, and in population. The town government reacted by electing its Board of Education for the first time and asking to raise the mill rate by 6 ½ mills after a 0 mill increase the year before. Two schools were opened as residential growth continued to skyrocket. It was bound to be a year full of controversy and contention in a mostly small “d” democratic town.

The grand list grew almost 7% from 1956 to 1957. The main factor in the grand list increase, according to the *Hartford Courant*, was the addition of 187 homes in Elmwood Acres housing project just south of Route 84 and east of Mayflower Street. These homes, built by the federal government during World War II as war worker housing, were sold to individual owners in 1956, adding over $1 million worth of property to the grand list. New homes, numbering 572, were also added to the list.

Economically, the town grew fast residentially, commercially and industrially over the course of 1956. Total undeveloped land in town dropped from about 4,756 acres to 4,351 acres, a drop of about 9%. Commercial and retail buildings numbered 414, an increase of 27 buildings or a 7% increase. There were 98 factories, 12 more than the previous year, and an increase of 14%. In 1957, the town counted 12 horses and mules. There were 83 head of cattle, the herd growing by 5 in the past year.

The town budget was $10 million (compared to about $200 million in 2007) and a population of around 60,000, equal to today’s. The education budget made up less than half of the total budget (compared to about 60% today). The education budget went up 20% in one year while the remainder of the budget increased by 36%.

The town continued to build its infrastructure including paving seven miles of roads, completing Trout Brook Drive from Fern to Asylum, constructing 19 miles of sidewalks, providing money to lower Trout Brook, building hardtop tennis courts at Fern Park, and improving the golf course at Buena Vista Park. There was one million dollars for the construction of Wolcott School; money for Cornerstone Pool that was set to be built on 3.6 acres owned by the town on Raymond Road, and where a new park will be built after Blue Back Square construction is completed.

The budget called for a 2% raise for employees to match inflation. It had money to employ 23 men to operate the new incinerator expected to go into operation in the summer on Brixton Road. There was also an increase in interest to pay on the bonds floated for the numerous school building projects over the previous eight years.

This budget called for a 6 ½ mill increase, 10% increase in taxes, the biggest single tax rate increase in West Hartford’s history. When a large increase was presented in 1955, citizens called for a referendum and defeated the budget. There was no increase in the mill rate in 1956.

Ozzie D’Arche, who instigated the successful 1955 referendum, lay in wait. Democrat Mayor Keith claimed that one of the main reasons for the increase was a past when the government spent only the absolute minimum without regard for future growth. His budget included a three-year plan for growth. He argued that if school building projects had been planned, the town could have avoided double sessions and decreased costs of site acquisitions. The previous year’s budget had not increased. Public feedback showed the public would not stand for more than a 4 ½ mill increase instead of the 6 ½ mill increase proposed. D’Arche led the charge to rein in on town spending and he and the memory of the 1955 referendum that led to a change in political leadership reined in the budget.

On January 22, 1,200 townspeople went to a hearing at King Philip School to weigh in on the budget. After lobbying and meetings and a reappraisal of the budget, the Council settled on a 2 ¾ mill increase for the year, down from the original 6 ½ mills.

The municipal election, then held on Tuesday April 2, was a show of confidence for the Democrats, returning a 4-3 majority on the council. All four Democrats were re-elected, including Mayor Harold Keith. In 1957, townspeople voted in seven districts for their Town Councilor. In the Third District, anti-tax man Ozzie D’Arche ran as an independent in a three-way race, with the Republican winning the open seat with twice as many votes as either the Democratic opponent or D’Arche. Republicans won the Board of Education with a 5 to 2 split. With a Republican registration double that of Democrats, the results were something of a surprise.

Active West Hartford citizens were ever present to check the power of the local government, just as they have been over the last 50 years. They made sure that townspeople knew how much the economic base of the town grew in the previous year and tried to keep a cap on spending. The elected Democratic officials and the Town Manager believed that townspeople had to be willing to pay for the services provided. That is, if they expected excellent schools and recreation, it would cost more to live here than it did in other towns.

This voice of the citizens is what keeps elected government mindful of “democracy and minority representation.” A strong minority party, a growing economy, and an active, educated citizenry remain the keys to a healthy town.
