## Town Center: The 1960s and Today {-}

*Originally appeared in West Hartford Life, October 2004*

> The homeowners of WH cannot permanently go on watching the residential character of our neighborhood and our town undermined and destroyed without doing something constructive about it.

> In the last decade zoning decisions have had the wholly regressive tendency of commercializing our town. The have outraged the common sense of the people who must bear the burden of decisions which devalue their homes, rob them of prized social and psychological values, and then burden them with assessments for road improvements, increased traffic and taxes for additional town services.

> -- West Hartford Federation of Homeowner Associations Resolution, 1961

West Hartford residents have always cared about the character of their town. Whenever changes are proposed, residents and homeowners wonder if West Hartford will continue to be the town in which they chose to live. The Federation of Homeowners in 1961 reacted to the tremendous growth in retail in the town with the opening of Lord & Taylor in Bishops Corner in the mid-1950s, and the plans for Corbins Corner in the early 1960s.

The Town Council, Town Manager and Town Planner were all concerned about what these developments would do to the town center and they spent much time, money and political capital on trying to insure its continued success.

At first glance, the Homeowner Association quote might have come from the Save Our Center group concerned about the present-day construction of Blue Back Square.

How have their concerns changed as the town developed from a growing suburb in the 1950s and 1960s to a mature suburb with little population growth in the 21st century, and how have they stayed the same?

In 1951, when the Town Council commissioned a comprehensive town plan from the private firm of Alfred Kaehrle, the town’s character truly was changing. The town’s population stood at 44,000, and had grown about 33% since 1940. Residential neighborhoods sprouted up on any undeveloped land.

Downtown Hartford was still the main shopping area for the region, Lord & Taylor had not yet opened in Bishop’s Corner, and Sears in Corbin’s Corner was not yet planned. Burnham’s grocery store on South Main Street across from the Town Hall anchored the Town Center. Since 1898, it had been the hub of shopping in the center. Angled parking at curbside brought customers right up to the stores, but people complained about traffic and feared losing the residential nature of this town.

Residents were clear that West Hartford was a residential town, not a city like Hartford and that was a good reason to live here. Hartford’s population peaked in 1950 at about 170,000; out-migration grew tremendously in the 1960s and 1970s as highways connected suburbs to city and shopping moved to strip malls in the suburbs.

The town had to provide services for its growing population. Between 1949 and 1959, 11 new schools were built in West Hartford. Even though the tax base continued to grow, the town had to scramble to keep up with the explosion in school age population and the increased traffic.

In the 1950s, residents who moved here characterized the town as a suburb, not a city. The town government reaffirmed those beliefs.

By 1959, the Town Planning and Zoning Commission had reworked Kaehrle’s 1951 town center proposal to encourage its commercial growth while maintaining the neighborhoods in the center. The plan included the extension of Walden Street from Farmington Avenue to Arapahoe Road, and the extension of Arapahoe from LaSalle Road to South Main with an eventual link up through Memorial Road to Trout Brook Drive (just completed in 2004). LaSalle Road would end at Ellsworth and not go through to Pelham Road to maintain the residential nature of the town outside the perimeter of traffic.

The TPZ wanted to build a perimeter traffic plan because traffic was a problem at the main intersection of Farmington Avenue and Main Street and to contain development within the perimeter formed by Walden and Arapahoe on the south and west. According to Town Manager, Richard L. Brown, the plan would keep the residential areas safe and stable.

By this time, Lord & Taylor’s 100,000 square foot store in Bishop’s Corner and the planned Sears Roebuck with 130,000 square feet in Corbin’s Corner threatened businesses in the center. The town planners foresaw opening a “junior department store” in the center to support specialty shops. In 1959, the Town Center’s largest dry goods store had 15,000 square feet.

The new plan included concern about parking with the proposal for a two-level parking lot. Plans also surfaced for a 100 room hotel with banquet facilities to be located on the southeast corner of Trout Brook and Farmington (where the Exxon station is today.)

The new Hall High School on North Main did not open until 1970, but already in 1959, town planners knew that the new school would be built, just two years after the completion of Conard. Some wanted the Old Hall kept as an education center after the north end high school was built. One plan had this building transformed into a college; the high percentage of West Hartford’s high school graduates who planned college level studies, they thought, would produce an overflow of students who would not be able to enroll in a traditional college and this building could provide a place for residents to complete the first two years of college work on a tuition basis.

By 1962, the Town Council came up with still another comprehensive plan for development. The plan was based on the population continuing to grow from 62,000 to 80,000 in 20 years. The population actually peaked in 1967 at about 73,000 and then declined until the 2000 census to about 61,000.

The continued thrust of this plan was to establish the character of the town as a residential community. The plan said, “the prime planning objective is to preserve the town’s good residential character” and to keep high standards in planning any new developments. No more than 10% of the town would be for commercial or industrial use. In 1962, according to the plan, people “shop, work and recreate” outside of West Hartford. There was much talk about zoning for apartments as that was seen as the only means for residential growth.

In 2004, 42 years later, residents again speak out about development in the town center. But unlike the 1960s, West Hartford no longer portrays itself as only a residential suburb. This new Blueback Square development is a mixed use development which integrates residential, office and retail space so that use of the area is spread out over the course of the day.

Residents continue to be concerned about the character of the town. The concerns about traffic and residential neighborhoods continue. And with this development, instead of the Town Center reacting to development in the north and south ends of town, Westfarms Mall has weighed in with apprehensions about how the center’s growth will affect their retail sales.

Residents today, just as 40 years ago, raise the concern that the town may become too urban and lose what they consider to be the “small town” residential feel.

The town government continues to work as a partner with developers, in their efforts toward controlled development which balances the need for new tax revenues, with neighborhood concerns, and with the changing role the town of West Hartford plays as a regional destination for shopping and nightlife.

As West Hartford residents have always done, they will continue to candidly question the motives of both government officials and commercial developers in the debate over how new developments define the town’s character.
