## Olivia Shelton, African-American Pioneer {-}

*Originally appeared in West Hartford Life, June 2003*

When Olivia and Clarence Shelton and their two children moved to 178 North Main Street in 1959, the man next door offered them $5,000 not to move there. This African American family crossed the housing boundary and some West Hartford residents did not like it.

![Olivia and Clarence Shelton moved to this house at 178 North Main Street in 1959. Though real estate agents tried to discourage them from buying the home by telling them there were termites and water in the basement, they went ahead and bought the house and lived there until 1994. Source: Noah Webster House & West Hartford Historical Society.](images/09-shelton.jpg)

In 1997, West Hartford resident Dorothy Billington interviewed Olivia Shelton when she was 87 years old. In that year, members of the West Hartford Historical Society took oral histories from members of our community whose stories may never hit the history books. These remembrances, now transcribed, offer a unique perspective into the past in our town which, when set in the context of their times, illuminate the character of our suburb.

Olivia Glascoe (1910-2001) was born on a farm in the small town of Franklinton, North Carolina. Her father rented land as a tenant farmer and they picked cotton. They raised cows and pigs. Olivia had aspirations and ambitions beyond the farm. She graduated from Shaw University in Raleigh, North Carolina and went on to get a Master’s Degree in Education from Columbia University. At Columbia she lived in the International House where she had contact with people from all over the world. Living in this house was probably not Olivia’s choice, but more likely, was a way Columbia segregated its dormitories.

After her studies at Columbia, Olivia taught school for eight years in North Carolina before marrying her husband Lt. Col. Clarence Byrd Shelton in 1942. From 1942 to 1944 they lived in Seattle and her first son, Clarence Jr. was born; they moved to Hartford in 1945.

When the Sheltons first came to Hartford, the Board of Education would only hire Olivia as a substitute teacher for three years, despite her teaching experience, her Ivy League education, and principal’s certificate. Why? Shelton replied, “Because I was black! I’m positive it was because I was black.” She took two or three years off when she had her second son and then decided to go back to teaching. Hartford did not hire her at this point. She appealed to Reverend Moody, one of the first black members of Hartford’s Board of Education, and he got a job for her.

This part of Shelton’s story reveals that segregation still existed in New England well after World War II. Many historians argue that World War II was a watershed for the civil rights movement because of the Fair Employment Practices Commission established by Franklin Roosevelt after much pressure from A. Phillip Randolph, a national leader of the African American community. However, as often is the case, practice was slow to follow this policy change.

The Sheltons rented a three-family home on Oakland Terrace in Hartford for their home from 1947 to 1959. They owned a farm in Burlington, Connecticut from about 1947 to the mid 1950s and spent their summers on the farm. Many friends and relatives visited. They had a huge garden, a large pond for swimming, and a barn with horses for riding. Her niece remembered many happy days there in the summer. Later, the Sheltons bought a Maine lake house with a number of other couples.

Olivia Shelton and her family moved to West Hartford in 1959 and lived in their 5 bedroom, 3½ bath Tudor on North Main Street for 35 years. Their second son Brent was 10 when they moved to West Hartford in 1959. He was the first black student to attend Bugbee school. Brent joined Cub Scouts and his den mother was G. Fox’s Beatrice Fox Auerbach’s daughter Georgette Koopman who lived nearby on Brookside Boulevard. Olivia said, “Brent made out alright, because at Bugbee, this lady took him in. He was friendly with her son... The people treated him alright. They didn’t dare treat him any other way because of Mrs. Auerbach... She owned G.Fox and Company. That made a difference.”

For Olivia, her positive experiences outweighed the prejudice she faced. Right after she moved in, she found a note in her mailbox which read “get out of here, you black bastards, while you still can.” She believed “that note did not represent the community.” At 87, Olivia’s recalled that she was happy she got the note before her sons, and that her overwhelming experience in West Hartford was “very good and wholesome.” She felt fine living on North Main Street, and said “Most of the people there are Jewish and they were nice to us.”

Olivia joined the First Church of Christ in 1961 and she taught third grade Sunday School for 12 years. The Sheltons were the only black family in the church. She was appointed a Deacon at the church as well.

Olivia volunteered as a clerk in the gift shop one day a week at the Science Museum. She served as the president of the Hartford Chapter of the National Council of Negro Women. She was also one of the founders of the West Hartford African American Social and Cultural Organization. In the summer of 1967, she trained to be a teacher for Project Concern. She was a Hartford teacher sent to work at Smith and Wolcott for a year.

When she moved to the McAuley in 1994, she was the first black resident. She lived on the edges and could go between cultures. She said that she lived a happy life as a pioneer.

Oral historians must be careful of their sources, and particularly of reminiscences of life. In a 1973 *West Hartford News* article, Olivia had quite a different take on her life here in West Hartford. Though in 1997, she did talk about the problems her sons had in school once they were in junior high and high school, she summed up her life here as very positive. In 1973, she told the *News* that there was a lot of “pettiness” here. Real estate agents told them that there were termites and water in the basement in certain houses so that they wouldn’t buy one in a white neighborhood. She said that the treatment made her so upset that after they moved in, they would attend real estate open houses in various neighborhoods “just for meanness and devilment... to scare the people.”

She said in 1973, “I don’t like to pretend to put forth that all is well--- I’m sure that you’ll run into that, interviewing other black families.” She said that her oldest son Clarence “caught hell in high school.” He went to Conard. “The girls loved him but the fathers hated him. They gave him a hard time. Every time he looked around, the police were after him.” High school was “terrible for him.” They sent their second son to Watkinson hoping to protect him somewhat, but that was tough for him as well.

Residents of West Hartford struggled with the reality of an integrated community. Though African Americans had lived here from the 18th century, and are clearly here in the early 20th century, segregation seems to have increased in the 1930s and 1940s, until it was a noticeable event to have a black family move in in the 1950s. Between 1959 and 1973, 39 black families, a total of 265 African American people out of a population of 70,000 settled in West Hartford. Some were helped by the Connecticut Council of Churches which worked to get black families to move to the suburbs. The 1973 *News* article made the point that many of these families were upper income and the greatest proportion lived in the Aiken school district.

But, the tension over what our community was remained. There were many people, like Georgette Koopman, who embraced the idea of a multi-racial community. The relationships of one individual made a difference. Then there were those afraid of difference who tried to make people like the Sheltons question their right to live in the town. Tensions over living in a multi-racial, multi-ethnic, and multi-religious community are played out in neighborhoods and schools every day as we attempt to live out the promise of the American Dream.
