## Democrats vs. Republicans: 1958-1972 {-}

*Originally appeared in West Hartford Life, October 2001*

> In 1961, it was socially improper, economically stupid and politically unwise to be a Democrat in West Hartford. But in 1972, it is an idea that has arrived.

This statement, made by Harry Kleinman, then Democratic Town Chairman, attorney, and past judge of the West Hartford Police Court, makes me wonder what changed in the town, at the state level, and at the federal level that turned West Hartford from a Republican to a Democratic town over these years.

Kleinman’s statement was a bit of hyperbole because, 17 years earlier, in 1955, Democrats gained control of the Town Council for the first time in the town’s 101 year history. At that time, the town was split into seven districts and Town Councilors were elected by district. Two years later, in 1957, Republicans outnumbered Democrats 14,000 to 6,000 but the Democrats maintained their 4-3 council majority by a mere four votes in the sixth district (Morley School and Quaker Hose Firehouse areas). Most of the Republicans lived in the first (largely north of Farmington and Asylum Avenues) and second districts (Town Hall, Sedgwick and Webster Hill School areas.) These two districts had a much larger populations than the other five, but the districts established in the 1920s were not readjusted as the population grew.

In an article written for the *West Hartford News* in 1972, Nan Glass, former Democratic Mayor of West Hartford chronicled the history of the Democratic Party. She wrote that the original Democrats in West Hartford, prior to World War II, were largely Irish Catholics from the south end of town. The chairmanship of the party held by Edward P. Quinn was passed to his sister Katherine in 1942 when he resigned to become Registrar of Voters. She was chairman for 10 years and then Richard T. Scully took over when Quinn became involved in the state and national Democratic Party structure.

Following World War II, in the 1950s and 1960s, Irish from the south end dominated the party: Brian O’Meara, Robert Shea, Helen Murray, Dorothy Muldoon, Thomas O’Neill Jr. and Edward B. Connors all played major roles in Democratic politics and town government.

In the 1960s, a steady stream of Jewish voters moved from the North End of Hartford to northern West Hartford. They brought with them their Democratic Party affiliation. They were joined by a growing number of residents of Italian background. A fourth faction included the “Yankee” liberals –- like Catherine C. Reynolds and State Senator Jay Jackson, the first Democrat from West Hartford to be elected to the State Senate in 1966.

In the early 1970s, with the 26th Amendment and the anti-Vietnam War movement, the Democratic Party made a big effort to register 18 to 21 year olds as Democrats.

These constituencies led the Democrats to pull ahead of the Republicans in registration by 1971, 15,000 to 14,200 with 13,000 unaffiliated voters. However, that did not mean that the Democrats dominated politics, even in the 1970s.

Just as demographics changed over the 40-year period, so did the nature of the electorate. In 1958, the liberal Abe Ribicoff was the first Democratic Governor ever to win West Hartford. But West Hartford voters remained conservative on local issues. A referendum to allow the sale of liquor in restaurants on Sunday was defeated for the second time 9,195 to 5,457 with only one precinct, King Philip School, voting in favor.

But Republicans did not take these local and state wins lightly. In 1958, a new charter, supported by the Republicans, who outnumbered Democrats 3 to 1, allowed Town Councilors to be elected at large, rather than by district. In April 1959, under the new charter, the Republicans took control back from the Democrats winning six seats and the Democrats winning three. The April 1961 election found the Republicans in control once more, though the gap in registration narrowed slightly.

National politics in 1964 displayed the independence of the voters. Democrat Lyndon B. Johnson swept the district with 65% voting for him. Local Republican leaders were visibly upset with Barry Goldwater’s showing. This was the first time a Democratic presidential candidate won in West Hartford. Democrat Thomas Dodd defeated the Republican ex-Governor John Lodge for Senate. The jubilant party at Democratic headquarters on New Britain Avenue was filled with young Democrats who had started a young adult political organization, United Democrats for West Hartford, in August of 1964. This group enrolled many new voters and claimed their share in the margin of victory.

In 1967, the Republicans maintained a majority in registration, 14,200 to 11,400. There were 13,300 unaffiliated voters, who tended to lean to the Republicans. Popular Republican Mayor Richard Sheehan did not run for re-election. The Democrats won the election and took control of the Town Council 6-3. Architect John M. Huntington became Mayor even though he was the third highest vote getter. It was thought that he was the butt of negative campaigning when Republicans accused him of supporting “reverse busing” to integrate the schools, the “Project Concern” initiative, even though he did not.

The 1968 Democratic primary voters could choose between Eugene McCarthy, Robert Kennedy and Hubert Humphrey and this led to a split in the local Democratic Party, but ultimately led to a majority of Democratic registered voters. The national party called for a modernization of party machinery and changes that would “democratize” the party. The party establishment felt the purpose of the town committee was to get Democrats elected while the newcomers in the form of the Caucus of Connecticut Democrats were more interested in the party taking positions on social issues. This particular faction of the party supported Eugene McCarthy for the Democratic Presidential nomination. Oliver and Mims Butterworth spearheaded this group.

The CCD managed to oust Katherine Quinn, the second most powerful Democratic Party leader in Connecticut, from the Democratic State Central Committee, a position she had held for 40 years. Mims Butterworth, a McCarthy supporter, took her place on the state committee from the 5th District.

However, the Democrats controlled the town for only two years. In 1969, Republicans won the Town Council, 6-3 and chose Ellsworth Grant as Mayor.

The Democratic slate in the 1971 election was entirely new, except for incumbent Brian O’Meara, and did better than any other slate in history. Catherine Reynolds, in her first election, was the top vote- getter. The Democratic newcomers actually beat a Republican incumbent. The Democrats gained one seat in the Council (5-4) and gained control of the Board of Education (4-3). The Republican Party chairman, Alfred ”Tim” Covello credited the Democratic presence to a general unhappiness with government at all levels, especially on the federal level. By 1971, many voters opposed Nixon’s policies in Vietnam and that may have been felt in the election.

But, the Republicans came back strong in the 1972 federal election with President Nixon defeating McGovern by 23,000 to 18,000. At the same time, Bill Cotter (D) defeated Republican Rittenband for Congress and Republican Nicholas Lenge defeated Democratic incumbent Jay Jackson for the State Senate seat.

The Democrats lost municipal elections in 1975 and 1977, and with the defeat of Jackson in 1976, Harry Kleinman felt it was time to give up the reins of the Democratic Party. He resigned after holding the position for 17 years.

Kleinman helped build the party through voter registration, but it was up to the next generation to consistently win elections. West Hartford’s thoughtful electorate could not easily be bound to party, but by the 1970s it was no longer an embarrassment or liability to be a Democrat.
