## “Remember Me”: The Vietnam War {-}

*Originally appeared in West Hartford Life, February 2005*

“Remember Me.” These are the plaintive words of Joe Donahue, historian of the Connecticut Veteran Memorial soon to be built in the center of town on the site where the first church was built in the West Division. Donahue has spent two years researching the 202 West Hartford war casualties. Donahue’s passion for finding out about these casualties embodies the spirit behind the building of the war memorial in the center of town.

A look at the 17 men who died in the Vietnam War gives a window on the sacrifices made by a country, a state, and a town when the federal government chooses to go to war.

The average age of the men who died was 24. Two men who died were 35; of the 15 others, the average age was 22. Four graduated from Hall, two from Conard, two from Kingswood and one from Northwest Catholic. Five were college graduates from Georgetown, University of Pennsylvania, the Naval Academy, Trinity, and Norwich University and all 17 graduated from high school. All were listed as Christian.

Geographically, only one man lived north of Asylum Avenue. One man lived on Hunter Drive, two in the Buena Vista area, and three in the area around Kennedy Park. Two lived near Fern Perk, three near Morley School, and one near Conard.

Nine of the men died on the ground, one the result of an accidental homicide. Seven died in helicopter or plane crashes. The highest national and town casualties were in the year 1968, the year of the Tet Offensive. For the nation, 14,000 died, which was about 25% of total casualties. In West Hartford, 6 of our 17 were killed in that year.

Below is a short paragraph on each man who died based on Donahue’s research. They are listed in the order in which they died.

1. Brian John Cronin, 775 Farmington Avenue was a Navy bombardier navigator aboard a light bomber that crashed in an unknown area. His plane was downed in the South China Sea. He was West Hartford’s first casualty and died in December 1964 at age 24. He played tennis. He went to UCONN where his father was Dean of the UConn School of Social Work. He graduated from East Hartford High School, and then lived with his widowed mother before he enlisted. JFK was his hero and he joined the Navy because of it.
2. Edmund Francis Eddy, of West Point Terrace was killed by small arms fire in March 1966. He was a Marine Corps Field Radio Operator. He was 22 when he died in Quang Ngai Province.
3. Edward Gaffney Creed, of North Steele Road, was killed in June 1966 in Thua Thien Province. He was a crew member on a medical evacuation mission when his helicopter caught fire from hostile gunfire and crashed. He was 21 when he died. He served for three 1/2 years.
4. David Hight, of Meadow Farms Road, was in the Army, and died at age 24 somewhere in Vietnam in June 1966. He died from wounds suffered from a grenade. He signed up for two years of service but died after serving for nine months. His parents moved to West Hartford the year Hight graduated from high school in New York state. He graduated from Norwich University.
5. John Welch III, age 24 from 28 North Quaker Lane and a graduate of St. Thomas Parochial School, Hall High School, and Georgetown University (1965) died of wounds suffered on the ground at Quang Ngai in February 1967. He entered Marine Corps Officers’ Candidate School in January 1966 and graduated with honors. He arrived in Vietnam in October 1966 and served for five months. Welch had a brother at the U.S. Naval Academy at the time and one other brother and two sisters.
6. William Markarian lived on Bretton Road and died from an explosive device at age 19 at Thua Thien. He left for Vietnam in May 1967 and died nine months later. He had been a gardener with Baker’s Nursery in Tariffville before he entered the military.
7. Crosley Fitton, Jr. died in February 1968 at age 35. He was an Air Force pilot flying an F105 Thunderchief on a combat mission as part of the Tet Offensive, flying over the outskirts of Hanoi when his plane was hit by a surface to air missile. He and his co-pilot bailed out and parachuted safely to the ground. It was unclear what happened next as the Air Force listed them as “Missing in Action.” In 1975, Fitton’s remains were handed over to a U.S. congressional delegation to Hanoi. His wife, who had remarried by 1975, and his parents were skeptical that the remains were really his. At age 17, Fitton and four other West Hartford boys went to Detroit to compete in a national model plane contests sponsored by Plymouth. His interest in planes continued. He was married and lived on Oakwood Avenue
8. John P. Holden II, who lived on Farmington Avenue, died at age 24 in Quang Tri Province. He served in the Marines and was killed in a mid-air collision of helicopters that had picked up four wounded Marines near Khe Sanh in February 1967. He was married.
9. Army Corporal Radioman Adam Knecht, age 20 from Oakwood Avenue was killed at Binh Duong in May 1968 of multiple fragmentation wounds. Adam lived in West Hartford until he was 11. In one of his last letters, Knecht had questioned “the purpose of wasting young American lives” in the Vietnam conflict. He was drafted.
10. Raymond Coyle Daley lived on East Normandy Drive and died in Quang Nam province in July 1968 when his helicopter was downed by enemy fire. He served as a First Lieutenant in the Marine Corps. He won the Air Medal, Purple Heart, Vietnam Service and Campaign Medal and National Defense Medal. He was 24 when he died. He graduated from Hall High School and attended Providence College and the Naval Academy.
11. Robert Lyon Norton of Keeney Avenue and a graduate of Hall High school died at age 35 in Quang Nam Province in December 1968 as the result of a plane crash under hostile fire. He served for 14 years in the Marine Corps. Norton received the Distinguished Flying Cross, the Air Medal and the Purple Heart. He lived most of his life in West Hartford. He was an Eagle Scout and graduate of the Hall High class of 1951. He attended UCONN, but did not graduate, entering the Naval Air Cadet Program during the Korean War.
12. Mark Hannay Dixon, of Uplands Drive died at age 23 in Quang Nam province. He earned a Purple Heart, Silver Star, Bronze Star, and Army Commendation for his service. He was killed trying to rescue a wounded comrade in Quang Nam. His Silver Star citation said that he “courageously crawled, under intense enemy fire, to the fallen soldier and began to administer first aid.” As he tried to carry the man to safety, he was hit by enemy fire. His tour of duty began in late March 1969 and he died one month later. He graduated from University of Pennsylvania. He was going to enter University of Michigan Law School in 1970. His father was a lawyer. Classmates at Kingswood established a scholarship for him and collected $6,500.
13. Thomas Hill, of Florence Street died at age 21 in Binh Duong province by a mortar missile. He served as a Warrant Officer in the US Army and was killed in June 1969. He was a member of the first graduating class at St. Brigid School, attended Northwest Catholic, Cheshire Academy and Wichita State University in Kansas. He entered the Army in October 1968 and became a helicopter pilot. Hill’s father was a Fire Captain in town and his mother a secretary to U.S. Senator Abraham Ribicoff.
14. Marine Lance Corporal Douglas Whiting Young, age 21 was killed on December 20, 1969 in Quang Nam Province as a result of an accidental homicide. He lived on Longview Road and graduated from Kingswood School in 1966 and attended Rensselaer Polytechnic Institute for two years. He was a member of the First Church of Christ Congregational.
15. Loring McKenzie Bailey, Jr., of Saint Augustine Street, was age 24 when he was killed in March 1970 at Quang Ngai Province on the ground. He was with the U.S. Army infantry. He was married. He served for only 5 ½ months before he died. He graduated from Trinity College in 1967. His wife was from West Hartford, though he grew up in Stonington.
16. Norman Westwood, from Terrace Road and a 1962 graduate of Conard High School, was killed at age 25 in May 1970. Westwood graduated from St. Anselm’s College. After college he joined the Navy. Westwood flew more than 100 missions and was awarded the Air Medal. He served for four years in the Navy in the reserves and as a pilot. He died when his F-4 Phantom fighter failed in its takeoff from the USS Coral Sea for a bombing mission over North Vietnam. His plane sank in the South China Sea. Westwood was the son of the West Hartford Deputy Fire Chief. Westwood hoped to return to the U.S. in June and marry his fiancé from California.
17. Gary Lewis, from South Street, graduated from Conard in 1969 and was 20 when he was killed by a booby trap in Quang Nam on June 30, 1971. Lewis enlisted in October 1969. His parents said his tour of duty was up in September and he was planning to come home to go to college.
18. Jeffrey Weed died in an airplane crash on his way to Vietnam on April 6, 1972. He was a Captain in the US Marine Corps. He grew up in West Hartford, and earned his Eagle Scout. He graduated from Mount Hermon School in Northfield, MA and then from Lehigh University in Pennsylvania. He had a low lottery number and chose to enlist. Because he was not in combat when his plane went down in the South China Sea, his name cannot appear on the Vietnam War Memorial. However, his name is on West Hartford’s wall.

The Veterans on the War Memorial Committee want the information Donahue gathered to be used in West Hartford’s history classrooms. Gathering the raw material is the first step toward helping teachers teach about war from a local perspective. As historians, teachers know that to accurately teach about war, they need to show many viewpoints: of those who fought, those who protested and those whose lives changed on the home front. Learning about those who died in service to the country is one these perspectives.
