## Conard’s Jimmy Johnson {-}

*Originally appeared in West Hartford Life, February 2014*

When Jimmy Johnson was elected captain of Conard’s 1959-60 basketball team, he became the first African American to hold that coveted position. He lived in a town that, just 10 years earlier, had restrictive covenants limiting the sale of homes to anyone Black. And only 39 black families (265 people or .3%) moved to town between 1959 and 1973. His experiences trumped the discrimination felt by others as he played the role that W.E.B. DuBois touted of one of the Talented Tenth. DuBois believed that the top ten percent of Blacks could be successful and help lead the way toward full community integration.

Johnson moved to West Hartford on November 11, 1954, when it was one of the wealthiest towns in the United States. He, his parents, and his two sisters lived in the Duffy district. His father owned rental properties in Hartford. Johnson entered the 6th grade at Duffy School and at 5’6” entered 7th grade at Sedgwick Junior High. At Sedgwick he played soccer, basketball, baseball and handball. At that time, the four junior high schools had competitive sports teams and by 9th grade, Johnson starred on his 9th grade basketball team.

His family clearly was financially successful. When not in school, Johnson spent time fishing in the MDC reservoir off Farmington Avenue. He went horseback riding in the reservoir as well, with his friend Bill Butler from Sunset Farms. Jimmy owned a horse for a year, until his father realized the high cost of stable charges and feed. Once in high school, Jimmy could be seen driving his late model Ford convertible around town.

In the summer he played on the outdoor basketball courts at Duffy and at Morley. As a tenth grader, he played junior varsity but did not see much playing time. In the summer before his junior year, Johnson played 2 ½ hours a day, 5 days a week in his determination to play varsity his junior year. He claims he missed his sister Sandra’s Conard graduation because he was playing ball; Sandra was the first African American to graduate from Conard in 1959.

In the late 1950s, summer games at Morley School on Fern Street brought great players and crowds. On these public courts, Johnson bragged that he would dunk so ferociously that “sparks flew off the chain-link net.” Johnson played with the likes of High School All American Johnny Egan (Weaver, Providence College and the NBA) and Ray Moore. When Egan played, cars were parked on both sides of the street for a ¼ of a mile.

As a junior, Johnson made the varsity, being “welcomed... with open arms and kind words,” by star Ed Driscoll. Johnson was the inside player and Driscoll shot from outside. Johnson blocked at least three shots per game. In his junior year, Johnson was selected to the all-league team along with Driscoll.

According to the *Hartford Courant* in 1959, “Heading the list of letterwinners is stylish Jimmy Johnson, the popular captain-elect of the Chieftains. He was my most improved player from a year ago,” said Coach Larry Stewart. “After four games with the Jayvees, he was moved up to the varsity where he finished second to Driscoll in both scoring and rebounding. He should have a fine year this time around.” In his senior year, Johnson (6’2’) was joined by Senior Ed Driscoll, 6’3”, sophomore Billy Dunn, 6’5”, Senior Dick Gitlin, 6’4”, and Senior Al Grotheer (6’4). That year, the team made the state tournament with a record of 10 and 6.

On Friday nights, everyone from 13 to 20 years old, could be found in the Conard gym watching the team. Coach Stewart guided Johnson’s team to a 10-6 record in the ’59-’60 season. Driscoll and Johnson together scored about half of Conard’s points.

On January 9, 1959, Hall’s boys’ basketball team beat Conard 49-43 before 1,400 fans at Conard’s gym. Conard’s Junior Jimmy Johnson and his teammates lost to their crosstown rival at a game that Hall was slated to win. Administrators had to turn spectators away because the gym was full. On their second meeting, five weeks later, Hall trounced Conard 65-48. Johnson scored 11 points. The game was played before a “capacity crowd at the Conard gym. Many fans were turned away before the varsity attraction even began due to lack of seats.”

Conard won 7 of its last 10 games to nail down the 14th seed in the CIAC basketball tournament. Conard finished fourth in the nine team CCI League. In the tournament, they played Coach Howie Dickenman’s Norwich Acads. They played their first tournament game against Norwich in Storrs and lost in the final quarter with a come from behind win by the Acads, 53-38 with Johnson scoring 7, Billy Dunn with 10 and Driscoll with 13.

In August, 1961, at the end of his junior year, Billy Dunn, 17, a class behind Johnson was killed in a car crash in Northampton, Massachusetts. Johnson, who had just graduated from high school, was devastated by Dunn’s death. Dunn’s parents who lived on Brenway Drive near Bugbee School, wrote a note to Jimmy and his parents which Johnson kept. Dunn’s mother Ruth wrote, “Bill loved Jimmie, and we all admire him greatly. We shall be greatly interested in his future, and hope he will come here sometimes as he used to... P.S. If we can ever help Jimmie with a job---school problem---or anything---please come to us.”

Johnson’s story reminded me of journalist Isabel Wilkerson’s 2011 *New York Times* essay, “A First Time for Everything,” in which she scoured obituaries in newspapers across the country and found over 300 obits that had one phrase in common, “the first African American to. . .” Wilkerson, argued that “Each position was in its own way both a happy triumph and a sad reminder of what it took to get there.”

Does that tell the story of Jimmy Johnson, the first African American student at Conard to be named captain of a sports team? Even though in 1959, Johnson became captain of the boys basketball team, his legacy is not so well known. Johnson, now a successful trial lawyer in Michigan has kept in touch with many of his classmates and shared his pictures playing basketball with short snippets of his life in town. His experience here made a difference.

And yet, it wasn’t until 16 years later, according to Conard Coach Eddie Litos, that another Black athlete appeared in a yearbook photo of a varsity team. Mark Walker started his career as a three year varsity player in 1973-4 having earned a letter when he was a sophomore. He became the captain in 1976. Between 1960-1974, according to Litos, no other African Americans appeared.

According to Wilkerson, as she scanned the obituaries, she noted how mundane the “first” positions were, how modest the dreams had been. And yet, she argued, “they somehow bear witness to how far the country has come and how it got to where it is. They speak to how many individual decisions had to be made, how many chances taken, the anxiety and second-guessing at the precise instant that each of these people was hired for whatever humble or lofty position they sought.”

For Johnson, in retrospect, his skill and determination seemed to trump the anxiety he may have felt integrating the team, and helped the white teammates accept him. At the same time, his role must have caused some tension in a town, where in 1959, when the Shelton family moved onto North Main Street, they found a note in their mailbox which said “get out of here, you black bastards, while you still can.” Johnson’s legacy, of a young man who starred, had friends, and made an effort to keep in touch with classmates, shows another side of the integration of the town. Johnson’s memories focus on his successes and his relationships which kindled his success.
