## What Kind of Town Are We? {-}

*Originally appeared in West Hartford Life, May 2004*

“West Hartford has style,” says Sue Wilson.

Nan Glass said we have “stability and commitment” among our government officials.

Flo Woodiel said she feels lucky to be able to express her left of mainstream political ideals without retribution.

Dick Woodworth believes that “it is the quality of the people that, as much as anything, contributes to the rightly ballyhooed quality of life in West Hartford.”

Sue Wilson, a former Town Councilor, Nan Glass, former Mayor and Town Clerk, Flo Woodiel, community activist and Dick Woodworth, former publisher of the *West Hartford News* and co-chair of the Sesquicentennial Celebration, and others all participated in interviews with Conard’s Local History classes in mid-March for the Sesquicentennial. The participants included town leaders in politics, business, social organizations and religion. They readily gave of their time to share what it meant to be involved in community leadership roles through the 1960s, 1970s and 1980s.

Ilze Krisst remembered when she moved to West Hartford in the early 1970s, joining the League of Women Voters. Many women did not work outside the home, but felt a strong sense of civic responsibility. Under her direction, the League developed its first Voter’s Guide for local elections. Members addressed issues, went home and researched them and came back to twice monthly meetings and debated them. At these lively intellectual discussions, Krisst found a comfortable and politically active peer group. Krisst remembered that many of the League women had young children and for each meeting, one of the members agreed to forego the meeting and babysit for all the children. Thirty years later, Krisst played a fundamental role in the founding of the Park Road Playhouse.

Sue Wilson served on the Town Council for two terms, from 1979 to 1983. Wilson entered town politics with the first group of women riding the wave of the feminist movement. In her second election, the Democrats gained a majority and Wilson felt she could do more. West Hartford’s population had peaked in the early 1970s and a town which at one point had 23 public schools and 14,000 students had severely declining enrollment. In the mid-1970s the Whitman, Beach Park and Elmwood Elementary Schools were closed. In 1979 both Plant and Talcott Junior Highs closed. This decline led to tensions among sections of town, as well as between the Board of Education and the Town Council.

In the early 1980s, the Board of Education voted to close the Smith School, in the southeast section of town. For the only time that Wilson remembered, the Town Council overruled the Board of Education to keep Smith School open. They felt it was necessary to retain the viability of the neighborhoods which surrounded the school. Wilson was particularly interested in supporting services for low and moderate income families. She went on to support the Interfaith Housing Coalition building affordable housing. Wilson took on the issue of part-time workers at the public library. She worked to establish a standard wage and benefits for these women who made the library go. She also became the first woman president of the Unitarian Universalist Church on Fern Street from 1985 to 1989.

Pastor Carl Anton of the Bethany Lutheran Church came to town in the 1960s as the pastor and has stayed. The church opened in 1944 as a German Lutheran Church. The Lutheran Church in Hartford on Capitol Avenue had Swedish roots. When the church was being built during World War II, some people in town believed that the church was an arm of the German bund. Swastikas appeared in town, even though there was absolutely no connection to the Nazis. Because of this, there was never a church service held in German at his church.

When Rabbi Harold Silver moved to town in 1968, he became only the second rabbi at Beth Israel, following in the footsteps of Abraham Feldman who had been rabbi since the synagogue moved to West Hartford in 1936. Rabbi Feldman established his role as a political activist through his support of the controversial busing program, Project Concern in 1966 and in his role on the Library Board. Rabbi Silver continued in the role of community activist as he supported social issues such as the Interfaith Housing Coalition’s decision to build scattered site housing for low income and disabled people. Of the 30,000 Jews who live in the Hartford area, a large percentage lives in West Hartford. Silver continues to minister to them in his role as Rabbi Emeritus.

Angelo Faenza continues to leave his mark on the town through his businesses and through community service. Faenza moved to town from Hartford when he bought the Prospect Café in the 1970s. Soon a successful restaurant, in the 1990s, he opened Faenza’s on Main at Rockledge. But his restaurants were only part of his commitment to the town. In 1986, he helped to start “Celebrate! West Hartford,” the annual spring festival held in the town’s center. In 1986, the Center was not the vibrant and active place it is today. The town population had declined since the early 1970s, schools were closed down and Westfarms Mall, which opened in 1974, took away much of the business. Faenza’s leadership in this community celebration helped to spur the resurgence of the center.

John Green, President and CEO of Lux, Bond, and Green, is an example of a local businessman who helps make West Hartford Center unique. Green’s great grandfather, Morris Green founded the company in 1898 in Hartford. John’s grandfather Irving became its president in 1933 and during his tenure, the West Hartford store opened in 1957 on LaSalle Road. John’s father Robert took the presidency in 1973 and in 1987, the store’s headquarters moved from Hartford to West Hartford.In 1992, at age 36, John assumed the presidency of the company. Presently there are seven stores, six in Connecticut and one in Boston. Unlike other jewelry stores, Lux, Bond & Green sales personnel are not paid commission. The store prides itself on the trust they build with their customers. Green has also given back to the community through the golf tournament his company sponsors each year. In the last 14 years, the tournament has raised over $200,000 for area charities.

Many of the student interviewers wondered why these community leaders volunteered so much time through their political work and community service. It is these residents that help define what makes us such a special town. Their dedication not just to their work, but also their dedication to the town helps to define the sense of care and concern that builds a community to which people are proud to belong.

*Thank you to students Julie Monahan, Anna Flores, Jennifer Lin, Nick Macca, Jesse Wrubel, Meredith Poltorak, Kristen Mangiafico, Ryan Kelly, Lauren Ramezanna, Joe Ryan and Jessica Feliciano for their help in recording and interpreting these interviews. Stay tuned next month for more interviews. Come to the Sesquicentennial’s Public History Day where you can hear what each of the interviewees believes make West Hartford unique.*
