## Gordon Bennett {-}

*Originally appeared in West Hartford Life, November 2009*

When the Noah Webster House had a fundraiser at the Brace Road Fire Department in the late 1990s, Gordon Bennett, a founder and benefactor of the Noah Webster House Foundation, got in the rescue cherry picker and scaled three stories to its full height. This didn’t surprise those in attendance who knew Bennett, but some young observers, worried about this 91 year old on this new adventure.

Gordon Bennett loves life and embodies the type of active community member that makes West Hartford such a vibrant community. He turned 100 on November 6, 2009. His economic and civic involvement has made West Hartford a better place. According to resident Booker DeVaughan, Bennett is a “complete gentleman, and West Hartford has benefited much from good works and dedication to the town.”

Gordon Bennett first appeared in public documents in the *Hartford Courant*, on its society page where it was noted: “Dec. 18, 1931, Mr. Charles W. Bennett and Mr. Gordon Bennett, sons of Mr. and Mrs. Charles J. Bennett of North Oxford Street, Hartford, “will return Saturday from Union College, Schenectady, NY.”

He graduated from Union with a degree in engineering. He remained loyal to his alma mater in his role by 1947 as the Secretary of Connecticut’s Union College Alumni Association. Today, Bennett is Union’s oldest living class agent and he recently received an award for fundraising.

After graduating with an engineering degree from Union, Bennett worked with his father who served as the Connecticut State Highway Commissioner. His father Charles W. Bennett was the second highway commissioner in Connecticut. Gordon talked about how, in the 1920s, when the highway was built from Hartford to New London in the 1920s and 30s, Bennett remembers that the road had many curves because it had to follow the landscape. There was no money to blast through hills or build bridges. Though he and his father were Republicans, they worked for Democratic Governor Wilbur Cross to build the Merritt Parkway. Cross hired them because Bennett’s father was one of the prominent highway engineers of his day.

By the late 1930s, Bennett married and had two daughters and moved from Hartford to Whiting Lane. Bennett remembered, “that was the place to be back then... it was a wonderful town. And you didn’t have to cross the river.”

When Bennett’s father died in 1941, Gordon was 32 years old and ready to go out on his own. He worked for Vulcan Radiator Company as an executive vice president and then moved onto to a ten-year stint at Hartford Empire Company (later Emhart) where he was export sales manager and glass plant manager. This is when Bennett began to travel the world, and for this job he did most of his traveling in Asia, South America, Western Europe, and Scandinavia.

Bennett was on the cutting edge of the global economy. World trade was part of his life in the 1940s and 1950s. According to the *Hartford Courant*, in March 1952, at age 43, Bennett, Granville Shattuck and Helen Sanborn, all experienced in foreign trade, opened a company called New England Overseas Corporation at 12 LaSalle Road. They managed export businesses for Connecticut small machine tools firms who did not have foreign trade department.

In 1957, Bennett became President of Whitlock Manufacturing Company, a principal supplier to rapidly expanding plastics, gasoline, synthetic fiber and atomic power industries. Whitlock Manufacturing came to West Hartford in 1891 when Walter Goodwin persuaded the company to locate on South Street along the railroad tracks. They bent pipe, preheated by steam for car radiators, water heaters and made giant water turbines for the Gatun Dam in Panama. Later they made storage heaters and tubular heat exchangers for laundries, textile plants, hotels and other large users of hot water. During World War II, Whitlock got involved in the Manhattan Project and supplied specially designed systems for nuclear submarines and aircraft carriers.

By 1963, Bennett was president of the company and between 1962 and 1963, profits tripled. Bennett’s family moved to Hilltop Drive. On his daily commute down South Main Street each day, he drove by Noah Webster’s birthplace. Fred Hamilton owned the house, though he and his wife had moved to the house just to its north. The Hamiltons and Bennetts were family friends, and as the story goes, in 1962, Bennett persuaded the Hamilton family to donate the house to the town. The town did not take the initiative to do anything to the house and it began to deteriorate. This is when Bennett stepped in.

Bennett, a business leader in town, used his contacts and his ability to sell. He convinced others to start the Noah Webster House Foundation and to raise money and restore the house. His friend, Dick Crampton served on the Town Council and took up the cause as well. According to Joan Warner, a founder of the Foundation, Gordon was a true leader in getting people to work with him and volunteer to move the project forward.

When they started in 1965, they had $280. The restored house opened to the public in 1968. It attracted visitors from all over and distinguished itself with its school programs. By 1974, they needed more room and Bennett was instrumental in adding the museum portion of the building. His role as supporter and benefactor is built on his love for community and for history. He is a self-proclaimed history buff.

Initiating the Noah Webster House is not his only service to the town. By the mid 1960s, Bennett was a director of the Rotary and member of the Chamber of Commerce. He was active in Republican politics and served on the Town Committee. In the 1970s when he retired, he served as a director on the Seniors Job Bank and as vice-president of the Noah Webster House. He continued to be involved with the Rotary and the Noah Webster House in 2009.

When Bennett retired, he and his wife continued to travel for another 20 years. He says he has traveled to 100 countries through work and play. When Bennett traveled, he was always happy to return to West Hartford, which he deems “a very lovely town, and very well run.” He says this friendly town has not changed a great deal in its manner, even though the population has grown substantially since the 1930s. Bennett’s commitment to West Hartford has helped to solidify this town as a great place to live, learn and work. Happy 100th birthday Gordon!!
