## Piper Brook Redevelopment Project {-}

*Originally appeared in West Hartford Life, September 2001*

Like most changes in West Hartford, the redevelopment of the Piper Brook area in the 1960s and 1970s was full of conflict. Piper Brook is in the southeast corner of West Hartford, bounded by New Britain Avenue on the north, Hillcrest Avenue on the east, the Newington town line on the south, and South Street to the west. It totaled 155 acres, and in 1970 was 30% of the town’s industrial zone.

Until 1924, the Piper Brook area was residential, including houses along Rose Avenue and a few on Custer and South Streets. In 1924, when West Hartford adopted its first zoning laws, the zoning commission zoned this area industrial. Soon industrial buildings and warehouses were squeezed onto small residential lots.

The area, according to George Cunningham, who lived in the Piper Brook neighborhood since 1940, was characterized more by vacant lots than anything else. Its clay soil led to problems with sewage and sanitary conditions. Small lots and frequent floods discouraged businesses and families from settling there. Much of the area was swampland. Every spring floods came up as far as South Street. In the flood of ’55, water reached as far as the properties on New Britain Avenue.

During World War II, tents comprising an anti-aircraft encampment adorned the vacant lots of the Piper Brook area. Those in the barracks were there to warn citizens of attacks from the Germans.

By 1956, West Hartford established a Development Commission whose job was to increase the tax base of the town and encourage industrial growth in the form of office buildings, research labs and apartment buildings. The town yearned for a development like that of Connecticut General in Bloomfield.

In 1962, the town hired a firm to survey the Piper Brook area for development. In 1965 a land use study found 132 houses needed to be relocated and the area needed flood control. The firm submitted this information to the Urban Renewal Administration, a federal agency established under Lyndon Johnson’s Great Society programs.

Historically, back as far as the 1930s, West Hartford was not reluctant to take advantage of federal funds for building projects in town. Under Franklin Roosevelt’s New Deal, West Hartford built its Town Hall and library, a pool at Beachland Park and sewers for Farmington Avenue. In the 1960s, federal money flowed again, and the town applied for money from Housing and Urban Development (HUD).

The federal government had a concern for what they considered to be “blighted areas.” Because the Piper Brook area had mixed uses with residential structures next to industrial ones, they considered there to be “a great potential as a future blighted area regardless of the condition of the structures today.” This made the entire Piper Brook area eligible for federal urban renewal funds. Their idea was to save as many commercial buildings as possible, move the residences and build new dwellings so that residents would be separate from the industrial district.

In November 1966, West Hartford residents defeated a bond referendum at the polls for 20% of the cost of the project. George Cunningham believed that fear motivated the voters. Many families had lived in the area for years and felt a sense of security in their neighborhoods. They attended the local church and their houses were paid for. Some heard that they would be compensated only by the original price of their homes and would be left alone to find new housing. Cunningham helped organize the Piper Brook Boosters Association to try and make the residents a part of the renewal project. He knew all the neighbors and he served on the Project Area Committee. Through this community organization, Cunningham galvanized support for the project.

Two years later, in November 1968, voters approved a revised municipal bond. The federal government grant of $4.5 million was approved in December of that year. And, the town voted almost $1 million in funds for the project.

The plans included building a 96-unit apartment building, realigning the Piper Brook channel, the construction of a new Rose Avenue with 33 residential lots, and building the infrastructure with town utilities. By 1970, 73 project area families were interested in relocating to these new apartments. One of the purposes of the subdivision was to make a place for the residents of Rose Avenue to relocate. The plan was to move some of the houses and build some new houses. The second phase of the project included fixing the interior streets in the project area by putting in town sewers and town water and rehabbing some of the 75 commercial buildings in the area. According to the original plans, the project would be completed by 1973.

However, the project did not go without a hitch. By January 1971, the West Hartford Redevelopment agency had approved William E. and Beverly Curry of Hartford as the developers. The apartments, to be built on Hillcrest Avenue, were for moderate-income families. In March 1971, HUD eased its standards by allowing more one family apartments to be built than were normally allowed in federally funded housing. But by April 8, Curry still had not secured the $1 million bond that he had assured the town he could get. He had to be removed from the project and the town had to find a new developer.

A zoning battle and trouble with town administrators continued to slow down the project, but in December 1971 building began, and by the summer of 1972, residents moved in.

In 1973, Education/Instrucción Inc. (E/I), a Hartford civil rights action group, filed a complaint with the Connecticut Community Development Program, claiming that continued work on the Piper Brook Redevelopment Project violated civil rights laws and state statutes prohibiting state agencies from discrimination. E/I stated that the moneys were used “to insulate and isolate and retrench suburban growth from the problems of the core cities.”

Nothing substantive came of these claims, but it did alert area residents to the segregation in the cities and pushed local officials to think about whether they were meeting the established purposes of the federal money.

In 1975, infrastructure work continued. The Redevelopment Agency came back to the town for another $2.6 million to complete work on streets in the area.

By early 1977, the town bought the $2.3 million mortgage from HUD. George Cunningham criticized the move, arguing the town would never complete the project. The town hoped sale of remaining land would help them pay off the mortgage. Cunningham claimed that the cost of a parcel of land had tripled since the town took over the mortgage.

At this point, the town closed out the project, disbanded the Redevelopment Agency and the executive director was no longer an employee of the town.

Newspaper articles in 1977 alluded to a change in the federal government requirements for federal redevelopment monies. The feds combined Urban Renewal grants with others into the HUD Community Block Grant program. This program required the town to build 192 new units of low and moderate income housing in three years. The Republican led Town Council feared that the town was losing control over its own destiny under the federal program. Councilor Bob Farr spoke out most strongly against the federal mandate, according to the *Hartford Times*. He suggested building only 100 units for the elderly and rehabbing units in existence.

By 1977, the value of the 20 unsold parcels of land was half its 1970 value, but town officials were eager to sell it to get it back on the tax rolls. They hoped that because they bought the mortgage from the federal government that restrictions placed on the land by HUD could be eased, making purchase and development easier.

The Piper Brook Redevelopment project illustrates the often contentious relationship between federal, state and local governments, the clash between the interests of city and suburb, and residents and industries.

By 2001, almost 35 years after the first plans, the area is a bustling commercial and industrial district. The Piper Brook apartments are full and the new community center sponsored by federal and town money has helped build the community that would please George Cunningham.
