## Project Concern and Educational Opportunity {-}

*Originally appeared in West Hartford Life, June 2001*

> It is one thing to be ideologically committed to equality of educational opportunity as a right and not as a privilege. It is yet another to intelligently implement programs that will in fact insure the practice of this ideal.
> -- Charles Richter, Superintendent of West Hartford Public Schools, 1966

Before the first Hartford students boarded buses to West Hartford in 1966 as part of Project Concern, the town wrestled with what role it wanted to play in providing equal educational opportunity for all children. Strong leadership by West Hartford’s superintendent, and federal and state support helped Project Concern succeed in West Hartford - but not without a fight.

In 1960, West Hartford had a total of 25 students of color out of a school population of over 6,000 students, less than one percent of the population. The city of Hartford had many elementary schools with over 85 percent students of color and a large majority living in poverty. Just six years before, the Supreme Court decided that separate but equal schools by law (de jure) were inherently unequal. Some Hartford area residents decided that they needed to address the fact that separate schools by housing patterns (de facto) did not provide equal opportunity for all.

In 1964, Hartford area business, education and political leaders gathered in a meeting to support cross-town busing with the “Meeting of Tomorrow.” This group commissioned a study that became known as the Harvard Report. Junior high school students from Hartford’s north end, the report found, were one and a half years behind the national average in math and reading.

The Connecticut State Department of Education, supported by the Hartford Board of Education, wrote a grant to develop a voluntary interdistrict-busing program and called it Project Concern. They submitted the grant to the Office of Economic Opportunity under Title IV of the Civil Rights Act of 1964. By 1965, they hoped 300 Hartford students could participate in an attempt at educational and social integration, to promote educational equality of opportunity.

Some West Hartford residents wanted to participate in the program. On April 14, 1966, 1,200 people attended a public hearing at Conard High School and stayed for a seven hour meeting. The *West Hartford News* claimed that the meeting was “the most passionate meeting in West Hartford’s history.”

Many who opposed the bussing program came to the meeting. One West Hartford resident argued that equal educational opportunity was a right by contending that he had “worked hard for 40 years so he could have his kids educated in West Hartford. No one bused me here.” An African American teacher from Hartford reacted by saying “a Negro child does not belong in West Hartford” after she heard the racist attitudes at the meeting. A Hall High School student who spoke in favor of the bussing program was told to “go to Weaver” if he wanted an integrated school.

The issue of local autonomy loomed large in the view of the opposition. West Hartford residents used the umbrella term of “neighborhood schools” to “protect” their local district. They believed that busing was the first step to losing autonomy and jurisdiction through an interdistrict program. Others argued that black students would bring down the level of educational attainment for white students in the classroom. Equality of educational opportunity, they argued, would lower achievement levels for all.

But there were also strong advocates of the program. The pro-Project Concern Committee of New Education Opportunities was formed with both Christian and Jewish support. Rabbi Abraham Feldman, from Temple Beth Israel, a founder of the group, went to the public hearings and clearly expressed his support for the interdistrict-busing program for both educational and social reasons.

Superintendent of Schools Charlie Richter wholeheartedly supported the program. He believed that West Hartford should be a leader in the Hartford area because, he felt, it would improve the already excellent educational system here. He argued the day after the Board of Education made their decision, “If West Hartford can’t do it (Project Concern), then no one can.”

On April 18, 1966 just four days after the public hearing, the Board of Education voted to accept Project Concern “in principle.” West Hartford would not incur any cost for the program because Hartford footed the bill through federal and private grant monies. The Board of Education boldly accepted the challenge, and chose to start by integrating their 1966 summer school. But, West Hartford’s commitment was only to this short-term trial.

The state approached West Hartford, Manchester, Farmington and Glastonbury to participate in the program. West Hartford was the first town to agree to the educational experiment. Glastonbury refused to participate with the other three after a tie vote on the Board of Education denied their participation. South Windsor and Simsbury also became part of this original group.

But, the opposition was strong. By early June, West Hartford opponents gathered 4,287 signatures on a petition to make the Board’s policy null and void. However, their petition failed because it was illegal for the Town Council to stop a Board of Education decision. The opponents threatened to sue the board for their use of “excessive power.” This too failed.

On Tuesday, July 5, 1966, 250 Project Concern students entered West Hartford’s Summer School and it went very smoothly. Money from Title IV of the 1964 Civil Rights Act ($270,000) and the Ford Foundation ($50,000) helped fund the summer program. In August, the Board of Education voted to extend the bussing program to the regular school year with kindergarten through fifth grade students.

The State Department of Education got $470,000 from Title I and Title III of the Elementary and Secondary Education Act of 1965 to carry out the regular school year program. On September 4, 1966, 75 Hartford students entered West Hartford’s elementary schools, the most of any of the participating towns.

Extensive studies of the project continued into the 1970s and 1980s. Each of the studies documented the benefits for both the Hartford and West Hartford students. Though not every student chose to remain in the program, those who did showed increased academic achievement and increased social interactions. Parents of children in classrooms with Project Concern students became supporters of the program while those who had no direct contact often continued their opposition.

Rights and privileges are ideas constantly in conflict in a democracy. If equality of educational opportunity is a right, who carries it out and how is it done? When students have unequal abilities, unequal motivation, and unequal knowledge, can there be equal opportunity? These thorny issues are fraught with tensions and continue to be discussed in West Hartford today. The issue of neighborhood schools and local autonomy in light of the state Racial Balance Act continue to challenge the town to address whether equal educational opportunity is a right or a privilege. In 1966, both political, religious and educational leadership in town saw it as a right.
