## Women’s Rights {-}

*Originally appeared in West Hartford Life, March 2011*

In 1972, a married woman who wanted a library card could only get it in her husband’s name.

The *Hartford Courant* posted jobs as “Help wanted – male” and “Help wanted – female.”

And, even though the Civil Rights Act of 1964 stated that women could not be discriminated against in their work, women employed by the Town of West Hartford were stuck in secretarial and clerk jobs which gave them much lower pay than men.

Bob Farr, as chair of the Human Rights Commission, faced these issues when the commission held a hearing on equal rights for women in 1972. The Commission sent invitations to 22 women’s organizations in the Hartford area including NOW and town employees.

The Commission was originally established to address racial issues, but Farr argued in 1972, “There are few blacks in West Hartford,” and so saw few complaints brought to the commission. Farr hoped to find out if there was discrimination in making women administrators in the school system, town services, private industry, and in the provision of day care.

The hearing led to the commission investigating employment practices by the town that the Commission believed could discriminate against women.

At the public meeting, Christine Carpentier of 14 Richmond Road represented 120 female town employees. She offered town employment statistics, which showed women confined to clerical and secretarial positions. Only 5 of 30 principals and vice-principals were women and those were elementary school principals. She said that the library was the only exception for employment. She also noted the library card issue. Carpentier said that she and her women’s consciousness raising group compiled the statistics in less than 24 hours.

The commission voted to ask the library to change its requirement to allow women to be recognized as Miss or Mrs. Using their own name when applying for a card, and after some negotiation, they did.

Ann Bandazian, president of the Central Connecticut Chapter of NOW spoke, and commended the Commission on having the hearing. She asked that the Commission fight to “remove male and female qualifications from job descriptions, pay equal pay for equal jobs and eliminate marital status from job applications.” Bandazian went on to say that she believed the three most important issues for women in 1972 were the right to “free abortion on demand,” ending educational and employment discrimination, and universal, voluntary day care.

Anne Streeter, the President of the League of Women Voters was the third speaker. Streeter agreed with Bandazian about day care and employment, particularly in meaningful full time jobs. She also made a more subtle argument by saying “If you were to stop the average woman in a supermarket and ask her if she was being discriminated against, she would say no. She would say no until she went out and tried to get a good job. Discrimination is not always something overt. Discrimination can be something lacking, rather than something obviously done.”

But the case that drew the most attention was one brought by eight women hired in July 1971 to be fire and police dispatchers. The women claimed that they were paid less than the men they replaced, that they should be paid double on holidays, and that they had been harassed. Before they were hired, regular fire and police personnel were the dispatchers and received the pay of police and firefighters. The women believed they deserved the same pay. By 1973, their pay ranged between $6,700 and $7,900 while the firemen dispatchers had made from $9,600 to $11,500.

Within four months of employment in November 1971, the eight women complained to the state Commission on Human Rights and Opportunities.

The Town Council’s General Government and Finance Committee, chaired by Chuck Matties concluded, after meeting with the Fire and Police Chiefs, that there was no bias or harassment. Fire Chief Yaccavone claimed that the women were well aware of their working conditions before they took their jobs. Their salaries and benefits met those of dispatchers in other towns. Matties said that the job description was not listed as a “woman’s job.” Corporation Counsel Ed Hebb said he had found no evidence of the women being harassed.

The state Commission on Human Rights disagreed. Their field representative Frances Goodale believed that the there was “reasonable cause" to believe that West Hartford violated the state's Fair Employment Practices Act. Their salaries were about $2,400 less than those of the men who worked before them. Goodale believed the women could get $25,000 in back pay. Goodale said that in fact the job had been posted as a “woman’s job” and that the town needed to follow the FEPA.

Eleven days later, on October 20, the *Hartford Courant* reported that Corporation Counsel met with Goodale in a conciliatory conference, which lasted for 2 ½ hours, but did not reach any conclusion. The women kept up their fight and the next September got a hearing before a Human Rights Commission tribunal, a group of men selected by the Governor.

If the tribunal decided in the women’s favor, they could be awarded $48,000 in back wages. Town Manager Richard Custer claimed this would be a real hardship on the town because of the tight budget.

Almost a year later, the case was still not settled. In January 1974, the Human Rights Commission finally heard the case. The Commission ruled against the Town of West Hartford and ordered back pay for the female dispatchers. The Town then appealed the decision and Judge William Graham of the Hartford Court of Common Pleas ruled that the town’s hiring favored women and the change in pay was aimed at saving money. After that decision, the town estimated they had saved $175,000 in back pay. Final legal arguments were presented in April 1974.

The town argued they changed the job description to "operator" after town officials decided to eliminate the position of fire dispatcher. According to a June 13, 1974 *Hartford Courant* article, a 1970 study by the town of West Hartford showed that the town could save money by hiring civilians rather than firefighters to be dispatchers. The Town’s position was that the men who did the job were overpaid. The Town believed that the present dispatcher pay should be decided by collective bargaining.

The Supreme Court overturned the Court of Common Pleas’ ruling about back pay, though they agreed that the town discriminated against the women. But, they did not believe that the women should be given back pay.

The women ably challenged the town for their rights and made their point, but there would be no back pay. They won the moral battle, but got no remuneration for their win. Nan Streeter, who was Mayor from 1975 to 1979, remembered women being frustrated with their jobs and pay during that period of time, but as mayor, she also knew that low pay for women helped to balance the budget.

Employment for women has changed tremendously over the past 40 years. No longer are there separate listings for male and female, though the jobs of secretaries and clerks remain almost exclusively in female hands.

In 2011 West Hartford has a female superintendent of schools. Still, the five secondary school principals are men, with six women vice principals out of eleven. In the elementary schools, eight of the eleven have women principals and 11 of 12 elementary curriculum specialists and vice principals are female. These assumptions about who is fit for the job and thus what they are paid have strong roots in the town.
