## West Hartford and the Mississippi Freedom Summer {-}

*Originally appeared in West Hartford Life, June 2013*

> Bring the nation’s children, and the parents will have to focus on Mississippi, our thinking ran. And if the parents raised their voices, the political establishment would be forced to listen.
> -- Bob Moses, recounting Freedom Summer, 2001

In late June 1964, West Hartford’s Susan Gladstone, 20, a student at Pembroke College (now part of Brown University) went to Clarksdale, Mississippi as part of the Mississippi Freedom Summer Project to register African American voters, teach in a “Negro Freedom School,” and help build the Mississippi Freedom Democratic Party. A 1962 Conard High School graduate, she had joined the Northern Student Movement to register Mississippi voters. While in Clarksdale, she stayed with an African American family.

The Congress of Federated Organizations (SNCC, SCLC, and CORE) organized the Freedom Summer Project which recruited over 800 northern college students to work on voting and education. Leader Bob Moses believed that the students could bring much needed publicity and protection to the African Americans who were already doing this work in Mississippi. As white violence toward Blacks increased in 1964, organizers thought that the white workers could help their cause.

Susan Gladstone arrived in Clarksdale with The Project, and met Police Chief Ben Collins, who she described as a “vicious man.” By July 11th, 100 African Americans had tried to register to vote, but only one succeeded by passing the literacy test. The town administered literacy tests designed to stop blacks from qualifying to vote. The Confederate flag stickers adorned courthouses doors where voters registered and were given the literacy test. Chief Collins “ordered Negroes not to try” and ordered the students to leave Clarksdale, according to the *Hartford Courant*.

Back in West Hartford, Gladstone’s parents, Dr. and Mrs. James E. Gladstone, were not so reassured that their daughter was safe, and still they supported her civil rights work. James’s 2007 obituary describes him as devoted to “causes of underserved people and all forms of progressive politics.” But, like hundreds of student activists’ parents, they were concerned for her safety. From their point of view, they found it “hard to believe that sort of thing [stopping registration] can go on in the United States.”

In 1960, Mississippi and Connecticut were miles apart in terms of wealth and educational levels of residents. Mississippi held the distinction as the poorest state in the nation, and Connecticut as one of the wealthiest. In Mississippi, 86% of Black families lived below the national poverty line. Blacks made up only 5% of the registered voters, but comprised 45% of the state’s population. Whites argued that Blacks had no interest in voting. Blacks worried they would lose their job if they registered.

Before arriving in Mississippi, Gladstone traveled to Oxford, Ohio where she learned voter registration tactics, the history of Mississippi and the strategy of nonviolence. She trained with Andrew Goodman and Mickey Schwerner and then traveled south on June 20, 1964. The very next day, June 21, three Ku Klux Klansmen murdered organizers James Chaney, Goodman, and Schwerner. During that summer of 1964, more than 60 black churches, businesses, schools, and homes were bombed or burned.

Gladstone’s parents helped realize Moses’ idea that white students would bring with them concerned white parents and more press. Since 1960, at least 12 civil rights activists had been murdered, but news did not spread outside of Mississippi. When the white students arrived, as Moses predicted, the national journalists began to pay attention. The FBI sent hundreds of agents to the state, to investigate, but not protect these activists. Five FBI agents went to Clarksdale.

Susan’s sister Andi, who was 16 in 1964, remembered her parents receiving numerous phone calls from Clarksdale threatening that they would kill Susan for the work she was doing in Clarksdale. Andi remembered hearing her parents crying in the other room during Susan’s time in Mississippi. Gladstone’s parents and their daughter Andi, along with other students’ parents from the northeast, travelled to Washington D.C. on July 1 and 2 hoping to meet with President Lyndon Johnson, seeking more federal protection for their daughter and the other civil rights workers in Mississippi. They called themselves the Parents' Mississippi Emergency Committee and were joined by parents from New York, New Jersey, Massachusetts and Pennsylvania. The West Hartford Committee members also included Mrs. Roydon Berger (parent of Robert), Mrs. Paul Landerman (parent of Dick), and Mr. and Mrs. I.M. Chaikin (parents of Henry), all West Hartford parents of students working in Mississippi.

The parents quickly arranged the trip after the three civil rights workers went missing. On July 1, the parents met with U.S. Senator Thomas Dodd and Asst. Atty. Gen. John Doar (father of West Hartford Town Councillor Burke Doar) from the Civil Rights Division of the Justice Department. Doar did not suggest to the parents that their children return home. Doar said, “We all accept the fact that there is danger there, as did our sons and daughters when they set out. Asking anything like that would have let them down miserably. They have a very deep commitment to what they are doing.”

The movement continued. On July 2, 1964, Lyndon Johnson signed the Civil Rights Act, prohibiting discrimination in public places, providing for schools and other public accommodations to be integrated, and making it illegal to discriminate by race in employment. This Civil Rights Act, the first to be passed since Reconstruction, came after months of lobbying bolstered by the August 1963 March on Washington.

The students continued their work, but with much more media coverage and federal protection for the movement. Mississippi continued to fight the changes and Governor Paul Johnson urged “non-compliance [of the Civil Rights Act] until the whole gamut of the law is tested in the courts.” To fight the Governor’s power, student volunteers helped to establish the Mississippi Freedom Democratic Party (MFDP), which attempted to unseat the state's all-white regular delegation at the Democratic National Convention in Atlantic City. Although the Democratic Party ultimately seated Mississippi's regular delegation, the MFDP's bid for recognition raised awareness of voter discrimination in the Deep South and helped secure passage of the Voting Rights Act of 1965.

Andi Gladstone remembered going with her parents to Atlantic City in August 1964 to the Democratic Convention where the Mississippi Freedom Democratic Party tried to be seated. She remembers staying up all night at a vigil and being supported by an African American man named Bayard Rustin, the organizer of the 1963 March on Washington.

According to Andi, Susan was so moved by her work that she dropped out of Pembroke and stayed on in Clarksdale for at least another six months. She returned to West Hartford and then enrolled at the University of Wisconsin and graduated two years later.

After her graduation she went to Antioch University where she earned her teaching degree. She moved to Washington, D.C. to teach junior high school in the late 1960s where she met her husband Art Ellison. They moved to New Hampshire where she worked with battered women and then became a vocal AIDS activist before she died of that disease in 1992.

Even though, in the 1960’s, there were some residents in West Hartford who worked to keep African Americans out of town, simultaneously, West Hartford’s youth, supported by their families, became warriors for justice in a very dangerous time. Gladstone’s courage in taking the trip to Mississippi showed her what it meant to fight for justice, and the value that the right to vote held in this nation. Her presence in Mississippi helped push the civil rights agenda, and was a part of creating this nation’s history. Susan’s sister said that experience “made her rock solid in her beliefs” about justice.

Gladstone’s papers at the Wisconsin Historical Society include diaries, letters and an interview. Her name appears in two books on civil rights workers in Mississippi and in several *Hartford Courant* articles.
