## School Prayer in 1963 {-}

*Originally appeared in West Hartford Life, August 2013*

Fifty years ago, when West Hartford students were heading back to school, the United States Supreme Court forced local Boards of Education to change their policy on school prayer. The policy at the time of the Supreme Court ruling stated that schools daily opening exercise “shall” include the Lord’s Prayer and a Bible reading. At the time, West Hartford’s Public Schools had almost equal numbers of Protestants, Jews and Roman Catholics. So this subject led to some controversy. The Board of Education needed to change its policy to be in tune with the Supreme Court rulings, but it did not happen immediately.

In *Engel v. Vitale* (June 25, 1962) Justice Hugo Black wrote the decision (6-1) that a state written non-denominational prayer in New York abridged freedom of religion. Black argued that the prayer itself affirmed religion, making it unconstitutional.

In late August 1962, the Chair of the West Hartford Board of Education, Attorney Willis G. Parsons Jr., ruled that the children would continue to say the Lord’s Prayer in West Hartford Public Schools. He argued that “We do not believe that this opinion can be used as a blueprint to cover all school activity involving some degree of religious expression.” Parson’s confident pronouncement came from the town’s lawyers, Nick Lenge and John Berman. They believed that their ruling also allowed for invocations at assemblies, Bible reading and grace before meals.

In March 1963, the Supreme Court heard the *Abington School District v. Schempp* case in which Supreme Court Justice Tom Clark wrote the decision that prohibited state-sponsored prayer in schools. In the *Abington* case, (8-1) Clark prohibited all Bible readings and other government/school-sponsored religious activities in the school setting.

Clark’s controversial opinion, issued on June 17, 1963, read:

> The place of religion in our society is an exalted one, achieved through a long tradition of reliance on the home, the church and the inviolable citadel of the individual heart and mind. We have come to recognize through bitter experience that it is not within the power of government to invade that citadel, whether its purpose or effect be to aid or oppose, to advance or retard. In the relationship between man and religion, the state is firmly committed to a position of neutrality.

This ruling made it more clear that a daily prayer or Bible reading could not be done in school.

The Rev. Gordon T. Scoville, minister of West Hartford’s Westminster Presbyterian Church welcomed the decision for upholding separation of church and state. He affirmed, in the *Hartford Courant* that, “I don’t believe the decision in any way asks us to give up God.” Others in the state did not agree with him.

The State Commissioner of Education, William J. Sanders, sent a letter to superintendents explaining the significance of *Abington* to Connecticut public schools. He explained that boards of education could not open each school day with a required Bible reading or recitation of the Lord’s Prayer. He knew, though, that individual schools would determine religious practices in other areas of the school day. The *Hartford Courant* quoted superintendents from Barkhamsted, New Britain and Middletown saying that religious practices would continue as they were until someone complained.

With the *Abington* ruling, West Hartford’s Board Chair Parsons knew policy had to change. Immediately after the ruling, he thought that West Hartford might replace the prayer with a moment of silence. A week after the ruling, Superintendent Edmund H. Thorne reported to the Board on how the ruling affected the schools. But still by mid-August, the Board had not ruled on the issue. Thorne asked for the Board to suspend the rule because school would soon begin. As of August 15, nothing in the School Code about prayers or reading the Bible reflected the new Supreme Court ruling.

At the September 12 meeting, the Board of Education banned prayers or any other devotional exercises in the public schools during school hours. The vote was a divisive 4-3 with Chairman Parsons (R), Robert Thayer (D), Thomas Smith (D) and Charles Buck (R) voting for the ban. Dorothy McNulty (R), Robert Nichols (R) and William Mosehauser (R) did not vote for the ban. More than 80 people listened to the debate at King Philip School’s library.

The vote proceeded in three steps. First McNulty made a motion to change the school code to read that the salute to the flag will be held during opening exercises and the teacher may have a “moment of silent meditation.” Then the Board adopted the same wording for assemblies.

Democrat Thayer argued that these votes “placed the teacher in jeopardy,” by opening them up to “severe pressure” from parents and “noted that this has been done in other matters ‘many times’ by West Hartford parents.” Thayer argued that the Board was shirking its duties if it did not rule directly on the prayer issue. Thayer contended that the Supreme Court clearly defined a teacher’s religious role at school. He wanted a measure passed which said “no employee of the Town of West Hartford will conduct, or authorize students to conduct prayers on school premises.”

Superintendent Thorne questioned Thayer, asking if this ruling would bar a teacher from saying a prayer at a Hi-Y or Boy Scout meeting after school but in the school building. Thayer said that the ruling would do that. Chairman Parsons reminded the Superintendent that the Supreme Court ruled that any type of devotional service in the schools was against the law during school hours.

Thorne worried that the ruling would affect the Christmas programs in the schools and urged the board not to go any further than it had to. The Board voted down Thayer’s motion.

This decision to separate church and state did not sit well with many people in town. The *Hartford Courant* reporter ended his article noting several teachers left the meeting dissatisfied that “grace” before and after meals was among the prayers banned.

In 2002, in a post 9/11 context, the Connecticut General Assembly passed a law requiring that each town have a policy “to ensure that time is available each school day for students in the schools under its jurisdiction to recite the “Pledge of Allegiance.” The law cannot be construed as requiring any student to recite the Pledge, but the opportunity to say it has to be there. Does the “under God” portion of that pledge, added in 1954 as an anti-communist point, make this a type of prayer which injects religion into a government/school-sponsored activity? I wonder how Clark, Thorne, McNulty and Thayer would weigh in on this issue.
