## The Butterworths Fought for Equal Representation {-}

Originally appeared in West Hartford Life, November 2010

In 1948, when Miriam "Mims" Butterworth and Oliver Butterworth moved from Kent to West Hartford, they lost equal representation in the General Assembly. At that time, Kent, with 1,400 people had two representatives in the state legislature, and West Hartford with more 40,000 people also had two representatives.

The Butterworths had 28 times the representation in Kent as they had in West Hartford. In the next 14 years, they joined a class action lawsuit that changed representation in Connecticut under the Fourteenth Amendment's Equal Protection Clause.

Every 10 years, the U.S. government takes a census to reapportion the U.S. House of Representatives. However, even though population shifted, there was no state law that forced the state to redistrict for the General Assembly.

The House of Representatives was set up under the 1818 Constitution with two representatives per town and 12 senators were elected at large from the state.

Twenty-one Senate districts were first established in 1829 and increased to 24 in 1881.

The 1903 redistricting increased the senatorial districts to 35 and in 1941 a new district was added for Greenwich, making the 36 we have today. Connecticut's last reapportionment was in 1904 and that one continued the dominance of the rural towns.

The U.S. Supreme Court in *Baker v. Carr* (1962) decided that federal courts could intervene to decide how states would reapportion their representatives. Based on a suit brought by citizens of Tennessee, they argued that there should be a “one person, one vote” measure for redistricting.

This case on representation, according to Justice Earl Warren, was "the most vital decision” during his career on the court, and the apportionment revolution which followed, he believed, was his most important achievement as Chief Justice. His ruling changed the way reapportionment was done from being decided politically by legislatures to allowing federal courts to decide the cases. The ruling in *Baker v. Carr* effectively ended the over-representation of rural areas (like Kent) in state legislatures and increased representation in suburbs like West Hartford.

Central cities like Hartford had been under-represented, but by the 1960s were losing population to the suburbs and so their representation did not change much. Right after the *Baker* decision, 36 states began reapportionment battles.

In Connecticut, talk turned quickly to reapportionment. The Republicans had a plan and the Democrats had a plan. Both parties knew the facts: 12 percent of the people elected the members of the House of Representatives in Connecticut.

Both parties agreed that the 36-person state Senate did not fairly represent the population. However they disagreed on what should happen to the 294-member House. Democrats argued for a unicameral legislature based on population. The Republican plan would make just nine percent of people elect the General Assembly and would give them additional state senators. However, the legislature could not agree, so the decision came to the Courts.

The Butterworth's involvement in the case came through their connection to the League of Women Voters of Connecticut, which supported this suit. The League, a non-partisan political organization whose purpose it is to encourage active participation in government and fair elections, saw the apportionment issue as important enough to fund the lawsuit and to get plaintiffs to be part of the class action.

Mims Butterworth was a member of the League.

Ten people from six different towns joined this class action lawsuit filed in 1962. S. Rains Wallace from West Hartford's 5th Senatorial District joined Oliver and Mims Butterworth.

Two men from Manchester, one from East Hartford, two from Fairfield, one from Bridgeport and one from Hartford made up the group of 10 who believed they were not represented fairly according to the Fourteenth Amendment. Mims Butterworth became the only female plaintiff in the case, even though the League of Women Voters was a driving force behind it.

Rains Wallace was married to a woman who, in 1956, was elected president of West Hartford's League of Women Voters. He was a psychology lecturer at Yale and an active community member, heading up a drive for the symphony and as chairman for the Greater Hartford Community Chest. His wife later served as president of the Connecticut League of Women Voters and in the late 1960s was head of the Overseas Education Fund of the league.

Oliver Butterworth was an author of children's books including *The Enormous Egg* (1956) and *The Trouble with Jenny's Ear* (1960) and a professor of English at Hartford College for Women. Mims Butterworth taught history at the Chaffee School and was active in the community.

They claimed their voting rights "were being invidiously discriminated against” by the present apportionment of representatives, according to a *Hartford Courant* article from February 12, 1964.

In a phone interview with Mims Butterworth, she remembered the case well. The plaintiffs were represented by Donald F. Keefe of Gumbart, Corbin, Tyler & Cooper in New Haven. Ralph Shulansky of Shulansky & Cohn in Hartford and the late West Hartford resident Ralph G. Elliot of Alcorn, Bakewell & Smith of Hartford wrote the brief.

They sued Gov. John Dempsey, Secretary of the State Ella Grasso, as well as the state Treasurer and Comptroller. Grasso's daughter was a sophomore at Chaffee in 1963 and approached Butterworth. Grasso said "I hear you are suing my mother." Butterworth said yes. Grasso continued, “well, I hope there will be something left for Christmas," thinking that Butterworth was suing Grasso for all her worldly goods.

Butterworth remembered the case being tried by the lawyers, but without the plaintiffs present. The lawyers argued at the U.S. District Court in New Haven and she and her husband wanted to sit in.

They finally had a chance to go to the courtroom and found the proceedings fascinating. At lunchtime she remembered being taken out to lunch by the lawyers at a private club. Only men could go in the front door; she had to enter through the back door. But that was a fight for another day.

The three-judge panel found in favor of Butterworth et al. in a 2-1 decision. They argued that their Fourteenth Amendment rights had been violated. The court found that both houses of the General Assembly had to be redistricted and ordered the legislature to redraw its district boundaries.

It also ordered the state to create a constitutional convention to rewrite the State Constitution to require redistricting every 10 years after the federal census. The court ordered that the legislature elected in 1963 serve until its successor took office in 1967 after the redistricting was completed, calling off the 1964 elections.

The state appealed the case to the U.S. Supreme Court, which affirmed the decision of the three-judge panel. In 1965, the state called a constitutional convention, the first since 1818.

According to Mims Butterworth, people rose to the occasion on both sides. She recalled that those who attended remembered it as being "the most satisfying political action they ever took."

In 2011, the state once again begin the process of redistricting to insure equal representation in our democracy.
