## West Hartford Education Association at 50 {-}

*November 2015*

On November 10, 1965, 539 out of 660 West Hartford teachers voted for the West Hartford Education Association be the sole representative for West Hartford public school teachers. This gave the association the power to negotiate contracts with the West Hartford Board of Education. At that moment, the “Association” became a union with the ability to collectively bargain with the Board of Education. Though an affiliate of the American Federation of Teachers existed in West Hartford, they did not challenge the WHEA in this election.

Before the Association had the legal standing as a union, the Superintendent, Charles Richter met with each teacher individually and had them sign their contract as an individual. Teachers had no say in working conditions, and no protections of their rights.

For instance, in the 1960s, a woman who was pregnant had to quit teaching when she “showed.” And, the Board of Education made a rule that upon turning 65, a teacher had to retire. Teachers found the “merit pay” idea unfair as the award of the extra $400 per year seemed to be based on loyalty to the administration.

The Association’s power came through public persuasion and bringing lawsuits against the Board of Education as in the 1963 Herzig case. Fred Herzig, a teacher at Conard High School was forced to retire when he reached the age of 65. The courts found that he had the right to remain teaching.

There was much upheaval in the West Hartford Public Schools in the 1960s in a time of rapid growth in the system. The Board of Education forced Superintendent Ed Thorne to retire after 16 years in the job in 1963. In 1964, the Board hired Charles O. Richter to replace Thorne. Richter came with the reputation of being innovative, full of energy, and by many accounts very strong willed and overbearing. He and the Board of Education believed they should have sole decision making ability over contracts and working conditions. This set the scene for a four year battle to get a written contract.

The vote for collective bargaining was long in the making. The WHEA began in 1928 as the West Hartford Teachers’ Association, an association of professionals. Soon thereafter, in 1935, the National Labor Relations Act, also known as the Wagner Act became the law of the land, allowing workers in the private sector to collectively bargain. It was not until 1962 when John F. Kennedy signed Executive Order 10998, that federal public employees earned the right to collectively bargain. Connecticut’s Legislature passed Public Law 10-153 in 1965 giving teachers the right to join and elect an organization and then establish a bargaining unit in negotiations with their board of education.

In 1965, West Hartford teachers did just that. But just having the Association represent them was only the start. The WHEA leadership then began to bargain for a written contract. It took four years, a lawsuit, a proposed slow-down by the teachers, hundreds of hours of negotiations, and mediators and arbitrators to negotiate a written contract.

Attempts for a written contract started in earnest a year after the vote, when in November 1966, Representative Council voted unanimously to seek a written contract. Supt. Richter wrote to WHEA President Janice Falcon, stating his support.

Richter was a tough cookie. Falcon could match him. She was elected president three times and she got the first written contract. In 2015 she was still alive but not willing to be interviewed at age 94, though we did have one phone conversation. She seemed like the leader the teachers needed at that moment.

Teachers wanted to negotiate working conditions, grievance procedures and insurance, as well as salaries. But 1966 proved to be a year full of contentious issues for the Board and the Superintendent. School busing from Hartford --- Project Concern --- began in summer school that year, voters turned down a referendum to build a new Hall High, and the union helped Wolcott teachers voice their grievances about an overbearing principal.

Negotiations hit an impasse because Superintendent Richter wanted to retain the power to be the final arbiter of all grievances. In May 1967, the Board of Education chair Edward Mosehauer said “I’m willing to negotiate with them, but the Board of Education runs this school system and that is not going to change.”

By June, 1967, no agreements had been reached about a written contract, and the WHEA encouraged teachers not to sign their individual contracts. 400 teachers refused to sign. By October 1967, the *Hartford Courant* reported that the contract talks had ended in failure after a 15 hour mediation session and the negotiation would go to arbitration.

WHEA President Falkin asked both the Connecticut Education Association and the National Education Association to investigate the contract impasse over working conditions, accumulated sick days, release time for the WHEA President, and grievance procedures. Salary schedules had already been agreed to. The CEA report, released in January 1968 claimed that a tough administration caused unrest among the staff.

Very quickly, arbitration hit a snag. The Board of Education chose Willis Parsons to be their arbitrator. He was the Board of Education chair until 1965 and then became Superintendent Richter’s personal attorney. The WHEA brought suit against the Board and won in February 1968, with the court arguing that Parsons could not be impartial. With a win under their belt, but still no contract, the WHEA and the Board of Education attempted to negotiate once more.

In the summer of 1968, teachers voted again not to sign their salary agreements. The WHEA came up with a set of issues on which they would “slow down” for the two days at the end of school after students finished to try to pressure the Board. In return, the Board of Education threatened to withhold half of their June salaries if they participated in the “3 day boycott.” The Board did not issue paychecks on June 15.

That same day, the state education commissioner stepped in and helped the two sides reach an agreement. The teachers called off their slowdown.

On July 3, 1968 the teachers signed their first written contract for one year. It took 17 months to negotiate.

But, the troubled relationships between the union and the Board and Superintendent did not end here. In 1969, the Board of Education chose to test the new Teacher Negotiation Act passed by the state legislature in 1969. This new law forced Boards of Education to negotiate on many more working conditions. The WHEA wanted to negotiate a contract with the Board of Education for both teachers and administrators. Even though they had settled the salaries, the negotiations went to arbitration and a three man arbitration panel came up with a package. After 22 failed negotiation sessions, and failed mediation, the Board, led by chair John Hand Conard, rejected the proposal. New WHEA President Dick Blaisdell said the Board was running roughshod over the teachers.

Even into October, the Board of Education, and John Hand Conard, tried to keep total control over working conditions and keep salaries at what they considered to be a reasonable level. But the new law made it necessary for the Board to negotiate all areas of teachers’ employment. June 27 was an all-day mediation at the state office of education.

At year’s end, the two sides had still not agreed on the contract. And into 1970, Richter continued to hold on to his belief that he could unilaterally decide on working conditions. The WHEA responded by printing a Superintendent’s report card in the *Hartford Courant* in April 1970, giving him six “F’s”.

It wasn’t until September, when the teachers were already back at school until both sides agreed to a new contract, 15 months after negotiating started.

Many factors contributed to their first contracts, one of the most important being the role of the federal government in allowing public employees to collectively bargain, and then the Connecticut State Law which allowed for the bargaining of working conditions as well as pay.

The union’s solidarity, their willingness to stand up to the power of the Board of Education, and their superintendent who at the least would be called headstrong, gave union members the role models to stand up for what is fair.

The union leadership was brazen and forceful in standing up for teachers’ rights. The binding arbitration law of 1979 changed these long drawn out negotiations and some in administration realized that in fact the union makes the school system even stronger. And yet unions continue to be under attack. The Supreme Court will hear a case in 2016 called *Fredericks v. California* that will allow employees to not have an agency fee. Teachers only have these rights if they continue to fight for them.
