## Moral Voices in West Hartford {-}

*Originally appeared in West Hartford Life, September 2007*

In 1966, West Hartford embarked on a path to offer educational opportunity to Hartford students by participating in Project Concern. The moral voice that emanated from the faith community provided a moral voice for policy makers in town as it helped to galvanize the community.

The impact the religious community had on public policy in West Hartford has varied over the years. When the town was founded in the early 18th century, the church and the government were one and not until 1818 did the state government separate the Congregational Church from its public role by disestablishing the church. In West Hartford, until the 1850s, there was one church in town –- the First Congregational Church. And, for the first 100 years of our history as a town, that church continued to hold a privileged place. In the early 1950s, with over 5,000 members, it was named one of the 10 most influential and successful churches in the country.

In the spring of 1966, just nine years after the integration of Central High School in Little Rock, West Hartford’s Board of Education voted to participate in the busing of 75 elementary age Hartford students to West Hartford. Manchester, Farmington, South Windsor and Simsbury joined the group. Project Concern was the first program of its kind in the country and was financed by national, state and Hartford funds.

On April 1, 1966, a committee of 50 formed the West Hartford Committee for Educational Opportunity to “draw to this cause as many as will come from the ranks of the thinking citizens of West Hartford... people who are willing to take a first step in the direction of providing equal educational opportunities for all children, regardless of color.” Rabbi Abraham Feldman and several ministers founded the group.

This in turn was followed by a vote of the executive board of the Webster Hill School’s Parent Teacher Organization to hold a referendum on the busing on April 6. The Web Hill community expressed concern that West Hartford would not be able to “maintain our educational standards” if Hartford students were bussed here. However, the law did not allow for a referendum.

In the first week of April, The Reverend John P. Webster, pastor of the First Church of Christ Congregational sent out letters to his congregation urging them to “get the facts” on the busing program. He strongly supported Project Concern and encouraged his parishioners to go to a public hearing and write a letter to Superintendent of Schools Charlie Richter to express their support for the project. In his letter, he quoted Rabbi Feldman, the convener of the West Hartford clergy group, that the whole program could “be dismissed or rejected unless there is some effective public opinion imparted to the Board of Education and the superintendent.”

Webster went on to write, “Ironically, someone said that there would be no word from the synagogues or churches on this matter because their people are involved with Passover and Easter. The Passover celebrates the sparing of an oppressed people for their escape from bondage. Easter celebrates the triumphant victory of Jesus Christ and His way over the forces of destruction and death.”

On April 15, Rev. Kingsland Van Winkle of the Trinity Episcopal Church, Hartford sent letters to his West Hartford parishioners urging them to support the regional desegregation plan by calling Board of Education members and the superintendent of schools. He argued that this project was a “very small but extremely significant attempt to achieve the sense of oneness which all of us feel is so essential to metropolitan living.”

On that same night, Rabbi Feldman spoke at a public hearing at Conard in front of 1,200 townspeople. He was booed, hissed, and catcalled. Someone shouted, “Take your congregation and go home.” At the end of his talk, the audience rose in a standing ovation amid boos from some audience members.

On April 18, the *Hartford Courant* reported that West Hartford church leaders used their pulpits to sharply criticize the behavior of some town residents at the public hearing at Conard.

The Roman Catholic clergy made a joint statement deploring “the vicious display of intemperate and abusive bigotry by some of our fellow citizens... That any minister of religion should have been booed and hissed here in West Hartford after expressing his convictions on this issue violates every norm of common courtesy, shamefully disgraces our entire community and makes a mockery of Christian charity.”

Rev. Wallace Grant Fiske, minister of the Universalist Church read an “open letter” to Rabbi Feldman, praising him for his public stance and denouncing the crowd. Fiske praised Feldman for his “mature, constructive leadership...”

As a reaction to the controversy, “stand-by mothers” organized to offer themselves as neighbors to the north end families involved in the busing program. Mrs. Alice Doyle and Mrs. Charlotte Kitowski led the group and sent a letter to the north end churches. Already, 32 families signed up to act as neighbors who could help out in case of emergency or illness in an attempt “to work together, to open up one more opportunity for our children, so that when they grow up, they won’t feel so apart.”

Just one week after the tumultuous meeting at Conard, 30 people went to a “Meeting of Concern” at the Elmwood Community Church to discuss the effects of the busing program. Ministers, representatives of the West Hartford public schools, the Hartford Board of Education, teachers, students, and citizens of the town attended. Hartford Board of Education member Dr. Lewis Fox told the group, “Something wonderful has happened in West Hartford. The one organized force in town was the combined churches and synagogues...”

The ideals of the clergy won the day as Hartford students attended summer school that summer and then 75 took the buses on September 7, 1966 to West Hartford schools.

The opponents of school integration continued to show their disapproval. On December 16, the publisher of the *Hartford Times*, who lived on Whetten Road, woke up to find a glass bottle filled with rags dipped in gasoline thrown through a window in his house. This followed a similar incident with Hartford’s Mayor George Kinsella and came after the Hartford Human Relations Commission received an anonymous note in which threats were made to those perceived to be supporting school integration.

The 2007 Supreme Court ruling in *McFarland v. Jefferson County Public Schools* rejected the use of a student's race in student assignment plans. This comes at a time when segregation rates for students of color are on the rise. West Hartford is a case in point. In 2007, the elementary schools are more segregated than they have ever been.

What role do political and religious leaders play on this issue today? On September 4, 2007, about 75 Hartford students enrolled in Project Choice came to school in West Hartford. Is the sentiment in 2007 more like that of the clergy in 1966 or the Webster Hill PTO in 1966?
