## Racial Unrest at Talcott Junior High, 1975 {-}

*Originally appeared in West Hartford Life, May 2010*

On Monday, October 13, 1975 at a Talcott Junior High school fair, a white youth “bumped” an African American student, and told the student to move out of the way. The black student retaliated by throwing an acorn at the white student who made a threatening move. The altercation escalated as the two boys had a fistfight and the African American youth’s cousin, a participant in Project Concern busing program from Hartford, joined in. A teacher broke up the fight.

The next day, white students harassed African American students both on the way to school and within the school. Talcott Junior High Principal Michael Stephanian called police in on Tuesday and Wednesday to protect students.

On Wednesday, as a group of African American youths walked east on New Britain Avenue toward their homes on Piper Brook, white youths taunted them from across the street. Police on the spot interrupted the incident and dispersed the two groups.

African American students at Talcott were from both West Hartford and Hartford. By 1975, Hartford students in the Project Concern program, which began in 1966 with elementary school students, attended junior high and high schools. The housing known as the Piper Brook Apartments, developed through federal money as affordable housing, opened in 1972 and many African American families moved to these apartments. By October 1975, Talcott had 601 students and 35 were African Americans, about 6% of the school’s population.

In a meeting covered by a *Hartford Courant* reporter on Thursday, October 16, at Mr. and Mrs. Louis Thuilard’s home at 125 Hillcrest Avenue, the African American parents contended that their children were afraid and felt it necessary to carry weapons to protect themselves from the white students, some of whom were from Conard High. Some parents decided not to send their children to school on that day, fearing for their safety. Det. Kenneth O’Brien from the police youth services division, Patrolman Arnold Bockus, Human Rights Commission member Reverend David Kern, and Pearl Dash of the Department of Children and Youth Services, and the NAACP attended the meeting.

A spokeswoman for the African American parents, Mrs. Louis Thuilard, asserted that school officials had not responded as quickly or as positively as they might have. Parents perceived that racial tension was “mushrooming,” and they believed that administrators were not doing enough to curb the tension.

Principal Michael Stephanian believed that the incident had been blown out of proportion, claiming that the disturbance was just a problem between two individuals, not a symbol of larger racial problems in the school. He became heated when pressed and further claimed, “The eruption of this problem in light of our past history is staggering.” He said that parents had not notified him and that his staff was trained to be sensitive to problems at the school.

Conard Principal Doug Christie, brought together the Conard students involved in the scuffle to discuss their issues and believed he had opened up a dialogue between the students.

While Principal Stephanian downplayed the incident, African American parents kept their children home on Thursday and Friday, October 16 and 17.

In a meeting at Talcott Junior High, the next day, about a dozen African American parents demanded that their children from Piper Brook Apartments, be bused to Talcott until fears about racial tension subsided.

The meeting, held in a classroom at the school, led to still another meeting on October 21 when town officials said they would answer the question about bus transportation. Those present at the meeting showed how seriously the town administration took the incident. Supt. Paul Burch, Board of Education Chair Elizabeth Stevens, Principal Michael Stephanian, Conard Principal Doug Christie, and several Town Council members attended. From outside of the school system came Rev. David Kern from West Hartford’s Human Rights Commission, Pearl Dash, Rick Lanz, a representative of the Bridge, a spokesman from Education/Instrucción (a Hartford Civil rights group), and Det. Kenneth O’Brien. Those parents who attended the meeting asked for:

- Recognition that communication between the school and town officials had to improve.
- The administration to see the incident as more than that between two individuals; town officials needed to consider its attitudes toward the needs of “the town’s minority residents.”
- The NAACP to follow the matter.
- School officials to hire a permanent employee who would be a “visible black with some responsibility” to act as a minority children’s advocate in the schools.

Louis Thuilard from Piper Brook contacted the Human Rights Commission and considered filing a complaint against the town for denying his children an equal education.

While the meeting was going on, the situation at the school seemed calm. At dismissal, uniformed and plainclothes police officers hovered in the school parking lot and adjoining areas to watch for trouble.

African American parents vowed to keep their students home on Monday, October 20 and Tuesday October 21 as well. The Police Chief, Francis G. Reynolds, pledged that the police would be at the school to ensure the safety of their children, but the parents did not believe their children would be safe.

On October 21, parents decided to send their students back to school on Wednesday, October 22, ending a four-day walkout when school officials promised bus service for a month to and from Hillcrest Avenue for the 40 students, both black and white, who lived east of the railroad underpass. Thuilard supported the move, saying he was “encouraged” at this “first step” to deal with the racial tension at Talcott.

Parents and school administration both realized that establishing the bus route was a first step. Thuillard pledged that he and other parents would talk to school officials about “long range solutions. I’m hopeful and encouraged,” he said, that “we’ll get as much participation from white parents as possible.”

Superintendent Paul Burch pledged bus service for one month and then a reassessment after a new Board of Education took office in November.

At the same time, Ida McKenney, West Hartford resident and a Human Rights Commission member, blasted the Commission for their lack of response to the “Talcott issue.” She believed that proactive attempts to integrate could have stopped the physical harassment before it started. She asked the Commission to investigate problems at Talcott in September and they refused to put it on their agenda.

When West Hartford’s population became more diverse in the 1970s, students forced town officials, educators, and parents to react. In 2010, with an achievement gap that belies the ability of African American and Hispanic students, perhaps an African American or Hispanic student advocate, like parents demanded 35 years ago, would help students negotiate their environment in a more effective way.
