## Save Our Reservoir: The Fight to Stop I-291 {-}

*January 2018*

The 1950s and 1960s were a time of intense highway planning and development across the U.S. West Hartford was no exception. Have you ever noticed the four-level stack of highway exits and entrances on I-84 that lead to nowhere near the Route 9 entrance by West Farms Mall? The federal and state governments built this stack, from 1969 to 1973, to connect to highway I-291, planned to encircle the city of Hartford. It’s a highway to nowhere because a group of citizens, led by Charlotte Kitowski fought this highway project. This group, the Committee to Save the Reservoir (CSR) is a textbook example of citizen advocacy.

In 1957, the federal government began to design and build highways around cities to reduce congestion. The I-291 route was to be 27 miles long, running from Rocky Hill around to Windsor, going through West Hartford to Simsbury Road (Route 185) with an interchange at North Main Street (Route 218), One of the motivations for this particular highway was the arrival in 1957 of Connecticut General Insurance Company in Bloomfield --- right near the proposed interchange.

![Looking north from a point in Farmington, the “stack to nowhere” shows the beginnings of the connector to Route 291, a circular highway that was never built through the MDC Reservoir. Note the monastery, and the Buena Vista development. You can also see Veteran’s Memorial Skating Rink on Cornerstone Drive. Soource: Noah Webster House & West Hartford Historical Society.](images/11-highway.jpg)

In 1959, the state’s Department of Transportation received funding to plan this connector between I-84 and I-91. At the time, the government projected that West Hartford would grow by 40,000 people to 100,000 by the year 2000 and that these people would need a limited access highway to move people around the region more quickly. Kitowski and CSR, did not see moving people faster as a sign of progress. And they took the chance to make their case against this highway expansion.

The Federal Highway Act of 1956 required officials to get citizen input from those affected by new highways, through public hearings. The goal was to get input to understand “the overall ecological balance in communities and their capacity to absorb disruption” before building the highways. In June 1960, West Hartford citizens attended the first hearing for this highway at Duffy School. Legislators argued that the interstate should go through the MDC Reservoir instead of the route through neighborhoods where they would have to tear down many houses.

Charlotte Kitowski (1923-2005) spearheaded the fight to stop this highway. A nurse by profession, she became a dedicated environmentalist in the battle to stop Route 291’s path through the Greater Hartford Metropolitan Water System. And she had the experience and skills to win the fight.

She and her husband moved to West Hartford in 1950 and raised three children at 50 Arnoldale Road. In the 1950s, she worked with others in town to oppose Senator Joseph McCarthy and the House Un-American Activities Committee as they tried to root out dissent during the Cold War. In September 1963, just three weeks after the March on Washington, the Connecticut Council of Churches asked her to sit on a strategy committee to address “race problems” to improve the lives of African Americans in the state in terms of housing, jobs, and history textbooks (She was the only woman on this committee). She expressed her ideals around community engagement like this: “People say there’s nothing you can do. I’ve just never had that feeling... Challenging the government is the way the government works!”

In 1969, Kitowski helped organize the community to challenge the new highway plan. A high school student drafted a petition to stop the highway and circulated it at Conard, Hall, Plant Jr. High, the West Hartford Academy and Hartford College for Women. Kitowski engaged with and supported these students. The actions of the high school students and Kitowski’s organizing experience led to the formation of the Committee to Save the Reservoir (CSR)

CSR organized its first event, the Reservoir Ramble, on May 25, 1969. About 140 citizens attended this rally at the MDC Reservoir on Farmington Avenue. The event garnered some press and more activists to circulate petitions against the highway. In nine days they had 6,700 signatures on their petition. They delivered the petition which grew to 10,000 signatures to Democratic Governor John Dempsey. The petitions and a resolution from Town Councillor Robert Krechevsky led to a State Highway Department public hearing on September 25, 1969.

Over 1,100 people attended the public hearing at Hall High (the present Town Hall in the center of town). Students sang a song entitled “Spirit of the Reservoir” from the school steps as townspeople walked into the hearing.

At the meeting, the Department of Transportation outlined the route of the highway which would be 100 feet from Reservoir 6 and less than 100 feet from Reservoir 2. Health Commissioner Dr. Franklin Foote objected to the route because of the negative effects of lead and chlorine in the water. He argued that the highway should be at least ¼ mile away from any water to reduce the risk of pollution. A biochemistry expert from Washington, D.C. and a professor from Dartmouth School of Medicine both spoke against the highway stating health risks to the water supply. The DOT summarily dismissed Health Department warnings.

The Republican mayor of Bloomfield, Lew Rome, testified that both the Bloomfield Town Council and Bloomfield Planning and Zoning Commission wanted the new highway. He urged West Hartford officials to join those in Bloomfield in support of the highway. This was unpopular with many of Bloomfield citizens, particularly environmentalists. Six weeks after the Mayor’s testimony, in the November election, six of the seven Bloomfield council members did not run for reelection and Democrats won control. They quickly voted to withdraw the town’s support for I-291.

After the hearing, Governor Dempsey asked Commissioner of DOT, George Conkling to address the issue of the highway through the reservoir. Conkling had no written statement of policy from the Health Department about the projected route. CSR hired an outside group to do an independent study of the area.

At this point, Kitowski felt the best path was to bypass Connecticut DOT and go straight to the federal government. She urged people to write to the U.S. Secretary of Transportation, John Volpe. And, CSR continued its letter writing campaign and petitions to state, local and MDC officials.

On the first Earth Day, in April 1970, CSR organized a bus tour through West Hartford; more than half of those on the tour were under 18. The buses, donated by the Connecticut Co. took riders on an ecological tour of town including where the state planned to build I-291.

In September 1970, a hearing in Bloomfield drew Kitowski and CSR and 400 Bloomfield residents. In October 1970, the Federal Bureau of Public Roads, to which CSR had written, suspended the design on the Bloomfield section of I-291 in response to claims made by the U.S. Deputy Under Secretary of Transportation John Olsson after he visited the site.

After this suspension, CSR felt good! In fact, the federal government declared that the next Connecticut governor had the power to cancel the plans to build the highway, no matter what happened at the federal level. So, the power shifted from DOT to the Governor’s race between First District Congressman Emilio Daddario (D) and Sixth District Congressman Thomas Meskill.

In November 1970, state voters elected former Bloomfield Mayor Thomas J. Meskill for Governor. Right away, Meskill tried to get a route further to the west, outside the reservoir, but that made the ring road too long and beyond what the federal government would subsidize. Meskill played both sides of the issue by supporting building I-291, all the time knowing that the federal government would not pay for this longer route.

This win put pressure on West Hartford’s electeds to fight the interstate. West Hartford’s Democratic State Senator Jay Jackson helped pass Senate Bill 291 (yes, that WAS the bill number!) to stop the highway. CSR continued the pressure with a letter writing campaign to the Governor to sign the bill. Governor Meskill vetoed the bill in May 1971 on the grounds that he did not have the authority to stop the highway.

After the veto, Kitowski got citizens from Bloomfield and Windsor to join together with her West Hartford advocates against I-291. With local citizens and state legislators organized against the highway, even the veto was not stopping them.

In September 1971, Governor Meskill promised to keep the highway out of the Reservoir. CSR circulated 11,000 fliers reminding the Governor of his promise. And, they broadened the campaign to include all 386,000 people who used MDC water. This was a regional problem

On September 25, 500 cyclists rode to the reservoir and gave speeches against the highway, calling their protest a “bike strike.”

Kitowski quickly accessed the new federal Environmental Protection Agency, established on December 2, 1970, to get their support in this attempt to save our water. In September 1971, the new Commissioner of the EPA, William Ruckelshaus officially supported the position of CSR.

In June 1972, CSR submitted a report to DOT with scientific experts voicing their concerns with the proximity of 291 to the water supply in the reservoirs. By federal law, DOT had to review the group’s report and submit an environmental impact statement to the federal government for approval.

CSR retained lawyers who filed suit against DOT stating it ignored Section 4 (F) of the 1966 Dept of Transportation Act which required DOT to say that there were no feasible and prudent alternatives to the use of parklands. The suit claimed that DOT did not look at alternatives to the interstate highway such as mass transit.

In August 1972, Kitowski and three CSR members traveled to Washington, D.C. to get national support for their fight. Kitowski presented a 300 page report by environmental experts to the Interior Department refuting the claims of Connecticut DOT. Federal transportation and environmental departments showed surprise at the amount of opposition to the 291 route, and requested more information. Possibly because of the previous state focus, the federal government did not even have accurate maps or information regarding the proposed route. The Department of the Interior said that DOT had to study the route again. Interior required DOT to hold another hearing back in Connecticut.

The third public hearing, in October 1972 at the old Hall Conference Center, drew 1,000 citizens. The Department of the Interior supported the route. The other three federal agencies did not. Republican Mayor Ellsworth Grant, the first speaker, reminded the DOT officials that he and the WH Town Council had passed resolutions opposing the highway three times and had authorized the Corporation Counsel to bring an injunction against the DOT to stop the construction. Officials made clear that federal law stipulated that if public land is to be used in development HUD, EPA, Interior and Agriculture have to be informed. CSR sent the transcripts, full of data on the threats to the area’s water supply, to Secretary of Transportation John Volpe.

With continued pressure to stop the highway, Gov. Meskill killed the plans on August 2, 1973, three days after his Transportation Commissioner, who supported the route, resigned. Tied to Meskill’s change of heart on the highway was a change in federal government regulations, allowing the state to shift the 90% reimbursement funds for this highway to other projects. The Capitol Region Council of Governments (CRCOG) then dispersed the money.

In December 1974, the EPA honored Kitowski with its Environmental Achievement Award, the highest honor given by the EPA’s regional office. The regional EPA Administrator said her “actions have proved that responsible public participation can be the keystone of our environmental efforts.” Kitowski had willingly taken on the leadership of a citizen advocacy group, coordinating the campaign by using local government, public hearings, the courts, scientific studies, and the nascent environmental movement to successfully fight state and national government.

As a biker, advocate and historian, one of my favorite stories happened in 1972 when DOT Commissioner Wood criticized Kitowski for driving her car on Interstate I-84 to get to a meeting at his office. He insinuated that we all need these highways, even Kitowski! At the next meeting, Kitowski rode her bike, and carried it right into Wood’s office, proclaiming there were not provisions for locking it up outside. The *Hartford Courant* documented her commute with two photos in the morning paper.
