## Recycling {-}

*Originally appeared in West Hartford Life, April 2011*

On January 27, 1971 Republican Deputy Mayor Arthur Fay proposed stricter controls on dumping in West Hartford. Since November 1957, West Hartford had incinerated about 60,000 tons of solid waste per year, about one ton per person per year, and about 4 pounds per day. By 1971, the town government knew that the landfill was almost full and the incinerator would need to be replaced.

Fay’s proposed town ordinance would require residents to separate newspaper from trash for recycling and would assess businesses a $5 dumping fee.

The idea for the ordinance came out of a proposal to build a new regional incinerator for West Hartford, Newington, Rocky Hill, and Newington at a cost of $27 million. Fay believed this new incinerator could be delayed for 10 to 15 years, by implementing a paper-recycling program. At the time, 46% of the town’s waste came from corrugated boxes, magazines, newspapers, and paper bags.

And, for business, of the 250 tons of trash produced each week, 200 tons was recyclable. But, business leaders questioned Fay’s statistics and claimed it was costly to separate their trash and take staples and tape off the boxes. Fay retorted that “more money is spent by industry in advertising their concern for ecology, than on their performance in demonstrating their concern.”

In September, the ordinance was tabled with only Fay voting in favor. Local businessmen had grave reservations about the dumping fees and the strict regulation of refuse collection that the ordinance prescribed. Leaders from Wiremold, Chandler Evans, Pratt & Whitney, Jacobs Manufacturing, Dunham Bush, and Holo-Krome all believed that further study needed to be made. They argued that businesses would move out of town if the ordinance were passed.

By May 1972, Fay reintroduced his ordinance with changes for residents. This ordinance made residential newspaper recycling participation mandatory. Residential garbage would not be picked up if newspapers were mixed with the trash. The bi-weekly newspaper-recycling program had had moderate success over the year. Town garbage collectors picked up about 30 tons of newspapers per week from private residents. Fay felt that with required recycling, the town could move to weekly recycling pickup. Fay’s ordinance was passed in June, requiring weekly newspaper recycling. Fay chose to drop the dumping fees from the ordinance and West Hartford’s Town Council adopted a mandatory residential newspaper-recycling program in May 1972.

In 1972, Fay was eager to get to the 50 tons of cardboard produced by business that was thrown away each week. Fay continued to remind townspeople that putting the paper in the incinerator cost $6 per ton and for every ton of paper recycled, 17 fewer trees needed to be chopped down.

The Council left businesses out of the recycling program. Their concern about the cost of cleaning up their contaminated corrugated boxes led them to lobby to stop the ordinance. At the same time, the Chamber of Commerce started to survey the recycling potential of town businesses. Councilman Brian O’Meara called for the creation of a joint committee of business leaders and town administrators to take a cooperative approach to recycling efforts.

By June 1973, Fay encouraged voluntary participation on the part of businesses. By October 1973, Fay claimed that the town recycled 60 tons of newsprint per week, about 60% of the newsprint in town. West Hartford sold the paper to recyclers and paid less in incineration fees. At that time the State Department of Environmental Protection was just starting a statewide recycling program and looked to West Hartford as a model.

In February 1975, Democratic Town Councilor Daniel Blume proposed an ordinance that would end newspaper recycling. The recycled newsprint market had declined and Blume claimed the recycling cost too much.

Barbara Blechner, leader of the Environmental Quality Committee of the League of Women Voters helped lead the fight to keep newspaper recycling in place. The League issued an eight-page report to change the way recycling was picked up. In East Hartford, Bloomfield, Newington and Norwalk special units were attached to regular garbage collection trucks so that newspapers could be picked up at the same time as garbage. In 1975, the town’s landfill was close to being filled, requiring the town to take some trash out of town. So the pressure was on to solve the problem.

The League saw the issue as a more global problem than the Town Council. According to the League, to make 1000 tons of low grade paper from virgin pulp was 3,400 times greater than to make the same paper out of recycled material. The League also understood that the cost to address waste problems not only including burning the trash, but also the fringe benefits and debt cost of collection and transportation of the waste.

By 1976, Republican Mayor Nan Streeter continued to encourage recycling. The Town Council issued a proclamation on March 16, 1976 declaring March 21 to March 28 “Recycle Newspaper Week.” Streeter, an avid member of the League, wrote that because the town believed that a healthy environment was vital to life, and that the incineration of newspapers increased air pollution, and the town collected newspapers, that residents should increase their efforts to recycle newspapers over this week.

In April 1975, Democrats on the Town Council rescinded the paper-recycling ordinance. The ordinance gave the director of the Department of Public Works the authority to establish recycling rules. The League of Women Voters strongly favored continuing the recycling ordinance. The League published a mimeographed script entitled “West Hartford Trash -- It Won’t Go Away -- Where Will it Go?” dated October 5 and 6, 1976. This marked the culmination of a long study by the League of Women voters on the issue of Solid Waste Disposal in West Hartford.

But Democratic Councilor Blume continued to argue that the recycling program cost the town too much money. Proposals included having residents take their bundled papers to one of the 5 fire stations in town or changing back to bi-weekly pickup. Republicans questioned his numbers and believed that the 50% of those who recycled weekly would not stop. They held onto the recycling program.

Then in 1977, the state DEP ordered the town’s incinerator to close and the town could not avoid its solid waste issues. At this point, West Hartford bought into the Connecticut Resource Recovery Authority and we trucked our wastes out of town. In that same year, Councilor Bob Farr urged schools to begin their recycling program. Farr believed that the town could save money with the program and that students would learn the habits of recycling and bring those good habits home. The progress in institutionalizing school recycling continues to today.

In 2010, West Hartford produced about 38,000 tons of solid waste, about 3.5 pounds per person per day, a decrease from 1971. At the same time, Town Manager Ron Van Winkle estimated that the town will recycle only about 7,200 tons of waste –- about .6 pounds per person per day or 240 pounds per year, about 15% of the total waste produced. As of January 1, 2010 the town uses single stream recycling with automated dumping which has increased recycling. Even that rate of recycling will save the town over $100,000 by reducing fees for non-recyclable waste.

Solid waste disposal is as expensive today as it was 40 years ago. But as landfills have closed, the push to reduce waste increases. Every individual can take their lead from Art Fay and the League of Women Voters to do their part to reduce, reuse and recycle. How many households can put more in their recycling bin than in their garbage?
