## The Agora Ballroom {-}

*Originally appeared in West Hartford Life, August 2006. Thanks to Rachel Aron’s research paper, “The History of a West Hartford Hot Spot – The Agora Ballroom,” for bringing this topic to my attention. Her paper was a 2006 winner in the Noah Webster House’s Freeman and Mary Meyer Prize on West Hartford History. Her complete paper can be read at the House.*

Teenagers in West Hartford often decry the lack of “things to do.” When they learn about the town’s Charter Oak Park, a horse race track, or Luna Amusement Park, they wonder why there can’t be fun around like that today. Recently, plans for a laser tag venue on New Park Avenue may provide entertainment for teenagers. In the 1970s and 1980s teenagers and young adults in town could go to Dexter Avenue for boxing matches, disco dancing and concerts of emerging rock groups from Bobby and the Midnights to The Clash to Santana to Joe Jackson as they made their way to stardom.

What was finally known as the Agora Ballroom at 165 Dexter Avenue, opened as a distribution warehouse for Royal Typewriter in 1963, built on top of the old West Hartford landfill (and near the present day Public Works Department). Royal stopped manufacturing typewriters in Hartford in 1968 and so the concrete rectangular building stood vacant for a while

The Columbia Music Hall opened in the building in September 1973. In its short time, it held both music and sports events. On August 17, 1973, promoter Manny Liebert announced that he would once again sponsor boxing in Connecticut, now that it was legal again, at the Columbia Music Hall at 165 Dexter Avenue in West Hartford. The facility had room for 900 parked cars and could seat 2,500 people. According to the *Hartford Courant*, the venue was situated right in the heart of the old Hartford sports scene, not far from Charter Oak Park where both harness and auto races were held.

The first bout on September 25, 1973 was the first boxing match ever to be held in West Hartford. The line up included a six fight card headlining with New Britainite Kevin Pentlow and D.G. Barber of Denver, Colorado. Liebert promised the undercard would have as many Connecticut boys as he could find. In April, a boxing line up included ex-Conard football player Howard Hall in his first professional bout. He won in two rounds over an opponent from Enfield.

At the same time, there was boxing, it was also a music hall. In the second week in September, Quicksilver, one of the original San Francisco Bay Area groups played. On September 22, 1973, jazz musician Herbie Mann held a concert there.

It was also a venue for local folk singers. Six local singing groups held a folk concert on January 8, 1974 to raise money for arts groups in the area. On January 12, the venue hosted three groups, Slade, a hard rock band from England, NRBQ, formally the Wildweeds from Windsor, and Brownsville Station, a hard rock band from Madison, Wisconsin. Todd Rungren sang in April of that year.

In February 1974, the Music Hall hosted The Charles Brothers Circus in an attempt to raise money for summer school for children from Charter Oak Terrace, right around the corner. Two hundred people watched the indoor circus.

It was even the site in January 1974 for West Hartford’s Mayor Catherine Reynolds to draw the Connecticut Lottery winner: Mrs. Bernice Schwartz of Haynes Road won $75,000.

In December 1974, a group of six called Starship Enterprise bought out the Columbia Music Hall and changed the name to the West Hartford Music Hall. They lasted only until November 1975 when it changed to Finnocchio’s East, a gay bar.

For a brief time from November 1975 to June 1976, the nightspot Finnocchio’s was an attraction for the gay community. Its New Year’s celebration was called the “First New Year’s Gayla Party” and featured the Arthur Blake Review. According to ads in the *Hartford Courant*, the Review was so popular that it was held over for four days. An attempt by entertainer Ivan Valentin to perform “Leading Ladies of New York” with his troop of female impersonators was shut down by the Connecticut state liquor commissioner in the spring 1976. Connecticut state law prohibited entertainment at a liquor establishment where men dressed as women or women dressed as men. Valentin said the show was shut down mainly because it attracted a largely homosexual crowd. Others argued that the show was seductive and dealt in sexual content.

By June of 1976, the entertainment venue turned to disco and fell on hard times. In 1977 it became the Hard Rock Café, with no connection to the chain of Hard Rock Cafés. By 1979, management changed the name again to Stage West.

In 1982, it became the Agora Ballroom, part of a chain of nightclubs based in Cleveland. The Agora was very popular and advertised free admission before 9:30 and 75 cent drinks. Ads enticed people to come hear Southside Johnny and the Asbury Jukes, Max Creek, Cryer, and the Dregs. In 1982, when the drinking age was 18, the Ballroom advertised “1st Drink Free with College I.D.”

The drinks were inexpensive, but part of the charm of the Agora was the tailgating in the parking lot. Attendees partied before they went in, went out to their cars at intermission and then partied again after the show ended. A stamp on their hand allowed for re-admission. The Agora parking lot became an important social gathering place. In the industrial area of town, this seemed not to cause a public nuisance, even when the Ballroom was open to 2 a.m. on weeknights and 3 a.m. on weekends.

In its first few months, Joe Jackson, Bonnie Raitt, Pousette Dart Band, Willie Nelson, and Gaelic Rocker Rory Gallagher held concerts there. Over the course of its six years, The Ramones, X, Peter Gabriel, Ozzy Osborne, R.E.M., U2, Metallica, Aerosmith, Husker Du, The Grateful Dead, Twisted Sister, King Crimson, Men at Work, Stray Cats, and the Average White Band all performed.

In the middle of the night in July 1987, the Agora was destroyed by vandals. It was thought to be an inside job, included stealing sound equipment, using chainsaws to cut posts holding up the balcony, and spray painting the walls. No one was ever arrested for the damage, and the venue never recovered.

Max Creek saw the Agora as a home base. They went back and performed after the vandalism and they believed the Agora Ballroom was “the best place to hear live music” in the area.The managers hosted a wide variety of music and bands which “defined the times,” including The Band, Missing Person, John Cippolina, and Peter Tosh. It also served as a spot, like the Webster Theater in Hartford today, for local and regional bands to get their start.

According to Mark Mercier of Max Creek, it was “in many people’s minds, the best place in the area to hear music, and since then, no place in Connecticut and western Massachusetts has come close to what it was. We had a wonderful time playing there.”

This nightclub provided a venue for emerging groups and entertainment for those in the region that was edgy and fun. My guess is that teenagers in town couldn’t wait until they were old enough to go to the Agora.
