## Democracy and School Renovations {-}

*Originally appeared in West Hartford Life, March 2012*

On February 21, 1973, 350 parents and their children marched from Trout Brook and Farmington Avenue up to the Town Hall on South Main Street to protest a proposed $15 million school renovation program. The marchers from Smith, Whitman, and Morley schools were worried about potential school closings and changes to their schools. Protesters from Wolcott, Elmwood and Beach Park schools also marched.

When they arrived at the Town Hall, they circled the Noah Webster Statue calling for Mayor Ellsworth Grant to appear to speak to them. Three Democratic Town Councilors showed up in support and State Representative Chuck Matties showed up to observe the protest.

Why would parents oppose renovations to their aging school buildings in the early 1970s when the state offered a 50% reimbursement rate, the unemployment rate was at 6% and the school system was seen as one of the best in the state?

As for any protest, there are multiple causes and this public display of displeasure with local government fits that bill. Declining enrollment, aging school buildings, a new philosophy of “open classrooms,” a call for neighborhood schools, fear of security, democracy on the neighborhood level, a determined school board chair, and a superintendent with big ideas all came together to cause unrest.

West Hartford’s population peaked in 1970 with about 70,000 residents and then lost about 10,000 over the next decade. What residents wouldn’t have known in 1971, was that five elementary schools and two junior highs would be closed over the next decade as the school population declined as well.

In 1971, Superintendent Charlie Richter moved to renovate all 19 town schools over the next three years. Charter Oak and Morley Schools were in the first of three phases and were characterized as overcrowded and without adequate facilities. Both schools were over 40 years old. Charter Oak had been built without a gym and both schools lacked many large rooms that could be used for multiple small group or single large group instruction.

By January 1972, Board Chairperson Madeline McKernan argued that the real reason for renovation was to “equalize facilities in the 13 elementary schools.” McKernan argued for more space for art, music, science labs, pupil series, teacher work areas, and some resource centers. The Board wanted to renovate eight schools at once in this first phase so that parents at specific schools were not able to push their agenda over that of another school. The eight schools in the first round were Bugbee, Braeburn, Whiting Lane, Charter Oak, Morley, Plant and Sedgwick Junior Highs and Conard High School.

By early March 1972, the plan had already shifted to focus on schools in the southeast sector of town. A joint Town Council-Board of Education building committee came up with a plan to replace Elmwood (1928), Smith (1915) and Charter Oak Schools (1929) with a single facility built to educate 1,000 elementary students.

According to Albert J. Marks, committee chair, this school would only be built if the parents of the children in the three schools liked the idea. Board of Ed chair McKernan said the committee believed the new school would cost little more than the estimated $1.5 million to renovate the three elementary schools.

Both Marks and McKernan agreed that the plan would have many advantages. It would cut administrative and upkeep costs. There could be more efficient staffing with full time art, music and physical education teachers. “The latest education concepts” could be more effectively built in a new school. The three unused sites could be turned over to the town and become income producing. Building the large school on a “house system” would help retain a small-school feeling.

At the first presentation, the joint committee asked PTA representatives from each school to take the information back to their schools. According to Marks, “If the town doesn’t want it, it doesn’t go. I want to make that very, very clear.”

Almost immediately, parents from the Elmwood School reacted negatively to the plan. Quickly Supt. Richter readjusted and suggested that Elmwood have the option of doubling up with Wolcott School, while Smith joined with Charter Oak. The Board already had a plan to build a 14 room addition on Wolcott and it would probably only take a few more rooms to take on Elmwood’s students who lived in a small district with a school that needed too many renovations to fix.

Fears of security raised their ugly head as well. The crowd applauded a woman who said that she would not allow her children to go to a school at Sterling Field because “there are certain sections there of people who are apt to be violent.” In the summer of 1970 there were problems there, allegedly from Hartford teenagers who lived in the Charter Oak Housing Project just over the Hartford line. Elmwood parents voted to consolidate with Wolcott.

By the end of March, the joint committee believed it had a solution, with both Smith and Charter Oak parents appearing to favor consolidation and a new school for 700 students at a cost of about $1.8 million. Though some Smith parents wanted the new school built on the Smith site, the 50% state reimbursement could not be used there because the site was so small.

Smith teacher Ralph Worth told the audience that the acoustics were terrible, the heating erratic and the atmosphere depressing. He added that the Smith staff completely supported consolidation.

However, when the plan was brought to a vote, only 26% of the parents voted and there was no mandate. Charter Oak parents voted for renovation, Smith parents were split, and Elmwood parents supported consolidation with Wolcott. At Charter Oak, the biggest fear seemed to be losing Sterling Field.

By November 1972. The Board decided to close Smith School and expand and renovate Charter Oak. At the same time the Board backed a plan to build a new Morley School on the site of the old St. Agnes home on Steele Road.

By this time, parents at Smith organized a Save Our School committee that organized the protest march. Morley School parents organized a Concerned Morley Community group because they did not want a new school on Steele Road. The Smith group sought a referendum on the entire $15 million bonding ordinance.

Board Chair McKernan continued to try to fix the schools. New charges that the plan was an attempt to get rid of neighborhood schools reflected a fear of busing in the time of volatile school integration battles being waged all over the country. McKernan argued that it was impossible to have all students walk to school in this town. McKernan continued to focus on the long range plan for the system in which “every child in this town has a right to an equal educational opportunity and that it should make no difference where any child happens to live and go to school.”

On June 5, 1973, West Hartford voters went to the polls and defeated the $2.6 million bonding ordinance by 3 to 1.

Just two months later, Superintendent Charlie Richter resigned under pressure because, according to the Board, he was out of touch with the town.

It wasn’t until December 1974 that the Board finally approved plans to renovate Charter Oak, Smith and Morley schools. In 1975, the estimated cost had risen to $4.7 million. The renovations were completed in 1976.
