## Inequities of Athletic Opportunities for Girls {-}

*Originally appeared in West Hartford Life, July 2002*

I can still see point guard Patty Gruzden, long hair streaming behind her in her green Talcott Junior High uniform, dribbling down Sedgwick’s basketball court after a steal and going in for the lay up. She was a tenacious, feisty, quick and truly competitive 7th grader in my first year in West Hartford.

I started teaching and coaching at Talcott Junior High in 1977, five years after Title IX became law. I coached the girls’ junior varsity field hockey and basketball teams. We had a six game season playing home and away at Plant, Sedgwick and King Philip. One of the greatest satisfactions as a coach was feeling the excitement and accomplishment of those 12 and 13-year-old girls from Elmwood as they entered the gym at Sedgwick, feeling confident they could compete.

In 1979, due to declining enrollment, Talcott and Plant were closed and the 9th grade moved to Conard High School. I coached freshman field hockey and JV softball. Based on my own observations and a study done by the Women’s Sports Foundation in 1997, these student athletes gained confidence, had higher self-esteem, and were less likely to get in trouble in school, use drugs, or participate in risky sexual behavior. But, West Hartford dropped competitive sports in the middle school in that same year.

What implications did West Hartford’s dropping competitive sports in the junior high/middle school in 1979 have on girls over the next 20 years? A cursory view of the statistics in the year 2000 would say: very little. In 2000, 47% of girls at Conard participated in a sport.

But, a closer look at the statistics, and the changing population in West Hartford over those 20 years reveals a far more complicated and disturbing story. A recent master's thesis by Tom Moore, a history teacher and football and girls lacrosse coach at Conard, raises a host of concerns.

When Title IX became law in 1972, Conard did not have any official varsity sports for girls. Title IX mandated that the school offer competitive sports for girls that would be comparable to the boys. Teams in swimming, field hockey, basketball, track and field, and tennis were the first sports offered to girls.

Around the same time that Title IX became law, the population in West Hartford began to change. The population of the town peaked in 1970 at about 70,000. Over the next decade, the population decreased by 10,000 and the demographics of the town changed as more immigrants and racial minorities moved to town. This was part of a larger national trend as northern cities lost population at an even higher rate, and a new immigration law in 1965 opened the doors to more non-European immigrants.

As the town’s population declined, the socioeconomic makeup of the town began to change. In 1972, the Piper Brook Housing Project opened in the southeast section of town. This was the first low-income housing for non-senior citizens in town. For the first time, low-income families could find apartment housing in West Hartford. From 1958 to 1970, Conard’s minority enrollment was less than two percent. According to Moore, five African Americans, three Asian and two Hispanic students graduated from Conard out of a total of 6,583 students during that time period. In 1973, one Hispanic girl, the only minority graduated with 495 others.

By 1980, 4.5 percent of the graduating class was minority and by 1981, 10 percent. By 1991, the minority population stood at 20 percent and by 2000 was 35 percent. Today Hispanics make up the largest percentage of minorities at 14 percent.

How have these demographic changes played out in sports participation? West Hartford has succeeded in providing high school girls the opportunity to compete, but the statistics show that young women of color and particularly African American and Hispanics have not benefited from Title IX in an equal way.

The great majority of the participating minority females were of Asian background. They make up as much as half of the cross country and volleyball teams and participate in a rate higher than their 9 percent of the population. With the exception of cheerleading, since 1990, only two Hispanic girls earned varsity letters out of 2,138 letters earned and both of those came in softball.

What factors, beyond pure individual choice, would make it so that less than 10 percent of Conard’s female athletes from a background other than Caucasian participate in sports? Why should this be of any concern for the schools where many believe the priority should be academics, not athletic competition?

Conard girls who play sports are high achieving students, according to Moore’s study. In the year 2000, 83 percent of the female athletes made the honor roll. Between 1973 and 2000, 1,201 students were inducted in the National Honor Society. The NHS draws about 10% of the senior class. Of this group, 70 percent were female. Since 1986, over 60 percent of the senior girls who won varsity letters were members of NHS.

The peer group that plays sports, though, seems difficult for African American and Hispanic girls to enter. For the most highly competitive sports of soccer and softball (only 60 percent of those who try out for softball make it), it is possible that they are not able to play competitively before high school to have the skills to make the team. Since 1979, West Hartford Public Schools have offered no competitive sports for middle school students. There are opportunities for girls to play on teams before high school, but only for those with the money to pay and parents available to cart them to games.

These findings present policy implications for the school system. The main thrust of Title IX is to provide equality between boys and girls, but the ideal of Title IX is equal access for participation.

An unintended consequence of the current West Hartford policy gives girls whose parents can pay for them to play in town and travel leagues before high school, a real advantage when they try out as freshmen. West Hartford’s pay for play rule may also keep some students from trying a new sport. Though money is available for scholarships, many students do not access it. Sports seem to have added to a division in the student body by race and economics, an unplanned result of Title IX.

Can we establish policies that produce sports teams that mirror the ethnic, racial, and socioeconomic diversity of our schools that we are so proud to celebrate?

Moore suggests that the town drop pay for play. He makes a case for the power of minority coaches as role models. And he suggests mandatory participation in at least one after school activity each year for every student.

But it seems like high school is too late. Why not bring back sports teams at the middle school? Even the amount of time students spend in gym has declined in the past few years. The new magnet middle school would be a great place to pilot a program, which made sports an integral part of the school day. If sports help develop confidence and risk-taking behavior which seems to improve academic performance, as Patty Grusden showed me 25 years ago, shouldn’t all students have access to these opportunities?
