## When Teachers Marched in Protest Down Farmington Avenue {-}

*Originally appeared in West Hartford Life, February 2004*

Between 1969 and 1975, West Hartford teachers grew militant in their demands for a negotiated contract. In April 1970, teachers marched from Hall High School (the present Town Hall) in the center of town down Farmington Avenue to the old East School on Whiting Lane to protest lack of action on their contract by the Board of Education.

Negotiating a contract led to terrific tension between taxpayers, teachers, and the Board of Education. The West Hartford Education Association (WHEA) claimed that teachers had few rights in the classroom and the Board was caught between supporting its teachers and raising taxes. Up until the late 1960s, Boards of Education acted paternalistically toward their teachers and felt they had the prerogative to establish all working conditions and pay.

It wasn’t until the mid 1960s that there was actually a written salary schedule for teachers in West Hartford. In 1968-69, Farmington teachers drew up a contract for the first time. In the fall of 1968, Hartford teachers went on strike over class size and working conditions. In July 1969, eight Connecticut towns were in arbitration.

The 1960s were a time for direct action and a time when ordinary citizens fought for equality and democracy and teachers would not be denied their rights. Just flexing their union muscles, however, could only work with the power of the 1969 state law making boards negotiate with their unions.

In 1969, the West Hartford Board of Education chose to test the new Teacher Negotiation Act passed by the state legislature in 1969. They tried to keep total control over working conditions and keep salaries at what they considered to be a reasonable level. The new law made it necessary for the Board to negotiate all areas of teachers’ employment.

In 1969, the WHEA attempted to negotiate a contract with the Board of Education for both teachers and administrators. When a three man arbitration panel came up with a package after 22 failed negotiation sessions, and failed mediation, the Board, led by chair John Hand Conard, (son of Frederick U. Conard) rejected the proposal.

Traditionally West Hartford had been about 5th in teachers’ salaries in the state. The proposal offered by the Board of Education would have dropped them to 15th. With 29 different issues on the table, the Board moved only on salary and refused to change its position on any other issue since negotiations began.

President of the WHEA, Dick Blaisdell understood that the idea of collective bargaining came from teachers, not from the board. He believed that the board needed to be reminded that collective bargaining for teachers was a right guaranteed by state statutes and not a favor to be dispensed. He said, “The Board’s expressed attitude is reminiscent of that which prevailed 30 years ago when the superintendent of schools was a father figure before whom teachers trembled and the board was completely unapproachable. That day has long passed and if the present superintendent doesn’t soon realize this, good teachers will continue to leave West Hartford in serious numbers.”

The Superintendent was Charlie Richter, known as a brilliant idea man. But he was also known for being arrogant by Board members and teachers alike. Blaisdell stated publicly that the Board, with Richter as its representative, was running roughshod over the teachers.

When negotiations and mediation failed by the end of June 1970, the process moved onto a three person arbitration panel. The arbitrators made their decision in late August and the Board, rejected their proposal. Teachers, including almost 130 new professionals, started a new year without a contract. Under the new law, the arbitration was not binding. On October 8, the Board rejected an arbitration decision which included salary proposals of $7,100 for a first year teacher with a BA up to $15,400 for a teacher with PhD and 17 years experience. Richter’s salary stood at $34,500.

Board Chair Conard rejected the settlement because it would have cost the town an additional $200,000 out of a budget of $13 million (about 1.5%). A further issue was that the awards “take away the Board’s power of decision over matters of educational policy.” These matters included binding arbitration over teacher grievances and release time for union business.

So, the struggle continued for another six months. Teachers did not want to go on strike, but they continued to look for ways to get the public’s attention. This led to the march down Farmington Avenue and then a final settlement before the end of the school year.

Five years later, in 1975, the Board and WHEA found themselves deadlocked again. At this point, the school population was declining and the issue of staff reduction was of key importance as the number of students in the school system continued to shrink and thus teachers had to be laid off. The school population hit its peak in 1970 with over 13,000 students, and the hiring of over 100 teachers in that year. By 1975, the number had shrunk to about 11,000 in 20 schools, and continued a decline for another 14 years, hitting its lowest point in 1989 at about 7,000. (In 2004 there were about 10,000 students in 15 schools.)

Negotiations began in November of 1974. The WHEA used a series of “pressure tactics” to get the school board to compromise including a boycott of a superintendent’s meeting a, a three-week work slowdown, an all nighter spent in each school, and then a strike vote. Marilyn Miller, a WHEA officer and negotiator, said she would go on strike “because of what I’ve seen in West Hartford these past ten months... the apathy of the public and the parents.” She went on to say that she believed that teachers were “the only group of people in West Hartford who care about education.”

On October 6, the *New York Times* covered the all night protest held by the teachers. They stayed overnight in their schools trying to bring attention to their plight without going on strike. At the beginning of November, teachers voted to give the leadership the ability to go on strike. Donald LaCroix, president of the WHEA and a kindergarten teacher, reported that 55% voted to use the strike as pressure for settlement. LaCroix believed that at least 50% of those who voted against the strike would not cross the picket line. Experts believed that to make the strike effective, 80% had to participate.

The rejected proposal called for 5% increase in the first year, 6.85% in the second year, and 6.9% in the third year. The school board offered 4.25%. Inflation was running between 6 and 8% at this time.

The teachers angered Board member Richard Roth because he felt they had voted to take part in a “blatantly unlawful and illegal act.” He said he was having a difficult time explaining to his children how they should respect their teachers when the WHEA decided to strike.

To make matters worse for the teachers, on November 5, Assistant Superintendent of Personnel Donald Hardy reported that the school board had a $1 million deficit. This deficit was one of the main reasons the school board had been loathe to accept the arbitration award for teachers. At the same meeting, the Board authorized teacher layoffs, replacement and salary deductions for those who went on strike.

In 1975, just as today, strikes by teachers were illegal in the state of Connecticut and school boards asked the courts for an injunction against the teachers. Assistant Superintendent of Schools Paul Burch said that this would not be done; instead, he stated that they would lay off striking teachers by random selection.

At that point, teacher and school board negotiators started a series of marathon negotiating sessions and with the help of mediators, came up with a three year contract signed in the first week in December. The final contract included a moratorium on staff reductions until 1977 and gave teachers binding arbitration of selected contract items for the first time.

In December 2003, West Hartford Teachers voted to approve a contract negotiated by the West Hartford Education Association and the West Hartford Board of Education, giving teachers a 2% raise in each of the next two years. About 75% of the teachers approved the two year contract which went into effect in September 2004. This contract was negotiated during an economic downturn but also at a time with strong town support for the school system.

Binding arbitration has helped to level the playing field between teachers and boards of education giving teachers the rights that most industrial workers got in 1935 with the Wagner Act. The power of the state law has made negotiations more civil and less divisive as both sides are pushed to be reasonable.
