## Controversy Over the New Town Hall {-}

*Originally appeared in West Hartford Life, February 2003*

West Hartford’s town government has a big stake in the vitality of the town’s center. The Town Council wants the center to have a healthy mix of retail, office space, and the requisite town buildings. Trying to balance these competing interests from 1970 to 1984 seemed like an unending task as the town dealt with the opening of Westfarms Mall, closing the Whitman School and the old Hall High, and a town government that needed more office space.

When Hall High moved to North Main Street in 1970, there was not a plan for the former school building on South Main Street. Some of its space was used for a variety of town offices and services. By 1972, it was clear that West Hartford was outgrowing its current Town Hall and the Town Council grappled with how to handle this space crunch. To address these concerns, the Council appointed a “Center Resources Committee” to study and plan for a larger Town Hall, to research the best use for the former Hall High School and to make recommendations about the Town Hall Annex. In their 1973 report, the Committee recommended demolishing Hall High (the current Town Hall) and the Town Hall Annex to make room for commercial development.

Republicans, who controlled the Council, recommended building a three story town complex on Norfeldt Field, at the corner of Boulevard and Trout Brook, to house the Police and Fire Departments and the Circuit Court.

It was not until mid August 1973 that architect Stanley Fisher proposed renovating the former Hall High into a new Town Hall at a public meeting. Fisher believed the town could save $3 million out of the $5.5 Million it would cost to construct a Town Hall addition and erect a public safety complex.

Republicans, led by Mayor Ellsworth Grant, supported the controversial public safety complex. But in October of 1973, Grant threw his support behind renovating the old Hall High. Single-handedly, Grant stopped planning on a proposed Town Hall addition. Democratic council member Catherine Reynolds, called Grant’s actions “arrogant.” As the Council elections heated up in late October, challenger Thomas Pikor, suggested an alternative plan that would include the recently closed Whitman School. He proposed that Hall High be rented out for office space.

The Democrats gained the majority on the Council in the ’73 election and moved to squash Grant’s plan and went on to hire an architect to study an addition to the Town Hall. Republicans wanted to use the old Hall High as the Town Hall, leaving Police and Court facilities in the Town Hall. Town Hall would use part of the high school building and lease the other offices for revenue.

In late 1974, the Center Resource Committee made a formal recommendation to have an architect conduct a study of municipal facilities.The architects were asked to study the various buildings and their potential uses. No action was taken on these plans.

The next time these issues hit the press was 1976. The Town Development Task Force replaced the Center Resource Committee. In response to the Task Force’s recommendation of a $4.4 million renovation of the former high school, Republican Mayor Ann Streeter argued that while they wanted to preserve the building, the cost was too high and the commercial potential of the lot would be a valuable asset to the town.

Members of the Task Force voted overwhelmingly to build a new Police/Court facility and to renovate the Whitman School as a community center and approved plans to renovate the Town Hall after the police and court moved out. However, they did not make a recommendation about the fate of the Hall High building. Not one of these recommendations was adopted and again, no action was taken.

In fact, by 1980, the former Whitman School reopened as the Police/Court building. This freed up space in the existing Town Hall.

After many more years of wrangling, and yet another task force, headed by Democrat Richard Mulready, a recommendation to renovate the former Hall High building came before the Town Council for a vote. Kaestle Boos, a local architecture firm first submitted a plan in 1981, but that plan never reached a vote. Two years later, in June of 1983, a similar plan of theirs was adopted by Council. Fall elections changed the composition of the Town Council with the Democrats seizing control. The new mayor, Kevin Sullivan, Deputy Mayor Chris Droney, Councilors Joe O’Brien and Republican Robert Gross united against the design and cost of the plan adopted by the previous Council. Supporting the Hall renovation plans were Republican Minority Leader and former mayor, Chuck Matties, Marjorie Anderson and Myron Congdon and Democrat Mims Butterworth. Democratic member Chuck Felson would cast the deciding vote.

Matties and other supporters of the plan, wanted to move the school offices to Town Hall and sell the Steele Road school administration building. In his call for the council to move on a plan in August of 1984, Mr. Matties said: “Over the past 15 years, every conceivable question has been asked and answered at least three times… I don’t particularly care what decision we make. Just so long as we make a decision. This has been dragging on for 15 years, and we’ve got to do something.”

In August of 1984, 12 years after the first discussions, the Town Council voted to renovate the former Hall High for the Town Hall. Three Councilmen, a Democrat and two Republicans, spoke in opposition to the plan. The Chamber of Commerce and the West Hartford Taxpayers Association threatened a referendum against the $8.5 million plan. However the referendum never materialized. Three years later, the newly renovated Town Hall opened with some fanfare.

In May of 1987, right after town offices moved to the renovated old Hall High, Councilwoman Madeline McKernan proposed selling the old town hall for commercial use. Proposals to renovate the Town Hall for an education center were $3 million, one million more than budgeted. The Superintendent and the Board of Education were happy with their headquarters on Steele Road, and a sale seemed like a way for the town to gain some tax revenue. The proposal was voted down and in 1990, the school administration moved into the old town hall.

In 2003, town planners considered adding on to the Town Hall, moving the education offices there, and making the education building commercial space. With the center commercial space at a premium, this may become a viable option.

West Hartford citizens who remember the wrangling over the old Hall may wonder about the value of one more citizens’ center task force, but as we’ve seen before, democracy can be a messy process. A number of factors including the economic downturn in the 1980s, the decline of school age children, closing of schools and yet the increase in the education budget, a series of budget referendums, and a lack of a united front by the council majority all made the decision about the town hall drag on for years.

Just recently, a citizens’ task force to decide on the proper site for a new middle school started and finished its business within six months for a project worth over $20 million. Bipartisan support, deep support for the schools, and a growing school population all led to this efficient decision. Allowing citizens a hand in these town decisions can empower the community while it can also divide the town. Discussions like these provide a healthy forum that allows for a participatory democracy, no matter how untidy.
