## Racial Balance Law {-}

*Originally appeared in West Hartford Life, December 2009*

On October 9, 2009, the Board of Education addressed West Hartford’s lack of compliance with the 1969 Racial Imbalance Law. A 2007 United States Supreme Court ruling, which threw out Seattle’s use of race to assign students to schools, has emboldened some Connecticut policymakers to question the constitutionality of the law. With the largest achievement gap of any state in the union, West Hartford is in the middle of the controversy over the efficacy of racial integration in schools.

The West Hartford School Board’s commitment to school integration has ebbed and flowed with its superintendents. From 1966 to 1970, Superintendent Charlie Richter, supported interdistrict integration within the context of the migration of African Americans from south to north, the civil rights movement, and subsequent urban unrest, and Lyndon Johnson’s Great Society programs.

On September 6, 1966, at West Hartford’s Fall Convocation, Superintendent Richter said:

> The West Hartford Board of Education attracted national attention during the 1965-66 school year when the Board of Education became the first to propose a program of mixing urban-suburban youngsters, the first to accept a controversial regional invitation to join with other towns in such a plan and the first to implement its own plan locally as part of the regular summer school program...

Richter believed that integrating schools would attack poverty, and he wanted West Hartford to be part of Lyndon Johnson’s Great Society, which addressed the roots of poverty. Although poverty was less visible in the 1960s, Richter argued, it was “no less real.” He believed, “in our society, poverty is still a problem and still exacts a price. And I believe that magnanimous Americans will reach down to lift up again.”

The national, state, and local impetus to integrate schools in the Hartford region is still a policy issue in 2009. The federal No Child Left Behind Act requires school systems to educate all students and close the achievement gap. The state, through the Racial Balance Act (1969) and the *Sheff v. O’Neill* case (filed in 1989) asks for voluntary integration within school districts in the Hartford region. Within the town, a magnet/redistricting plan in 1995 tried to better balance the 11 elementary schools by establishing three elementary school magnets, and redrawing district lines. Segregated schools developed because of regionally segregated housing patterns for the many migrants to Connecticut and West Hartford from the 1950’s until today.

Between 1950 and 1960, the African-American population in Connecticut more than doubled from 53,000 to 107,000. From 1960 to 1970, 80,000 Hispanics migrated to Connecticut. These migrants moved to cities at the same time that white middle class residents moved to the suburbs. In the 1950s and 1960s, Hartford factories closed and some, like Colt’s Firearms moved to the suburbs or south.

Though the civil rights movement of the 1960s, was largely perceived as a southern event, cries for black power and civil rights activism flourished in Hartford as well. There was a growing militancy among new black leaders that galvanized the black community. Those who had lived through being second-class citizens lost some of their fear and willingly fought for their equal rights.

According to Connecticut historian Herbert Janick, “black youths” looted Hartford’s North End in 1967, 1968, and 1969. In July and September 1967, frustrated and angry youths, reacting to Dr. Martin Luther King’s assassination in April 1968, threw rocks and bricks at police and firemen, chanting, “You killed Martin Luther King!” On Labor Day 1969, mobs fought state and city police. Those in the mob set fire to a public library and damaged almost 100 buildings. Over 500 people were arrested in this, the largest riot.

These riots led to much soul searching on the part of the city, state and federal government. Johnson’s Great Society programs were based on addressing the deep seated causes of poverty and so jobs programs and educational programs were both implemented. City and state government reacted by pushing through summer camp and work experience programs for city youth. It is in that context that Connecticut’s General Assembly passed their Racial Imbalance Act in 1969, believing that a good education in an integrated setting could help the city’s poor succeed.

In the 1960s, Hartford’s schools were about 50% white, so there was a chance for intradistrict integration. But, by time the Racial Balance Act was implemented, many Connecticut cities had more than 75% students of color in their schools, so believed the only way to integrate was by crossing district lines.

In West Hartford, according to the 1960 census, 229 African Americans, 0.4% of the population lived here. By 1970, the number grew to 263, but stayed the same fraction of a percent of the population. Clearly, for Superintendent Richter, integration was an interdistrict issue in the mid 1960s.

According to the *Hartford Courant*, the education committee in the state legislature rejected the first set of regulations for the racial imbalance law drawn up by the State Board of Education. In the ensuing years, the major Connecticut cities threatened lawsuits against the state. But, by the late 1970s, the federal courts were holding states liable for not moving quickly enough on de facto segregation. Each Connecticut city worked independently with the commissioner of education to develop individual desegregation plans. But, city officials claimed that they could not desegregate schools within a city.

City officials claimed that the racial imbalance act was racist because it put such a positive value on “whiteness” and a negative value on “blackness.” They believed the only way desegregation could happen was through a regional effort. Officials from Hartford, New Britain, New Haven, Norwalk, Stamford and Waterbury all signed a statement to that effect.

In 1976, for the first time, the state Board of Education drew up regulations to carry out the racial imbalance law. In the context of the busing uproar in Boston, Connecticut officials were understandably nervous about any forced busing and it took them seven years to write up the regulations, which allowed for plus or minus 25% students of color at a school than the town’s school system average. With these regulations, virtually all-white suburbs, and all-black cities would not change. The regulations did not mandate busing, or any specific means to achieve racial balance. It was clear that the only true integration would come from student transfers across town lines. From 1969 to 1979, Connecticut schools became more segregated.

Superintendent Richter chose to champion voluntary busing in West Hartford before the Racial Balance Act, before the riots, and twelve years after Brown v. Board of Education. In 1970, The West Hartford and Hartford Boards of Education agreed to a recommendation to double the number of Project Concern students in West Hartford to almost 400.

According to Richter, integration made for good schools. He believed “That good schools can make a community a better place in which to live. Good schools attract good people.” With this spirit, Richter and the Board of Education defined a positive role for West Hartford’s schools in its voluntary efforts to integrate at a time when the West Hartford community itself was not integrated.
