## McCue, Sinatro and Reynolds {-}

*Originally appeared in West Hartford Life, June 2004*

Bob McCue, Pat Sinatro, and Katie Reynolds participated in interviews with Conard’s Local History classes in mid-March for the Sesquicentennial. Public employees, business owners and elected officials like these three build bridges between different constituencies helping to develop a sense of a West Hartford community.

Bob McCue, retired Chief of Police was born in West Hartford during the Great Depression. He boasts three generations serving on the WHPD. His father Martin was Chief of Police and started his service in 1929. McCue’s son, Bob, Jr. is now Assistant Police Chief.

McCue joined the police force in 1952 at a time when West Hartford’s population was about 45,000 and retired in 1990 when the population stood at about 60,000. He showed interest in building bridges between the police and children and teens. In the late 1960s, there was animosity on the part of teens towards police officers that grew out of police actions towards civil rights and anti war protestors. In the 1960s McCue was one of the founders of the Police Explorers program which introduced young men and women to the career of the police officer. In 1969, McCue helped develop the “Officer Friendly” program to teach children about safety and to familiarize them with police officers. McCue and Detective Pete McDermott used these programs to encourage positive relationships between the WHPD and local teens.

McCue also felt it was important within his department to teach his officers the history of the department. He wrote a column called “Roots” in the police newsletter which described the changes in the WHPD. Before the department was unionized in 1964, officers bought their own uniforms and even their badges and couldn’t get paid for overtime work. McCue’s family tie through his father, gave him the impetus to pass the stories along to members of the department to help build pride in their department and in their work.

McCue remembered a closer relationship between the police and neighbors in the 1950s when he first joined the force. When the town had more of a small town feeling, residents left their house keys at the police station when they went on vacation, and during each shift, an officer checked their house. As the population grew in the 1960s, this practice had to be discontinued. Bike patrols, established in the last ten years, are an attempt by the police force to redevelop these personal relationships in neighborhoods.

When Katie Reynolds ran as a Democrat for Town Council in 1971, she was the first woman of that party to be elected. In her run for re-election in 1973, she won re-election and she was also the top vote getter and became the first of four female mayors over the next 25 years. In the 1973 election, Republicans led by Ellsworth Grant lost the majority they had held for 20 of the previous 26 years. In that election, the top four vote getters were women.

Reynolds’ election appealed directly to women and she dubbed her run, “the housewife’s campaign.” Reynolds rode the new wave of feminism which came out of the 1960s with the formation of the National Organization of Women in 1966 and the ratification of the Equal Rights Amendment by Congress in 1972 both of which encouraged women to get involved in public life. And yet, she couched her election strategy on women being different; women, she argued, would be less partisan than men and would be more willing to make decisions for the good of the town rather than the good of the party. This same argument was used by many of the woman suffragists at the turn of the 20th century.

And, politics in the 1960s and 1970s in West Hartford were wracked by partisanship as politicians, business owners and neighbors argued over developments in Elmwood, at Corbins Corner, Bishops Corner and Westfarms Mall. The mall was a $40 million development project that took a reversal of a Town Council vote in 1966 and a Supreme Court decision in 1970 to go forward. Reynolds served on the council during its creation and the mall opened when she was mayor.

Reynolds has not dropped out of public life since leaving the council almost 30 years ago. She has been part of the center’s retail success with her store, Comina.

Pat Sinatro owns a real estate and insurance company in the center. His company, founded in 1936 by his father, owns many of the buildings in the center on LaSalle Road and Farmington Avenue. After Westfarms Mall opened in 1974, center stores lost business. Sinatro was instrumental in revitalizing the center in the 1980s when he lured popular stores and restaurants into town and developed a climate which drew people there. He has organized “Dancing Under the Stars” for the past few years to bring people of all ages into the center.

Sinatro believes both the educational and recreational facilities in town are top notch. The excellent educational system, including public, private and parochial schools, has a great reputation with area colleges. Sinatro thinks the town is particularly unique because of its recreational complex at Buena Vista which includes skating, tennis, golf and swimming, all within walking distance. At any time of day or year, people of all ages take advantage of these public facilities.

West Hartford has a character all its own. The sense of community here is built around a pride in the town and a desire to make the town a great place in which to live. Elections here are always contested. Parents believe the elementary school their children go to is the best in town. Shopping opportunities abound. Recreational facilities and sports leagues provide opportunities for athletes of all ages. But it is town leaders like Sinatro, McCue, and Reynolds whose ideas and actions build the sense of community which helps make the town exceptional.

*Thank you to Local History students Casey O’Brien, D.J. Ehnot, Parth Thaker, Michael Abourizk, Tim Gerundo, and Andrew Reynolds for completing the interviews and analysis of these three town leaders. Thanks also to Mims Butterworth, Ellsworth Grant and Dick Woodworth for background information in their Sesquicentennial book Celebrate West Hartford.*
