# Afterword

**Speech delivered at Ceremony for Dedication of Tracey’s Tree, October 9, 2017**

This speech tells much about my work as Town Historian and the power of history in our lives. Delivered at Burgoyne Park in Elmwood on the occasion of planting an elm tree, now known as Tracey’s Tree. See local news: <http://we-ha.com/traceys-tree-dedicated-honor-west-hartford-historian-retired-teacher-dr-tracey-wilson/>

Good Afternoon!

Thank you so much for this ceremony. I am humbled and honored to have this elm tree planted in my name. Who gets to have something like this?. . .and especially when I can appreciate it. In these days of consciously thinking about who should be commemorated and what statues can stand, I feel even more honored that there was consensus that I’m one for the ages.

First I want to thank Rick Liftig who was the mastermind of this whole thing --- and then Jenn DiCola Matos and Pam and Charlie Hilborn who helped carry out the plan. Thanks too, to the Governor’s Foot Guard --- which was formed in 1771 and joined the march to the Battle of Saratoga in 1777, for adding to this celebration. And all of you who came --- family Beth and Adam and Peter (and Brittany, Caroline, and Billie, who couldn’t be here) and my brother Dave, friends, teacher colleagues, and particularly my retiree partner Liz Devine, former students, the Solidarity Sisters, Katherine who helped me pick the apples yesterday, elected officials and those of you running for elected office and members of the Universalist Church all members of this community for whom I am so grateful to be a part.

Many of you gave money in my name to benefit two of my favorite non-profits --- the Noah Webster House and Knox, Inc. --- history and gardens are two of my favorite things! Thank you.

To me, the planting of this elm tree represents

- a symbol in history,
- a community event, and
- a tool for educating us about liberty in a democracy.

You see, trees have special significance

- in our environment and also
- as symbols --- Marcus Garvey, the great black nationalist, proclaimed 100 years ago,

> A people without the knowledge of their past history, origin, and culture, is like a tree without roots.

He knew the power that history can have in people's lives --- that knowing our history cannot only keep us rooted, but history can also give us a firm footing to branch out --- to give shade, to reach the sky. And as we are seeing in Puerto Rico, even as soon as a week after the hurricane, those trees whose roots held, already have leaves sprouting.

Our celebration today is about history and it coincides with the day 240 years ago in Saratoga, when American General Benedict Arnold’s troops repulsed British General Johnny Burgoyne’s troops in the Second Battle at Saratoga. This battle turned out to be a turning point in the Revolutionary War. Ten days later, General Burgoyne surrendered 5,000 British and Hessian troops to American General Horatio Gates.

This battle reverberated in France, when the French told American envoy Benjamin Franklin that they would become an ally to the Americans in their fight for independence against the British.

When word got back to the West Division of Hartford, Ebenezer Faxon whose homestead was on this corner, planted a small grove of elms right here, on the corner of Quaker Lane --- then known as East Street and New Britain Avenue, then known as South Street. They grew and became a town landmark known as the Burgoyne Elms --- properly known as the Victory over Burgoyne Elms.

The idea of a regular everyday tree being a symbol is powerful. I dare say that most of us like trees --- they give shade and sometimes fruit, they produce beauty when their leaves change, and they help turn carbon dioxide into oxygen. Yet these elm trees became much more.

The history of the elm as a liberty tree began in 1765 as a protest to the British-imposed Stamp Act. In 1765, when the British Parliament passed the Stamp Act, Boston Patriots hung a British tax collector in effigy from an elm tree. This Stamp Act put taxes on newspapers, printed materials and college diplomas --- so the protest of hanging the tax collector in effigy symbolized a desire of these Patriots for access to information, access to an education, rule by law, and individual liberty. Most historians argue that the protest was not so much about the tax, but it was more about having representation in a government that raised that tax. And I agree.

So, this Liberty Tree had branches which could be used for political purposes or some might say for social change. This idea of a tree representing liberty, representing a fight against tyranny and oppression, led Faxon to plant them here on this plot of land, in what for over 200 years has been known as --- Victory over Burgoyne Park.

That protest demonstrated support for liberty - that we define in two ways:

1. liberty from government tyranny and coercion
2. liberty to participate in government

I want you to try, like the Governor's Foot Guard must every time they put on their uniforms, to think back 240 years and wonder

- What did liberty mean to the people who lived here 240 years ago?
- Was it so different from what we yearn for today?
- Would we understand each other’s ideal?

**COMMUNITY**

These elm trees represent these historical questions and they represent the kind of community in which we live.

Faxon planted elm trees and we plant elm trees as a symbol of liberty and also a way to gather our community, to remind us that we are not just 63,000 individuals, living out our daily lives in isolation, but that our lives are made better by living in community - and by celebrating and enjoying the community in which we live.

In a lot of ways a community --- like Elmwood, like West Hartford --- is a covenant. It is an agreement to live together --- and in a covenantal relationship we ask, not what we get, but what we can give. Here many of you have given time to set up this ceremony, given money to these two great organizations, Knox and Noah Webster. I have worked to give back to the community through the writing of its history, through many years of Empty Bowls banquets, my work with the Noah Webster House, and through my leadership in the Universalist Church on Fern Street.

The second definition of liberty --- is the liberty to participate in government. I urge you to get involved in public service --- this could mean, like my wife Beth, that you run and serve in elective office. Though politicians are criticized continuously, they are who translate and safeguard and put these ideas of liberty into action. They represent us as we relay our ideas to them for what we want government to do. Beth would tell you that as a Senator from West Hartford, she gets 2 to 3 times as many calls from constituents than other Senators. Our community’s hyper-engagement helps define our aspirations through peaceful civic engagement. That is one of the reasons we love this community so much - because its citizenry is enfranchised and empowered to make government work, something for which the Patriots fought.

Being civically involved also means getting involved in organizations like the Noah Webster House and Knox Inc., the Elmwood Business Association, and the Black Lives Matter Movement. It could also mean being on the Library Board, coaching a youth sports league, advocating, like Mary Ellen Thibodeau does for safer streets for bicyclists and pedestrians, or organizing a block party in your neighborhood, or helping to organize hurricane relief for Puerto Rico.

And in Elmwood and West Hartford, we celebrate this engagement. The names of our schools honor local heroes who were involved in our community. This park is now known as Blanchfield Park as a tribute to Bill Blanchfield who worked in this community and came here everyday to raise the flag. Behind us is the former Talcott Jr. High, named after James A. Talcott, a businessman who donated money and books to start our town library in 1897. Conard High School was named after Frederick U. Conard, President of Niles-Bement-Pond in Elmwood and the Chair of our Board of Education.

So, I challenge you,

- How do you participate in your community? Not just in the past, but also today.
- What is your covenant with this town, your town?
- How do you help people make connections and build local institutions and get involved in civic life like this tree planting ceremony is doing today?

**EDUCATION**

And finally, this elm tree, I hope can be a symbol for the importance of education in our community that helps students understand what liberty is.

I’d like all the teachers who are here to raise their hands and stand. I believe it is the teachers who keep our country safe, who protect our democracy, and are our biggest defenders of liberty. All teachers are models for democracy, civic discourse and critical thinking by the way they model those values in their classrooms, regardless of subject matter. And, when our Social Studies teachers teach our history and the principles of American government, students learn what freedom is. Please give them a round of applause.

I feel so lucky to have had the chance to be your colleague and to serve this community as a teacher, starting right here at Talcott Jr. High in 1977 and then at Conard until 2015.

As you know, I love **history**. I studied women’s history, African American History and Labor History in school. What all those fields have in common is that they are not the people who “won” and often their voices were not heard in the standard narrative of US History. My job, I thought, was to make their stories come alive --- to give a voice to the voiceless and to try to complicate a narrative that mostly focused on men and political history.

As teachers, we tell local and national stories that help us get at the historian’s enterprise:

- What causes change?
- How does an event compare to what happened in another time and place?
- What is the context of the event? and
- What changes and what remains the same?

West Hartford has stories: of the Beach sisters, Bristow, Luna Park, and World War II housing, and an individual teacher’s vision all help define a community

- where the Beach sisters could be leaders and drive their own cars as early as 1905,
- where an enslaved man who bought his freedom, right before these elms were planted could get a school, Bristow, named after him in 2004,
- where people came by trolley to Luna Park for manufactured fun in a city of lights,
- where the head of the West Hartford Housing Authority successfully banned African Americans from living in federal housing built right near here during World War II, ironically, our 20th century fight for democracy;
- where in the 1970s and 80s, a school teacher, Eve Soumerai, who survived the Holocaust, even before there was Unified Theater, integrated students with disabilities into her musical theater productions.

Each of these stories helps us understand the texture of our town today--- and provide multiple narratives that continue in this complex inner ring suburb that we call home.

These stories themselves become symbols, like this tree, of values that matter to our community. They are a way to break into student’s certainty of a single narrative, and to raise questions about who had power, and finally I hope they help give agency and voice to those who study the past.

I like to think that I have lived up to the aspirations of Ebenezer Faxon, 240 years ago when he showed with his action of planting elm trees, that they would be a symbol to safeguard liberty. I believe safeguarding liberty happens in the political realm, and in our schools. I take pride in former students who chose to run for elected office including State Rep Joe Verrengia, Town Councillors Dallas Dodge and Chris Williams - and Ryan Langan who is running for office. And, when I find out one of my former students has become a teacher my heart jumps. I think of Katy Worth McCarthy, Kevin Liftig, Diana Coyne, Melissa Behrens, Anne McKernan, Leslie Hadra, Steve O’Meara, Emily Goetz, Kelly McCormick Brouse, Anna Bennett, Michael Bennett, Ebony Jones, Morgan Reed, big Carl Johnson, and many more. This job of teaching students how to live an examined life is passed from one generation to the next. Like the idea of liberty embodied in these elm trees, our teaching reverberates beyond our classroom.

So thanks once again for this great honor. I am so happy to have moved to this community 40 years ago and today to feel rooted in this place --- you have allowed me to branch out, to plant seeds, and to provide shade for students and people who needed it. And in this past year and a half as I have had to learn to live with cancer, I have been so grateful to my family, friends, and this community for your support. Without you, I don’t think I’d be here today, basking in this day, on this busy corner, just aching to get to the apples and doughnut holes!

Thank you!
